{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "chatbot",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "chatbot",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "chatbot-1.107.0-0.6.21.jar",
          "url": "chatbot-1.107.0-0.6.21.jar",
          "size": 19067,
          "sha512": "4e3cdf1340b405e931602a17598a324fbfc63985613623091a0c1260eb8e2e4fd7da8603f05765901a9e71b09d109d514a2f4c65fa48787c422e23f5ac44bb18",
          "sha256": "6347d11a944c0b277d54dc1d73a91769d7142858e536968ae886ee791b65e344",
          "sha1": "f9b6a3d29b781990ee27e9c9d56296f8cd5a33c4",
          "md5": "6db2caaebf3db91c2d61a3be01a522ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "chatbot",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "chatbot-1.107.0-0.6.21.jar",
          "url": "chatbot-1.107.0-0.6.21.jar",
          "size": 19067,
          "sha512": "4e3cdf1340b405e931602a17598a324fbfc63985613623091a0c1260eb8e2e4fd7da8603f05765901a9e71b09d109d514a2f4c65fa48787c422e23f5ac44bb18",
          "sha256": "6347d11a944c0b277d54dc1d73a91769d7142858e536968ae886ee791b65e344",
          "sha1": "f9b6a3d29b781990ee27e9c9d56296f8cd5a33c4",
          "md5": "6db2caaebf3db91c2d61a3be01a522ad"
        }
      ]
    }
  ]
}
