{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cloudwatch",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cloudwatch",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cloudwatch-1.113.0-0.6.21.jar",
          "url": "cloudwatch-1.113.0-0.6.21.jar",
          "size": 334861,
          "sha512": "5470aa05343cafc5100e36891fd0c0864ee0c0bf630ab6f4f602f34afadddf614b1985f27d629a927d6c50dc10065c9da7f1a4cc461277b74df6b0cc262bc8e6",
          "sha256": "35f19b65db28768059d0f6f4d3cb073990cacd31eda2b9c4e50b80412c06daf0",
          "sha1": "a68582ee2d21d2b3544d9ffec3ea70a3c4687cbe",
          "md5": "3d94b81225978c97396cf929a93efa37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cloudwatch",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cloudwatch-1.113.0-0.6.21.jar",
          "url": "cloudwatch-1.113.0-0.6.21.jar",
          "size": 334861,
          "sha512": "5470aa05343cafc5100e36891fd0c0864ee0c0bf630ab6f4f602f34afadddf614b1985f27d629a927d6c50dc10065c9da7f1a4cc461277b74df6b0cc262bc8e6",
          "sha256": "35f19b65db28768059d0f6f4d3cb073990cacd31eda2b9c4e50b80412c06daf0",
          "sha1": "a68582ee2d21d2b3544d9ffec3ea70a3c4687cbe",
          "md5": "3d94b81225978c97396cf929a93efa37"
        }
      ]
    }
  ]
}
