{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "opsworkscm",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "opsworkscm",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "opsworkscm-1.113.0-0.6.21.jar",
          "url": "opsworkscm-1.113.0-0.6.21.jar",
          "size": 43063,
          "sha512": "a937590764293be1187f7188b142ea8701dd9318c77d2637196db93e72732a28ae3f82b4e9f5bc9fbe40b895db073a9f077570b8b56f72ccfd1a4e4aeafb858d",
          "sha256": "fbdc668ba914c193eff44081ad7083704321880d33df19655e239f599874e1bb",
          "sha1": "24f76eab21a761842fdc416f02895957d02c18d7",
          "md5": "815889d5f8d31423b9db62da2c3246f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "opsworkscm",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "opsworkscm-1.113.0-0.6.21.jar",
          "url": "opsworkscm-1.113.0-0.6.21.jar",
          "size": 43063,
          "sha512": "a937590764293be1187f7188b142ea8701dd9318c77d2637196db93e72732a28ae3f82b4e9f5bc9fbe40b895db073a9f077570b8b56f72ccfd1a4e4aeafb858d",
          "sha256": "fbdc668ba914c193eff44081ad7083704321880d33df19655e239f599874e1bb",
          "sha1": "24f76eab21a761842fdc416f02895957d02c18d7",
          "md5": "815889d5f8d31423b9db62da2c3246f7"
        }
      ]
    }
  ]
}
