{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lookoutvision",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lookoutvision",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "lookoutvision-1.117.0-0.6.25.jar",
          "url": "lookoutvision-1.117.0-0.6.25.jar",
          "size": 8644,
          "sha512": "22562eb35568656347825ba98aea8fea3a31bcc4e9e5a49ca9ac4a8fe7701f69ae115d9e22f7eb991473950a4319da8b81101fa1e61622f601e193e3083f0065",
          "sha256": "d4639965acc9e5c377f278e01dfec818e246c1566582595e7a27bcf01bcb15ef",
          "sha1": "92c611d48fdeb3905910672ae42e57c0a7bbcb61",
          "md5": "abd672f3bb8bb6e8ab9e8e55948fa8be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lookoutvision",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "lookoutvision-1.117.0-0.6.25.jar",
          "url": "lookoutvision-1.117.0-0.6.25.jar",
          "size": 8644,
          "sha512": "22562eb35568656347825ba98aea8fea3a31bcc4e9e5a49ca9ac4a8fe7701f69ae115d9e22f7eb991473950a4319da8b81101fa1e61622f601e193e3083f0065",
          "sha256": "d4639965acc9e5c377f278e01dfec818e246c1566582595e7a27bcf01bcb15ef",
          "sha1": "92c611d48fdeb3905910672ae42e57c0a7bbcb61",
          "md5": "abd672f3bb8bb6e8ab9e8e55948fa8be"
        }
      ]
    }
  ]
}
