{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "certificatemanager",
    "version": "1.59.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "certificatemanager",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "certificatemanager-1.59.0-0.6.22.jar",
          "url": "certificatemanager-1.59.0-0.6.22.jar",
          "size": 44992,
          "sha512": "285e442333689436788273397ac826ce4f97e84038c8143a77c32a096695e63e1f3e78544ca927639b9458daaed8c65aa39984e881c5fcab44c5918d9ee1d937",
          "sha256": "217f2d34dd1f205ecbd74df0514f18d067599e1b2740cf7fbc4670be5e5bca5d",
          "sha1": "b4ceea6bffcf9b8c4146e7ffb182b641486d84ef",
          "md5": "bf82d98fb1eb3c5a4723228aca29d0b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "certificatemanager",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "certificatemanager-1.59.0-0.6.22.jar",
          "url": "certificatemanager-1.59.0-0.6.22.jar",
          "size": 44992,
          "sha512": "285e442333689436788273397ac826ce4f97e84038c8143a77c32a096695e63e1f3e78544ca927639b9458daaed8c65aa39984e881c5fcab44c5918d9ee1d937",
          "sha256": "217f2d34dd1f205ecbd74df0514f18d067599e1b2740cf7fbc4670be5e5bca5d",
          "sha1": "b4ceea6bffcf9b8c4146e7ffb182b641486d84ef",
          "md5": "bf82d98fb1eb3c5a4723228aca29d0b6"
        }
      ]
    }
  ]
}
