{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "wafregional",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.113.0-0.6.21.jar",
          "url": "wafregional-1.113.0-0.6.21.jar",
          "size": 251060,
          "sha512": "e1425bc88752c10e260a1028336f97af5d484d03fb22ce4be908024f9f80d571f8cff54721322b485c8ee0a9ba3462f0cc19a58a87c41c16b16b72c6915b57dd",
          "sha256": "159362563c0e6ef86ffcfa5d3afd5acae65af3324c427b275e2a3adc379a559d",
          "sha1": "c0a1da244cb8b14fdba8c5237f53c58df25a1ccb",
          "md5": "bcb9b910332120b5c4fb79230e6e3807"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.113.0-0.6.21.jar",
          "url": "wafregional-1.113.0-0.6.21.jar",
          "size": 251060,
          "sha512": "e1425bc88752c10e260a1028336f97af5d484d03fb22ce4be908024f9f80d571f8cff54721322b485c8ee0a9ba3462f0cc19a58a87c41c16b16b72c6915b57dd",
          "sha256": "159362563c0e6ef86ffcfa5d3afd5acae65af3324c427b275e2a3adc379a559d",
          "sha1": "c0a1da244cb8b14fdba8c5237f53c58df25a1ccb",
          "md5": "bcb9b910332120b5c4fb79230e6e3807"
        }
      ]
    }
  ]
}
