{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "xray",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "xray",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "xray-1.114.0-0.6.21.jar",
          "url": "xray-1.114.0-0.6.21.jar",
          "size": 91746,
          "sha512": "9e5648fc511834a815bbdcecb3a196878d62b4478852d903beaac524388592850be484209d1c247cb664a9c9bdae47d40b56c216249e74fd9365f5d546c02fa",
          "sha256": "8b8cd61ba5b96653ff985f1f1c6ab77430292f615682946a19867ff6e50f69cf",
          "sha1": "a85f9db2fc4b633c615d9b7cc6621507a6170fad",
          "md5": "cde431035be1dfdf491065c2e1f6a47a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "xray",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "xray-1.114.0-0.6.21.jar",
          "url": "xray-1.114.0-0.6.21.jar",
          "size": 91746,
          "sha512": "9e5648fc511834a815bbdcecb3a196878d62b4478852d903beaac524388592850be484209d1c247cb664a9c9bdae47d40b56c216249e74fd9365f5d546c02fa",
          "sha256": "8b8cd61ba5b96653ff985f1f1c6ab77430292f615682946a19867ff6e50f69cf",
          "sha1": "a85f9db2fc4b633c615d9b7cc6621507a6170fad",
          "md5": "cde431035be1dfdf491065c2e1f6a47a"
        }
      ]
    }
  ]
}
