{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "greengrassv2",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "greengrassv2",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "greengrassv2-1.117.0-0.6.25.jar",
          "url": "greengrassv2-1.117.0-0.6.25.jar",
          "size": 119337,
          "sha512": "2ff44a3199c9c6c99dddba240fc6471e75269d36c85a4eed9c90499c4995bc6539d6fe7603607000e606aa33e342917638680ec94c0c7396494748dc10d83dbb",
          "sha256": "ea8c8cef811c446ea5a93fd91cc7187a1c5638e52e6859f80b852f4e7775fc58",
          "sha1": "1d0af8752d504a9a64c20083dbeafb0ae1ba1520",
          "md5": "c398c17555bdd9716204d377d274ddac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "greengrassv2",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "greengrassv2-1.117.0-0.6.25.jar",
          "url": "greengrassv2-1.117.0-0.6.25.jar",
          "size": 119337,
          "sha512": "2ff44a3199c9c6c99dddba240fc6471e75269d36c85a4eed9c90499c4995bc6539d6fe7603607000e606aa33e342917638680ec94c0c7396494748dc10d83dbb",
          "sha256": "ea8c8cef811c446ea5a93fd91cc7187a1c5638e52e6859f80b852f4e7775fc58",
          "sha1": "1d0af8752d504a9a64c20083dbeafb0ae1ba1520",
          "md5": "c398c17555bdd9716204d377d274ddac"
        }
      ]
    }
  ]
}
