{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "autoscalingplans",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "autoscalingplans",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscalingplans-1.102.0-0.6.21.jar",
          "url": "autoscalingplans-1.102.0-0.6.21.jar",
          "size": 109984,
          "sha512": "a38a64f3870adc35a379abd4a4aa448d312ece33973c43d7fcb7b3e33fff9af61180296944358d59c884ccebc350b5875edb8d885b755e3a0edee9125b376f39",
          "sha256": "5c14fa4cdd609fb3514ad7c13f933a4d623b09bd3992a89af522ad3a3d2b5990",
          "sha1": "d7508c9a1a8c0cc878bf471be59518b5abbf0b53",
          "md5": "873bffabc6824b70ab73e44c1edbce09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "autoscalingplans",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscalingplans-1.102.0-0.6.21.jar",
          "url": "autoscalingplans-1.102.0-0.6.21.jar",
          "size": 109984,
          "sha512": "a38a64f3870adc35a379abd4a4aa448d312ece33973c43d7fcb7b3e33fff9af61180296944358d59c884ccebc350b5875edb8d885b755e3a0edee9125b376f39",
          "sha256": "5c14fa4cdd609fb3514ad7c13f933a4d623b09bd3992a89af522ad3a3d2b5990",
          "sha1": "d7508c9a1a8c0cc878bf471be59518b5abbf0b53",
          "md5": "873bffabc6824b70ab73e44c1edbce09"
        }
      ]
    }
  ]
}
