{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cur",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cur",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "cur-1.117.0-0.6.25.jar",
          "url": "cur-1.117.0-0.6.25.jar",
          "size": 19911,
          "sha512": "37fbac51135275abb7f76fd7efc1c4fb2d6e95420c11199d2c6743f4dc236285b1cdb919e1b8c09d831e83aefff9c1a771145c4eae65e1db313782d659d01758",
          "sha256": "20652d154ef4e27cf3a9b9ee95f9edd09e11aaca8c9daab558f23c226f155479",
          "sha1": "08371c2bb0ad595f33b719e7b9549c77f6ebf78f",
          "md5": "048f1561142e04ecd828efe5b18afdfa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cur",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "cur-1.117.0-0.6.25.jar",
          "url": "cur-1.117.0-0.6.25.jar",
          "size": 19911,
          "sha512": "37fbac51135275abb7f76fd7efc1c4fb2d6e95420c11199d2c6743f4dc236285b1cdb919e1b8c09d831e83aefff9c1a771145c4eae65e1db313782d659d01758",
          "sha256": "20652d154ef4e27cf3a9b9ee95f9edd09e11aaca8c9daab558f23c226f155479",
          "sha1": "08371c2bb0ad595f33b719e7b9549c77f6ebf78f",
          "md5": "048f1561142e04ecd828efe5b18afdfa"
        }
      ]
    }
  ]
}
