{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "chatbot",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "chatbot",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "chatbot-1.102.0-0.6.21.jar",
          "url": "chatbot-1.102.0-0.6.21.jar",
          "size": 19081,
          "sha512": "281f9736d5ec86c1fff4c8df1614e03b3a8ffa8f595b2c0ef399c038ee00585bee791ca511e06f0d4a268b274363ffb108bb285cd0b0ebc8a50281c57cd6809e",
          "sha256": "65d6b074b3fb59d84931e808e9383ec8b433bb1d6ec670f862dde5012e54270c",
          "sha1": "5c4636c2c6187182b2d044d5b0c0280a0d2d9c91",
          "md5": "bd3cf7abea9e8c3978c4dc77aeb3ce26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "chatbot",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "chatbot-1.102.0-0.6.21.jar",
          "url": "chatbot-1.102.0-0.6.21.jar",
          "size": 19081,
          "sha512": "281f9736d5ec86c1fff4c8df1614e03b3a8ffa8f595b2c0ef399c038ee00585bee791ca511e06f0d4a268b274363ffb108bb285cd0b0ebc8a50281c57cd6809e",
          "sha256": "65d6b074b3fb59d84931e808e9383ec8b433bb1d6ec670f862dde5012e54270c",
          "sha1": "5c4636c2c6187182b2d044d5b0c0280a0d2d9c91",
          "md5": "bd3cf7abea9e8c3978c4dc77aeb3ce26"
        }
      ]
    }
  ]
}
