{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "networkfirewall",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "networkfirewall",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "networkfirewall-1.107.0-0.6.21.jar",
          "url": "networkfirewall-1.107.0-0.6.21.jar",
          "size": 337496,
          "sha512": "adfb5dba8ff992884b311c0d8aede0d28977edb7dceb3750cd92ca4d4c8360f8fde464e583c3c63da826391978ba8b4f5835a1b63c60c7cd80804b58b7eabf05",
          "sha256": "95f9a8d7a7ad07df40edcf79836f92e2504570b3b06104d738e1a0675560b20",
          "sha1": "9a867ec25de2be915bd638ed743091e9d562d444",
          "md5": "2f0f904c30849db04e54ff010fa354c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "networkfirewall",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "networkfirewall-1.107.0-0.6.21.jar",
          "url": "networkfirewall-1.107.0-0.6.21.jar",
          "size": 337496,
          "sha512": "adfb5dba8ff992884b311c0d8aede0d28977edb7dceb3750cd92ca4d4c8360f8fde464e583c3c63da826391978ba8b4f5835a1b63c60c7cd80804b58b7eabf05",
          "sha256": "95f9a8d7a7ad07df40edcf79836f92e2504570b3b06104d738e1a0675560b20",
          "sha1": "9a867ec25de2be915bd638ed743091e9d562d444",
          "md5": "2f0f904c30849db04e54ff010fa354c6"
        }
      ]
    }
  ]
}
