{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-lambda-layer-awscli",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-lambda-layer-awscli",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-lambda-layer-awscli-1.114.0-0.6.21.jar",
          "url": "cdk-lambda-layer-awscli-1.114.0-0.6.21.jar",
          "size": 448,
          "sha512": "6f40b99d302a1ea8a188f610d7be4fdbf35f3027692bac4303e882d24312d91225118adb1595558766bacc760b9446de2525155877c3aa5520a2691e723823ce",
          "sha256": "260e8a71e4d76ed8715bdc8d6f9a05f044c2cc56565e5127ce8d33215a172a70",
          "sha1": "3e760a8d750f0d244195eca9a50e74891bdbf6c0",
          "md5": "4bf40960c0f351960140751b1abb590c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-lambda-layer-awscli",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-lambda-layer-awscli-1.114.0-0.6.21.jar",
          "url": "cdk-lambda-layer-awscli-1.114.0-0.6.21.jar",
          "size": 448,
          "sha512": "6f40b99d302a1ea8a188f610d7be4fdbf35f3027692bac4303e882d24312d91225118adb1595558766bacc760b9446de2525155877c3aa5520a2691e723823ce",
          "sha256": "260e8a71e4d76ed8715bdc8d6f9a05f044c2cc56565e5127ce8d33215a172a70",
          "sha1": "3e760a8d750f0d244195eca9a50e74891bdbf6c0",
          "md5": "4bf40960c0f351960140751b1abb590c"
        }
      ]
    }
  ]
}
