{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-customresources",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudformation",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-customresources-1.109.0-0.6.21.jar",
          "url": "cdk-customresources-1.109.0-0.6.21.jar",
          "size": 27675,
          "sha512": "8875bb50ef93f3b42685d4dcf651e64a84df2ae8d36c7af411c7e6d26d674dcd5e72e99a1cd30db59a7f7c2453139c9244daf21e5c5490dab7771a47b8f01e03",
          "sha256": "589ea07c9f0879bd9de3d50c1ec3aab1bcb66c3f04b1746e55ba94ff003d8e27",
          "sha1": "122262ffcb3a15b0ab587cf20d70ea98e3be7c3d",
          "md5": "515629a4f7997d51df7afa0ac438200c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudformation",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-customresources-1.109.0-0.6.21.jar",
          "url": "cdk-customresources-1.109.0-0.6.21.jar",
          "size": 27675,
          "sha512": "8875bb50ef93f3b42685d4dcf651e64a84df2ae8d36c7af411c7e6d26d674dcd5e72e99a1cd30db59a7f7c2453139c9244daf21e5c5490dab7771a47b8f01e03",
          "sha256": "589ea07c9f0879bd9de3d50c1ec3aab1bcb66c3f04b1746e55ba94ff003d8e27",
          "sha1": "122262ffcb3a15b0ab587cf20d70ea98e3be7c3d",
          "md5": "515629a4f7997d51df7afa0ac438200c"
        }
      ]
    }
  ]
}
