{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "directoryservice",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "directoryservice",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "directoryservice-1.112.0-0.6.21.jar",
          "url": "directoryservice-1.112.0-0.6.21.jar",
          "size": 77707,
          "sha512": "ee6e23826a14a028cbf5335d1b79a9518b14c31395f7467f0adb0fc9ba0f3d6991ae1274ed830d434eb0a14a7138f3089c85dbf919b4a6617a4ee234b26ba8fd",
          "sha256": "b0699a3aada3302ce6a13f7de99cae110559ef040a93ac655f879261ce0841b2",
          "sha1": "201845d705d3517df77f0b0e62aa77c1e76476cb",
          "md5": "d48e1df1ba494852cdee9235ebe9cdb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "directoryservice",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "directoryservice-1.112.0-0.6.21.jar",
          "url": "directoryservice-1.112.0-0.6.21.jar",
          "size": 77707,
          "sha512": "ee6e23826a14a028cbf5335d1b79a9518b14c31395f7467f0adb0fc9ba0f3d6991ae1274ed830d434eb0a14a7138f3089c85dbf919b4a6617a4ee234b26ba8fd",
          "sha256": "b0699a3aada3302ce6a13f7de99cae110559ef040a93ac655f879261ce0841b2",
          "sha1": "201845d705d3517df77f0b0e62aa77c1e76476cb",
          "md5": "d48e1df1ba494852cdee9235ebe9cdb5"
        }
      ]
    }
  ]
}
