{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "devopsguru",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "devopsguru",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "devopsguru-1.99.0-0.6.21.jar",
          "url": "devopsguru-1.99.0-0.6.21.jar",
          "size": 56995,
          "sha512": "b28fee450f023c2c8ecda9f4991e41c67346efa87c8182a879044bf8b1b3ea8844795e7351f7293968c9d8fd9fefb2a2d97d1375a0cae70f96ff9849a9db9437",
          "sha256": "4079f05cf4c5bee97b5497cc16762df91989eabba93bad1648b3849e533e958d",
          "sha1": "4a29aeabe04fdd7ad63bcbd79202f6cdb4314efe",
          "md5": "2e08b4a44efe8ccf50e36a9d9bc3c0a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "devopsguru",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "devopsguru-1.99.0-0.6.21.jar",
          "url": "devopsguru-1.99.0-0.6.21.jar",
          "size": 56995,
          "sha512": "b28fee450f023c2c8ecda9f4991e41c67346efa87c8182a879044bf8b1b3ea8844795e7351f7293968c9d8fd9fefb2a2d97d1375a0cae70f96ff9849a9db9437",
          "sha256": "4079f05cf4c5bee97b5497cc16762df91989eabba93bad1648b3849e533e958d",
          "sha1": "4a29aeabe04fdd7ad63bcbd79202f6cdb4314efe",
          "md5": "2e08b4a44efe8ccf50e36a9d9bc3c0a2"
        }
      ]
    }
  ]
}
