{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lambda-nodejs",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-nodejs",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-nodejs-1.99.0-0.6.21.jar",
          "url": "lambda-nodejs-1.99.0-0.6.21.jar",
          "size": 25679,
          "sha512": "7584f62010e8ce8acd620722ee0c5758304934ee57884e9464ed79e7cdb7fb545c1203784d63bc4f4b0925342adabfabc6c53490f4e2c9e2f52620a7feea0b0f",
          "sha256": "7e0c17af4193edf908f4de6d4c61ef880f8249622ada2ae844bc8c657835303",
          "sha1": "c4d47711d73df512807a4a38709cc572711ad45d",
          "md5": "bb8ad527d6414f38293a63e59da79e65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-nodejs",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-nodejs-1.99.0-0.6.21.jar",
          "url": "lambda-nodejs-1.99.0-0.6.21.jar",
          "size": 25679,
          "sha512": "7584f62010e8ce8acd620722ee0c5758304934ee57884e9464ed79e7cdb7fb545c1203784d63bc4f4b0925342adabfabc6c53490f4e2c9e2f52620a7feea0b0f",
          "sha256": "7e0c17af4193edf908f4de6d4c61ef880f8249622ada2ae844bc8c657835303",
          "sha1": "c4d47711d73df512807a4a38709cc572711ad45d",
          "md5": "bb8ad527d6414f38293a63e59da79e65"
        }
      ]
    }
  ]
}
