{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "chatbot",
    "version": "1.110.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cnrjfrtzdvad5bhmsg7msamtuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "chatbot",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "chatbot-1.110.0-0.6.21.jar",
          "url": "chatbot-1.110.0-0.6.21.jar",
          "size": 19083,
          "sha512": "be801d031b9dd05788535a4ce043a2f73dfe71868092abbfc4b2f279a1629d2f30f5ecc8992c6ce062dc8b38c6851fbca6c796fbfd1d01286145c189b21c58d0",
          "sha256": "1a9e0cb5284fd660abd53fd44a76e031b8717af67c90517e125d3f1c4abd87f9",
          "sha1": "fcdc3395b9fc8f03da02f6e3c6a0f439e9fc3f51",
          "md5": "4571dd22eb6db44732a51fe97a4e842f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "chatbot",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "chatbot-1.110.0-0.6.21.jar",
          "url": "chatbot-1.110.0-0.6.21.jar",
          "size": 19083,
          "sha512": "be801d031b9dd05788535a4ce043a2f73dfe71868092abbfc4b2f279a1629d2f30f5ecc8992c6ce062dc8b38c6851fbca6c796fbfd1d01286145c189b21c58d0",
          "sha256": "1a9e0cb5284fd660abd53fd44a76e031b8717af67c90517e125d3f1c4abd87f9",
          "sha1": "fcdc3395b9fc8f03da02f6e3c6a0f439e9fc3f51",
          "md5": "4571dd22eb6db44732a51fe97a4e842f"
        }
      ]
    }
  ]
}
