{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codeartifact",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codeartifact",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codeartifact-1.107.0-0.6.21.jar",
          "url": "codeartifact-1.107.0-0.6.21.jar",
          "size": 17923,
          "sha512": "805bee80bdaa6df16da0b4fc47c32324e3f2e26aa832ca9655df0098d3e09d0982f5718c2bd1ea65841bb7b3db827427bc57493df6b7081d59b53050edf79ac9",
          "sha256": "d20d9df208ac18e1c38cb38f7ed8cb0a45d9d2910e9789a89b0d0c48146d5b0c",
          "sha1": "1dbebb4ece3ea097c89f6ae1e68836c0e2b9081c",
          "md5": "f64239e6bc1996b3b200741de6dd7f9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codeartifact",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codeartifact-1.107.0-0.6.21.jar",
          "url": "codeartifact-1.107.0-0.6.21.jar",
          "size": 17923,
          "sha512": "805bee80bdaa6df16da0b4fc47c32324e3f2e26aa832ca9655df0098d3e09d0982f5718c2bd1ea65841bb7b3db827427bc57493df6b7081d59b53050edf79ac9",
          "sha256": "d20d9df208ac18e1c38cb38f7ed8cb0a45d9d2910e9789a89b0d0c48146d5b0c",
          "sha1": "1dbebb4ece3ea097c89f6ae1e68836c0e2b9081c",
          "md5": "f64239e6bc1996b3b200741de6dd7f9a"
        }
      ]
    }
  ]
}
