{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "eventschemas",
    "version": "1.31.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.31.0-0.6.23.jar",
          "url": "eventschemas-1.31.0-0.6.23.jar",
          "size": 35997,
          "sha512": "5fcacc525e99a5f2e492b305689498dd9a0f42677a2713a6da2f5eeadb1247638bda6e2ceb7babcbd8cd03afbedf64eb19b52b4c4570953d0b173caa9f63c0bf",
          "sha256": "a680312962ec67dd8dbf3bd1271a571510238fa8aeaae03127c9a16bee6342c1",
          "sha1": "4eccdf2a480b466097629ed2e36110ce21980ee5",
          "md5": "99b77eeb7b35e4a7bc84f2f6d088f3d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.31.0-0.6.23.jar",
          "url": "eventschemas-1.31.0-0.6.23.jar",
          "size": 35997,
          "sha512": "5fcacc525e99a5f2e492b305689498dd9a0f42677a2713a6da2f5eeadb1247638bda6e2ceb7babcbd8cd03afbedf64eb19b52b4c4570953d0b173caa9f63c0bf",
          "sha256": "a680312962ec67dd8dbf3bd1271a571510238fa8aeaae03127c9a16bee6342c1",
          "sha1": "4eccdf2a480b466097629ed2e36110ce21980ee5",
          "md5": "99b77eeb7b35e4a7bc84f2f6d088f3d7"
        }
      ]
    }
  ]
}
