{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ssmincidents",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ssmincidents",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ssmincidents-1.108.0-0.6.21.jar",
          "url": "ssmincidents-1.108.0-0.6.21.jar",
          "size": 108439,
          "sha512": "4fb8e4edbfc071deca7cbf13a0e4ff996f269a02848d3baec0abb2d29ca837cea129bb90ec691975be262ca8fecb425b401daaf9869b3e67686997de1deca6ce",
          "sha256": "e9f9cc4a52bc039aa4d2025933a52b8815ac710396c0a6e91924d3529d4e9a45",
          "sha1": "e1301b86921a1e5fc6aedf1aae79e9aacecacfe3",
          "md5": "e2efa9faad4ebc3d7386eb57bca26df9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ssmincidents",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ssmincidents-1.108.0-0.6.21.jar",
          "url": "ssmincidents-1.108.0-0.6.21.jar",
          "size": 108439,
          "sha512": "4fb8e4edbfc071deca7cbf13a0e4ff996f269a02848d3baec0abb2d29ca837cea129bb90ec691975be262ca8fecb425b401daaf9869b3e67686997de1deca6ce",
          "sha256": "e9f9cc4a52bc039aa4d2025933a52b8815ac710396c0a6e91924d3529d4e9a45",
          "sha1": "e1301b86921a1e5fc6aedf1aae79e9aacecacfe3",
          "md5": "e2efa9faad4ebc3d7386eb57bca26df9"
        }
      ]
    }
  ]
}
