{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "apprunner",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "apprunner",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apprunner-1.107.0-0.6.21.jar",
          "url": "apprunner-1.107.0-0.6.21.jar",
          "size": 134992,
          "sha512": "15dbf63d0540d065283af4ba70303e941e58186b24b2dbba255b6d98cde3135df50a7610d03f34236518ca8c04a5e2c11918d5c49b632e7900428d21a48aff21",
          "sha256": "63a655271d623625c5a33a5da2dd35bb858f1df2617559f722a88d964e6154b9",
          "sha1": "dca9cfd0781d2a9bbd5e5a7b7111048e4ac9a28a",
          "md5": "24337f8ff54c28972c68ae6df7ffc31d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "apprunner",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apprunner-1.107.0-0.6.21.jar",
          "url": "apprunner-1.107.0-0.6.21.jar",
          "size": 134992,
          "sha512": "15dbf63d0540d065283af4ba70303e941e58186b24b2dbba255b6d98cde3135df50a7610d03f34236518ca8c04a5e2c11918d5c49b632e7900428d21a48aff21",
          "sha256": "63a655271d623625c5a33a5da2dd35bb858f1df2617559f722a88d964e6154b9",
          "sha1": "dca9cfd0781d2a9bbd5e5a7b7111048e4ac9a28a",
          "md5": "24337f8ff54c28972c68ae6df7ffc31d"
        }
      ]
    }
  ]
}
