{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "autoscaling-hooktargets",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling-hooktargets",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns-subscriptions",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-hooktargets-1.99.0-0.6.21.jar",
          "url": "autoscaling-hooktargets-1.99.0-0.6.21.jar",
          "size": 448,
          "sha512": "8a2088b963b16102ac0a10873335280963f07d34ffa5c4cb54d1441d232e4b603981ae450c1cb9a3c2e27fa96ea02f47e3dfc3d3abba9a54803f65c7cd036ba0",
          "sha256": "d6e6bc39afe142c91e5f552dc67e2cde56c1b84e5c12cd871f159bebec69c60",
          "sha1": "c868f43efb75d6debe192c7489c94056e0f69d4f",
          "md5": "cb706cae9a389ba3e41f8a9db64688e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling-hooktargets",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns-subscriptions",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-hooktargets-1.99.0-0.6.21.jar",
          "url": "autoscaling-hooktargets-1.99.0-0.6.21.jar",
          "size": 448,
          "sha512": "8a2088b963b16102ac0a10873335280963f07d34ffa5c4cb54d1441d232e4b603981ae450c1cb9a3c2e27fa96ea02f47e3dfc3d3abba9a54803f65c7cd036ba0",
          "sha256": "d6e6bc39afe142c91e5f552dc67e2cde56c1b84e5c12cd871f159bebec69c60",
          "sha1": "c868f43efb75d6debe192c7489c94056e0f69d4f",
          "md5": "cb706cae9a389ba3e41f8a9db64688e7"
        }
      ]
    }
  ]
}
