{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ce",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "pksuzuox3ne6pgnvsva7g32w2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ce",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ce-1.110.1-0.6.21.jar",
          "url": "ce-1.110.1-0.6.21.jar",
          "size": 36833,
          "sha512": "f140ae2ad1e6939c5a40818168294896ffac9f62a83d9a3b7e48be3ef88d1f504d1255f9c7a9a3875288acb8349c6c82fdcd5f11ffeefb7305c3b89461353201",
          "sha256": "d0c58788817ecf08e38812852f0e2a49c8c6b89b36ef7f3bd93c1b6519a189cd",
          "sha1": "f2fc815a9faf4084f3c2e6aa52595aa0c467e3b5",
          "md5": "47a93b336f60c663ff7c58b34c5260c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ce",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ce-1.110.1-0.6.21.jar",
          "url": "ce-1.110.1-0.6.21.jar",
          "size": 36833,
          "sha512": "f140ae2ad1e6939c5a40818168294896ffac9f62a83d9a3b7e48be3ef88d1f504d1255f9c7a9a3875288acb8349c6c82fdcd5f11ffeefb7305c3b89461353201",
          "sha256": "d0c58788817ecf08e38812852f0e2a49c8c6b89b36ef7f3bd93c1b6519a189cd",
          "sha1": "f2fc815a9faf4084f3c2e6aa52595aa0c467e3b5",
          "md5": "47a93b336f60c663ff7c58b34c5260c8"
        }
      ]
    }
  ]
}
