{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iam",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iam",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iam-1.103.0-0.6.21.jar",
          "url": "iam-1.103.0-0.6.21.jar",
          "size": 269182,
          "sha512": "b5dee98fd6e6c401193bc8c9e2818d803ef9ca15d2ffac1349a9872e8195985ddf47b265c42d009aad18db240e49f40f575c1c0058ca1cb1af698f690950c728",
          "sha256": "6ee0338a5720779ee4ca029d085e2891fc7c9d0ea15d997464e93ebfd930a027",
          "sha1": "5c45f591aad9902e06ff8a2b50a4413f1fa56993",
          "md5": "3beb192e5abbee0d49d151bfb33b744a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iam",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iam-1.103.0-0.6.21.jar",
          "url": "iam-1.103.0-0.6.21.jar",
          "size": 269182,
          "sha512": "b5dee98fd6e6c401193bc8c9e2818d803ef9ca15d2ffac1349a9872e8195985ddf47b265c42d009aad18db240e49f40f575c1c0058ca1cb1af698f690950c728",
          "sha256": "6ee0338a5720779ee4ca029d085e2891fc7c9d0ea15d997464e93ebfd930a027",
          "sha1": "5c45f591aad9902e06ff8a2b50a4413f1fa56993",
          "md5": "3beb192e5abbee0d49d151bfb33b744a"
        }
      ]
    }
  ]
}
