{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sns",
    "version": "1.100.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "smkqp7thvbfexba6catfwegxzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sns",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sns-1.100.0-0.6.21.jar",
          "url": "sns-1.100.0-0.6.21.jar",
          "size": 104748,
          "sha512": "908eae7b8e7d4ab07f153af76ceef8a0f10c2e84f5b2b93c9ad1c8f55b1733a7df4b30746d107dece16b353724402dc1376a806d4f3eb08e873c0f07e9271603",
          "sha256": "b78767410e117d0fa9612743ee885cfbd9beebee9f4832c4d633dfd6e67552dc",
          "sha1": "5f937b8d65a18fcf3e3465bf7e58255ad41cd45c",
          "md5": "9588353464d4bbade0fc47201dd328f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sns",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sns-1.100.0-0.6.21.jar",
          "url": "sns-1.100.0-0.6.21.jar",
          "size": 104748,
          "sha512": "908eae7b8e7d4ab07f153af76ceef8a0f10c2e84f5b2b93c9ad1c8f55b1733a7df4b30746d107dece16b353724402dc1376a806d4f3eb08e873c0f07e9271603",
          "sha256": "b78767410e117d0fa9612743ee885cfbd9beebee9f4832c4d633dfd6e67552dc",
          "sha1": "5f937b8d65a18fcf3e3465bf7e58255ad41cd45c",
          "md5": "9588353464d4bbade0fc47201dd328f9"
        }
      ]
    }
  ]
}
