{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iam",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iam",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iam-1.109.0-0.6.21.jar",
          "url": "iam-1.109.0-0.6.21.jar",
          "size": 269223,
          "sha512": "6027c66c64b8befe57d7ab1a1abfa9143ef4bd8c1e8322b4529e215c7af16fa7511c630ca2ef67afdbe5ba3cc8a31c7b45fe2eedcac23776b9dc251096fff39a",
          "sha256": "cb0ca9e35ada0c426b5a46b81ef543131354be93b4b6f883a8b42a898421735e",
          "sha1": "3b879e5a6acc348763e96f6682e52e7c29e1b7a1",
          "md5": "6721a2071e4c489d31d17119c745b76c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iam",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iam-1.109.0-0.6.21.jar",
          "url": "iam-1.109.0-0.6.21.jar",
          "size": 269223,
          "sha512": "6027c66c64b8befe57d7ab1a1abfa9143ef4bd8c1e8322b4529e215c7af16fa7511c630ca2ef67afdbe5ba3cc8a31c7b45fe2eedcac23776b9dc251096fff39a",
          "sha256": "cb0ca9e35ada0c426b5a46b81ef543131354be93b4b6f883a8b42a898421735e",
          "sha1": "3b879e5a6acc348763e96f6682e52e7c29e1b7a1",
          "md5": "6721a2071e4c489d31d17119c745b76c"
        }
      ]
    }
  ]
}
