{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "wafregional",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "pksuzuox3ne6pgnvsva7g32w2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.110.1-0.6.21.jar",
          "url": "wafregional-1.110.1-0.6.21.jar",
          "size": 251036,
          "sha512": "b64594e9c1c639ec14579680a8a2a6bf7af5a6bb0bf7a128a34ab388e447770b6ed5a00277f66a811b16fcc3d3de97f10039f084537e91947183a76f71f2bab9",
          "sha256": "44b5d7b4f211ac9b50b7c42d9da95416ad0fe02470b2c88ae4470d3479c033ca",
          "sha1": "6dbf82ed1b2b45d4ed327b72f81aecf1c3d515",
          "md5": "495ef5ed3474950899b73f3902b09a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.110.1-0.6.21.jar",
          "url": "wafregional-1.110.1-0.6.21.jar",
          "size": 251036,
          "sha512": "b64594e9c1c639ec14579680a8a2a6bf7af5a6bb0bf7a128a34ab388e447770b6ed5a00277f66a811b16fcc3d3de97f10039f084537e91947183a76f71f2bab9",
          "sha256": "44b5d7b4f211ac9b50b7c42d9da95416ad0fe02470b2c88ae4470d3479c033ca",
          "sha1": "6dbf82ed1b2b45d4ed327b72f81aecf1c3d515",
          "md5": "495ef5ed3474950899b73f3902b09a4"
        }
      ]
    }
  ]
}
