{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "resourcegroups",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "resourcegroups",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "resourcegroups-1.105.0-0.6.21.jar",
          "url": "resourcegroups-1.105.0-0.6.21.jar",
          "size": 59355,
          "sha512": "671b19b75f29e7285f06a066086972b432f251ce86c40ea0797a3059f8642738255a1914c891679fe7cf0201e27a0adc3a62be8bc407fd6bd985f3dde2dfbd76",
          "sha256": "685b7e1007e1c55f5527432118da10631a56b1f1790e956be710a8efd72ee54",
          "sha1": "bcfd5d5ed95dcce35577db008b5d972e48ac2385",
          "md5": "619c86a5a36156844fc956facf0686ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "resourcegroups",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "resourcegroups-1.105.0-0.6.21.jar",
          "url": "resourcegroups-1.105.0-0.6.21.jar",
          "size": 59355,
          "sha512": "671b19b75f29e7285f06a066086972b432f251ce86c40ea0797a3059f8642738255a1914c891679fe7cf0201e27a0adc3a62be8bc407fd6bd985f3dde2dfbd76",
          "sha256": "685b7e1007e1c55f5527432118da10631a56b1f1790e956be710a8efd72ee54",
          "sha1": "bcfd5d5ed95dcce35577db008b5d972e48ac2385",
          "md5": "619c86a5a36156844fc956facf0686ec"
        }
      ]
    }
  ]
}
