{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestarnotifications",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "codestarnotifications-1.118.0-0.6.25.jar",
          "url": "codestarnotifications-1.118.0-0.6.25.jar",
          "size": 42231,
          "sha512": "76b317173a893ead153948030f395f8fc13b80145d9138cca91a2bed457f742aa4b97d12cd61a0052148e2c81db44610e485a266ed19f9d33b340b1154afe2e9",
          "sha256": "708f33f45f8fcf0a90ff49ede5491272482df4d90ac77568fde72426cc7b6f47",
          "sha1": "7aa178514fdd5cb4a3103c191cd29c43205bb714",
          "md5": "74bc4887a03e7e1c033eaa2c6c7a165c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "codestarnotifications-1.118.0-0.6.25.jar",
          "url": "codestarnotifications-1.118.0-0.6.25.jar",
          "size": 42231,
          "sha512": "76b317173a893ead153948030f395f8fc13b80145d9138cca91a2bed457f742aa4b97d12cd61a0052148e2c81db44610e485a266ed19f9d33b340b1154afe2e9",
          "sha256": "708f33f45f8fcf0a90ff49ede5491272482df4d90ac77568fde72426cc7b6f47",
          "sha1": "7aa178514fdd5cb4a3103c191cd29c43205bb714",
          "md5": "74bc4887a03e7e1c033eaa2c6c7a165c"
        }
      ]
    }
  ]
}
