{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "kms",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "kms",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "kms-1.117.0-0.6.25.jar",
          "url": "kms-1.117.0-0.6.25.jar",
          "size": 77629,
          "sha512": "5e2c63a068614533519f987ed11aa6daf36dd02ebff2f00588b88568415e0980a0b4c22329a2becd9ea545b9baac76a42749e3a149449fa2cf21a05cd487129f",
          "sha256": "bd7523c8216df60c483c068894e6a229bda6f8c52d2dfe2fdbd383b93d651b31",
          "sha1": "e762ec0303e5763642fb1818cbedaf6f57276e40",
          "md5": "9cc42b1efdec5c751431c73dc425f825"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "kms",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "kms-1.117.0-0.6.25.jar",
          "url": "kms-1.117.0-0.6.25.jar",
          "size": 77629,
          "sha512": "5e2c63a068614533519f987ed11aa6daf36dd02ebff2f00588b88568415e0980a0b4c22329a2becd9ea545b9baac76a42749e3a149449fa2cf21a05cd487129f",
          "sha256": "bd7523c8216df60c483c068894e6a229bda6f8c52d2dfe2fdbd383b93d651b31",
          "sha1": "e762ec0303e5763642fb1818cbedaf6f57276e40",
          "md5": "9cc42b1efdec5c751431c73dc425f825"
        }
      ]
    }
  ]
}
