{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestarconnections",
    "version": "1.59.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestarconnections",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "codestarconnections-1.59.0-0.6.23.jar",
          "url": "codestarconnections-1.59.0-0.6.23.jar",
          "size": 9593,
          "sha512": "d35f732e897f46068bfe40453b01a000dd2b263ef498abc34e7b57a015d5639470957779198a392720a98af3f330ea4409d75717a2bec090fb433ac071707f7b",
          "sha256": "746ca4f72e92b345119e93ee671bdc9894fa574cb4ef6f9931c3e9c38ff328d3",
          "sha1": "a316f5cb907523106cbb38ae1aad5133ee927735",
          "md5": "76f5ef75de50a8ff1fa02ab7c539c19c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestarconnections",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "codestarconnections-1.59.0-0.6.23.jar",
          "url": "codestarconnections-1.59.0-0.6.23.jar",
          "size": 9593,
          "sha512": "d35f732e897f46068bfe40453b01a000dd2b263ef498abc34e7b57a015d5639470957779198a392720a98af3f330ea4409d75717a2bec090fb433ac071707f7b",
          "sha256": "746ca4f72e92b345119e93ee671bdc9894fa574cb4ef6f9931c3e9c38ff328d3",
          "sha1": "a316f5cb907523106cbb38ae1aad5133ee927735",
          "md5": "76f5ef75de50a8ff1fa02ab7c539c19c"
        }
      ]
    }
  ]
}
