{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotthingsgraph",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotthingsgraph",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotthingsgraph-1.108.0-0.6.21.jar",
          "url": "iotthingsgraph-1.108.0-0.6.21.jar",
          "size": 22260,
          "sha512": "ca8ce33bd7a84e031bedaf209ee2adb0db4496a0f77b7857bea86768ef926c69d0ad235179e7eb953ea2b865bb20457a3b5f8ef6cea30a0bb26b317d161eae94",
          "sha256": "615905e44c4fc0ece29ab3321a38f93868a40d790620bc63f7df832a20f31fe7",
          "sha1": "5e6127c33d486db8e966f5965c962cd6d87619ac",
          "md5": "3cdf0034a5a28769398d8afeaec49a75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotthingsgraph",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotthingsgraph-1.108.0-0.6.21.jar",
          "url": "iotthingsgraph-1.108.0-0.6.21.jar",
          "size": 22260,
          "sha512": "ca8ce33bd7a84e031bedaf209ee2adb0db4496a0f77b7857bea86768ef926c69d0ad235179e7eb953ea2b865bb20457a3b5f8ef6cea30a0bb26b317d161eae94",
          "sha256": "615905e44c4fc0ece29ab3321a38f93868a40d790620bc63f7df832a20f31fe7",
          "sha1": "5e6127c33d486db8e966f5965c962cd6d87619ac",
          "md5": "3cdf0034a5a28769398d8afeaec49a75"
        }
      ]
    }
  ]
}
