{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "apprunner",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "apprunner",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apprunner-1.112.0-0.6.21.jar",
          "url": "apprunner-1.112.0-0.6.21.jar",
          "size": 134977,
          "sha512": "3075c59f17e0a34b5f7a9e5f399d7a86144548f8963fe9d4cd7e8ad87bfca791d81a3d382aae7dea923a89f57c192022afd659c74e90536c72675890bc337766",
          "sha256": "941ca25b5768950886927369fd8363590b84a198ede7967e446a5dd7ef724c7f",
          "sha1": "3233eb4f4f3e1720d4d0ecb19ff1ee8862024295",
          "md5": "ec4eab431b44698a084b398c8370d71c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "apprunner",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apprunner-1.112.0-0.6.21.jar",
          "url": "apprunner-1.112.0-0.6.21.jar",
          "size": 134977,
          "sha512": "3075c59f17e0a34b5f7a9e5f399d7a86144548f8963fe9d4cd7e8ad87bfca791d81a3d382aae7dea923a89f57c192022afd659c74e90536c72675890bc337766",
          "sha256": "941ca25b5768950886927369fd8363590b84a198ede7967e446a5dd7ef724c7f",
          "sha1": "3233eb4f4f3e1720d4d0ecb19ff1ee8862024295",
          "md5": "ec4eab431b44698a084b398c8370d71c"
        }
      ]
    }
  ]
}
