{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "directoryservice",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "directoryservice",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "directoryservice-1.108.1-0.6.21.jar",
          "url": "directoryservice-1.108.1-0.6.21.jar",
          "size": 77711,
          "sha512": "7c4403db7d4571e81cc64991ecd9689fdb418d8c1c5c6d332580b6617d034d9f55a5aaaeba80bf2e7672789262108f095f37b7addd946358971b8e345caef4d4",
          "sha256": "13195bc1bcf4e854e156fe6636a35d9df45c78dfa177c519f818926cdb6f5411",
          "sha1": "d24f7f49c8c3e9ed6e9ae29d0d19a0823fef9841",
          "md5": "e1dede7233b7ed42bd29aac6d381f9fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "directoryservice",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "directoryservice-1.108.1-0.6.21.jar",
          "url": "directoryservice-1.108.1-0.6.21.jar",
          "size": 77711,
          "sha512": "7c4403db7d4571e81cc64991ecd9689fdb418d8c1c5c6d332580b6617d034d9f55a5aaaeba80bf2e7672789262108f095f37b7addd946358971b8e345caef4d4",
          "sha256": "13195bc1bcf4e854e156fe6636a35d9df45c78dfa177c519f818926cdb6f5411",
          "sha1": "d24f7f49c8c3e9ed6e9ae29d0d19a0823fef9841",
          "md5": "e1dede7233b7ed42bd29aac6d381f9fa"
        }
      ]
    }
  ]
}
