{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "connect",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "connect",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "connect-1.113.0-0.6.21.jar",
          "url": "connect-1.113.0-0.6.21.jar",
          "size": 46877,
          "sha512": "a90a37f3b210cb8b1ab9277dfc32da17b2e1e6efe2ff4b3a24816a7770152b2afb3c05e0f978b43fb85b6e5cac9bccb7c2860e2b757f07b3b73d4155cc2adc9e",
          "sha256": "925af965960ea8da3576a313d209f43def8568b87da1a50a55fdfc3a36cf44fc",
          "sha1": "550dadc78571be94994656f94ab8859cd1175366",
          "md5": "119562cafb0fd9b2e215dcfbca9c2ac5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "connect",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "connect-1.113.0-0.6.21.jar",
          "url": "connect-1.113.0-0.6.21.jar",
          "size": 46877,
          "sha512": "a90a37f3b210cb8b1ab9277dfc32da17b2e1e6efe2ff4b3a24816a7770152b2afb3c05e0f978b43fb85b6e5cac9bccb7c2860e2b757f07b3b73d4155cc2adc9e",
          "sha256": "925af965960ea8da3576a313d209f43def8568b87da1a50a55fdfc3a36cf44fc",
          "sha1": "550dadc78571be94994656f94ab8859cd1175366",
          "md5": "119562cafb0fd9b2e215dcfbca9c2ac5"
        }
      ]
    }
  ]
}
