{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "apigatewayv2-integrations",
    "version": "1.106.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "apa3jttzlbgsjbklj7vcehaque"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "apigatewayv2-integrations",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "apigatewayv2",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "servicediscovery",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apigatewayv2-integrations-1.106.1-0.6.21.jar",
          "url": "apigatewayv2-integrations-1.106.1-0.6.21.jar",
          "size": 47903,
          "sha512": "7dfdc953cf83fdee1ca76823a3716299047ded634f3af7709ce5aa86307df755f632f97c17760b54b3b6008eda85443b1a83af4676305f794031e0fb47209de2",
          "sha256": "2665da87ecb54c500aede6f38a45503e78e4670382e94e8809164ec79ca27647",
          "sha1": "ced31cf3c857e6a34a9f982edcc3ea62fb3fa89f",
          "md5": "43176653050d6b136a8065a4201c41bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "apigatewayv2-integrations",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "apigatewayv2",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "servicediscovery",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apigatewayv2-integrations-1.106.1-0.6.21.jar",
          "url": "apigatewayv2-integrations-1.106.1-0.6.21.jar",
          "size": 47903,
          "sha512": "7dfdc953cf83fdee1ca76823a3716299047ded634f3af7709ce5aa86307df755f632f97c17760b54b3b6008eda85443b1a83af4676305f794031e0fb47209de2",
          "sha256": "2665da87ecb54c500aede6f38a45503e78e4670382e94e8809164ec79ca27647",
          "sha1": "ced31cf3c857e6a34a9f982edcc3ea62fb3fa89f",
          "md5": "43176653050d6b136a8065a4201c41bc"
        }
      ]
    }
  ]
}
