{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "accessanalyzer",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "accessanalyzer",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "accessanalyzer-1.105.0-0.6.21.jar",
          "url": "accessanalyzer-1.105.0-0.6.21.jar",
          "size": 35428,
          "sha512": "5bd684ef849e75b349c55972f486c4b7be85fca75d1c5592c9dcce3e17a80f050fd3dd42b97138874b83c0073cd421025b9d21916edd6717bb0505fe1823791b",
          "sha256": "d7e999d144b22cafc946469b7acdbda098d809494d8a6e670da910a50ef7543e",
          "sha1": "649c870cb72b731b23dcc09a369c4f8d65827724",
          "md5": "9efc90e41a583db349e3a02edb59405e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "accessanalyzer",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "accessanalyzer-1.105.0-0.6.21.jar",
          "url": "accessanalyzer-1.105.0-0.6.21.jar",
          "size": 35428,
          "sha512": "5bd684ef849e75b349c55972f486c4b7be85fca75d1c5592c9dcce3e17a80f050fd3dd42b97138874b83c0073cd421025b9d21916edd6717bb0505fe1823791b",
          "sha256": "d7e999d144b22cafc946469b7acdbda098d809494d8a6e670da910a50ef7543e",
          "sha1": "649c870cb72b731b23dcc09a369c4f8d65827724",
          "md5": "9efc90e41a583db349e3a02edb59405e"
        }
      ]
    }
  ]
}
