{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "emrcontainers",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "emrcontainers",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emrcontainers-1.108.0-0.6.21.jar",
          "url": "emrcontainers-1.108.0-0.6.21.jar",
          "size": 38496,
          "sha512": "6760f477e1de601ed111995584d510a0ef5fde2f432833ed3c813ade2998f7764a76fac9e9f72f06d7b08c2fa50be92329aee7e0ea38dd4f6129a12608ccc9f",
          "sha256": "7851db30b95fd87ce5d8e5d69e2e98c75f018d99de92273aaaa5b355eea35ca8",
          "sha1": "e5eda52b1bea531213824812633fb1d2248aa545",
          "md5": "f20b23feb3f9aeb066f2d12dedf7a93d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "emrcontainers",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emrcontainers-1.108.0-0.6.21.jar",
          "url": "emrcontainers-1.108.0-0.6.21.jar",
          "size": 38496,
          "sha512": "6760f477e1de601ed111995584d510a0ef5fde2f432833ed3c813ade2998f7764a76fac9e9f72f06d7b08c2fa50be92329aee7e0ea38dd4f6129a12608ccc9f",
          "sha256": "7851db30b95fd87ce5d8e5d69e2e98c75f018d99de92273aaaa5b355eea35ca8",
          "sha1": "e5eda52b1bea531213824812633fb1d2248aa545",
          "md5": "f20b23feb3f9aeb066f2d12dedf7a93d"
        }
      ]
    }
  ]
}
