{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cloudwatch-actions",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cloudwatch-actions",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "applicationautoscaling",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cloudwatch-actions-1.116.0-0.6.21.jar",
          "url": "cloudwatch-actions-1.116.0-0.6.21.jar",
          "size": 438,
          "sha512": "2cdd46c4eb213d382ba58c4d433701bf5bbb31470887da90ba993541a9f4fe5a0e7ea34b184d3b75670f076ca275a4c9aca524083cdfdb63224dc1b4ca2550ca",
          "sha256": "26ece84d2047a62deab68f4dd677691cb159cffb3e1114ba51645e0ef8578976",
          "sha1": "1c5f712c8fd4c28b72713a6ec9b81dfe923558a5",
          "md5": "c1197ee679771f997edb9460ad1bbf88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cloudwatch-actions",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "applicationautoscaling",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cloudwatch-actions-1.116.0-0.6.21.jar",
          "url": "cloudwatch-actions-1.116.0-0.6.21.jar",
          "size": 438,
          "sha512": "2cdd46c4eb213d382ba58c4d433701bf5bbb31470887da90ba993541a9f4fe5a0e7ea34b184d3b75670f076ca275a4c9aca524083cdfdb63224dc1b4ca2550ca",
          "sha256": "26ece84d2047a62deab68f4dd677691cb159cffb3e1114ba51645e0ef8578976",
          "sha1": "1c5f712c8fd4c28b72713a6ec9b81dfe923558a5",
          "md5": "c1197ee679771f997edb9460ad1bbf88"
        }
      ]
    }
  ]
}
