{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "licensemanager",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "licensemanager",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "licensemanager-1.108.0-0.6.21.jar",
          "url": "licensemanager-1.108.0-0.6.21.jar",
          "size": 110257,
          "sha512": "bdaa686848adeea07e33ec8f596eea7d710bbf4e40717c2295bf0a24d08ac9d941b6af4ffd88406b932678213ae7799e1349158e82064154adc8347026ab420f",
          "sha256": "2b8c6e9093884061a3935899b25371a3cf3d1781eed20ee9a26665487157e2f3",
          "sha1": "119251e7dd74c524a81f996fc0e86638295d84f4",
          "md5": "f7faed35a530bcf999b2b9b06fc1e673"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "licensemanager",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "licensemanager-1.108.0-0.6.21.jar",
          "url": "licensemanager-1.108.0-0.6.21.jar",
          "size": 110257,
          "sha512": "bdaa686848adeea07e33ec8f596eea7d710bbf4e40717c2295bf0a24d08ac9d941b6af4ffd88406b932678213ae7799e1349158e82064154adc8347026ab420f",
          "sha256": "2b8c6e9093884061a3935899b25371a3cf3d1781eed20ee9a26665487157e2f3",
          "sha1": "119251e7dd74c524a81f996fc0e86638295d84f4",
          "md5": "f7faed35a530bcf999b2b9b06fc1e673"
        }
      ]
    }
  ]
}
