{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "finspace",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "finspace",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "finspace-1.107.0-0.6.21.jar",
          "url": "finspace-1.107.0-0.6.21.jar",
          "size": 23120,
          "sha512": "7f5018f2e78606d312a3d34e4acef891cc04724abd531249685325919533e85d79b3f345865e5b13f95bcfbb1cf15a4a5c0320b672f788f0f84bdf86b2d58261",
          "sha256": "ee7a80086009e885228d25d2965f9196079c2f8681addaf6cabaeebdff33fe6f",
          "sha1": "10f86af38db3a6236ad5820d19c562818cff5a04",
          "md5": "3728e7f924832fdc4e3912f22622eca1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "finspace",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "finspace-1.107.0-0.6.21.jar",
          "url": "finspace-1.107.0-0.6.21.jar",
          "size": 23120,
          "sha512": "7f5018f2e78606d312a3d34e4acef891cc04724abd531249685325919533e85d79b3f345865e5b13f95bcfbb1cf15a4a5c0320b672f788f0f84bdf86b2d58261",
          "sha256": "ee7a80086009e885228d25d2965f9196079c2f8681addaf6cabaeebdff33fe6f",
          "sha1": "10f86af38db3a6236ad5820d19c562818cff5a04",
          "md5": "3728e7f924832fdc4e3912f22622eca1"
        }
      ]
    }
  ]
}
