{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "dax",
    "version": "1.64.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "dax",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "dax-1.64.0-0.6.22.jar",
          "url": "dax-1.64.0-0.6.22.jar",
          "size": 42378,
          "sha512": "e390ec7e6fe2d1ee795c84b1b2439cac643d229ed939399f145f6289c5246dca9d91417cdffed91088fb8f544b83e15f74be56e85a0d6ece8dcc5301e5aceee1",
          "sha256": "72ad8290be88b39042a0b01de986106314899250e7a75a8eb130049a0ed51b7a",
          "sha1": "2e09579eb12f8ae6a84baf0f74fdfcb14d1c1cdd",
          "md5": "abde7d8153190d07c6486fc431b00e34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "dax",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "dax-1.64.0-0.6.22.jar",
          "url": "dax-1.64.0-0.6.22.jar",
          "size": 42378,
          "sha512": "e390ec7e6fe2d1ee795c84b1b2439cac643d229ed939399f145f6289c5246dca9d91417cdffed91088fb8f544b83e15f74be56e85a0d6ece8dcc5301e5aceee1",
          "sha256": "72ad8290be88b39042a0b01de986106314899250e7a75a8eb130049a0ed51b7a",
          "sha1": "2e09579eb12f8ae6a84baf0f74fdfcb14d1c1cdd",
          "md5": "abde7d8153190d07c6486fc431b00e34"
        }
      ]
    }
  ]
}
