{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "signer",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "signer",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "signer-1.106.0-0.6.21.jar",
          "url": "signer-1.106.0-0.6.21.jar",
          "size": 40345,
          "sha512": "187163a8c533a785973fcb8cbf447773a52dd1f7403e338abf6833dba84fb3c72fd5c48e98e6f64b8d4ac1f8c59db85589b9596d3c35d301f59b67b114bcb2e5",
          "sha256": "b50555a8db93b38d13b52f29dc634751874c62a9b67915409d5fc2b539d18505",
          "sha1": "fc1e9bb033d66c6d9dbc7ea96ef5b7106e36bc1b",
          "md5": "93ef360d30707769fb258c633de6ba1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "signer",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "signer-1.106.0-0.6.21.jar",
          "url": "signer-1.106.0-0.6.21.jar",
          "size": 40345,
          "sha512": "187163a8c533a785973fcb8cbf447773a52dd1f7403e338abf6833dba84fb3c72fd5c48e98e6f64b8d4ac1f8c59db85589b9596d3c35d301f59b67b114bcb2e5",
          "sha256": "b50555a8db93b38d13b52f29dc634751874c62a9b67915409d5fc2b539d18505",
          "sha1": "fc1e9bb033d66c6d9dbc7ea96ef5b7106e36bc1b",
          "md5": "93ef360d30707769fb258c633de6ba1d"
        }
      ]
    }
  ]
}
