{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "wafregional",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.108.1-0.6.21.jar",
          "url": "wafregional-1.108.1-0.6.21.jar",
          "size": 251046,
          "sha512": "24c784993669018205629cfcc7a436b081e38d74fc2bbf2de4272689fafe2a19b9533b4b79093cdc742c76861238899532e090141e287458010e449fa0d9162a",
          "sha256": "48e427eecb19ce7a5896cf2590cc061eb0c70391bb90cdafb033c4e06ee26ceb",
          "sha1": "27bae6961c84f634a88df2fb97ade67014b63137",
          "md5": "a4c71a407c2b0d676c1e42c02cca2c91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.108.1-0.6.21.jar",
          "url": "wafregional-1.108.1-0.6.21.jar",
          "size": 251046,
          "sha512": "24c784993669018205629cfcc7a436b081e38d74fc2bbf2de4272689fafe2a19b9533b4b79093cdc742c76861238899532e090141e287458010e449fa0d9162a",
          "sha256": "48e427eecb19ce7a5896cf2590cc061eb0c70391bb90cdafb033c4e06ee26ceb",
          "sha1": "27bae6961c84f634a88df2fb97ade67014b63137",
          "md5": "a4c71a407c2b0d676c1e42c02cca2c91"
        }
      ]
    }
  ]
}
