{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lookoutvision",
    "version": "1.101.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "jaowebu54rhl3bnpwvdhdg2v5y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lookoutvision",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lookoutvision-1.101.0-0.6.21.jar",
          "url": "lookoutvision-1.101.0-0.6.21.jar",
          "size": 8632,
          "sha512": "85c20b7995926630235c4998c4eb41d05187df654b5cb10d6a2ec259432e4b5ec1a4efabf3b50fb626e298b244fb9b48b0602e5961990e092c1b2f889e6b500c",
          "sha256": "a58d0797f8b79e33c2a816f2dc4a4c6a209c094aadf9a2c6771b6455e17647ad",
          "sha1": "bb7114cdd823ead348cd8c22c52384f479ebbd50",
          "md5": "6262dd051fa0d01a67345e6f0eea421c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lookoutvision",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lookoutvision-1.101.0-0.6.21.jar",
          "url": "lookoutvision-1.101.0-0.6.21.jar",
          "size": 8632,
          "sha512": "85c20b7995926630235c4998c4eb41d05187df654b5cb10d6a2ec259432e4b5ec1a4efabf3b50fb626e298b244fb9b48b0602e5961990e092c1b2f889e6b500c",
          "sha256": "a58d0797f8b79e33c2a816f2dc4a4c6a209c094aadf9a2c6771b6455e17647ad",
          "sha1": "bb7114cdd823ead348cd8c22c52384f479ebbd50",
          "md5": "6262dd051fa0d01a67345e6f0eea421c"
        }
      ]
    }
  ]
}
