{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "finspace",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "finspace",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "finspace-1.104.0-0.6.21.jar",
          "url": "finspace-1.104.0-0.6.21.jar",
          "size": 23117,
          "sha512": "87c29ae37eca88d64500e20ed3a2535f180145ac40b90924987697e25d0059eea3bd8571333452821d97d09d1e98fd871b1ff7bac8593c43e9721cd7c206b409",
          "sha256": "d10d2a6bb873877034cb1503eed0f0b30ad3f963b4b1f4e537676c21292946e5",
          "sha1": "984b5467f7374bb804f6ec3ff7ba716dde714214",
          "md5": "269ed89a8f76cbe6a8bd1f1751dcd079"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "finspace",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "finspace-1.104.0-0.6.21.jar",
          "url": "finspace-1.104.0-0.6.21.jar",
          "size": 23117,
          "sha512": "87c29ae37eca88d64500e20ed3a2535f180145ac40b90924987697e25d0059eea3bd8571333452821d97d09d1e98fd871b1ff7bac8593c43e9721cd7c206b409",
          "sha256": "d10d2a6bb873877034cb1503eed0f0b30ad3f963b4b1f4e537676c21292946e5",
          "sha1": "984b5467f7374bb804f6ec3ff7ba716dde714214",
          "md5": "269ed89a8f76cbe6a8bd1f1751dcd079"
        }
      ]
    }
  ]
}
