{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "certificatemanager",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "certificatemanager",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "certificatemanager-1.116.0-0.6.21.jar",
          "url": "certificatemanager-1.116.0-0.6.21.jar",
          "size": 64653,
          "sha512": "41e7b123e8bfafcca76ef90c6d09010800aa0201ebccecbf39b521f65434914ac2f83ab8208a66c7405981d12a0a25601f144546f70ad4047cb7fd4833c6bf64",
          "sha256": "9ea6668e9c366f396c5420aed64b1a36a98b5b24158715c744ab5b74f4a5959b",
          "sha1": "51c7a2442066fa78481ef4afd33116e5408490a9",
          "md5": "19791de96308c2d4449fb825c01990c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "certificatemanager",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "certificatemanager-1.116.0-0.6.21.jar",
          "url": "certificatemanager-1.116.0-0.6.21.jar",
          "size": 64653,
          "sha512": "41e7b123e8bfafcca76ef90c6d09010800aa0201ebccecbf39b521f65434914ac2f83ab8208a66c7405981d12a0a25601f144546f70ad4047cb7fd4833c6bf64",
          "sha256": "9ea6668e9c366f396c5420aed64b1a36a98b5b24158715c744ab5b74f4a5959b",
          "sha1": "51c7a2442066fa78481ef4afd33116e5408490a9",
          "md5": "19791de96308c2d4449fb825c01990c"
        }
      ]
    }
  ]
}
