{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lambda-go",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-go",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-go-1.118.0-0.6.25.jar",
          "url": "lambda-go-1.118.0-0.6.25.jar",
          "size": 24381,
          "sha512": "6134479876543b577e8d010b57c0aa6483d11a61aef216797aaf88bfdbdac9875a2e893e439523a7c3492e7bffe467ad9a42e924e5b3821be18fe5836abdd1c0",
          "sha256": "404ea23c951a23a4fc359763973206a545a3692a4c547141131944dba05c8836",
          "sha1": "a81c8bad3cdcb469eebaad391cab24d4f0c33124",
          "md5": "49d9b6f133b7b4dab17ac333595d1084"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-go",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-go-1.118.0-0.6.25.jar",
          "url": "lambda-go-1.118.0-0.6.25.jar",
          "size": 24381,
          "sha512": "6134479876543b577e8d010b57c0aa6483d11a61aef216797aaf88bfdbdac9875a2e893e439523a7c3492e7bffe467ad9a42e924e5b3821be18fe5836abdd1c0",
          "sha256": "404ea23c951a23a4fc359763973206a545a3692a4c547141131944dba05c8836",
          "sha1": "a81c8bad3cdcb469eebaad391cab24d4f0c33124",
          "md5": "49d9b6f133b7b4dab17ac333595d1084"
        }
      ]
    }
  ]
}
