{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-cx-api",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "pksuzuox3ne6pgnvsva7g32w2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cx-api-1.110.1-0.6.21.jar",
          "url": "cdk-cx-api-1.110.1-0.6.21.jar",
          "size": 76020,
          "sha512": "571df016ce046a2025a1621761b97fbb502f5f515041289883beb190128b3944cf974ae4be805b3835447789b41ee89cce69d171c7c41ba80a12d0bc78fc98b1",
          "sha256": "3239ff80c9637d712dbc7344e2079c39325ccd026523fceb1ce221e2ddeb032c",
          "sha1": "40c89c1341f9af9decd893ac2e4c8aae70be7271",
          "md5": "92fd7ac9d8adf73233bda15d70413d4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cx-api-1.110.1-0.6.21.jar",
          "url": "cdk-cx-api-1.110.1-0.6.21.jar",
          "size": 76020,
          "sha512": "571df016ce046a2025a1621761b97fbb502f5f515041289883beb190128b3944cf974ae4be805b3835447789b41ee89cce69d171c7c41ba80a12d0bc78fc98b1",
          "sha256": "3239ff80c9637d712dbc7344e2079c39325ccd026523fceb1ce221e2ddeb032c",
          "sha1": "40c89c1341f9af9decd893ac2e4c8aae70be7271",
          "md5": "92fd7ac9d8adf73233bda15d70413d4c"
        }
      ]
    }
  ]
}
