{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-assets",
    "version": "1.64.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-1.64.0-0.6.23.jar",
          "url": "cdk-assets-1.64.0-0.6.23.jar",
          "size": 15761,
          "sha512": "ec4485998c8258f1b97f2385411cfefa8b103d76e24f0f8df2d1147b92deb465c7b22c8a9ee4b7b3afb590f08a12f6a03e4ab7fadde66f9af3f1fc15f8e94e84",
          "sha256": "95f7ff7bf0df7d10b7ff37d9641957f3d5ad670a2f628fb3cc51704098912427",
          "sha1": "d6985df7b938c654658fc8c5ee2a796a89a803a2",
          "md5": "497e4fcfdc752667a650942bdb50edcc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-1.64.0-0.6.23.jar",
          "url": "cdk-assets-1.64.0-0.6.23.jar",
          "size": 15761,
          "sha512": "ec4485998c8258f1b97f2385411cfefa8b103d76e24f0f8df2d1147b92deb465c7b22c8a9ee4b7b3afb590f08a12f6a03e4ab7fadde66f9af3f1fc15f8e94e84",
          "sha256": "95f7ff7bf0df7d10b7ff37d9641957f3d5ad670a2f628fb3cc51704098912427",
          "sha1": "d6985df7b938c654658fc8c5ee2a796a89a803a2",
          "md5": "497e4fcfdc752667a650942bdb50edcc"
        }
      ]
    }
  ]
}
