{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lookoutmetrics",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lookoutmetrics",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lookoutmetrics-1.112.0-0.6.21.jar",
          "url": "lookoutmetrics-1.112.0-0.6.21.jar",
          "size": 141079,
          "sha512": "ec6d0269872a6bcfa2d6fd638ee09200f55d95a8afd814b0feb7dfb749b2922e556a0e9e534de2fe90e7b45ad57b420cf80cce8264e53fee84da096f6c0c6cb6",
          "sha256": "cfb974ac2c2b45dc6086f8bbd2b907e5f91e8e2e1ba87ee5fa9691190b2098ba",
          "sha1": "1f376d217f3bbe2e4613511d9c2aba2ad900a11b",
          "md5": "65d903d3069d984939ad2a213af12d29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lookoutmetrics",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lookoutmetrics-1.112.0-0.6.21.jar",
          "url": "lookoutmetrics-1.112.0-0.6.21.jar",
          "size": 141079,
          "sha512": "ec6d0269872a6bcfa2d6fd638ee09200f55d95a8afd814b0feb7dfb749b2922e556a0e9e534de2fe90e7b45ad57b420cf80cce8264e53fee84da096f6c0c6cb6",
          "sha256": "cfb974ac2c2b45dc6086f8bbd2b907e5f91e8e2e1ba87ee5fa9691190b2098ba",
          "sha1": "1f376d217f3bbe2e4613511d9c2aba2ad900a11b",
          "md5": "65d903d3069d984939ad2a213af12d29"
        }
      ]
    }
  ]
}
