{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sdb",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sdb",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdb-1.115.0-0.6.21.jar",
          "url": "sdb-1.115.0-0.6.21.jar",
          "size": 8444,
          "sha512": "a16411eb90856e4ef7b3142b254ec06a57ff8591d05e852b290d497cd95c32a8981294c19735684597a6a6648171c6de449146e65d203258e656a724befab475",
          "sha256": "319fe029da6704be73594d46ce3a8657727e89e12ff9c6f35ffc00dbd7be3a4b",
          "sha1": "6b4aa6c6c58dde291ab19bf606c3382ba2a31453",
          "md5": "86a455c893cff82ac725f4518a6b0f30"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sdb",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdb-1.115.0-0.6.21.jar",
          "url": "sdb-1.115.0-0.6.21.jar",
          "size": 8444,
          "sha512": "a16411eb90856e4ef7b3142b254ec06a57ff8591d05e852b290d497cd95c32a8981294c19735684597a6a6648171c6de449146e65d203258e656a724befab475",
          "sha256": "319fe029da6704be73594d46ce3a8657727e89e12ff9c6f35ffc00dbd7be3a4b",
          "sha1": "6b4aa6c6c58dde291ab19bf606c3382ba2a31453",
          "md5": "86a455c893cff82ac725f4518a6b0f30"
        }
      ]
    }
  ]
}
