{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-yaml-cfn",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-yaml-cfn",
          "version": {
            "requires": "1.107.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-yaml-cfn-1.107.0-0.6.21.jar",
          "url": "cdk-yaml-cfn-1.107.0-0.6.21.jar",
          "size": 426,
          "sha512": "d81b04c160c066471fc87d21a08e8f9b342f551cb491a9ebcf7de79ba8dac80a92ef7bce6d77258a3c5cfd2e19e6bfc382d1e1aa8be2d6ecfa2f8d69c32afe5c",
          "sha256": "53c4825931487f5dc8ecb039c5463435a357481454738b6e0950787bbccbfc59",
          "sha1": "ee85fe9ea8df996f9fd81db68d29272869baefae",
          "md5": "f49738e9af62c37728523337f7ee82bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-yaml-cfn",
          "version": {
            "requires": "1.107.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-yaml-cfn-1.107.0-0.6.21.jar",
          "url": "cdk-yaml-cfn-1.107.0-0.6.21.jar",
          "size": 426,
          "sha512": "d81b04c160c066471fc87d21a08e8f9b342f551cb491a9ebcf7de79ba8dac80a92ef7bce6d77258a3c5cfd2e19e6bfc382d1e1aa8be2d6ecfa2f8d69c32afe5c",
          "sha256": "53c4825931487f5dc8ecb039c5463435a357481454738b6e0950787bbccbfc59",
          "sha1": "ee85fe9ea8df996f9fd81db68d29272869baefae",
          "md5": "f49738e9af62c37728523337f7ee82bf"
        }
      ]
    }
  ]
}
