{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-yaml-cfn",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-yaml-cfn",
          "version": {
            "requires": "1.118.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-yaml-cfn-1.118.0-0.6.25.jar",
          "url": "cdk-yaml-cfn-1.118.0-0.6.25.jar",
          "size": 426,
          "sha512": "83a7f13f23e6464250cc8653f4b31f4d50ea93d9da5ffe2229393ece8ac50bf033ce5ce6711591907e4f0be50ebed6a059e705b69ca7164a645301ac2a255b14",
          "sha256": "af7032c58bfa67fdee7ffc1edfec80ceae47692ecd180895098d5674d0d392cf",
          "sha1": "7e22d76a5583d0c729b7e9d7d09f7d91b854fbc9",
          "md5": "5431acd6dd6f656f0eeaa99930a8d8e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-yaml-cfn",
          "version": {
            "requires": "1.118.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-yaml-cfn-1.118.0-0.6.25.jar",
          "url": "cdk-yaml-cfn-1.118.0-0.6.25.jar",
          "size": 426,
          "sha512": "83a7f13f23e6464250cc8653f4b31f4d50ea93d9da5ffe2229393ece8ac50bf033ce5ce6711591907e4f0be50ebed6a059e705b69ca7164a645301ac2a255b14",
          "sha256": "af7032c58bfa67fdee7ffc1edfec80ceae47692ecd180895098d5674d0d392cf",
          "sha1": "7e22d76a5583d0c729b7e9d7d09f7d91b854fbc9",
          "md5": "5431acd6dd6f656f0eeaa99930a8d8e4"
        }
      ]
    }
  ]
}
