{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "autoscaling-common",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling-common",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-common-1.106.0-0.6.21.jar",
          "url": "autoscaling-common-1.106.0-0.6.21.jar",
          "size": 15780,
          "sha512": "554d106db5e077cef2fa956ef028af3f6d349c133da66365488fd5ce53d2836f3b8fbbff11058f40a197e7e3f9a6992d1b5bd4c4d765640d03a63bc8dea31832",
          "sha256": "e5df3b6ba9dcd2b542e966bde8a820a71127c1517a5f163134e471b940d845ac",
          "sha1": "90f1710c41efdb5fd71f435c6c5ecbd1b231dd64",
          "md5": "86ad41d025a5a444e718054f0b9215fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling-common",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-common-1.106.0-0.6.21.jar",
          "url": "autoscaling-common-1.106.0-0.6.21.jar",
          "size": 15780,
          "sha512": "554d106db5e077cef2fa956ef028af3f6d349c133da66365488fd5ce53d2836f3b8fbbff11058f40a197e7e3f9a6992d1b5bd4c4d765640d03a63bc8dea31832",
          "sha256": "e5df3b6ba9dcd2b542e966bde8a820a71127c1517a5f163134e471b940d845ac",
          "sha1": "90f1710c41efdb5fd71f435c6c5ecbd1b231dd64",
          "md5": "86ad41d025a5a444e718054f0b9215fd"
        }
      ]
    }
  ]
}
