{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotwireless",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotwireless",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotwireless-1.114.0-0.6.21.jar",
          "url": "iotwireless-1.114.0-0.6.21.jar",
          "size": 308927,
          "sha512": "4aa1d70cc15f0b3e1c73ce2c9999a612f5a9da7dff8a20c00bae170578e34a828e18e70dd26c530ccbc99b269a8f8fa16cdf74f6a753e55418993c9b9a2d07e5",
          "sha256": "4410a37f2c816528134845fcbc79be4f6467713e82e9989ae2524650a0a37f46",
          "sha1": "ce0b773abce95d72253dddbab3abb28290728c95",
          "md5": "6815ceba4bfcf58b70462085f8a44896"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotwireless",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotwireless-1.114.0-0.6.21.jar",
          "url": "iotwireless-1.114.0-0.6.21.jar",
          "size": 308927,
          "sha512": "4aa1d70cc15f0b3e1c73ce2c9999a612f5a9da7dff8a20c00bae170578e34a828e18e70dd26c530ccbc99b269a8f8fa16cdf74f6a753e55418993c9b9a2d07e5",
          "sha256": "4410a37f2c816528134845fcbc79be4f6467713e82e9989ae2524650a0a37f46",
          "sha1": "ce0b773abce95d72253dddbab3abb28290728c95",
          "md5": "6815ceba4bfcf58b70462085f8a44896"
        }
      ]
    }
  ]
}
