{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codecommit",
    "version": "1.31.0-unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codecommit",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "codecommit-1.31.0-unspecified.jar",
          "url": "codecommit-1.31.0-unspecified.jar",
          "size": 56431,
          "sha512": "37aae4c178a4d1154e783a2ae7b1ad71e6843539bf789f0aca3b6b296e14fab94eeb8663a574e08fbd09d5130354b35c479773927c6ab448325c4906ebe9de71",
          "sha256": "8b9dd2a4227a0f511aa8ad8a6388b2a66dd7e941b9d241f2529b7dd27630be4c",
          "sha1": "2b4bb12ee0bce77fc5ea13b28b62976f398dcd81",
          "md5": "4e3e8b9fe83863a1b306927a9b949a27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codecommit",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "codecommit-1.31.0-unspecified.jar",
          "url": "codecommit-1.31.0-unspecified.jar",
          "size": 56431,
          "sha512": "37aae4c178a4d1154e783a2ae7b1ad71e6843539bf789f0aca3b6b296e14fab94eeb8663a574e08fbd09d5130354b35c479773927c6ab448325c4906ebe9de71",
          "sha256": "8b9dd2a4227a0f511aa8ad8a6388b2a66dd7e941b9d241f2529b7dd27630be4c",
          "sha1": "2b4bb12ee0bce77fc5ea13b28b62976f398dcd81",
          "md5": "4e3e8b9fe83863a1b306927a9b949a27"
        }
      ]
    }
  ]
}
