{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "directoryservice",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "directoryservice",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "directoryservice-1.117.0-0.6.25.jar",
          "url": "directoryservice-1.117.0-0.6.25.jar",
          "size": 77682,
          "sha512": "748a098801e185896703c5b1029188ebb5d19c49e484ba7cc5b0fe56a97c6c811666cbe9ad096d73bd838519cee3d972395891ec015125fbbacdc06be78b9ec2",
          "sha256": "7b20f3b7106c07fa946e22e68d8a63c9ffaed3aab4fbe837ea9c6562895560a5",
          "sha1": "c9c719fb92a7b74b08e999bb4ab5f332c1c759aa",
          "md5": "2bf7f43d267ea3f5da33da84c807e642"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "directoryservice",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "directoryservice-1.117.0-0.6.25.jar",
          "url": "directoryservice-1.117.0-0.6.25.jar",
          "size": 77682,
          "sha512": "748a098801e185896703c5b1029188ebb5d19c49e484ba7cc5b0fe56a97c6c811666cbe9ad096d73bd838519cee3d972395891ec015125fbbacdc06be78b9ec2",
          "sha256": "7b20f3b7106c07fa946e22e68d8a63c9ffaed3aab4fbe837ea9c6562895560a5",
          "sha1": "c9c719fb92a7b74b08e999bb4ab5f332c1c759aa",
          "md5": "2bf7f43d267ea3f5da33da84c807e642"
        }
      ]
    }
  ]
}
