{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "accessanalyzer",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "accessanalyzer",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "accessanalyzer-1.114.0-0.6.21.jar",
          "url": "accessanalyzer-1.114.0-0.6.21.jar",
          "size": 35430,
          "sha512": "b22683335f9a625d28cc61344d9af5a0ed410e2bcd1f3d021a1676c1032151055b20c87e2cdbb95959aec8d3e3454b703f93848b709a47aa492891bae8705ca",
          "sha256": "3d4aa1d9b21f7b7bd2c5f3912cf4edf773a05d1aae1ffedc67b7264c70f0758c",
          "sha1": "670ea83cc293542c9649bc2272b772960c2aa3cd",
          "md5": "11982a565b74d44c3467220ad550f917"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "accessanalyzer",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "accessanalyzer-1.114.0-0.6.21.jar",
          "url": "accessanalyzer-1.114.0-0.6.21.jar",
          "size": 35430,
          "sha512": "b22683335f9a625d28cc61344d9af5a0ed410e2bcd1f3d021a1676c1032151055b20c87e2cdbb95959aec8d3e3454b703f93848b709a47aa492891bae8705ca",
          "sha256": "3d4aa1d9b21f7b7bd2c5f3912cf4edf773a05d1aae1ffedc67b7264c70f0758c",
          "sha1": "670ea83cc293542c9649bc2272b772960c2aa3cd",
          "md5": "11982a565b74d44c3467220ad550f917"
        }
      ]
    }
  ]
}
