{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "wafregional",
    "version": "1.98.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.98.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.98.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.98.0-0.6.25.jar",
          "url": "wafregional-1.98.0-0.6.25.jar",
          "size": 251085,
          "sha512": "fd5f854d4a78e4192018b4df58dd7a8ceac9e8643ffcd9640c555bf4cccaddb4c477ecf4e773a7f75c1ab5ee731023b82671fb4f3d4f776e0a326338e0e981bb",
          "sha256": "c7016d2eda54cd3323f8763be7c932fb8b31e45944ace4121b5af5bb9a778b1e",
          "sha1": "fab78ade60147b1246de46610cc242476f6a15d9",
          "md5": "e832915dc379a250cba1003887d5d3ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.98.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.98.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.98.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.98.0-0.6.25.jar",
          "url": "wafregional-1.98.0-0.6.25.jar",
          "size": 251085,
          "sha512": "fd5f854d4a78e4192018b4df58dd7a8ceac9e8643ffcd9640c555bf4cccaddb4c477ecf4e773a7f75c1ab5ee731023b82671fb4f3d4f776e0a326338e0e981bb",
          "sha256": "c7016d2eda54cd3323f8763be7c932fb8b31e45944ace4121b5af5bb9a778b1e",
          "sha1": "fab78ade60147b1246de46610cc242476f6a15d9",
          "md5": "e832915dc379a250cba1003887d5d3ce"
        }
      ]
    }
  ]
}
