{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iot",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iot",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iot-1.99.0-0.6.21.jar",
          "url": "iot-1.99.0-0.6.21.jar",
          "size": 735621,
          "sha512": "6dbf1e4f49990625718f672121d875d1bb9829ecde50ebadd62bccbf4df83a020ff326efda87ad92b57cd6cb8f590e9d82aa44019757990e1f8393aba9ea7d19",
          "sha256": "389e4b637691b427da1cb58d08488077e3e0a757b6364a52ce9aeace214a4066",
          "sha1": "8a20a107de0c513efb96e78f5c051fc65eeadc40",
          "md5": "f6fed90fcfea1a047f6822fad437b340"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iot",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iot-1.99.0-0.6.21.jar",
          "url": "iot-1.99.0-0.6.21.jar",
          "size": 735621,
          "sha512": "6dbf1e4f49990625718f672121d875d1bb9829ecde50ebadd62bccbf4df83a020ff326efda87ad92b57cd6cb8f590e9d82aa44019757990e1f8393aba9ea7d19",
          "sha256": "389e4b637691b427da1cb58d08488077e3e0a757b6364a52ce9aeace214a4066",
          "sha1": "8a20a107de0c513efb96e78f5c051fc65eeadc40",
          "md5": "f6fed90fcfea1a047f6822fad437b340"
        }
      ]
    }
  ]
}
