{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "alexa-ask",
    "version": "1.64.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "alexa-ask",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "alexa-ask-1.64.0-0.6.22.jar",
          "url": "alexa-ask-1.64.0-0.6.22.jar",
          "size": 41745,
          "sha512": "d047f99a1763f120e1da79378cb96b38a959933f2334bd008d759368d47eb5d550c80962ba548687a3cc9038881e9dff2f93c744fe9105a39df8b14cd6c4ca2a",
          "sha256": "7334c9400df6666dbb562a8cd89146582f77f65ca8faba6df0fee5a991248538",
          "sha1": "b07c73f42d54397765e70aa952224a55e60b57d4",
          "md5": "cbac1d0e418782c47bff4ace0e9c6021"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "alexa-ask",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "alexa-ask-1.64.0-0.6.22.jar",
          "url": "alexa-ask-1.64.0-0.6.22.jar",
          "size": 41745,
          "sha512": "d047f99a1763f120e1da79378cb96b38a959933f2334bd008d759368d47eb5d550c80962ba548687a3cc9038881e9dff2f93c744fe9105a39df8b14cd6c4ca2a",
          "sha256": "7334c9400df6666dbb562a8cd89146582f77f65ca8faba6df0fee5a991248538",
          "sha1": "b07c73f42d54397765e70aa952224a55e60b57d4",
          "md5": "cbac1d0e418782c47bff4ace0e9c6021"
        }
      ]
    }
  ]
}
