{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-lambda-layer-awscli",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-lambda-layer-awscli",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-lambda-layer-awscli-1.107.0-0.6.21.jar",
          "url": "cdk-lambda-layer-awscli-1.107.0-0.6.21.jar",
          "size": 448,
          "sha512": "21fa394f8c7ac64d4bb2fb300c50e8aebbefa3252c7a697afd435a341fdc6935c7ffdcc3e38110a6716068ce1f6a1be13eacc6356a31ec4211860c694682bd28",
          "sha256": "7a08c4b3047438a88648c11ea8c15a3d68fe4a92ec57c25b7c90a9645edeb0fe",
          "sha1": "ecd5789796e7d5c63e1f4e7f5445735f8d8728ae",
          "md5": "77d5cbe26e8e1fe7c66593575f6a3e62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-lambda-layer-awscli",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-lambda-layer-awscli-1.107.0-0.6.21.jar",
          "url": "cdk-lambda-layer-awscli-1.107.0-0.6.21.jar",
          "size": 448,
          "sha512": "21fa394f8c7ac64d4bb2fb300c50e8aebbefa3252c7a697afd435a341fdc6935c7ffdcc3e38110a6716068ce1f6a1be13eacc6356a31ec4211860c694682bd28",
          "sha256": "7a08c4b3047438a88648c11ea8c15a3d68fe4a92ec57c25b7c90a9645edeb0fe",
          "sha1": "ecd5789796e7d5c63e1f4e7f5445735f8d8728ae",
          "md5": "77d5cbe26e8e1fe7c66593575f6a3e62"
        }
      ]
    }
  ]
}
