{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-region-info",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.103.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-region-info-1.103.0-0.6.21.jar",
          "url": "cdk-region-info-1.103.0-0.6.21.jar",
          "size": 432,
          "sha512": "9220b91ecfa1c84e95ef75b350d70706dd768bcdfa9f6ed06ba1332ecfdd97f77109b3fbe3526ae3105942c5afe26f634f416943bb43a28d69557078a9a45e0c",
          "sha256": "d138df7b7a4244ccb5d559736096dedcfebc274419d96794589f14417c8e501d",
          "sha1": "53d8d5b66ac2b40db602358669dfd0aa1e8eae03",
          "md5": "59a11e9ce39ae002bfaae8a48da36dfe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.103.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-region-info-1.103.0-0.6.21.jar",
          "url": "cdk-region-info-1.103.0-0.6.21.jar",
          "size": 432,
          "sha512": "9220b91ecfa1c84e95ef75b350d70706dd768bcdfa9f6ed06ba1332ecfdd97f77109b3fbe3526ae3105942c5afe26f634f416943bb43a28d69557078a9a45e0c",
          "sha256": "d138df7b7a4244ccb5d559736096dedcfebc274419d96794589f14417c8e501d",
          "sha1": "53d8d5b66ac2b40db602358669dfd0aa1e8eae03",
          "md5": "59a11e9ce39ae002bfaae8a48da36dfe"
        }
      ]
    }
  ]
}
