{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ivs",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "k23roxkwqjbs5i6arr4lg4r4xm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ivs",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ivs-1.110.1-0.6.21.jar",
          "url": "ivs-1.110.1-0.6.21.jar",
          "size": 80896,
          "sha512": "a9467abcdfaf58284e84aff15c7f13310df98de93a0535a44d211c92d57b656afd239293acb7feb73197cf6b732593365947748c172ab7380d4d0a1a08beec9e",
          "sha256": "4572e82089fb8b24af4867f591dfa532ee270f129d96036e7eb772e77b333250",
          "sha1": "d8864e918c8898f594dae10d22612d6e5de588f4",
          "md5": "197b150887aae098d125ddbdd5a58e03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ivs",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ivs-1.110.1-0.6.21.jar",
          "url": "ivs-1.110.1-0.6.21.jar",
          "size": 80896,
          "sha512": "a9467abcdfaf58284e84aff15c7f13310df98de93a0535a44d211c92d57b656afd239293acb7feb73197cf6b732593365947748c172ab7380d4d0a1a08beec9e",
          "sha256": "4572e82089fb8b24af4867f591dfa532ee270f129d96036e7eb772e77b333250",
          "sha1": "d8864e918c8898f594dae10d22612d6e5de588f4",
          "md5": "197b150887aae098d125ddbdd5a58e03"
        }
      ]
    }
  ]
}
