{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-customresources",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudformation",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-customresources-1.105.0-0.6.21.jar",
          "url": "cdk-customresources-1.105.0-0.6.21.jar",
          "size": 27384,
          "sha512": "3b9c3912466064d1e16ebf64945d80556b943b1e8c5b2e37733ada0d7e6109f9cea49450cc45d69bbbf5ac5c4230ab4e9334bb2c7b4e8c762bfdc834ec24d05d",
          "sha256": "6b9f0866ffc10927cb8690f5d1daa1a105f37a851c60795b9ecadcaf4fd5d1f6",
          "sha1": "396be7eda7ec482a2494b9f9b60b3fb82bbb101f",
          "md5": "a1e78da9dac4532ed05bd943b21e9a01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudformation",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-customresources-1.105.0-0.6.21.jar",
          "url": "cdk-customresources-1.105.0-0.6.21.jar",
          "size": 27384,
          "sha512": "3b9c3912466064d1e16ebf64945d80556b943b1e8c5b2e37733ada0d7e6109f9cea49450cc45d69bbbf5ac5c4230ab4e9334bb2c7b4e8c762bfdc834ec24d05d",
          "sha256": "6b9f0866ffc10927cb8690f5d1daa1a105f37a851c60795b9ecadcaf4fd5d1f6",
          "sha1": "396be7eda7ec482a2494b9f9b60b3fb82bbb101f",
          "md5": "a1e78da9dac4532ed05bd943b21e9a01"
        }
      ]
    }
  ]
}
