{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "finspace",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "finspace",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "finspace-1.116.0-0.6.21.jar",
          "url": "finspace-1.116.0-0.6.21.jar",
          "size": 23104,
          "sha512": "f360110d3cf97c9b5ab5bf3b047c9a37181f825829b6f06db5648644d995e3f96aaa30bdf47f10c37e4ead01ad9e496a612a823002e6cf02f3d2be92d2e0984a",
          "sha256": "82b708a738ce426516f2837cf10ce15f018d2f1c33b3a1deb252d0dec420a688",
          "sha1": "c9b459ac763b39fb2320f8e4374812c2789e503d",
          "md5": "73769a875cd9f0dbb301d1f495877207"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "finspace",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "finspace-1.116.0-0.6.21.jar",
          "url": "finspace-1.116.0-0.6.21.jar",
          "size": 23104,
          "sha512": "f360110d3cf97c9b5ab5bf3b047c9a37181f825829b6f06db5648644d995e3f96aaa30bdf47f10c37e4ead01ad9e496a612a823002e6cf02f3d2be92d2e0984a",
          "sha256": "82b708a738ce426516f2837cf10ce15f018d2f1c33b3a1deb252d0dec420a688",
          "sha1": "c9b459ac763b39fb2320f8e4374812c2789e503d",
          "md5": "73769a875cd9f0dbb301d1f495877207"
        }
      ]
    }
  ]
}
