{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "kinesis",
    "version": "1.110.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cnrjfrtzdvad5bhmsg7msamtuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "kinesis",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesis-1.110.0-0.6.21.jar",
          "url": "kinesis-1.110.0-0.6.21.jar",
          "size": 40313,
          "sha512": "5f34eb410db92e1b467b369681caef953832c7c000304d019ee11f80962c908c4eb7db68c7c37512e9a8372fcc1b4168a1eb1eb61a3410e67c309e3731dabdd",
          "sha256": "d9717c68d179023e7fba01193fc9c10fe868f466129134a881bbad9169446170",
          "sha1": "4c177d39309f6b9a3cdb2d90c3b1d5d930a14189",
          "md5": "9f313ef15c5edf3d39924782e27e762f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "kinesis",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesis-1.110.0-0.6.21.jar",
          "url": "kinesis-1.110.0-0.6.21.jar",
          "size": 40313,
          "sha512": "5f34eb410db92e1b467b369681caef953832c7c000304d019ee11f80962c908c4eb7db68c7c37512e9a8372fcc1b4168a1eb1eb61a3410e67c309e3731dabdd",
          "sha256": "d9717c68d179023e7fba01193fc9c10fe868f466129134a881bbad9169446170",
          "sha1": "4c177d39309f6b9a3cdb2d90c3b1d5d930a14189",
          "md5": "9f313ef15c5edf3d39924782e27e762f"
        }
      ]
    }
  ]
}
