{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "xray",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "xray",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "xray-1.113.0-0.6.21.jar",
          "url": "xray-1.113.0-0.6.21.jar",
          "size": 91772,
          "sha512": "6ea79488802566ca909b7717c37a689cb0972a05e644c1cb24f3444cdfd52a6699be882c9d64f85bbb445af519f2a2ed4318aa9ad29ea4ab12fc7303551c4c69",
          "sha256": "f0ecd58eaaad1edebd0b0ed9daddd10837c3fe733784ad00acf9cb6202302f1a",
          "sha1": "cf12870b3dbc1c9da3e75c651c3cf078ebb21e09",
          "md5": "8c73200293264615d4bbb21f99347d37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "xray",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "xray-1.113.0-0.6.21.jar",
          "url": "xray-1.113.0-0.6.21.jar",
          "size": 91772,
          "sha512": "6ea79488802566ca909b7717c37a689cb0972a05e644c1cb24f3444cdfd52a6699be882c9d64f85bbb445af519f2a2ed4318aa9ad29ea4ab12fc7303551c4c69",
          "sha256": "f0ecd58eaaad1edebd0b0ed9daddd10837c3fe733784ad00acf9cb6202302f1a",
          "sha1": "cf12870b3dbc1c9da3e75c651c3cf078ebb21e09",
          "md5": "8c73200293264615d4bbb21f99347d37"
        }
      ]
    }
  ]
}
