{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "stepfunctions",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "stepfunctions",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "stepfunctions-1.112.0-0.6.21.jar",
          "url": "stepfunctions-1.112.0-0.6.21.jar",
          "size": 224982,
          "sha512": "539ddba233b7897d968f5629d0595c6f5b550c0a5154f97c98324d571b9564fa89c180e6888dc756c2b0a1f9bc8e053e43e75d879eda4a5c1410c6fcdf414100",
          "sha256": "1747815e9729babd4066cccfc25e1b9bee4360240b182e52914da75e0b06fece",
          "sha1": "6335bb8919b13f998010c710efd977c6d241d779",
          "md5": "1e8a389fa01910dfaf58aa9f5a6fa820"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "stepfunctions",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "stepfunctions-1.112.0-0.6.21.jar",
          "url": "stepfunctions-1.112.0-0.6.21.jar",
          "size": 224982,
          "sha512": "539ddba233b7897d968f5629d0595c6f5b550c0a5154f97c98324d571b9564fa89c180e6888dc756c2b0a1f9bc8e053e43e75d879eda4a5c1410c6fcdf414100",
          "sha256": "1747815e9729babd4066cccfc25e1b9bee4360240b182e52914da75e0b06fece",
          "sha1": "6335bb8919b13f998010c710efd977c6d241d779",
          "md5": "1e8a389fa01910dfaf58aa9f5a6fa820"
        }
      ]
    }
  ]
}
