{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "mediastore",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "mediastore",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediastore-1.105.0-0.6.21.jar",
          "url": "mediastore-1.105.0-0.6.21.jar",
          "size": 52105,
          "sha512": "e71c98c1cfb216079753367d61eefd6f01b688424006cafda8885bf2090b36d673812bbf57c011d72c35b28b46e4834ecd760bce9ebb07b3ffd342b424723a63",
          "sha256": "4c8123768cc570a3517fbafba43f8814dd9b2f42f2403ff3dc6339983b3a66b0",
          "sha1": "996b6c8f58868249a2f432f7bf820a06ec66cde",
          "md5": "48a69d0d7302b181fea21622d415955a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "mediastore",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediastore-1.105.0-0.6.21.jar",
          "url": "mediastore-1.105.0-0.6.21.jar",
          "size": 52105,
          "sha512": "e71c98c1cfb216079753367d61eefd6f01b688424006cafda8885bf2090b36d673812bbf57c011d72c35b28b46e4834ecd760bce9ebb07b3ffd342b424723a63",
          "sha256": "4c8123768cc570a3517fbafba43f8814dd9b2f42f2403ff3dc6339983b3a66b0",
          "sha1": "996b6c8f58868249a2f432f7bf820a06ec66cde",
          "md5": "48a69d0d7302b181fea21622d415955a"
        }
      ]
    }
  ]
}
