{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "mediapackage",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "mediapackage",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediapackage-1.111.0-0.6.21.jar",
          "url": "mediapackage-1.111.0-0.6.21.jar",
          "size": 449970,
          "sha512": "c4cb9dcff09604154815d09c4659bcde93b705833062e9a3d1c1bf26a0704dee899e5857f1ad6bdb341cd6b8fdcc2a704557636e887a673a30764208fd2a8893",
          "sha256": "fd98772f4596211080f56867eadc4e58db0132bcbacbccef30d1a6db3b2596c9",
          "sha1": "12675d0746e6fea3d429baabdab2a7619e84fa4b",
          "md5": "f19a7df5c3b8603e2a8e6d420afde2e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "mediapackage",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediapackage-1.111.0-0.6.21.jar",
          "url": "mediapackage-1.111.0-0.6.21.jar",
          "size": 449970,
          "sha512": "c4cb9dcff09604154815d09c4659bcde93b705833062e9a3d1c1bf26a0704dee899e5857f1ad6bdb341cd6b8fdcc2a704557636e887a673a30764208fd2a8893",
          "sha256": "fd98772f4596211080f56867eadc4e58db0132bcbacbccef30d1a6db3b2596c9",
          "sha1": "12675d0746e6fea3d429baabdab2a7619e84fa4b",
          "md5": "f19a7df5c3b8603e2a8e6d420afde2e8"
        }
      ]
    }
  ]
}
