{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "opsworks",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "opsworks",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "opsworks-1.106.0-0.6.21.jar",
          "url": "opsworks-1.106.0-0.6.21.jar",
          "size": 465512,
          "sha512": "fde173bccf887392fd30807446f4f2995947c6dcd045660c1986540ae1cddabf149e071a066500f941fe2c26c74f69bb011cad6ccae41cc42130a8c06a63fdee",
          "sha256": "dfb6d9977606ced69b094cd3df44a2588a46104b2eb85cdb1c59492b53f690ee",
          "sha1": "1f335aa009b1870968fc4c90833fe99ae7cbb04",
          "md5": "a72d426e3771aa6081198affb9c02f5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "opsworks",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "opsworks-1.106.0-0.6.21.jar",
          "url": "opsworks-1.106.0-0.6.21.jar",
          "size": 465512,
          "sha512": "fde173bccf887392fd30807446f4f2995947c6dcd045660c1986540ae1cddabf149e071a066500f941fe2c26c74f69bb011cad6ccae41cc42130a8c06a63fdee",
          "sha256": "dfb6d9977606ced69b094cd3df44a2588a46104b2eb85cdb1c59492b53f690ee",
          "sha1": "1f335aa009b1870968fc4c90833fe99ae7cbb04",
          "md5": "a72d426e3771aa6081198affb9c02f5b"
        }
      ]
    }
  ]
}
