{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "athena",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "athena",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "athena-1.112.0-0.6.21.jar",
          "url": "athena-1.112.0-0.6.21.jar",
          "size": 152036,
          "sha512": "3d98ebf70dd4a9dcebaaa10baa8bd4253c0cb559638dd8479a606732b3933e055f428a2d7553529f8ce06cca48cab455f310ca00213adfb5911f6f851d3c7ab1",
          "sha256": "bbb93008327ddb6d6d113bb8b1d60c8d87e31c2f2d491ae126fb6622c1cffaf7",
          "sha1": "c67c533b6908b32bb7890f0d100284dde387e3fe",
          "md5": "606d0b8e7867e6e1834aef91950f9324"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "athena",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "athena-1.112.0-0.6.21.jar",
          "url": "athena-1.112.0-0.6.21.jar",
          "size": 152036,
          "sha512": "3d98ebf70dd4a9dcebaaa10baa8bd4253c0cb559638dd8479a606732b3933e055f428a2d7553529f8ce06cca48cab455f310ca00213adfb5911f6f851d3c7ab1",
          "sha256": "bbb93008327ddb6d6d113bb8b1d60c8d87e31c2f2d491ae126fb6622c1cffaf7",
          "sha1": "c67c533b6908b32bb7890f0d100284dde387e3fe",
          "md5": "606d0b8e7867e6e1834aef91950f9324"
        }
      ]
    }
  ]
}
