{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cur",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cur",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cur-1.112.0-0.6.21.jar",
          "url": "cur-1.112.0-0.6.21.jar",
          "size": 19942,
          "sha512": "8cf4e3744aa9776e0983dc1b29e4316fc91c9e7ceddbd7a540b29fff3de4f68a4c8078e668a3171f090c3d9fd5640352efc8b92d2429c5886ff69601bfde84f5",
          "sha256": "5889241e9bae90126f7e82433a323b765d3f6a477f7bf868b17623b3653705bb",
          "sha1": "7ac2494d57c85f86d017168fe856ec699c504072",
          "md5": "8df0eb56e7d230598787548ea918e4b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cur",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cur-1.112.0-0.6.21.jar",
          "url": "cur-1.112.0-0.6.21.jar",
          "size": 19942,
          "sha512": "8cf4e3744aa9776e0983dc1b29e4316fc91c9e7ceddbd7a540b29fff3de4f68a4c8078e668a3171f090c3d9fd5640352efc8b92d2429c5886ff69601bfde84f5",
          "sha256": "5889241e9bae90126f7e82433a323b765d3f6a477f7bf868b17623b3653705bb",
          "sha1": "7ac2494d57c85f86d017168fe856ec699c504072",
          "md5": "8df0eb56e7d230598787548ea918e4b2"
        }
      ]
    }
  ]
}
