{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "kinesisanalytics",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "kinesisanalytics",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesisanalytics-1.115.0-0.6.21.jar",
          "url": "kinesisanalytics-1.115.0-0.6.21.jar",
          "size": 695157,
          "sha512": "72014f5a5fc6cde6ddd5e78c5c07130db91013536f04e7cc706a8b7df144f8e05ef7b2025b636a36418e570110d72c256c958f69f569715e4b5e8ee9807fd800",
          "sha256": "8b91640fbd6ba7be6db009bbb8e0fcc2e45f3b31f3c03cdbebe21bf17e1038ce",
          "sha1": "f2d871ca473fb14a952ae6317c8e22bc240e7e4f",
          "md5": "2f4c256bde8adc2986b6bbaf83760921"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "kinesisanalytics",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesisanalytics-1.115.0-0.6.21.jar",
          "url": "kinesisanalytics-1.115.0-0.6.21.jar",
          "size": 695157,
          "sha512": "72014f5a5fc6cde6ddd5e78c5c07130db91013536f04e7cc706a8b7df144f8e05ef7b2025b636a36418e570110d72c256c958f69f569715e4b5e8ee9807fd800",
          "sha256": "8b91640fbd6ba7be6db009bbb8e0fcc2e45f3b31f3c03cdbebe21bf17e1038ce",
          "sha1": "f2d871ca473fb14a952ae6317c8e22bc240e7e4f",
          "md5": "2f4c256bde8adc2986b6bbaf83760921"
        }
      ]
    }
  ]
}
