{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "events",
    "version": "1.106.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "apa3jttzlbgsjbklj7vcehaque"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "events",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "events-1.106.1-0.6.21.jar",
          "url": "events-1.106.1-0.6.21.jar",
          "size": 259665,
          "sha512": "de79ffdad43729ec52d96aaf6da0fc2d31b13d690df6e0cd7c692ad36585b3a4970c4eb31918ab02a68394f0835d2d2b0639e69cec89c1b36403d349b9a13536",
          "sha256": "4fae92f9b100c129e5f3b92624bb53911f5fa3e20d4a43d7eecc5a6f5a74db65",
          "sha1": "ae1bb032c84c1403ad34e39042ed21ff737eec28",
          "md5": "d73bb74b60539eb4c00a20eb30aaed83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "events",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "events-1.106.1-0.6.21.jar",
          "url": "events-1.106.1-0.6.21.jar",
          "size": 259665,
          "sha512": "de79ffdad43729ec52d96aaf6da0fc2d31b13d690df6e0cd7c692ad36585b3a4970c4eb31918ab02a68394f0835d2d2b0639e69cec89c1b36403d349b9a13536",
          "sha256": "4fae92f9b100c129e5f3b92624bb53911f5fa3e20d4a43d7eecc5a6f5a74db65",
          "sha1": "ae1bb032c84c1403ad34e39042ed21ff737eec28",
          "md5": "d73bb74b60539eb4c00a20eb30aaed83"
        }
      ]
    }
  ]
}
