{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "macie",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "macie",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "macie-1.104.0-0.6.21.jar",
          "url": "macie-1.104.0-0.6.21.jar",
          "size": 47711,
          "sha512": "aac4bb95a59901c58ca8916b34888cc9f7ad711414327d8277abe4369a3887f2187ba79796e03244b0f0dc80666f607f14b37e8a6b55af387dc393ffb6aff324",
          "sha256": "b8021da77c8d5175d36b0375c4676b33dd6f7d60e77063c6238d1827afeb691f",
          "sha1": "83004e61960ba1b6c605c31c49db334ddee4397e",
          "md5": "1e5654bc5a738276901fa875baaa9bff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "macie",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "macie-1.104.0-0.6.21.jar",
          "url": "macie-1.104.0-0.6.21.jar",
          "size": 47711,
          "sha512": "aac4bb95a59901c58ca8916b34888cc9f7ad711414327d8277abe4369a3887f2187ba79796e03244b0f0dc80666f607f14b37e8a6b55af387dc393ffb6aff324",
          "sha256": "b8021da77c8d5175d36b0375c4676b33dd6f7d60e77063c6238d1827afeb691f",
          "sha1": "83004e61960ba1b6c605c31c49db334ddee4397e",
          "md5": "1e5654bc5a738276901fa875baaa9bff"
        }
      ]
    }
  ]
}
