{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "emr",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "emr",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "emr-1.118.0-0.6.25.jar",
          "url": "emr-1.118.0-0.6.25.jar",
          "size": 619102,
          "sha512": "5b1bf3f6c143f456c24fdd517ee43283e5faf81613d58adb5c02788483d994f28d8093c5824e9614d0a48557988485ce4ce58524484247b1bc35f03254725399",
          "sha256": "2d2e426ce93216003af19bdd2eca1b31b9febe6a0cce90a515c13e0659b16a3f",
          "sha1": "fca95f603fa25e7df5f4a95761ebae670b8eb6be",
          "md5": "2f6c0afe2230075c55c0692abe4df52e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "emr",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "emr-1.118.0-0.6.25.jar",
          "url": "emr-1.118.0-0.6.25.jar",
          "size": 619102,
          "sha512": "5b1bf3f6c143f456c24fdd517ee43283e5faf81613d58adb5c02788483d994f28d8093c5824e9614d0a48557988485ce4ce58524484247b1bc35f03254725399",
          "sha256": "2d2e426ce93216003af19bdd2eca1b31b9febe6a0cce90a515c13e0659b16a3f",
          "sha1": "fca95f603fa25e7df5f4a95761ebae670b8eb6be",
          "md5": "2f6c0afe2230075c55c0692abe4df52e"
        }
      ]
    }
  ]
}
