{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cloudfront-origins",
    "version": "1.64.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cloudfront-origins",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudfront",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cloudfront-origins-1.64.0-0.6.21.jar",
          "url": "cloudfront-origins-1.64.0-0.6.21.jar",
          "size": 21132,
          "sha512": "2459c46e25434b72b5aa4b94d196ab299ec83e8b5931af5a7bb456ebcb269ff7d8093e03cc1448fdcc64e4ca9642f6db73736e454398634c2b1bcf6f5c14afc0",
          "sha256": "d49a18c573a6988cfce388e7a2b6afd08a24a98f8fbfb5d2fad98d1a17fb0327",
          "sha1": "905b092f83a5b8532b66e66b9be938ecf4ccabfe",
          "md5": "7cdf973e9f9f5e2965af0e673ebb7f6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cloudfront-origins",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudfront",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cloudfront-origins-1.64.0-0.6.21.jar",
          "url": "cloudfront-origins-1.64.0-0.6.21.jar",
          "size": 21132,
          "sha512": "2459c46e25434b72b5aa4b94d196ab299ec83e8b5931af5a7bb456ebcb269ff7d8093e03cc1448fdcc64e4ca9642f6db73736e454398634c2b1bcf6f5c14afc0",
          "sha256": "d49a18c573a6988cfce388e7a2b6afd08a24a98f8fbfb5d2fad98d1a17fb0327",
          "sha1": "905b092f83a5b8532b66e66b9be938ecf4ccabfe",
          "md5": "7cdf973e9f9f5e2965af0e673ebb7f6f"
        }
      ]
    }
  ]
}
