{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "eventschemas",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.108.1-0.6.21.jar",
          "url": "eventschemas-1.108.1-0.6.21.jar",
          "size": 43037,
          "sha512": "7dfca2b1929472ca2dda254c8eb9c58a5fc8eef4def4507dd0933ed2f24734d958f064910ed5c46d215c1f66e682c41a8002ca22b228814d77fef9bda437554a",
          "sha256": "7a0298a1126f817a6b85c1c69f1e29c6f9db37dad98d2be0e09a12a0d60a2d4",
          "sha1": "abce9db858f642084f5b41d752af363533a0fe1b",
          "md5": "3ad8b3239110e672194041afc47a4e2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.108.1-0.6.21.jar",
          "url": "eventschemas-1.108.1-0.6.21.jar",
          "size": 43037,
          "sha512": "7dfca2b1929472ca2dda254c8eb9c58a5fc8eef4def4507dd0933ed2f24734d958f064910ed5c46d215c1f66e682c41a8002ca22b228814d77fef9bda437554a",
          "sha256": "7a0298a1126f817a6b85c1c69f1e29c6f9db37dad98d2be0e09a12a0d60a2d4",
          "sha1": "abce9db858f642084f5b41d752af363533a0fe1b",
          "md5": "3ad8b3239110e672194041afc47a4e2f"
        }
      ]
    }
  ]
}
