{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticloadbalancingv2-targets",
    "version": "1.31.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticloadbalancingv2-targets",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-assets",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "elasticloadbalancingv2-targets-1.31.0-0.6.22.jar",
          "url": "elasticloadbalancingv2-targets-1.31.0-0.6.22.jar",
          "size": 462,
          "sha512": "1ff51e33c1d015a02c1a510e699520e7966612921cbc17fb8ce248ef98b70254becbd301258205776cdd8ec9d3a86820db1e3a05cdba7fc7cd6163feb26fd05a",
          "sha256": "27dc161b7a55aceaa39597313ae4b3442ac7f1d4e0cc76693d0b0f53a06f22af",
          "sha1": "8265647784058e0812c01a31aa98135591ced9c5",
          "md5": "777ee82138aff3fd3e37f7991b6d1de7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticloadbalancingv2-targets",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-assets",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "elasticloadbalancingv2-targets-1.31.0-0.6.22.jar",
          "url": "elasticloadbalancingv2-targets-1.31.0-0.6.22.jar",
          "size": 462,
          "sha512": "1ff51e33c1d015a02c1a510e699520e7966612921cbc17fb8ce248ef98b70254becbd301258205776cdd8ec9d3a86820db1e3a05cdba7fc7cd6163feb26fd05a",
          "sha256": "27dc161b7a55aceaa39597313ae4b3442ac7f1d4e0cc76693d0b0f53a06f22af",
          "sha1": "8265647784058e0812c01a31aa98135591ced9c5",
          "md5": "777ee82138aff3fd3e37f7991b6d1de7"
        }
      ]
    }
  ]
}
