{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "dms",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "dms",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dms-1.104.0-0.6.21.jar",
          "url": "dms-1.104.0-0.6.21.jar",
          "size": 285966,
          "sha512": "ad5098c0e731a77ee5d13ba6dc1979738fb6e5adc1e4613b2bf602e4c79c48e957b3bd11a4c66c337fdb2a31766b1a5e6d11c88cad43971c106fca811444e4c4",
          "sha256": "44de472f8c369c4382ddb637a807256ca478209ebca5d9b3f4ef03231f1567ad",
          "sha1": "1d760fbe3ac6e42d645a08f680ea844970fde78e",
          "md5": "f81e89d33049a97340ae01e8298e9430"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "dms",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dms-1.104.0-0.6.21.jar",
          "url": "dms-1.104.0-0.6.21.jar",
          "size": 285966,
          "sha512": "ad5098c0e731a77ee5d13ba6dc1979738fb6e5adc1e4613b2bf602e4c79c48e957b3bd11a4c66c337fdb2a31766b1a5e6d11c88cad43971c106fca811444e4c4",
          "sha256": "44de472f8c369c4382ddb637a807256ca478209ebca5d9b3f4ef03231f1567ad",
          "sha1": "1d760fbe3ac6e42d645a08f680ea844970fde78e",
          "md5": "f81e89d33049a97340ae01e8298e9430"
        }
      ]
    }
  ]
}
