{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ce",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ce",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ce-1.111.0-0.6.21.jar",
          "url": "ce-1.111.0-0.6.21.jar",
          "size": 36805,
          "sha512": "5c0759af77dd69fcbefabac9faec39b53f1f0d84c555db55db1e2114bbecede384ee544d1052cfeba120821ca4da8c18546b5d41540d2a993b4f83f9a820a0a1",
          "sha256": "f10d2d53af934e1cccfb890acc0ddebcd262187128d556b15e26214f25bc90cb",
          "sha1": "1d3fe0bab73dc7f65cc07b8e4bca5aad8a033e46",
          "md5": "922b598bd02b883838eb026b94b09a14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ce",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ce-1.111.0-0.6.21.jar",
          "url": "ce-1.111.0-0.6.21.jar",
          "size": 36805,
          "sha512": "5c0759af77dd69fcbefabac9faec39b53f1f0d84c555db55db1e2114bbecede384ee544d1052cfeba120821ca4da8c18546b5d41540d2a993b4f83f9a820a0a1",
          "sha256": "f10d2d53af934e1cccfb890acc0ddebcd262187128d556b15e26214f25bc90cb",
          "sha1": "1d3fe0bab73dc7f65cc07b8e4bca5aad8a033e46",
          "md5": "922b598bd02b883838eb026b94b09a14"
        }
      ]
    }
  ]
}
