{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "route53-targets",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "route53-targets",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "apigateway",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudfront",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cognito",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancing",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "globalaccelerator",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "route53-targets-1.112.0-0.6.21.jar",
          "url": "route53-targets-1.112.0-0.6.21.jar",
          "size": 432,
          "sha512": "719c98366b0fe69f0cff836057f406e2e067180d4051cf999fa71d7b692d24916e1f5337b60247a2c56087af30dd5a42ea57adcd8aacb8a68c835480457898ef",
          "sha256": "b73a0bc201db1c4f943f7811f5f378cffe2d10253ddc39d79a38d4f595b98eb",
          "sha1": "b245e7eba7d99369dc0370483f0e63f5452394cb",
          "md5": "8beb7ea9f37299e1670eaddce06597df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "route53-targets",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "apigateway",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudfront",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cognito",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancing",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "globalaccelerator",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "route53-targets-1.112.0-0.6.21.jar",
          "url": "route53-targets-1.112.0-0.6.21.jar",
          "size": 432,
          "sha512": "719c98366b0fe69f0cff836057f406e2e067180d4051cf999fa71d7b692d24916e1f5337b60247a2c56087af30dd5a42ea57adcd8aacb8a68c835480457898ef",
          "sha256": "b73a0bc201db1c4f943f7811f5f378cffe2d10253ddc39d79a38d4f595b98eb",
          "sha1": "b245e7eba7d99369dc0370483f0e63f5452394cb",
          "md5": "8beb7ea9f37299e1670eaddce06597df"
        }
      ]
    }
  ]
}
