{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "appconfig",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "appconfig",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appconfig-1.115.0-0.6.21.jar",
          "url": "appconfig-1.115.0-0.6.21.jar",
          "size": 93389,
          "sha512": "c84ddfb412e7d2129e1e276cbf01dd1fee64121fce88a7750b26afe6719138cf870429c9f9c6e370a3d3f76e858841eba8c88806c18c90e5a771fae212e802db",
          "sha256": "b42e0d69a573b9a5d0623f4b84ae100d70c57ba02f7f788a9aee4ded4a1cb8c7",
          "sha1": "3d8300621e9cbc731443148543aa38a9b5898d89",
          "md5": "d7fdd79d134b60f5dccb6025ef7e28eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "appconfig",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appconfig-1.115.0-0.6.21.jar",
          "url": "appconfig-1.115.0-0.6.21.jar",
          "size": 93389,
          "sha512": "c84ddfb412e7d2129e1e276cbf01dd1fee64121fce88a7750b26afe6719138cf870429c9f9c6e370a3d3f76e858841eba8c88806c18c90e5a771fae212e802db",
          "sha256": "b42e0d69a573b9a5d0623f4b84ae100d70c57ba02f7f788a9aee4ded4a1cb8c7",
          "sha1": "3d8300621e9cbc731443148543aa38a9b5898d89",
          "md5": "d7fdd79d134b60f5dccb6025ef7e28eb"
        }
      ]
    }
  ]
}
