{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-lambda-layer-kubectl",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-lambda-layer-kubectl",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-lambda-layer-kubectl-1.118.0-0.6.25.jar",
          "url": "cdk-lambda-layer-kubectl-1.118.0-0.6.25.jar",
          "size": 450,
          "sha512": "146afaa630dbb32d0a413489d761dff5d3511fb7e806f309b2542cff44c568a467a23ba66b8307f257ea665014afe56f6176472e4f6f2349d182236b010e7b68",
          "sha256": "d4129c0dc4cea34c923fbd6e8019b38690fada7553e30990c07ec6fc649fa73c",
          "sha1": "daaae0dc3c223619852ff3fab3645cc057035fe5",
          "md5": "107a128cdd41da747b9960d2d8ea4674"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-lambda-layer-kubectl",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-lambda-layer-kubectl-1.118.0-0.6.25.jar",
          "url": "cdk-lambda-layer-kubectl-1.118.0-0.6.25.jar",
          "size": 450,
          "sha512": "146afaa630dbb32d0a413489d761dff5d3511fb7e806f309b2542cff44c568a467a23ba66b8307f257ea665014afe56f6176472e4f6f2349d182236b010e7b68",
          "sha256": "d4129c0dc4cea34c923fbd6e8019b38690fada7553e30990c07ec6fc649fa73c",
          "sha1": "daaae0dc3c223619852ff3fab3645cc057035fe5",
          "md5": "107a128cdd41da747b9960d2d8ea4674"
        }
      ]
    }
  ]
}
