{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "servicecatalogappregistry",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "servicecatalogappregistry",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "servicecatalogappregistry-1.111.0-0.6.21.jar",
          "url": "servicecatalogappregistry-1.111.0-0.6.21.jar",
          "size": 45198,
          "sha512": "86e068fac3cc45f5bd12b1340a55d89868b14c9143ac4e8d88c0b9a51ac4aa25f974a49e83ecc1f4a4eadf065e94318bc19adc032ca3eb36f95c165079f9cc54",
          "sha256": "818a413b2d34b09521db663daa6a0ffde5fd8dc8bc64489f539dc9c1a0c56bf1",
          "sha1": "47f445bca21d03386f44d1dbbd8c0406b9c89f3e",
          "md5": "755f74a91026ee5a556ed9c542aed88e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "servicecatalogappregistry",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "servicecatalogappregistry-1.111.0-0.6.21.jar",
          "url": "servicecatalogappregistry-1.111.0-0.6.21.jar",
          "size": 45198,
          "sha512": "86e068fac3cc45f5bd12b1340a55d89868b14c9143ac4e8d88c0b9a51ac4aa25f974a49e83ecc1f4a4eadf065e94318bc19adc032ca3eb36f95c165079f9cc54",
          "sha256": "818a413b2d34b09521db663daa6a0ffde5fd8dc8bc64489f539dc9c1a0c56bf1",
          "sha1": "47f445bca21d03386f44d1dbbd8c0406b9c89f3e",
          "md5": "755f74a91026ee5a556ed9c542aed88e"
        }
      ]
    }
  ]
}
