{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "pinpoint",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "pinpoint",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "pinpoint-1.103.0-0.6.21.jar",
          "url": "pinpoint-1.103.0-0.6.21.jar",
          "size": 629273,
          "sha512": "e8a2b3037fea6ecf4f04d6ae3d32fa491d52e00975a3154168f4da43fcc694e2256c067789be6724dc0e26aea5470d149d8c23c000e9af018ee9c312b5c945da",
          "sha256": "c91214ff5949b9ca9090e715919765b70da1b4128c90baae5c7a0d72fa36371d",
          "sha1": "55768f502bc8b1b8acf080d8130f4d67b6a3291f",
          "md5": "b7b1853bf588ac455f2ca8fe17285129"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "pinpoint",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "pinpoint-1.103.0-0.6.21.jar",
          "url": "pinpoint-1.103.0-0.6.21.jar",
          "size": 629273,
          "sha512": "e8a2b3037fea6ecf4f04d6ae3d32fa491d52e00975a3154168f4da43fcc694e2256c067789be6724dc0e26aea5470d149d8c23c000e9af018ee9c312b5c945da",
          "sha256": "c91214ff5949b9ca9090e715919765b70da1b4128c90baae5c7a0d72fa36371d",
          "sha1": "55768f502bc8b1b8acf080d8130f4d67b6a3291f",
          "md5": "b7b1853bf588ac455f2ca8fe17285129"
        }
      ]
    }
  ]
}
