{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-assets",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-1.113.0-0.6.21.jar",
          "url": "cdk-assets-1.113.0-0.6.21.jar",
          "size": 16459,
          "sha512": "9da8f31e7e5ab337ffd81c624f483476bfd69488abad25a5d05ce096b5964d54e58cbfb4a9a503603f03faabf570d1fb951117d7c4fdd7e47f91a4f0db8dab19",
          "sha256": "ecd39f2e29db5a5c0557fbbb7ff25fe8e4247e657f12066c12801f0f846ffda9",
          "sha1": "b08a29f6aadfd2d3efe8275851bb2a4c5c2b5569",
          "md5": "d6516024495e67d47a591cf1204a31d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-1.113.0-0.6.21.jar",
          "url": "cdk-assets-1.113.0-0.6.21.jar",
          "size": 16459,
          "sha512": "9da8f31e7e5ab337ffd81c624f483476bfd69488abad25a5d05ce096b5964d54e58cbfb4a9a503603f03faabf570d1fb951117d7c4fdd7e47f91a4f0db8dab19",
          "sha256": "ecd39f2e29db5a5c0557fbbb7ff25fe8e4247e657f12066c12801f0f846ffda9",
          "sha1": "b08a29f6aadfd2d3efe8275851bb2a4c5c2b5569",
          "md5": "d6516024495e67d47a591cf1204a31d4"
        }
      ]
    }
  ]
}
