{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codeguruprofiler",
    "version": "1.117.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ka4pthfoybhvvnwbwaxmu2dbry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codeguruprofiler",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codeguruprofiler-1.117.0-0.6.21.jar",
          "url": "codeguruprofiler-1.117.0-0.6.21.jar",
          "size": 30593,
          "sha512": "c65e645b36b379b705c377058fb591cccdf4f0b2b386f4cad8dddfe19e43cc41b60648c3d63447de94c32da04d954e4edf29c0cf3e010e020c5b8500d1fd8638",
          "sha256": "72f22255a3df5cc87252e2570645c2cb69804b758477a452e2e871e276cd0ec6",
          "sha1": "b10a5bbdccb8055086cbfbc2247b1a2254749176",
          "md5": "5e560635a44d1fee8a8c783fe32557ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codeguruprofiler",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codeguruprofiler-1.117.0-0.6.21.jar",
          "url": "codeguruprofiler-1.117.0-0.6.21.jar",
          "size": 30593,
          "sha512": "c65e645b36b379b705c377058fb591cccdf4f0b2b386f4cad8dddfe19e43cc41b60648c3d63447de94c32da04d954e4edf29c0cf3e010e020c5b8500d1fd8638",
          "sha256": "72f22255a3df5cc87252e2570645c2cb69804b758477a452e2e871e276cd0ec6",
          "sha1": "b10a5bbdccb8055086cbfbc2247b1a2254749176",
          "md5": "5e560635a44d1fee8a8c783fe32557ac"
        }
      ]
    }
  ]
}
