{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iam",
    "version": "1.31.0-unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iam",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "iam-1.31.0-unspecified.jar",
          "url": "iam-1.31.0-unspecified.jar",
          "size": 215217,
          "sha512": "e561a883c739fca36496ee1cae58f5bf41a4a5d31d87f0e00eafbb5c9efe3b588b13f09d0b4e09cba1293bc317bae0605242892b89ffef262c06d9f04adc6987",
          "sha256": "ef248d2935a8acfe40db2eaed6e1496d8128268b5d4db3fabcddee94d75208ba",
          "sha1": "a2c5e6345fc8ce12c55d1dc035d736918cdd709e",
          "md5": "cbb7fb7310eea070e978b3dc7655ecb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iam",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "iam-1.31.0-unspecified.jar",
          "url": "iam-1.31.0-unspecified.jar",
          "size": 215217,
          "sha512": "e561a883c739fca36496ee1cae58f5bf41a4a5d31d87f0e00eafbb5c9efe3b588b13f09d0b4e09cba1293bc317bae0605242892b89ffef262c06d9f04adc6987",
          "sha256": "ef248d2935a8acfe40db2eaed6e1496d8128268b5d4db3fabcddee94d75208ba",
          "sha1": "a2c5e6345fc8ce12c55d1dc035d736918cdd709e",
          "md5": "cbb7fb7310eea070e978b3dc7655ecb6"
        }
      ]
    }
  ]
}
