{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "finspace",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "finspace",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "finspace-1.113.0-0.6.21.jar",
          "url": "finspace-1.113.0-0.6.21.jar",
          "size": 23112,
          "sha512": "389dd978f044181e8bd91926259ccb616fd68b4e92e54f981786405a7c3219da15f386fa6fa248dd4b06bab21aff7f4788175c8ce18b7da44e8ede9f099754fd",
          "sha256": "77122571ce9bcc96d7a32ace359983df0e8753b44d4fdea21845c956f5f70cd9",
          "sha1": "64c8d68769b5d9d260771337a4abd35d73fff015",
          "md5": "3e3f071e94cd516cddf8ef75b14ff50b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "finspace",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "finspace-1.113.0-0.6.21.jar",
          "url": "finspace-1.113.0-0.6.21.jar",
          "size": 23112,
          "sha512": "389dd978f044181e8bd91926259ccb616fd68b4e92e54f981786405a7c3219da15f386fa6fa248dd4b06bab21aff7f4788175c8ce18b7da44e8ede9f099754fd",
          "sha256": "77122571ce9bcc96d7a32ace359983df0e8753b44d4fdea21845c956f5f70cd9",
          "sha1": "64c8d68769b5d9d260771337a4abd35d73fff015",
          "md5": "3e3f071e94cd516cddf8ef75b14ff50b"
        }
      ]
    }
  ]
}
