{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-cx-api",
    "version": "1.59.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cx-api-1.59.0-0.6.22.jar",
          "url": "cdk-cx-api-1.59.0-0.6.22.jar",
          "size": 62092,
          "sha512": "78101eb60f1a565506ffc2e4104aa49745540e52eb617fab65693d828f36738444d3364d048bbf6f819777dd63795014784f6c284809885301b86e6772ddce73",
          "sha256": "c8e70197f6ddd70c689835002c9e7fb1202b8a42a4bf9152972de7d0245b613e",
          "sha1": "227bb2819d876711a851c915f0152bf2a550fef6",
          "md5": "6147073a01c52632b211410622922995"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cx-api-1.59.0-0.6.22.jar",
          "url": "cdk-cx-api-1.59.0-0.6.22.jar",
          "size": 62092,
          "sha512": "78101eb60f1a565506ffc2e4104aa49745540e52eb617fab65693d828f36738444d3364d048bbf6f819777dd63795014784f6c284809885301b86e6772ddce73",
          "sha256": "c8e70197f6ddd70c689835002c9e7fb1202b8a42a4bf9152972de7d0245b613e",
          "sha1": "227bb2819d876711a851c915f0152bf2a550fef6",
          "md5": "6147073a01c52632b211410622922995"
        }
      ]
    }
  ]
}
