{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "detective",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "detective",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "detective-1.113.0-0.6.21.jar",
          "url": "detective-1.113.0-0.6.21.jar",
          "size": 24978,
          "sha512": "7079a942c619201aaf3342c800d1896c1fefca45380567bb27bcc6d4cd3c799b5c55f8ae2c53b4514a72094c0b77e59cc5e8912804da46d29ffd0e9aa459a7fc",
          "sha256": "3342da364bc18629238a82892acada58aa0a71e1f3634f31eb322c7037e8ac50",
          "sha1": "736d948b68d4bc362b44c255eb3766eb441698ce",
          "md5": "f31d1fcd4ff8847181106af6f446f7df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "detective",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "detective-1.113.0-0.6.21.jar",
          "url": "detective-1.113.0-0.6.21.jar",
          "size": 24978,
          "sha512": "7079a942c619201aaf3342c800d1896c1fefca45380567bb27bcc6d4cd3c799b5c55f8ae2c53b4514a72094c0b77e59cc5e8912804da46d29ffd0e9aa459a7fc",
          "sha256": "3342da364bc18629238a82892acada58aa0a71e1f3634f31eb322c7037e8ac50",
          "sha1": "736d948b68d4bc362b44c255eb3766eb441698ce",
          "md5": "f31d1fcd4ff8847181106af6f446f7df"
        }
      ]
    }
  ]
}
