{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "signer",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "signer",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "signer-1.117.0-0.6.25.jar",
          "url": "signer-1.117.0-0.6.25.jar",
          "size": 40337,
          "sha512": "c21bc2afc05fa11a5fde81862921669d35e4327cb515469fd72cabd7d75194a0628700ca2da8890112e62cfe056c03898c3807396907e31e7593ce4751971f4a",
          "sha256": "12d3bc664b944d97ae947c28197e4c6c691f1889a8982e056657134e369775c7",
          "sha1": "0611c64b873cabbe86daf9de2da2460d17b79411",
          "md5": "2fad14d98623a1f917c59b0a52c55f67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "signer",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "signer-1.117.0-0.6.25.jar",
          "url": "signer-1.117.0-0.6.25.jar",
          "size": 40337,
          "sha512": "c21bc2afc05fa11a5fde81862921669d35e4327cb515469fd72cabd7d75194a0628700ca2da8890112e62cfe056c03898c3807396907e31e7593ce4751971f4a",
          "sha256": "12d3bc664b944d97ae947c28197e4c6c691f1889a8982e056657134e369775c7",
          "sha1": "0611c64b873cabbe86daf9de2da2460d17b79411",
          "md5": "2fad14d98623a1f917c59b0a52c55f67"
        }
      ]
    }
  ]
}
