{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "quicksight",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "quicksight",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "quicksight-1.106.0-0.6.21.jar",
          "url": "quicksight-1.106.0-0.6.21.jar",
          "size": 977756,
          "sha512": "6fb151264ec0b7008693040580e6693f03b7979bf74d23ebfe3c547ae43797c51a56513d59b7c21414a8164dd1448de8726230ee3215abc611ca5803416d6769",
          "sha256": "44644903c20b5d92171e243c221e46761f05f26f0cdf7f5fed5748e4536874bf",
          "sha1": "c6cf8612363b6c591ac7b08757a8f02d969c99af",
          "md5": "9fa5c20b4fbf36cc7ef55fce93b51e7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "quicksight",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "quicksight-1.106.0-0.6.21.jar",
          "url": "quicksight-1.106.0-0.6.21.jar",
          "size": 977756,
          "sha512": "6fb151264ec0b7008693040580e6693f03b7979bf74d23ebfe3c547ae43797c51a56513d59b7c21414a8164dd1448de8726230ee3215abc611ca5803416d6769",
          "sha256": "44644903c20b5d92171e243c221e46761f05f26f0cdf7f5fed5748e4536874bf",
          "sha1": "c6cf8612363b6c591ac7b08757a8f02d969c99af",
          "md5": "9fa5c20b4fbf36cc7ef55fce93b51e7b"
        }
      ]
    }
  ]
}
