{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "eventschemas",
    "version": "1.110.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cnrjfrtzdvad5bhmsg7msamtuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.110.0-0.6.21.jar",
          "url": "eventschemas-1.110.0-0.6.21.jar",
          "size": 43023,
          "sha512": "6cc3286ac80fa825763bbfbd153434fbf50adcb46d8c1eab272be98171e0bad579a101c037a43d219e02db684683146823fe001fc7d3a6997d7c5782fc4caccc",
          "sha256": "5550c24b2b016c6f14ceefbf202fb1b8738cecf88d954d41fb0b919f66a2d6c9",
          "sha1": "2b974d7b6e7ae3afb101d08104d11359a1e8886e",
          "md5": "12c5130a99e923bb63b79759efd99380"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.110.0-0.6.21.jar",
          "url": "eventschemas-1.110.0-0.6.21.jar",
          "size": 43023,
          "sha512": "6cc3286ac80fa825763bbfbd153434fbf50adcb46d8c1eab272be98171e0bad579a101c037a43d219e02db684683146823fe001fc7d3a6997d7c5782fc4caccc",
          "sha256": "5550c24b2b016c6f14ceefbf202fb1b8738cecf88d954d41fb0b919f66a2d6c9",
          "sha1": "2b974d7b6e7ae3afb101d08104d11359a1e8886e",
          "md5": "12c5130a99e923bb63b79759efd99380"
        }
      ]
    }
  ]
}
