{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lookoutmetrics",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "k23roxkwqjbs5i6arr4lg4r4xm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lookoutmetrics",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lookoutmetrics-1.110.1-0.6.21.jar",
          "url": "lookoutmetrics-1.110.1-0.6.21.jar",
          "size": 141161,
          "sha512": "bb1e17930ad71904ff739cf1ef356335e26a4af11f9150709c0e27475445b10fb513aad1f4e426943a7136c220ac62ff528f32fa1de6303657f9d82422b9fb0f",
          "sha256": "ba01a39fc7b5fbb6f562da02295753520bb6f398c4047af7c233c5f79cb52eb1",
          "sha1": "7f320cf407f8f4f98e450e3a3c22918ac0e4fb6d",
          "md5": "b3b5fe2c5e4635fa0a36fb3e1efee65d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lookoutmetrics",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lookoutmetrics-1.110.1-0.6.21.jar",
          "url": "lookoutmetrics-1.110.1-0.6.21.jar",
          "size": 141161,
          "sha512": "bb1e17930ad71904ff739cf1ef356335e26a4af11f9150709c0e27475445b10fb513aad1f4e426943a7136c220ac62ff528f32fa1de6303657f9d82422b9fb0f",
          "sha256": "ba01a39fc7b5fbb6f562da02295753520bb6f398c4047af7c233c5f79cb52eb1",
          "sha1": "7f320cf407f8f4f98e450e3a3c22918ac0e4fb6d",
          "md5": "b3b5fe2c5e4635fa0a36fb3e1efee65d"
        }
      ]
    }
  ]
}
