{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticache",
    "version": "1.31.0-unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticache",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "elasticache-1.31.0-unspecified.jar",
          "url": "elasticache-1.31.0-unspecified.jar",
          "size": 120119,
          "sha512": "22bd83f0812ab9ee7cbc17012e00100bb26b699f842eb9a1fda5c6b54f749e49e64ef79211bfdb754d3b750ace7fa4007bc95fec360f70f581bd9d55d1c0a181",
          "sha256": "4f8ae5f024164db58f6c0d6e818599ab41da608b6e9f7618ecf850ea3acdaf9d",
          "sha1": "afad2fe564820093170303bc578b360e5e439c43",
          "md5": "64eb9476f937ea5ac7270c12b645b69f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticache",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "elasticache-1.31.0-unspecified.jar",
          "url": "elasticache-1.31.0-unspecified.jar",
          "size": 120119,
          "sha512": "22bd83f0812ab9ee7cbc17012e00100bb26b699f842eb9a1fda5c6b54f749e49e64ef79211bfdb754d3b750ace7fa4007bc95fec360f70f581bd9d55d1c0a181",
          "sha256": "4f8ae5f024164db58f6c0d6e818599ab41da608b6e9f7618ecf850ea3acdaf9d",
          "sha1": "afad2fe564820093170303bc578b360e5e439c43",
          "md5": "64eb9476f937ea5ac7270c12b645b69f"
        }
      ]
    }
  ]
}
