{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "frauddetector",
    "version": "1.106.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "apa3jttzlbgsjbklj7vcehaque"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "frauddetector",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "frauddetector-1.106.1-0.6.21.jar",
          "url": "frauddetector-1.106.1-0.6.21.jar",
          "size": 183190,
          "sha512": "42fae557c42a7fd05d126bcf6dad9fe1be4fdd51c7fc8d67c38f0afa515368d303f7f3369211703bb2a552d188dfa5fdf420b696c89a070429756ea6ee57fe7f",
          "sha256": "84da9f0443662f59c9d81976ce4d9e70f22b8a868a4d2931aae4531decc40192",
          "sha1": "b11271ead4149c2241cc9d5fb2b0afb6987fbb22",
          "md5": "ac63079b59afbad0811550227cc3ab92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "frauddetector",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "frauddetector-1.106.1-0.6.21.jar",
          "url": "frauddetector-1.106.1-0.6.21.jar",
          "size": 183190,
          "sha512": "42fae557c42a7fd05d126bcf6dad9fe1be4fdd51c7fc8d67c38f0afa515368d303f7f3369211703bb2a552d188dfa5fdf420b696c89a070429756ea6ee57fe7f",
          "sha256": "84da9f0443662f59c9d81976ce4d9e70f22b8a868a4d2931aae4531decc40192",
          "sha1": "b11271ead4149c2241cc9d5fb2b0afb6987fbb22",
          "md5": "ac63079b59afbad0811550227cc3ab92"
        }
      ]
    }
  ]
}
