{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "mwaa",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "mwaa",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mwaa-1.105.0-0.6.21.jar",
          "url": "mwaa-1.105.0-0.6.21.jar",
          "size": 71907,
          "sha512": "2b104be59045550f5af168f8b7503f574e28f192e3cf37b63c2254e6f938cea11357ee3818cfb92bcca7c46b7ed5efefe4ab1df72e5b1863f5a8396f57c8ec71",
          "sha256": "5774fc2fef24f1f84896da9b3ad9184589ecb0772c0ed79d3c12e8338011ffe2",
          "sha1": "e38b2bfb1c8efa2667e75a621074528a6aef952c",
          "md5": "c604010472228a0faa9da8b7d0cd94ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "mwaa",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mwaa-1.105.0-0.6.21.jar",
          "url": "mwaa-1.105.0-0.6.21.jar",
          "size": 71907,
          "sha512": "2b104be59045550f5af168f8b7503f574e28f192e3cf37b63c2254e6f938cea11357ee3818cfb92bcca7c46b7ed5efefe4ab1df72e5b1863f5a8396f57c8ec71",
          "sha256": "5774fc2fef24f1f84896da9b3ad9184589ecb0772c0ed79d3c12e8338011ffe2",
          "sha1": "e38b2bfb1c8efa2667e75a621074528a6aef952c",
          "md5": "c604010472228a0faa9da8b7d0cd94ea"
        }
      ]
    }
  ]
}
