{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ecr",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ecr",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ecr-1.108.0-0.6.21.jar",
          "url": "ecr-1.108.0-0.6.21.jar",
          "size": 123874,
          "sha512": "2ebc12320fdd5af0d333df21d338f497f70e190f2a47f2b706bf8d74d6e974d45f703c5542385d82c28896c9e373dadb99d31aa1137f5b69b478d79e1636f9",
          "sha256": "6c9dcdf9cf669684a8a02c3b3ad23c4ea71c0ed5fad0ca3ae29abe9d20fba44b",
          "sha1": "9beee99f853cfaa894875e2f39ac02d552fe3dd3",
          "md5": "7348ac99fdcc53d2d0cc42cd3d117f8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ecr",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ecr-1.108.0-0.6.21.jar",
          "url": "ecr-1.108.0-0.6.21.jar",
          "size": 123874,
          "sha512": "2ebc12320fdd5af0d333df21d338f497f70e190f2a47f2b706bf8d74d6e974d45f703c5542385d82c28896c9e373dadb99d31aa1137f5b69b478d79e1636f9",
          "sha256": "6c9dcdf9cf669684a8a02c3b3ad23c4ea71c0ed5fad0ca3ae29abe9d20fba44b",
          "sha1": "9beee99f853cfaa894875e2f39ac02d552fe3dd3",
          "md5": "7348ac99fdcc53d2d0cc42cd3d117f8b"
        }
      ]
    }
  ]
}
