{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "imagebuilder",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.108.0-0.6.21.jar",
          "url": "imagebuilder-1.108.0-0.6.21.jar",
          "size": 285004,
          "sha512": "95716d4fc1c17e6363adc13ba3fa20e8423ac1f600de569e4a1509afed53bcecaecacc12fa6ad71bc66a69f85266eca1d65ea1006baa6374438a91e4c292e8ce",
          "sha256": "296348a4b4120cc505b8b340908730f876243b3877c3e912b40191b1492ff28d",
          "sha1": "abe906b5a53439207661f7b693cbd99e7b9508e9",
          "md5": "90f2d3a22f092ed900d6038598dff6db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.108.0-0.6.21.jar",
          "url": "imagebuilder-1.108.0-0.6.21.jar",
          "size": 285004,
          "sha512": "95716d4fc1c17e6363adc13ba3fa20e8423ac1f600de569e4a1509afed53bcecaecacc12fa6ad71bc66a69f85266eca1d65ea1006baa6374438a91e4c292e8ce",
          "sha256": "296348a4b4120cc505b8b340908730f876243b3877c3e912b40191b1492ff28d",
          "sha1": "abe906b5a53439207661f7b693cbd99e7b9508e9",
          "md5": "90f2d3a22f092ed900d6038598dff6db"
        }
      ]
    }
  ]
}
