{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "emrcontainers",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "emrcontainers",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emrcontainers-1.103.0-0.6.21.jar",
          "url": "emrcontainers-1.103.0-0.6.21.jar",
          "size": 38487,
          "sha512": "8cd68429202732db7f6a12e67feaa1eaf2ba5fc4ad18862414997ffda8c506b9768cb04f5707a971cd8defbaf18ade16271f9a81b2f2cd706924b80c3cc910",
          "sha256": "369cf0c7610a9fb4b43d334b697749ee0ecb3632a46871ac8e79d41201b8b5b2",
          "sha1": "391f7f72b1d1775ae33dffd749fe82b930810d4b",
          "md5": "aee5e6da31687f179d28f629df3a550c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "emrcontainers",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emrcontainers-1.103.0-0.6.21.jar",
          "url": "emrcontainers-1.103.0-0.6.21.jar",
          "size": 38487,
          "sha512": "8cd68429202732db7f6a12e67feaa1eaf2ba5fc4ad18862414997ffda8c506b9768cb04f5707a971cd8defbaf18ade16271f9a81b2f2cd706924b80c3cc910",
          "sha256": "369cf0c7610a9fb4b43d334b697749ee0ecb3632a46871ac8e79d41201b8b5b2",
          "sha1": "391f7f72b1d1775ae33dffd749fe82b930810d4b",
          "md5": "aee5e6da31687f179d28f629df3a550c"
        }
      ]
    }
  ]
}
