{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "macie",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "macie",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "macie-1.117.0-0.6.25.jar",
          "url": "macie-1.117.0-0.6.25.jar",
          "size": 47726,
          "sha512": "08dce640978d3ae5fe04a4c52bdccc04fff9d20e609f07cd303178f18b74525a78df5f53d367b1aaf5aaa57b42c1c9fe57cf405c386497e59b9235956a835ea7",
          "sha256": "b97f94bc79e02d8fd96ce8d09cd44eea653e75d22bd29c30fa745be86e399105",
          "sha1": "636af96f55e86ae7c393dc1cf5b21fb738dc4ea9",
          "md5": "309a4ff37c9611de3d09ac0542f28588"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "macie",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "macie-1.117.0-0.6.25.jar",
          "url": "macie-1.117.0-0.6.25.jar",
          "size": 47726,
          "sha512": "08dce640978d3ae5fe04a4c52bdccc04fff9d20e609f07cd303178f18b74525a78df5f53d367b1aaf5aaa57b42c1c9fe57cf405c386497e59b9235956a835ea7",
          "sha256": "b97f94bc79e02d8fd96ce8d09cd44eea653e75d22bd29c30fa745be86e399105",
          "sha1": "636af96f55e86ae7c393dc1cf5b21fb738dc4ea9",
          "md5": "309a4ff37c9611de3d09ac0542f28588"
        }
      ]
    }
  ]
}
