{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "wafv2",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "wafv2",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "wafv2-1.104.0-0.6.21.jar",
          "url": "wafv2-1.104.0-0.6.21.jar",
          "size": 695796,
          "sha512": "298cdaa4167d3d80f79f495f0c65f0cbf6494d9401862ac84a20339230e07980e9c0b05b10e0f1cbeb3883c16ac59694e90b034bcd4309c5ec46746bfe60d98e",
          "sha256": "6fdcb108287a273601f0d13a9a80e189ceb002b9593f669cc3592bbb1330a07a",
          "sha1": "4d911eb83178eedaff28eb5acfc214be66ee7091",
          "md5": "e7b52bf4170e94e287a57126bdf4ab0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "wafv2",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "wafv2-1.104.0-0.6.21.jar",
          "url": "wafv2-1.104.0-0.6.21.jar",
          "size": 695796,
          "sha512": "298cdaa4167d3d80f79f495f0c65f0cbf6494d9401862ac84a20339230e07980e9c0b05b10e0f1cbeb3883c16ac59694e90b034bcd4309c5ec46746bfe60d98e",
          "sha256": "6fdcb108287a273601f0d13a9a80e189ceb002b9593f669cc3592bbb1330a07a",
          "sha1": "4d911eb83178eedaff28eb5acfc214be66ee7091",
          "md5": "e7b52bf4170e94e287a57126bdf4ab0c"
        }
      ]
    }
  ]
}
