{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "securityhub",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "securityhub",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "securityhub-1.108.0-0.6.21.jar",
          "url": "securityhub-1.108.0-0.6.21.jar",
          "size": 8533,
          "sha512": "2755e8af295ee60b295ecce455c7dbca9b877afd457ae905491822ae7c912c9eb4bfec728e305b58eab92a79b4d2ca102ad33ef26edde09b974f1010a50942f0",
          "sha256": "706795e40d8591eb27805925e1fd67606e95d6ff79aa4c34b40cb86899f458f8",
          "sha1": "1fc2dc2ac8ca2d70ec5ecd6cb95b115f4729ca3",
          "md5": "c38f1232588fbb17b14e339abc1e7827"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "securityhub",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "securityhub-1.108.0-0.6.21.jar",
          "url": "securityhub-1.108.0-0.6.21.jar",
          "size": 8533,
          "sha512": "2755e8af295ee60b295ecce455c7dbca9b877afd457ae905491822ae7c912c9eb4bfec728e305b58eab92a79b4d2ca102ad33ef26edde09b974f1010a50942f0",
          "sha256": "706795e40d8591eb27805925e1fd67606e95d6ff79aa4c34b40cb86899f458f8",
          "sha1": "1fc2dc2ac8ca2d70ec5ecd6cb95b115f4729ca3",
          "md5": "c38f1232588fbb17b14e339abc1e7827"
        }
      ]
    }
  ]
}
