{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotsitewise",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotsitewise",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotsitewise-1.115.0-0.6.21.jar",
          "url": "iotsitewise-1.115.0-0.6.21.jar",
          "size": 288195,
          "sha512": "d110e824d5ad4d75a2f8db67f865a57fd665f5d82ba48d2bea575dfc9e03d716cfe411050c9a4a47ebb59a6ad971d744a2e5be919b07326dfbbf7a2edcc39c1e",
          "sha256": "996fd15af3f81434b112a629c5c1284a06cc0af1df7b29d478a787d5f9236915",
          "sha1": "52e8c00e9ce09f7e93447b82991d5fe49fd84ea",
          "md5": "ef16e380f1d845648f17c018f06f51e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotsitewise",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotsitewise-1.115.0-0.6.21.jar",
          "url": "iotsitewise-1.115.0-0.6.21.jar",
          "size": 288195,
          "sha512": "d110e824d5ad4d75a2f8db67f865a57fd665f5d82ba48d2bea575dfc9e03d716cfe411050c9a4a47ebb59a6ad971d744a2e5be919b07326dfbbf7a2edcc39c1e",
          "sha256": "996fd15af3f81434b112a629c5c1284a06cc0af1df7b29d478a787d5f9236915",
          "sha1": "52e8c00e9ce09f7e93447b82991d5fe49fd84ea",
          "md5": "ef16e380f1d845648f17c018f06f51e2"
        }
      ]
    }
  ]
}
