{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sagemaker",
    "version": "1.110.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cnrjfrtzdvad5bhmsg7msamtuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sagemaker",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sagemaker-1.110.0-0.6.21.jar",
          "url": "sagemaker-1.110.0-0.6.21.jar",
          "size": 1474633,
          "sha512": "696eb12d017b55732039f25854b4ce632e8fa79c81e146d486a3ee01cc9a1ae16ce6dd71007724b5e9e8f0bfb334f48559b269a41850daa47a5e140743dc118",
          "sha256": "30aaba35304fbfb90aea68f96e733cae78cb3f5a3fccd081b6e6cd9f49219bd7",
          "sha1": "3156603164bd30cabb0af9535f33c0b3e950b223",
          "md5": "75f9d3c182e638c360b7a2e218eb94a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sagemaker",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sagemaker-1.110.0-0.6.21.jar",
          "url": "sagemaker-1.110.0-0.6.21.jar",
          "size": 1474633,
          "sha512": "696eb12d017b55732039f25854b4ce632e8fa79c81e146d486a3ee01cc9a1ae16ce6dd71007724b5e9e8f0bfb334f48559b269a41850daa47a5e140743dc118",
          "sha256": "30aaba35304fbfb90aea68f96e733cae78cb3f5a3fccd081b6e6cd9f49219bd7",
          "sha1": "3156603164bd30cabb0af9535f33c0b3e950b223",
          "md5": "75f9d3c182e638c360b7a2e218eb94a6"
        }
      ]
    }
  ]
}
