{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "athena",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "athena",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "athena-1.117.0-0.6.25.jar",
          "url": "athena-1.117.0-0.6.25.jar",
          "size": 152021,
          "sha512": "7a9dd6f81e99bf912a8359077c6de620f37ee3048ccb8a19cc74ed5c4489dc0761dc2e608dba3366c37abc6659c654d85adbea7db7fc9779a42623cb0c2c706d",
          "sha256": "3fb0de63939989156baff0c9baafbc91267579d1cdc23216bd807e26c6e03257",
          "sha1": "66b5564e69c538d473f905908d69495191c7993b",
          "md5": "6ec9f287ad98462ea299dda0871f5b3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "athena",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "athena-1.117.0-0.6.25.jar",
          "url": "athena-1.117.0-0.6.25.jar",
          "size": 152021,
          "sha512": "7a9dd6f81e99bf912a8359077c6de620f37ee3048ccb8a19cc74ed5c4489dc0761dc2e608dba3366c37abc6659c654d85adbea7db7fc9779a42623cb0c2c706d",
          "sha256": "3fb0de63939989156baff0c9baafbc91267579d1cdc23216bd807e26c6e03257",
          "sha1": "66b5564e69c538d473f905908d69495191c7993b",
          "md5": "6ec9f287ad98462ea299dda0871f5b3b"
        }
      ]
    }
  ]
}
