{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "medialive",
    "version": "1.31.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "medialive",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "medialive-1.31.0-0.6.23.jar",
          "url": "medialive-1.31.0-0.6.23.jar",
          "size": 303031,
          "sha512": "a3ad31d5b19a37a68664f48108320b0de5ed69337ebdbdeb556d55e1726418c444a5bb540021bc8986effeeea02f110cca7f3c03c17304305252f09b32906f34",
          "sha256": "e7cf4ab7c04c6e986fe71b1f89bc39041b098e36b35aa7755595d342f86ce1cc",
          "sha1": "69383f4a46b164ea9e341bdf37966f60479fd15f",
          "md5": "2b15c63e12600275d68243ea40ed66da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "medialive",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "medialive-1.31.0-0.6.23.jar",
          "url": "medialive-1.31.0-0.6.23.jar",
          "size": 303031,
          "sha512": "a3ad31d5b19a37a68664f48108320b0de5ed69337ebdbdeb556d55e1726418c444a5bb540021bc8986effeeea02f110cca7f3c03c17304305252f09b32906f34",
          "sha256": "e7cf4ab7c04c6e986fe71b1f89bc39041b098e36b35aa7755595d342f86ce1cc",
          "sha1": "69383f4a46b164ea9e341bdf37966f60479fd15f",
          "md5": "2b15c63e12600275d68243ea40ed66da"
        }
      ]
    }
  ]
}
