{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "mediaconnect",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "mediaconnect",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediaconnect-1.112.0-0.6.21.jar",
          "url": "mediaconnect-1.112.0-0.6.21.jar",
          "size": 130888,
          "sha512": "c53122e09f587fd00975be2d91cdec8e86e74deb3824319899701969d38babdea9a287e7f3610c4aecaf3aa8841fcfa52c7d9b487e6e2f26c9d7738b6183e806",
          "sha256": "226b5d781d165e0e2a51ef8beddf90a03c7180c89d3e78ff102a92800e2b0299",
          "sha1": "aa9ef164996cf092f9539176e99b9afe8096d115",
          "md5": "445e5331855f1f84210915802ee5088c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "mediaconnect",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediaconnect-1.112.0-0.6.21.jar",
          "url": "mediaconnect-1.112.0-0.6.21.jar",
          "size": 130888,
          "sha512": "c53122e09f587fd00975be2d91cdec8e86e74deb3824319899701969d38babdea9a287e7f3610c4aecaf3aa8841fcfa52c7d9b487e6e2f26c9d7738b6183e806",
          "sha256": "226b5d781d165e0e2a51ef8beddf90a03c7180c89d3e78ff102a92800e2b0299",
          "sha1": "aa9ef164996cf092f9539176e99b9afe8096d115",
          "md5": "445e5331855f1f84210915802ee5088c"
        }
      ]
    }
  ]
}
