{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lakeformation",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lakeformation",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lakeformation-1.111.0-0.6.21.jar",
          "url": "lakeformation-1.111.0-0.6.21.jar",
          "size": 118752,
          "sha512": "e6bf8c92ecf5bcd8f787209b8ec7d6e88933b043ef6ad15a3b6d9819c31733bb8b12944f57fa7308c266735523f05e9dee720836ca48ce056d13c3d7008d7705",
          "sha256": "3441512d43561618749e573aaf169b352563a25376d4603233f4545827d0b0c3",
          "sha1": "a53943c373a02e29d3f68577b6657bfb76ee95fe",
          "md5": "18f71463ab0a1656bbeeb3f56054e035"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lakeformation",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lakeformation-1.111.0-0.6.21.jar",
          "url": "lakeformation-1.111.0-0.6.21.jar",
          "size": 118752,
          "sha512": "e6bf8c92ecf5bcd8f787209b8ec7d6e88933b043ef6ad15a3b6d9819c31733bb8b12944f57fa7308c266735523f05e9dee720836ca48ce056d13c3d7008d7705",
          "sha256": "3441512d43561618749e573aaf169b352563a25376d4603233f4545827d0b0c3",
          "sha1": "a53943c373a02e29d3f68577b6657bfb76ee95fe",
          "md5": "18f71463ab0a1656bbeeb3f56054e035"
        }
      ]
    }
  ]
}
