{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cloudwatch",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cloudwatch",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cloudwatch-1.99.0-0.6.21.jar",
          "url": "cloudwatch-1.99.0-0.6.21.jar",
          "size": 333580,
          "sha512": "5df264e597c031d3b074c490cdfdb05c8e732fe116960451ff7595acebcccadc9f28cbaf1f73f7dc9c38f43140a548dfbf75b99c591d593574a4387750f136c1",
          "sha256": "3608c8f5d5771eb255435ea0e9b120ef0e0025634b0c247ae03b4c1edb123dc0",
          "sha1": "c0423ffe964f12458f66a9857d3961574a98416e",
          "md5": "d3bd515cd4b2fead395b98311facced3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cloudwatch",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cloudwatch-1.99.0-0.6.21.jar",
          "url": "cloudwatch-1.99.0-0.6.21.jar",
          "size": 333580,
          "sha512": "5df264e597c031d3b074c490cdfdb05c8e732fe116960451ff7595acebcccadc9f28cbaf1f73f7dc9c38f43140a548dfbf75b99c591d593574a4387750f136c1",
          "sha256": "3608c8f5d5771eb255435ea0e9b120ef0e0025634b0c247ae03b4c1edb123dc0",
          "sha1": "c0423ffe964f12458f66a9857d3961574a98416e",
          "md5": "d3bd515cd4b2fead395b98311facced3"
        }
      ]
    }
  ]
}
