{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "opsworks",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "opsworks",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "opsworks-1.108.0-0.6.21.jar",
          "url": "opsworks-1.108.0-0.6.21.jar",
          "size": 465497,
          "sha512": "c846338cf0d01b0c9942aaed216c295ba19583f21e863ce1707ff50abb2d6b4b627adda67ea8a4c76d3a33201fbfa32ccacb7a76df130f8046fd9247be31589a",
          "sha256": "1caed52714ef4b2ad521b5662899b84c1e6c8611a6edf0cc823ade6ae6e77b3c",
          "sha1": "1bab985152e82d6996adf96479f902df73f52906",
          "md5": "2d17fe10c67a31a98cd77bab4cd2ef1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "opsworks",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "opsworks-1.108.0-0.6.21.jar",
          "url": "opsworks-1.108.0-0.6.21.jar",
          "size": 465497,
          "sha512": "c846338cf0d01b0c9942aaed216c295ba19583f21e863ce1707ff50abb2d6b4b627adda67ea8a4c76d3a33201fbfa32ccacb7a76df130f8046fd9247be31589a",
          "sha256": "1caed52714ef4b2ad521b5662899b84c1e6c8611a6edf0cc823ade6ae6e77b3c",
          "sha1": "1bab985152e82d6996adf96479f902df73f52906",
          "md5": "2d17fe10c67a31a98cd77bab4cd2ef1b"
        }
      ]
    }
  ]
}
