{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "detective",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "detective",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "detective-1.108.1-0.6.21.jar",
          "url": "detective-1.108.1-0.6.21.jar",
          "size": 24997,
          "sha512": "f65fc4c1ecbd0870e5badd96adad66ba0e5964da541d89a3f11aab05e7e27c996b53cb3f3973d88a28dc6b9c87795cc35f0960834eed0d00b722e7e974cab1a6",
          "sha256": "c47822404bcf44d6f1fa131ad46daf9aa81791cfd0e0c0f2d4a49136a5f187bf",
          "sha1": "aa2cdba625f3df8ccaf79488f4d92083b7eb8d6d",
          "md5": "36070c301c504e952918c2fbeac758d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "detective",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "detective-1.108.1-0.6.21.jar",
          "url": "detective-1.108.1-0.6.21.jar",
          "size": 24997,
          "sha512": "f65fc4c1ecbd0870e5badd96adad66ba0e5964da541d89a3f11aab05e7e27c996b53cb3f3973d88a28dc6b9c87795cc35f0960834eed0d00b722e7e974cab1a6",
          "sha256": "c47822404bcf44d6f1fa131ad46daf9aa81791cfd0e0c0f2d4a49136a5f187bf",
          "sha1": "aa2cdba625f3df8ccaf79488f4d92083b7eb8d6d",
          "md5": "36070c301c504e952918c2fbeac758d1"
        }
      ]
    }
  ]
}
