{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "mediapackage",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "mediapackage",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediapackage-1.105.0-0.6.21.jar",
          "url": "mediapackage-1.105.0-0.6.21.jar",
          "size": 405194,
          "sha512": "9a00c5b88ef73166908841d6b08965417677bc6829974028e72a35f11e33d5221e6077713b12fffab563b29e68b6c8ab48d7b5febcd75d993acd76e244a58e67",
          "sha256": "e0e697eb19f2b72c20eedd8c9518e182c7b16c1bbc4cd3ad82096f458d6bd552",
          "sha1": "c30b85507304e7fafa0e2fdaddeea5600202b2cd",
          "md5": "22e0078a22d64f364ff9934e4ef190f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "mediapackage",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediapackage-1.105.0-0.6.21.jar",
          "url": "mediapackage-1.105.0-0.6.21.jar",
          "size": 405194,
          "sha512": "9a00c5b88ef73166908841d6b08965417677bc6829974028e72a35f11e33d5221e6077713b12fffab563b29e68b6c8ab48d7b5febcd75d993acd76e244a58e67",
          "sha256": "e0e697eb19f2b72c20eedd8c9518e182c7b16c1bbc4cd3ad82096f458d6bd552",
          "sha1": "c30b85507304e7fafa0e2fdaddeea5600202b2cd",
          "md5": "22e0078a22d64f364ff9934e4ef190f6"
        }
      ]
    }
  ]
}
