{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotanalytics",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotanalytics",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotanalytics-1.106.0-0.6.21.jar",
          "url": "iotanalytics-1.106.0-0.6.21.jar",
          "size": 472859,
          "sha512": "e33965b78d2ef03de30ebd35951b5f8bc9365fd9af2cd362bcfc89e20fe11aea5050b9009a298884a12ee39810f5379255a3edb0dbebd47c6fdb0ce9830eaba8",
          "sha256": "e790ec40d47797534cd388fc7eb0f43ff98f906d824a01d407d974e56738798a",
          "sha1": "b2291f08cc2a629a0fb28a7c391a9b988e99270d",
          "md5": "1e890a0e437846d32cc3b33d28d9942a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotanalytics",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotanalytics-1.106.0-0.6.21.jar",
          "url": "iotanalytics-1.106.0-0.6.21.jar",
          "size": 472859,
          "sha512": "e33965b78d2ef03de30ebd35951b5f8bc9365fd9af2cd362bcfc89e20fe11aea5050b9009a298884a12ee39810f5379255a3edb0dbebd47c6fdb0ce9830eaba8",
          "sha256": "e790ec40d47797534cd388fc7eb0f43ff98f906d824a01d407d974e56738798a",
          "sha1": "b2291f08cc2a629a0fb28a7c391a9b988e99270d",
          "md5": "1e890a0e437846d32cc3b33d28d9942a"
        }
      ]
    }
  ]
}
