{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "fms",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "fms",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fms-1.116.0-0.6.21.jar",
          "url": "fms-1.116.0-0.6.21.jar",
          "size": 75010,
          "sha512": "4e2f272b4b3167789877b2511bd4788ae4ca6ec50e17cbe3f84911e200e4c10af14d11ace76952989076072a09c14d7d35c2b3da57ed88c2e2e0c674a8423354",
          "sha256": "149f8b83acd0a91047d22c7feeb08cbf5a2cc74ed3cbb7def6e955e1ddf207d5",
          "sha1": "2a97e6ea9fed53d88606f12c2db2315698ae9229",
          "md5": "6af04271b698f8189654d7f6099aa21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "fms",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fms-1.116.0-0.6.21.jar",
          "url": "fms-1.116.0-0.6.21.jar",
          "size": 75010,
          "sha512": "4e2f272b4b3167789877b2511bd4788ae4ca6ec50e17cbe3f84911e200e4c10af14d11ace76952989076072a09c14d7d35c2b3da57ed88c2e2e0c674a8423354",
          "sha256": "149f8b83acd0a91047d22c7feeb08cbf5a2cc74ed3cbb7def6e955e1ddf207d5",
          "sha1": "2a97e6ea9fed53d88606f12c2db2315698ae9229",
          "md5": "6af04271b698f8189654d7f6099aa21"
        }
      ]
    }
  ]
}
