{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ssmcontacts",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ssmcontacts",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ssmcontacts-1.108.1-0.6.21.jar",
          "url": "ssmcontacts-1.108.1-0.6.21.jar",
          "size": 66461,
          "sha512": "915e460e8902bd6e0d33e289f03924dc2119a5e7e00eb3cb70d412f9843d8ae4b635273acb6f00c9a1b51020bd5dffc1fc170b2e4a97c07962a06c517c914e4b",
          "sha256": "cf4108047777c69e638107478b59813eb18cabafef93688332ecf1ce22e28326",
          "sha1": "2709ad7a42d518b5b9a89e0a8b2da1eb3b2ce095",
          "md5": "d78355425f5f8d8d249e45ae98b61a02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ssmcontacts",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ssmcontacts-1.108.1-0.6.21.jar",
          "url": "ssmcontacts-1.108.1-0.6.21.jar",
          "size": 66461,
          "sha512": "915e460e8902bd6e0d33e289f03924dc2119a5e7e00eb3cb70d412f9843d8ae4b635273acb6f00c9a1b51020bd5dffc1fc170b2e4a97c07962a06c517c914e4b",
          "sha256": "cf4108047777c69e638107478b59813eb18cabafef93688332ecf1ce22e28326",
          "sha1": "2709ad7a42d518b5b9a89e0a8b2da1eb3b2ce095",
          "md5": "d78355425f5f8d8d249e45ae98b61a02"
        }
      ]
    }
  ]
}
