{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sagemaker",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sagemaker",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sagemaker-1.114.0-0.6.21.jar",
          "url": "sagemaker-1.114.0-0.6.21.jar",
          "size": 1474697,
          "sha512": "b195769b47a87e79b134457faae013f12e2f9e2126a791711947572f5b5dc32356982db7835ab5b9809fece94826b5e50b5932cf56ba6f495d3a6136d87ca3fd",
          "sha256": "3a6da55d1ab23ae98ae2252925ae77faf789c8028ccdcf949d898fbdff3becc6",
          "sha1": "71deeb7453542ac7bff1c44708b206dc0b34adc4",
          "md5": "3a7d3f4a434b27ff4d4d2c3e36fc90de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sagemaker",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sagemaker-1.114.0-0.6.21.jar",
          "url": "sagemaker-1.114.0-0.6.21.jar",
          "size": 1474697,
          "sha512": "b195769b47a87e79b134457faae013f12e2f9e2126a791711947572f5b5dc32356982db7835ab5b9809fece94826b5e50b5932cf56ba6f495d3a6136d87ca3fd",
          "sha256": "3a6da55d1ab23ae98ae2252925ae77faf789c8028ccdcf949d898fbdff3becc6",
          "sha1": "71deeb7453542ac7bff1c44708b206dc0b34adc4",
          "md5": "3a7d3f4a434b27ff4d4d2c3e36fc90de"
        }
      ]
    }
  ]
}
