{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "networkmanager",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "networkmanager",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "networkmanager-1.102.0-0.6.21.jar",
          "url": "networkmanager-1.102.0-0.6.21.jar",
          "size": 92771,
          "sha512": "a88237bcca9044d4f99316b45b19923c11e4bfe203cdd0c2cdb735ead2da945da42a548fb48e110efd7839facf19a32bf3dfc8a364038929bf66bf932e914936",
          "sha256": "76190eb2c8049fba1cfd2f9b046ab5748c343bfe20cff2c386c7f8330a885372",
          "sha1": "798722c8a9a61a491856f74d3aaefeaf5a84b91e",
          "md5": "fa239c440547192a507791eed2579b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "networkmanager",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "networkmanager-1.102.0-0.6.21.jar",
          "url": "networkmanager-1.102.0-0.6.21.jar",
          "size": 92771,
          "sha512": "a88237bcca9044d4f99316b45b19923c11e4bfe203cdd0c2cdb735ead2da945da42a548fb48e110efd7839facf19a32bf3dfc8a364038929bf66bf932e914936",
          "sha256": "76190eb2c8049fba1cfd2f9b046ab5748c343bfe20cff2c386c7f8330a885372",
          "sha1": "798722c8a9a61a491856f74d3aaefeaf5a84b91e",
          "md5": "fa239c440547192a507791eed2579b0"
        }
      ]
    }
  ]
}
