{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-region-info",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.106.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-region-info-1.106.0-0.6.21.jar",
          "url": "cdk-region-info-1.106.0-0.6.21.jar",
          "size": 432,
          "sha512": "b313adeff5e58f948cfdae1f8901dd3ec485c64aa79ae6043849ce6c53128b2b1a3db4ac2bc3d40493db1202b7a86344d433a6c21f5a016e25938edd2983abbe",
          "sha256": "18ca7981f30beb3c5a5fb3f5f7d4ab1b3d5587a9050eb8af8996a00c907a9707",
          "sha1": "93ffebeba8691433132ec474c10dd96ce3a18bf2",
          "md5": "e764385151d14990607232d0936c5049"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.106.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-region-info-1.106.0-0.6.21.jar",
          "url": "cdk-region-info-1.106.0-0.6.21.jar",
          "size": 432,
          "sha512": "b313adeff5e58f948cfdae1f8901dd3ec485c64aa79ae6043849ce6c53128b2b1a3db4ac2bc3d40493db1202b7a86344d433a6c21f5a016e25938edd2983abbe",
          "sha256": "18ca7981f30beb3c5a5fb3f5f7d4ab1b3d5587a9050eb8af8996a00c907a9707",
          "sha1": "93ffebeba8691433132ec474c10dd96ce3a18bf2",
          "md5": "e764385151d14990607232d0936c5049"
        }
      ]
    }
  ]
}
