{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "managedblockchain",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "managedblockchain",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "managedblockchain-1.108.0-0.6.21.jar",
          "url": "managedblockchain-1.108.0-0.6.21.jar",
          "size": 105050,
          "sha512": "dbd46ad5db680054cf4a185c5609ff511769f010ae114f418b3dc5d16902476c482c8eae6b27f824b11e3294715d35d88c56be0bc212139dee524dae2382934d",
          "sha256": "424fe826a37ed4c5e1511a668105e5aa111f542a541613d0ad7ebb293c28fc45",
          "sha1": "76820f0c7eab6c4881e05f437a8289add9a2ab81",
          "md5": "938b70db6dae6ea51d21318ebffd4027"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "managedblockchain",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "managedblockchain-1.108.0-0.6.21.jar",
          "url": "managedblockchain-1.108.0-0.6.21.jar",
          "size": 105050,
          "sha512": "dbd46ad5db680054cf4a185c5609ff511769f010ae114f418b3dc5d16902476c482c8eae6b27f824b11e3294715d35d88c56be0bc212139dee524dae2382934d",
          "sha256": "424fe826a37ed4c5e1511a668105e5aa111f542a541613d0ad7ebb293c28fc45",
          "sha1": "76820f0c7eab6c4881e05f437a8289add9a2ab81",
          "md5": "938b70db6dae6ea51d21318ebffd4027"
        }
      ]
    }
  ]
}
