{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticbeanstalk",
    "version": "1.31.0-unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticbeanstalk",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "elasticbeanstalk-1.31.0-unspecified.jar",
          "url": "elasticbeanstalk-1.31.0-unspecified.jar",
          "size": 154988,
          "sha512": "287beab71542b712b5c9567c81b5ad810c532f91bf85826ecb1e1541fa0902ce44d67194b7a74e5c35c8d1e59bebd750d6e8e4ccb61a429ce591ef9d3081205d",
          "sha256": "3ffe6c1fb5970cd3e0dba036136ccb28fbf79f56c72b59fb94696a5dfd22cb30",
          "sha1": "ca09f699a4b84ae2d6d7d30d2aa5e3e1b87ae772",
          "md5": "d3b879a87ba2b3f9f81cb95d9af3afb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticbeanstalk",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "elasticbeanstalk-1.31.0-unspecified.jar",
          "url": "elasticbeanstalk-1.31.0-unspecified.jar",
          "size": 154988,
          "sha512": "287beab71542b712b5c9567c81b5ad810c532f91bf85826ecb1e1541fa0902ce44d67194b7a74e5c35c8d1e59bebd750d6e8e4ccb61a429ce591ef9d3081205d",
          "sha256": "3ffe6c1fb5970cd3e0dba036136ccb28fbf79f56c72b59fb94696a5dfd22cb30",
          "sha1": "ca09f699a4b84ae2d6d7d30d2aa5e3e1b87ae772",
          "md5": "d3b879a87ba2b3f9f81cb95d9af3afb8"
        }
      ]
    }
  ]
}
