{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-region-info",
    "version": "1.31.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.31.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-region-info-1.31.0-0.6.23.jar",
          "url": "cdk-region-info-1.31.0-0.6.23.jar",
          "size": 432,
          "sha512": "9cddfd13c3830980d7fb63835b4d547b5adc426b4cd1266e9a29ad5f208a3b5fde518d5b7a3a0fb115abc0e3657b82cccd34490e015fdbdf9816a7d19df578e2",
          "sha256": "2ec5f24f49e83763b123805dc4f1a645dcca6a42383672556e54b9648fd54042",
          "sha1": "e58d966096fdfb71c10bf5669bb62b014a19e3bd",
          "md5": "016af8eee896d2cc0de29fd105f22ff3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.31.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-region-info-1.31.0-0.6.23.jar",
          "url": "cdk-region-info-1.31.0-0.6.23.jar",
          "size": 432,
          "sha512": "9cddfd13c3830980d7fb63835b4d547b5adc426b4cd1266e9a29ad5f208a3b5fde518d5b7a3a0fb115abc0e3657b82cccd34490e015fdbdf9816a7d19df578e2",
          "sha256": "2ec5f24f49e83763b123805dc4f1a645dcca6a42383672556e54b9648fd54042",
          "sha1": "e58d966096fdfb71c10bf5669bb62b014a19e3bd",
          "md5": "016af8eee896d2cc0de29fd105f22ff3"
        }
      ]
    }
  ]
}
