{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "greengrass",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "greengrass",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrass-1.104.0-0.6.21.jar",
          "url": "greengrass-1.104.0-0.6.21.jar",
          "size": 685708,
          "sha512": "ebe10125d1ce20350adc2770eab6f3933ff5c3b81c10d5084194d61dec6362f706cdc61b4106134f98a99445a1283a23bbcaf2c2d282c6f2fb6bfb2e2d3edf4f",
          "sha256": "c4052dff890853b80a34336e48ac5bb3906311406308666033faccce1c670000",
          "sha1": "ae0c1a00a7da52185f529715600ff4639b82e8ce",
          "md5": "d551863c4d1705d3ce8a7f1441dd384e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "greengrass",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrass-1.104.0-0.6.21.jar",
          "url": "greengrass-1.104.0-0.6.21.jar",
          "size": 685708,
          "sha512": "ebe10125d1ce20350adc2770eab6f3933ff5c3b81c10d5084194d61dec6362f706cdc61b4106134f98a99445a1283a23bbcaf2c2d282c6f2fb6bfb2e2d3edf4f",
          "sha256": "c4052dff890853b80a34336e48ac5bb3906311406308666033faccce1c670000",
          "sha1": "ae0c1a00a7da52185f529715600ff4639b82e8ce",
          "md5": "d551863c4d1705d3ce8a7f1441dd384e"
        }
      ]
    }
  ]
}
