{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "inspector",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "inspector",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "inspector-1.109.0-0.6.21.jar",
          "url": "inspector-1.109.0-0.6.21.jar",
          "size": 41159,
          "sha512": "fbf323b0e0fa92a427a85a453c231ba0de9a4c96d6c59c105e21accf651bfd9b99613bb8f39d548cc5b548569e9db7ca17511e085021d8a90b2bcec2e80527e2",
          "sha256": "9faf08645173a66394d16c5635189b74feac984a0d2a4c5997a027121fbcf2ab",
          "sha1": "5e172be030360df177ab8c32d37b5e2fbccb2ca4",
          "md5": "75f7176eab716bceda9993e926df7fef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "inspector",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "inspector-1.109.0-0.6.21.jar",
          "url": "inspector-1.109.0-0.6.21.jar",
          "size": 41159,
          "sha512": "fbf323b0e0fa92a427a85a453c231ba0de9a4c96d6c59c105e21accf651bfd9b99613bb8f39d548cc5b548569e9db7ca17511e085021d8a90b2bcec2e80527e2",
          "sha256": "9faf08645173a66394d16c5635189b74feac984a0d2a4c5997a027121fbcf2ab",
          "sha1": "5e172be030360df177ab8c32d37b5e2fbccb2ca4",
          "md5": "75f7176eab716bceda9993e926df7fef"
        }
      ]
    }
  ]
}
