{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "qldb",
    "version": "1.110.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cnrjfrtzdvad5bhmsg7msamtuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "qldb",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "qldb-1.110.0-0.6.21.jar",
          "url": "qldb-1.110.0-0.6.21.jar",
          "size": 43393,
          "sha512": "1cfb6041485878b5e44ec38ea791a1ad885a02cd829db1d421be54a706586759d52de457d92e3b317e045e7e33dfa32b49e35ac2788b1c0449a02d0d0a746f54",
          "sha256": "1eb74bb6aae5924adfd957d618261252e46f28c74fa850acd1a803a365f5498d",
          "sha1": "fe3bbf2cef0baf6ddeeae090012a060d70f73b4b",
          "md5": "1cbb231d4d42ed9b0c441bb81f97f7e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "qldb",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "qldb-1.110.0-0.6.21.jar",
          "url": "qldb-1.110.0-0.6.21.jar",
          "size": 43393,
          "sha512": "1cfb6041485878b5e44ec38ea791a1ad885a02cd829db1d421be54a706586759d52de457d92e3b317e045e7e33dfa32b49e35ac2788b1c0449a02d0d0a746f54",
          "sha256": "1eb74bb6aae5924adfd957d618261252e46f28c74fa850acd1a803a365f5498d",
          "sha1": "fe3bbf2cef0baf6ddeeae090012a060d70f73b4b",
          "md5": "1cbb231d4d42ed9b0c441bb81f97f7e8"
        }
      ]
    }
  ]
}
