{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sagemaker",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sagemaker",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sagemaker-1.103.0-0.6.21.jar",
          "url": "sagemaker-1.103.0-0.6.21.jar",
          "size": 1474262,
          "sha512": "d31637eeca987b41e8227c4e69c5407f12cf640806da45323e2750ddeb086e0b63c0f6dfccd76ce81d795892b2c2be5720466314f9e7a97b121079820eccbbe2",
          "sha256": "203d92cf28cebb0f02ce88b0f8a8fdc077177edd0e0295ee81783622e508ac5d",
          "sha1": "4075be07e05a95b494113cd9e0e1223cacbf850f",
          "md5": "d487dd1e2670da5e5994f0011b1ae282"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sagemaker",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sagemaker-1.103.0-0.6.21.jar",
          "url": "sagemaker-1.103.0-0.6.21.jar",
          "size": 1474262,
          "sha512": "d31637eeca987b41e8227c4e69c5407f12cf640806da45323e2750ddeb086e0b63c0f6dfccd76ce81d795892b2c2be5720466314f9e7a97b121079820eccbbe2",
          "sha256": "203d92cf28cebb0f02ce88b0f8a8fdc077177edd0e0295ee81783622e508ac5d",
          "sha1": "4075be07e05a95b494113cd9e0e1223cacbf850f",
          "md5": "d487dd1e2670da5e5994f0011b1ae282"
        }
      ]
    }
  ]
}
