{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "imagebuilder",
    "version": "1.100.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "smkqp7thvbfexba6catfwegxzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.100.0-0.6.21.jar",
          "url": "imagebuilder-1.100.0-0.6.21.jar",
          "size": 240727,
          "sha512": "2bf5bf183fe5949078f1bde6b77862c1c2280a9700c4f5c2d2b16a4db38255f9e3518c463c4b6466dd5e79d0fd9f9b406d5cbd0e9a1eefff5c3642fa64e1be95",
          "sha256": "43ba972f6409b94a8a94391d57551c8d76b2c209ac6e3b3650e862608d8883ad",
          "sha1": "a302baacb81d771e98d15546ccb41be4b6387565",
          "md5": "21fe5e4759229cfc83f7c801ef31f5d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.100.0-0.6.21.jar",
          "url": "imagebuilder-1.100.0-0.6.21.jar",
          "size": 240727,
          "sha512": "2bf5bf183fe5949078f1bde6b77862c1c2280a9700c4f5c2d2b16a4db38255f9e3518c463c4b6466dd5e79d0fd9f9b406d5cbd0e9a1eefff5c3642fa64e1be95",
          "sha256": "43ba972f6409b94a8a94391d57551c8d76b2c209ac6e3b3650e862608d8883ad",
          "sha1": "a302baacb81d771e98d15546ccb41be4b6387565",
          "md5": "21fe5e4759229cfc83f7c801ef31f5d3"
        }
      ]
    }
  ]
}
