{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "greengrassv2",
    "version": "1.106.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "apa3jttzlbgsjbklj7vcehaque"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "greengrassv2",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrassv2-1.106.1-0.6.21.jar",
          "url": "greengrassv2-1.106.1-0.6.21.jar",
          "size": 119313,
          "sha512": "bc9de3dba4b758af936671c0cf69765d26b071dc6c085253ef3a1c4b8f28953e16886f1a4f673df7c462011c59981a936eaeaf0ac139da0af9a19b8dada7e84c",
          "sha256": "a66c573be25763d42e2f974eefff9a5b3020f5516b6f5ea9bcf06122a59ca95",
          "sha1": "dba202ee3f507c7320a2ab94a59ddce3a1fa314c",
          "md5": "88f149d3f7003adfb737c31315372b35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "greengrassv2",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrassv2-1.106.1-0.6.21.jar",
          "url": "greengrassv2-1.106.1-0.6.21.jar",
          "size": 119313,
          "sha512": "bc9de3dba4b758af936671c0cf69765d26b071dc6c085253ef3a1c4b8f28953e16886f1a4f673df7c462011c59981a936eaeaf0ac139da0af9a19b8dada7e84c",
          "sha256": "a66c573be25763d42e2f974eefff9a5b3020f5516b6f5ea9bcf06122a59ca95",
          "sha1": "dba202ee3f507c7320a2ab94a59ddce3a1fa314c",
          "md5": "88f149d3f7003adfb737c31315372b35"
        }
      ]
    }
  ]
}
