{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "workspaces",
    "version": "1.31.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "workspaces",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "workspaces-1.31.0-0.6.23.jar",
          "url": "workspaces-1.31.0-0.6.23.jar",
          "size": 40834,
          "sha512": "0ae442f43e1618b98579e35aa90b31d02534ca7e845d8130e67e4bd9b2609f6c94945702f89b5fd23187d6ab0212036b7c743399ee8eea458e10f0fd6dfd3ffb",
          "sha256": "3e9e26eb44477ced44840a34bd120905645c2e685adbe4141650c971cf0d9e24",
          "sha1": "14f0600839d698c30fba5082670e292bf7976459",
          "md5": "1f2cf05f07b741c784d03bb55e1ba2d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "workspaces",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "workspaces-1.31.0-0.6.23.jar",
          "url": "workspaces-1.31.0-0.6.23.jar",
          "size": 40834,
          "sha512": "0ae442f43e1618b98579e35aa90b31d02534ca7e845d8130e67e4bd9b2609f6c94945702f89b5fd23187d6ab0212036b7c743399ee8eea458e10f0fd6dfd3ffb",
          "sha256": "3e9e26eb44477ced44840a34bd120905645c2e685adbe4141650c971cf0d9e24",
          "sha1": "14f0600839d698c30fba5082670e292bf7976459",
          "md5": "1f2cf05f07b741c784d03bb55e1ba2d0"
        }
      ]
    }
  ]
}
