{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticache",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticache",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticache-1.116.0-0.6.21.jar",
          "url": "elasticache-1.116.0-0.6.21.jar",
          "size": 281315,
          "sha512": "12870a86c7fdcb55de0cc0319d380656d57097455f1a3f235165c46b5364a1a53096e01b6262c9dc9349e0e5f557a2531c3664ee39ee897f6942413728c9748a",
          "sha256": "19d11376ecc2c7def7dac377a4631ad42ef999ef59404b6af66a4f320d6df0c0",
          "sha1": "e078d5e4b224f9e60927384b2ec83c9280b93737",
          "md5": "55cd600a9741c73ffcb755ced9156948"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticache",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticache-1.116.0-0.6.21.jar",
          "url": "elasticache-1.116.0-0.6.21.jar",
          "size": 281315,
          "sha512": "12870a86c7fdcb55de0cc0319d380656d57097455f1a3f235165c46b5364a1a53096e01b6262c9dc9349e0e5f557a2531c3664ee39ee897f6942413728c9748a",
          "sha256": "19d11376ecc2c7def7dac377a4631ad42ef999ef59404b6af66a4f320d6df0c0",
          "sha1": "e078d5e4b224f9e60927384b2ec83c9280b93737",
          "md5": "55cd600a9741c73ffcb755ced9156948"
        }
      ]
    }
  ]
}
