{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "licensemanager",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "pksuzuox3ne6pgnvsva7g32w2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "licensemanager",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "licensemanager-1.110.1-0.6.21.jar",
          "url": "licensemanager-1.110.1-0.6.21.jar",
          "size": 110306,
          "sha512": "3156386f671abc0924351a8d93f74d53df0383fb0a4e8ee3c3deb2d15e9370b87801cb7bd2f9b87c71dbb191da5a371c56ed5b307ffd641d1547f38670ec9d7",
          "sha256": "a7d76a6173557c76e8f65b6c089e7f7c239556882eb59e56ad9f91d1c116475b",
          "sha1": "c3284d43ea9ff06526292d7ea3b02ecd825a8ba8",
          "md5": "8aef1f574b83b6b28c13eac1e61020e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "licensemanager",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "licensemanager-1.110.1-0.6.21.jar",
          "url": "licensemanager-1.110.1-0.6.21.jar",
          "size": 110306,
          "sha512": "3156386f671abc0924351a8d93f74d53df0383fb0a4e8ee3c3deb2d15e9370b87801cb7bd2f9b87c71dbb191da5a371c56ed5b307ffd641d1547f38670ec9d7",
          "sha256": "a7d76a6173557c76e8f65b6c089e7f7c239556882eb59e56ad9f91d1c116475b",
          "sha1": "c3284d43ea9ff06526292d7ea3b02ecd825a8ba8",
          "md5": "8aef1f574b83b6b28c13eac1e61020e3"
        }
      ]
    }
  ]
}
