{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "emrcontainers",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "emrcontainers",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emrcontainers-1.105.0-0.6.21.jar",
          "url": "emrcontainers-1.105.0-0.6.21.jar",
          "size": 38492,
          "sha512": "f9011ecd611637c5fbf35ae42e25a0cc54b5cad1778c1ac228db791a4acf0e75c8703f6d5751ee5798765ec54f0fa22ddba523c58b44c660712e60bc879bdae7",
          "sha256": "5c8ad455be46a86359d941d8f95ef2b772f155dddf4ce1c18358dc3a8bf19ca8",
          "sha1": "2aec2addae5c3d07f233f5a2ab744e79b7b5e0d0",
          "md5": "5c6fbc1705623f933ed1b7b1efff5314"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "emrcontainers",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emrcontainers-1.105.0-0.6.21.jar",
          "url": "emrcontainers-1.105.0-0.6.21.jar",
          "size": 38492,
          "sha512": "f9011ecd611637c5fbf35ae42e25a0cc54b5cad1778c1ac228db791a4acf0e75c8703f6d5751ee5798765ec54f0fa22ddba523c58b44c660712e60bc879bdae7",
          "sha256": "5c8ad455be46a86359d941d8f95ef2b772f155dddf4ce1c18358dc3a8bf19ca8",
          "sha1": "2aec2addae5c3d07f233f5a2ab744e79b7b5e0d0",
          "md5": "5c6fbc1705623f933ed1b7b1efff5314"
        }
      ]
    }
  ]
}
