{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestarconnections",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestarconnections",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarconnections-1.112.0-0.6.21.jar",
          "url": "codestarconnections-1.112.0-0.6.21.jar",
          "size": 9592,
          "sha512": "5835f248968ac41e79a3627ee4143663c4079e67211f4d128adb01ac2edbbf1f24af6f89f9978e941ec753a58ccdf6f50ae41b607828b63d0c9ee36c74658c27",
          "sha256": "987efbfa4ce7e8b507189380231409fb5c8f34a49ad6c22898cb211f5fddbe",
          "sha1": "765db1c0b2f23da4ddd97a6013a0f2d157bcf22d",
          "md5": "7bd0d59a947057ebf300dcf5d6e9fdee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestarconnections",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarconnections-1.112.0-0.6.21.jar",
          "url": "codestarconnections-1.112.0-0.6.21.jar",
          "size": 9592,
          "sha512": "5835f248968ac41e79a3627ee4143663c4079e67211f4d128adb01ac2edbbf1f24af6f89f9978e941ec753a58ccdf6f50ae41b607828b63d0c9ee36c74658c27",
          "sha256": "987efbfa4ce7e8b507189380231409fb5c8f34a49ad6c22898cb211f5fddbe",
          "sha1": "765db1c0b2f23da4ddd97a6013a0f2d157bcf22d",
          "md5": "7bd0d59a947057ebf300dcf5d6e9fdee"
        }
      ]
    }
  ]
}
