{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lambda-nodejs",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-nodejs",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-nodejs-1.107.0-0.6.21.jar",
          "url": "lambda-nodejs-1.107.0-0.6.21.jar",
          "size": 25634,
          "sha512": "8fb893e3050c74836a3e1399796795a0efab8aed343278bea43055d4537bc9ecdfd824f3fa78fbbcfbdb0b78e9bacf02563c49453e7a30a476338b6e98f0f5d2",
          "sha256": "7dac89fa10eb35fc0d96e6a43326fee9052539cd6d3db6ff12119398a0d0e485",
          "sha1": "7c5d7620c55dadef1b899a6e5e7415b02697c012",
          "md5": "1483bba91d40af204775091aba63705a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-nodejs",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-nodejs-1.107.0-0.6.21.jar",
          "url": "lambda-nodejs-1.107.0-0.6.21.jar",
          "size": 25634,
          "sha512": "8fb893e3050c74836a3e1399796795a0efab8aed343278bea43055d4537bc9ecdfd824f3fa78fbbcfbdb0b78e9bacf02563c49453e7a30a476338b6e98f0f5d2",
          "sha256": "7dac89fa10eb35fc0d96e6a43326fee9052539cd6d3db6ff12119398a0d0e485",
          "sha1": "7c5d7620c55dadef1b899a6e5e7415b02697c012",
          "md5": "1483bba91d40af204775091aba63705a"
        }
      ]
    }
  ]
}
