{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "events",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "events",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "events-1.109.0-0.6.21.jar",
          "url": "events-1.109.0-0.6.21.jar",
          "size": 259703,
          "sha512": "f5f8f96a46f42bb06dc39f9a24756c981ee201ce2dfb496ad5097129037c02f8ee9211b0bac607756a31206effe9c30a42f9e4e529961ebd73de7d26ef1ed944",
          "sha256": "ba6633d7e698c4187f34537687a48a5c006cb110a35a958c7fe5d4499cba2514",
          "sha1": "921d452a00e80c1cc45254934c2692baa1b8b9f4",
          "md5": "efeaef4194d91c2a48a144a2b1fbede"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "events",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "events-1.109.0-0.6.21.jar",
          "url": "events-1.109.0-0.6.21.jar",
          "size": 259703,
          "sha512": "f5f8f96a46f42bb06dc39f9a24756c981ee201ce2dfb496ad5097129037c02f8ee9211b0bac607756a31206effe9c30a42f9e4e529961ebd73de7d26ef1ed944",
          "sha256": "ba6633d7e698c4187f34537687a48a5c006cb110a35a958c7fe5d4499cba2514",
          "sha1": "921d452a00e80c1cc45254934c2692baa1b8b9f4",
          "md5": "efeaef4194d91c2a48a144a2b1fbede"
        }
      ]
    }
  ]
}
