{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "efs",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "efs",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "efs-1.102.0-0.6.21.jar",
          "url": "efs-1.102.0-0.6.21.jar",
          "size": 149436,
          "sha512": "2b489132a41c0f998ad13dd8e19a38a7ecbe529d0e38ce89757af138b08dd5d02e17bdf3dd6e192439e8297cefbe8c481867201661de13690880ef875a5a5de8",
          "sha256": "1ea8527b581625ac5a3ff963a3b48ef9d654d89e4635485156ca9601e3169632",
          "sha1": "8f0afd713253310e6ec0c286a81fd4295d16d75e",
          "md5": "6680703d9ba6cf24ebfe08ba5c93c6f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "efs",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "efs-1.102.0-0.6.21.jar",
          "url": "efs-1.102.0-0.6.21.jar",
          "size": 149436,
          "sha512": "2b489132a41c0f998ad13dd8e19a38a7ecbe529d0e38ce89757af138b08dd5d02e17bdf3dd6e192439e8297cefbe8c481867201661de13690880ef875a5a5de8",
          "sha256": "1ea8527b581625ac5a3ff963a3b48ef9d654d89e4635485156ca9601e3169632",
          "sha1": "8f0afd713253310e6ec0c286a81fd4295d16d75e",
          "md5": "6680703d9ba6cf24ebfe08ba5c93c6f9"
        }
      ]
    }
  ]
}
