{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codeguruprofiler",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codeguruprofiler",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codeguruprofiler-1.103.0-0.6.21.jar",
          "url": "codeguruprofiler-1.103.0-0.6.21.jar",
          "size": 30616,
          "sha512": "9413d94d007918053276d4a26bf9b79a3452a47084cd9dd3b4b17d168a69fb66241827cf0b0857da32b3c4f07bd44c7b01a41ca799fd320305074078e36011d9",
          "sha256": "f8255a36a2f9f9c695ef5f7d96d4578312f5c1e56101b53753199ef069ea037b",
          "sha1": "de85e888ebcff844877291c257a8cdc673dc52c6",
          "md5": "8c71249fe55d237f20bfffd3f8474ef2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codeguruprofiler",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codeguruprofiler-1.103.0-0.6.21.jar",
          "url": "codeguruprofiler-1.103.0-0.6.21.jar",
          "size": 30616,
          "sha512": "9413d94d007918053276d4a26bf9b79a3452a47084cd9dd3b4b17d168a69fb66241827cf0b0857da32b3c4f07bd44c7b01a41ca799fd320305074078e36011d9",
          "sha256": "f8255a36a2f9f9c695ef5f7d96d4578312f5c1e56101b53753199ef069ea037b",
          "sha1": "de85e888ebcff844877291c257a8cdc673dc52c6",
          "md5": "8c71249fe55d237f20bfffd3f8474ef2"
        }
      ]
    }
  ]
}
