{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cur",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cur",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cur-1.114.0-0.6.21.jar",
          "url": "cur-1.114.0-0.6.21.jar",
          "size": 19930,
          "sha512": "f3ec3dab7a8435358269c18a8062df5707cd1c6ab33dee1164d7c3b56c93b2ebba30a250f36a528948c023760a32915b94c9a8f1ff668c57a90405d80aba4ef7",
          "sha256": "c15f53ea944d65521c1353a521145b7086a37ff1681003559d4b9582d8a465e2",
          "sha1": "e7a6990bdedcb46b1f3e12575952b09fb1cbf8a",
          "md5": "21428f423aa67ab8d53455eb5fc1e9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cur",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cur-1.114.0-0.6.21.jar",
          "url": "cur-1.114.0-0.6.21.jar",
          "size": 19930,
          "sha512": "f3ec3dab7a8435358269c18a8062df5707cd1c6ab33dee1164d7c3b56c93b2ebba30a250f36a528948c023760a32915b94c9a8f1ff668c57a90405d80aba4ef7",
          "sha256": "c15f53ea944d65521c1353a521145b7086a37ff1681003559d4b9582d8a465e2",
          "sha1": "e7a6990bdedcb46b1f3e12575952b09fb1cbf8a",
          "md5": "21428f423aa67ab8d53455eb5fc1e9c"
        }
      ]
    }
  ]
}
