{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "databrew",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "databrew",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "databrew-1.105.0-0.6.21.jar",
          "url": "databrew-1.105.0-0.6.21.jar",
          "size": 374460,
          "sha512": "9b73b81f700677039c290c459ddd0c49b01e37a1da213cfe2e5620c07119efd20829d2200ae2f210e9893e8ee1a8be0e1a99c875bfde7189f1242fb3271ebe1b",
          "sha256": "4c50dc3bafcb06e70e6a05a54ef13f1bbc9310e984abe3c1e9548d52526a0ead",
          "sha1": "a82d2ac56865cb6f8f347410406c9b71e88d2582",
          "md5": "bf154abdbd8814a0465d08886afc6ec7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "databrew",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "databrew-1.105.0-0.6.21.jar",
          "url": "databrew-1.105.0-0.6.21.jar",
          "size": 374460,
          "sha512": "9b73b81f700677039c290c459ddd0c49b01e37a1da213cfe2e5620c07119efd20829d2200ae2f210e9893e8ee1a8be0e1a99c875bfde7189f1242fb3271ebe1b",
          "sha256": "4c50dc3bafcb06e70e6a05a54ef13f1bbc9310e984abe3c1e9548d52526a0ead",
          "sha1": "a82d2ac56865cb6f8f347410406c9b71e88d2582",
          "md5": "bf154abdbd8814a0465d08886afc6ec7"
        }
      ]
    }
  ]
}
