{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sns-subscriptions",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sns-subscriptions",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sns-subscriptions-1.107.0-0.6.21.jar",
          "url": "sns-subscriptions-1.107.0-0.6.21.jar",
          "size": 23754,
          "sha512": "f9702069e20e5de5b9c98b18895817e2ee7f3562e63b7c7eae323e371ec2bf510cd156c303b04a4a29ec39a621fe686280d10732fc65c64b00e0b171e13e8333",
          "sha256": "7dd3bc4c4faa7db8d911678b06637032009d4798939fb0404f3ba74c603ad30f",
          "sha1": "361b614bf59f326b8a37f732044d88207863f838",
          "md5": "aa91ff02229169aa3cfe2623b923aab3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sns-subscriptions",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sns-subscriptions-1.107.0-0.6.21.jar",
          "url": "sns-subscriptions-1.107.0-0.6.21.jar",
          "size": 23754,
          "sha512": "f9702069e20e5de5b9c98b18895817e2ee7f3562e63b7c7eae323e371ec2bf510cd156c303b04a4a29ec39a621fe686280d10732fc65c64b00e0b171e13e8333",
          "sha256": "7dd3bc4c4faa7db8d911678b06637032009d4798939fb0404f3ba74c603ad30f",
          "sha1": "361b614bf59f326b8a37f732044d88207863f838",
          "md5": "aa91ff02229169aa3cfe2623b923aab3"
        }
      ]
    }
  ]
}
