{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticloadbalancingv2-targets",
    "version": "1.64.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticloadbalancingv2-targets",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "elasticloadbalancingv2-targets-1.64.0-0.6.23.jar",
          "url": "elasticloadbalancingv2-targets-1.64.0-0.6.23.jar",
          "size": 462,
          "sha512": "28882ccde56a8dc0abfaab94c262a9fc68211178779bf1fbf58a0b469c592f17e878df25e6f993cc402054c4aa7476f7f898468f7f0926de4ea0b7d62f81f3b9",
          "sha256": "57ae821a0e02675e31a3b62955e5ec1381777c1ef892047aa0702bbbc4a1c844",
          "sha1": "9669d8aedd65916703284bb61e3c30c8b73d7446",
          "md5": "f0a636dda3b7fa55600df86f99db70a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticloadbalancingv2-targets",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "elasticloadbalancingv2-targets-1.64.0-0.6.23.jar",
          "url": "elasticloadbalancingv2-targets-1.64.0-0.6.23.jar",
          "size": 462,
          "sha512": "28882ccde56a8dc0abfaab94c262a9fc68211178779bf1fbf58a0b469c592f17e878df25e6f993cc402054c4aa7476f7f898468f7f0926de4ea0b7d62f81f3b9",
          "sha256": "57ae821a0e02675e31a3b62955e5ec1381777c1ef892047aa0702bbbc4a1c844",
          "sha1": "9669d8aedd65916703284bb61e3c30c8b73d7446",
          "md5": "f0a636dda3b7fa55600df86f99db70a1"
        }
      ]
    }
  ]
}
