{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codegurureviewer",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codegurureviewer",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codegurureviewer-1.105.0-0.6.21.jar",
          "url": "codegurureviewer-1.105.0-0.6.21.jar",
          "size": 9920,
          "sha512": "34adad5b40bcf27f6a7ab3bbfc8187515dd6801b5d2ee7d937ebc0ac7f12fb45d8ceb36df5006e942f6c29bfad2ff0c7b3a1e54cbedf1f3f3b2fe550ee6a04fe",
          "sha256": "bfd450eb2c2c3451aceb5d9207bcbd302cd03378fe910e38dd9f687f0f110491",
          "sha1": "850a07259a4985a8bb105993037e7b315339d173",
          "md5": "5504b6a4755dcc703a5dc06d9cde7a0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codegurureviewer",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codegurureviewer-1.105.0-0.6.21.jar",
          "url": "codegurureviewer-1.105.0-0.6.21.jar",
          "size": 9920,
          "sha512": "34adad5b40bcf27f6a7ab3bbfc8187515dd6801b5d2ee7d937ebc0ac7f12fb45d8ceb36df5006e942f6c29bfad2ff0c7b3a1e54cbedf1f3f3b2fe550ee6a04fe",
          "sha256": "bfd450eb2c2c3451aceb5d9207bcbd302cd03378fe910e38dd9f687f0f110491",
          "sha1": "850a07259a4985a8bb105993037e7b315339d173",
          "md5": "5504b6a4755dcc703a5dc06d9cde7a0c"
        }
      ]
    }
  ]
}
