{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lambda-nodejs",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-nodejs",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-nodejs-1.104.0-0.6.21.jar",
          "url": "lambda-nodejs-1.104.0-0.6.21.jar",
          "size": 25653,
          "sha512": "82df623e6e3b16093e5da18b6e016823b46605f2ea42d34a6f215be5d022c4d403f2e2de41458bc2f7881ef1a0fe931089c81ffeedd551fd5106379ddf23318b",
          "sha256": "2010d715dbc4e71b973687e892c469a9b6516815355689d8ae9cd3ccc40fc800",
          "sha1": "faad4714eff56bab24916fe07315cb440a444177",
          "md5": "d3e32f7c21593749fc6df6938faf6be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-nodejs",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-nodejs-1.104.0-0.6.21.jar",
          "url": "lambda-nodejs-1.104.0-0.6.21.jar",
          "size": 25653,
          "sha512": "82df623e6e3b16093e5da18b6e016823b46605f2ea42d34a6f215be5d022c4d403f2e2de41458bc2f7881ef1a0fe931089c81ffeedd551fd5106379ddf23318b",
          "sha256": "2010d715dbc4e71b973687e892c469a9b6516815355689d8ae9cd3ccc40fc800",
          "sha1": "faad4714eff56bab24916fe07315cb440a444177",
          "md5": "d3e32f7c21593749fc6df6938faf6be"
        }
      ]
    }
  ]
}
