{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotanalytics",
    "version": "1.34.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotanalytics",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "iotanalytics-1.34.0-0.6.22.jar",
          "url": "iotanalytics-1.34.0-0.6.22.jar",
          "size": 400482,
          "sha512": "f7a572702e352e771abec7d8f14e33cab3556d0e354f3b08a02c67848fc6febe81fdeb0680ae61acaaf4ded0e485ae4c8185952056e6f11a58f272be8ad2ba2c",
          "sha256": "cbabf01f0fbfef06bff261b384a6d288543cbdab548a77a753c7be8a29752f6d",
          "sha1": "0ada9aa77b4dca1c2b39e012fe5c9b66231d1b13",
          "md5": "d2c064e1ba1f9ff1e2968b2a75c93de3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotanalytics",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "iotanalytics-1.34.0-0.6.22.jar",
          "url": "iotanalytics-1.34.0-0.6.22.jar",
          "size": 400482,
          "sha512": "f7a572702e352e771abec7d8f14e33cab3556d0e354f3b08a02c67848fc6febe81fdeb0680ae61acaaf4ded0e485ae4c8185952056e6f11a58f272be8ad2ba2c",
          "sha256": "cbabf01f0fbfef06bff261b384a6d288543cbdab548a77a753c7be8a29752f6d",
          "sha1": "0ada9aa77b4dca1c2b39e012fe5c9b66231d1b13",
          "md5": "d2c064e1ba1f9ff1e2968b2a75c93de3"
        }
      ]
    }
  ]
}
