{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotcoredeviceadvisor",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotcoredeviceadvisor",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotcoredeviceadvisor-1.115.0-0.6.21.jar",
          "url": "iotcoredeviceadvisor-1.115.0-0.6.21.jar",
          "size": 9307,
          "sha512": "4b02c4d37b706a80a6d8df201fecda40afe1dfef0f919779946dca3deece47b2504be3e5873739394600c39fa79d18785f19aeee899b89bd79f37732823600ec",
          "sha256": "4ab7a73d7edeb817500db06b5856a6c6a435ec8c21544a5e96a85accbbde8eb5",
          "sha1": "2f0595ca0e74062e839034d3ca3016ff7183803a",
          "md5": "b2ea3f3d189e8ebad4b79e409ffa45e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotcoredeviceadvisor",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotcoredeviceadvisor-1.115.0-0.6.21.jar",
          "url": "iotcoredeviceadvisor-1.115.0-0.6.21.jar",
          "size": 9307,
          "sha512": "4b02c4d37b706a80a6d8df201fecda40afe1dfef0f919779946dca3deece47b2504be3e5873739394600c39fa79d18785f19aeee899b89bd79f37732823600ec",
          "sha256": "4ab7a73d7edeb817500db06b5856a6c6a435ec8c21544a5e96a85accbbde8eb5",
          "sha1": "2f0595ca0e74062e839034d3ca3016ff7183803a",
          "md5": "b2ea3f3d189e8ebad4b79e409ffa45e7"
        }
      ]
    }
  ]
}
