{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codeartifact",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codeartifact",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codeartifact-1.111.0-0.6.21.jar",
          "url": "codeartifact-1.111.0-0.6.21.jar",
          "size": 17904,
          "sha512": "edaf6fbff932cfa1c8cb6c9ba5b9826688565d747012e5a8f13437a32e1555f74d670d4a6ef055da52d1a7498fcb13913903c85bdc79fcffb3694b47b4ac61d9",
          "sha256": "41b653ba704f683949a5cca5b4cbac2f1a61864c5cb3b3750be5a467ddc7b378",
          "sha1": "e159c25d379d856293e76deba1e24ea315b130a2",
          "md5": "bd2ab08cb76886c6e2a72b0e6b1ea5a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codeartifact",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codeartifact-1.111.0-0.6.21.jar",
          "url": "codeartifact-1.111.0-0.6.21.jar",
          "size": 17904,
          "sha512": "edaf6fbff932cfa1c8cb6c9ba5b9826688565d747012e5a8f13437a32e1555f74d670d4a6ef055da52d1a7498fcb13913903c85bdc79fcffb3694b47b4ac61d9",
          "sha256": "41b653ba704f683949a5cca5b4cbac2f1a61864c5cb3b3750be5a467ddc7b378",
          "sha1": "e159c25d379d856293e76deba1e24ea315b130a2",
          "md5": "bd2ab08cb76886c6e2a72b0e6b1ea5a6"
        }
      ]
    }
  ]
}
