{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "mediaconvert",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "mediaconvert",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediaconvert-1.105.0-0.6.21.jar",
          "url": "mediaconvert-1.105.0-0.6.21.jar",
          "size": 51055,
          "sha512": "a4c548180acdeccdcca9e2dbaf320fe25569dd96d34ab821453cb95882196cd677da0f0e8f4f640bd0f61b5f08b52bed6b8f4a06c1cafdc33f72c4f40d9bfc18",
          "sha256": "fca17662f247d67f947a58079b7e9580d3ac188a7d50f6a6a80dc66fff17a0b8",
          "sha1": "3a4d1f7cbbe3220c67bde91d8ea7d8b95960dce",
          "md5": "c4f6618a363bf8f27f5772a3c5ee2c65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "mediaconvert",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediaconvert-1.105.0-0.6.21.jar",
          "url": "mediaconvert-1.105.0-0.6.21.jar",
          "size": 51055,
          "sha512": "a4c548180acdeccdcca9e2dbaf320fe25569dd96d34ab821453cb95882196cd677da0f0e8f4f640bd0f61b5f08b52bed6b8f4a06c1cafdc33f72c4f40d9bfc18",
          "sha256": "fca17662f247d67f947a58079b7e9580d3ac188a7d50f6a6a80dc66fff17a0b8",
          "sha1": "3a4d1f7cbbe3220c67bde91d8ea7d8b95960dce",
          "md5": "c4f6618a363bf8f27f5772a3c5ee2c65"
        }
      ]
    }
  ]
}
