{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sagemaker",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sagemaker",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sagemaker-1.99.0-0.6.21.jar",
          "url": "sagemaker-1.99.0-0.6.21.jar",
          "size": 1482471,
          "sha512": "e585fd11b4247e85979bc62fd4d97dcd1fd505168bfbf762b2279b1a4fb0cb51702217acb72aef8c3a2f74b1ea0eddf7311d14c8da2f2e14c12efa56d2d151a7",
          "sha256": "6b71673cdecb71e67cf47b0a389b7e3708c512f727a31146e67c3bf65004d479",
          "sha1": "ecc90398de849f46847974eb39a665a18f336ca2",
          "md5": "f92e3104df8f7b03a2c6948fd69dba1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sagemaker",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sagemaker-1.99.0-0.6.21.jar",
          "url": "sagemaker-1.99.0-0.6.21.jar",
          "size": 1482471,
          "sha512": "e585fd11b4247e85979bc62fd4d97dcd1fd505168bfbf762b2279b1a4fb0cb51702217acb72aef8c3a2f74b1ea0eddf7311d14c8da2f2e14c12efa56d2d151a7",
          "sha256": "6b71673cdecb71e67cf47b0a389b7e3708c512f727a31146e67c3bf65004d479",
          "sha1": "ecc90398de849f46847974eb39a665a18f336ca2",
          "md5": "f92e3104df8f7b03a2c6948fd69dba1c"
        }
      ]
    }
  ]
}
