{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "batch",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "batch",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ecr",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ecs",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "secretsmanager",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ssm",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "batch-1.118.0-0.6.25.jar",
          "url": "batch-1.118.0-0.6.25.jar",
          "size": 339294,
          "sha512": "18a4ef701f8d8f4c9b754fcf05d326c004d2a5f30754d24174cba84746125763f4e806c49d86740948154a0d912136fcbdffc58c3e0b77a528539af4b271c59c",
          "sha256": "be8ae40ec470b3638976a04d22e0fd2e8d398ea31bd055f0ae1b881fc9b977f4",
          "sha1": "aaaa1077d2bf378785f417eac08b083e91b37c86",
          "md5": "e9cc4de2f55c8c2eb7eb9ac74471d393"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "batch",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ecr",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ecs",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "secretsmanager",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ssm",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "batch-1.118.0-0.6.25.jar",
          "url": "batch-1.118.0-0.6.25.jar",
          "size": 339294,
          "sha512": "18a4ef701f8d8f4c9b754fcf05d326c004d2a5f30754d24174cba84746125763f4e806c49d86740948154a0d912136fcbdffc58c3e0b77a528539af4b271c59c",
          "sha256": "be8ae40ec470b3638976a04d22e0fd2e8d398ea31bd055f0ae1b881fc9b977f4",
          "sha1": "aaaa1077d2bf378785f417eac08b083e91b37c86",
          "md5": "e9cc4de2f55c8c2eb7eb9ac74471d393"
        }
      ]
    }
  ]
}
