{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "waf",
    "version": "1.34.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "waf",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "waf-1.34.0-0.6.22.jar",
          "url": "waf-1.34.0-0.6.22.jar",
          "size": 189094,
          "sha512": "e0c44d597bd396ff5be3707ffdaf100e91beb5a20748e7f5abc2ec4f41fd0436a029c48c5bbcde804f5cbd612f32aaf8d0be6a3ed41447f77f15b302521a1845",
          "sha256": "12c875476959adcaa73649fa8c378875c4a40e9e84453eff7d5343aec7e4ece9",
          "sha1": "7edea7994e421e05eac07a80475c898c4a3f8eb8",
          "md5": "bbf20bb3d1cfc5a8ed3954c11495afb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "waf",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "waf-1.34.0-0.6.22.jar",
          "url": "waf-1.34.0-0.6.22.jar",
          "size": 189094,
          "sha512": "e0c44d597bd396ff5be3707ffdaf100e91beb5a20748e7f5abc2ec4f41fd0436a029c48c5bbcde804f5cbd612f32aaf8d0be6a3ed41447f77f15b302521a1845",
          "sha256": "12c875476959adcaa73649fa8c378875c4a40e9e84453eff7d5343aec7e4ece9",
          "sha1": "7edea7994e421e05eac07a80475c898c4a3f8eb8",
          "md5": "bbf20bb3d1cfc5a8ed3954c11495afb0"
        }
      ]
    }
  ]
}
