{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-cx-api",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cx-api-1.113.0-0.6.21.jar",
          "url": "cdk-cx-api-1.113.0-0.6.21.jar",
          "size": 76033,
          "sha512": "54ca7d03b029025c9b427a330921cf4924b14823e8b75e651837850a4fa8e1a723620470f813e4c94e3d6d2ce08151f2981325b0b05f955bbcac114b372d9c40",
          "sha256": "e9abeba4b2bf6d4c1a81a7548ebf4e850a0201b7208e4e3779357af943da0a21",
          "sha1": "3718757a37e14f59efd5391be69faf90dbb96710",
          "md5": "a2b78c2889396eb0cabe84e81120695e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cx-api-1.113.0-0.6.21.jar",
          "url": "cdk-cx-api-1.113.0-0.6.21.jar",
          "size": 76033,
          "sha512": "54ca7d03b029025c9b427a330921cf4924b14823e8b75e651837850a4fa8e1a723620470f813e4c94e3d6d2ce08151f2981325b0b05f955bbcac114b372d9c40",
          "sha256": "e9abeba4b2bf6d4c1a81a7548ebf4e850a0201b7208e4e3779357af943da0a21",
          "sha1": "3718757a37e14f59efd5391be69faf90dbb96710",
          "md5": "a2b78c2889396eb0cabe84e81120695e"
        }
      ]
    }
  ]
}
