{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codeguruprofiler",
    "version": "1.34.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codeguruprofiler",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "codeguruprofiler-1.34.0-0.6.22.jar",
          "url": "codeguruprofiler-1.34.0-0.6.22.jar",
          "size": 8776,
          "sha512": "ded6e2178fdc23466748f0cef88a92d45794fd33763c3329d85d77f9971a96b974dde4f5581e71df2b391b94010dae80ea146ffe95dbb796ceb96e66df4ceaf4",
          "sha256": "4b7ece2a66856807555c95c2c1f0d2b8118b3890396a2a5593e7628bd6e24449",
          "sha1": "c26459ae149f3470d800e8099094f73909fa0319",
          "md5": "6a1f0dbb3acd9f24ee32787d2ed243d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codeguruprofiler",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "codeguruprofiler-1.34.0-0.6.22.jar",
          "url": "codeguruprofiler-1.34.0-0.6.22.jar",
          "size": 8776,
          "sha512": "ded6e2178fdc23466748f0cef88a92d45794fd33763c3329d85d77f9971a96b974dde4f5581e71df2b391b94010dae80ea146ffe95dbb796ceb96e66df4ceaf4",
          "sha256": "4b7ece2a66856807555c95c2c1f0d2b8118b3890396a2a5593e7628bd6e24449",
          "sha1": "c26459ae149f3470d800e8099094f73909fa0319",
          "md5": "6a1f0dbb3acd9f24ee32787d2ed243d6"
        }
      ]
    }
  ]
}
