{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "waf",
    "version": "1.31.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "waf",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "waf-1.31.0-0.6.23.jar",
          "url": "waf-1.31.0-0.6.23.jar",
          "size": 189105,
          "sha512": "0f59c8498fdd5e0c8b947396668ef10cfa3e663ade01c5d0dfe1501b6268f19da8365d2ebd16211c1681410fbc864b9d7d31137f8c306e1dc56af804231e7fa2",
          "sha256": "e6927ce20d2ff757ff6c955fb6b46850c3118c7e14889200af5eec32ccc376e0",
          "sha1": "eef39c3c8daa75c4c52bb1d6208ff8d3373ff4d0",
          "md5": "6f083b7d78e77c08f24cc09bd3c2f363"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "waf",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "waf-1.31.0-0.6.23.jar",
          "url": "waf-1.31.0-0.6.23.jar",
          "size": 189105,
          "sha512": "0f59c8498fdd5e0c8b947396668ef10cfa3e663ade01c5d0dfe1501b6268f19da8365d2ebd16211c1681410fbc864b9d7d31137f8c306e1dc56af804231e7fa2",
          "sha256": "e6927ce20d2ff757ff6c955fb6b46850c3118c7e14889200af5eec32ccc376e0",
          "sha1": "eef39c3c8daa75c4c52bb1d6208ff8d3373ff4d0",
          "md5": "6f083b7d78e77c08f24cc09bd3c2f363"
        }
      ]
    }
  ]
}
