{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "alexa-ask",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "alexa-ask",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "alexa-ask-1.108.1-0.6.21.jar",
          "url": "alexa-ask-1.108.1-0.6.21.jar",
          "size": 41766,
          "sha512": "851d20e39cd9684bef5adde30717581fab6b25e49a023d7b9b46fa178a7f820e7e3aac96a6ff6cb02bc08d24be184b724027ac17f11bd441cefbeec07585cc18",
          "sha256": "ff436400088abf84765e579897cf33aa964766826ba4f7a75c3786822b1a4641",
          "sha1": "b186145493948e84aaf8bea26895c1b5fa59062a",
          "md5": "dee2bb841d68e000a6e3d85b9a3be298"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "alexa-ask",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "alexa-ask-1.108.1-0.6.21.jar",
          "url": "alexa-ask-1.108.1-0.6.21.jar",
          "size": 41766,
          "sha512": "851d20e39cd9684bef5adde30717581fab6b25e49a023d7b9b46fa178a7f820e7e3aac96a6ff6cb02bc08d24be184b724027ac17f11bd441cefbeec07585cc18",
          "sha256": "ff436400088abf84765e579897cf33aa964766826ba4f7a75c3786822b1a4641",
          "sha1": "b186145493948e84aaf8bea26895c1b5fa59062a",
          "md5": "dee2bb841d68e000a6e3d85b9a3be298"
        }
      ]
    }
  ]
}
