{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "budgets",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "budgets",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "budgets-1.118.0-0.6.25.jar",
          "url": "budgets-1.118.0-0.6.25.jar",
          "size": 190252,
          "sha512": "d89c615a814dab28a90770a9ee86acb8c56c2c9f364a1d801631b1a2b4572255638286e5c12cb91c60744b0eff4ea5ab1b61f9c9fe3817c034a77b9281d608fa",
          "sha256": "5be8f601f2d6d76d924bfbe2dd9d2586999d640bfd696295abfd55f6c4525803",
          "sha1": "2760082a0ce2158ef704d0b41d50c025ea6b38b9",
          "md5": "ec86ede6c0f8d4ed547ba21766b8e1f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "budgets",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "budgets-1.118.0-0.6.25.jar",
          "url": "budgets-1.118.0-0.6.25.jar",
          "size": 190252,
          "sha512": "d89c615a814dab28a90770a9ee86acb8c56c2c9f364a1d801631b1a2b4572255638286e5c12cb91c60744b0eff4ea5ab1b61f9c9fe3817c034a77b9281d608fa",
          "sha256": "5be8f601f2d6d76d924bfbe2dd9d2586999d640bfd696295abfd55f6c4525803",
          "sha1": "2760082a0ce2158ef704d0b41d50c025ea6b38b9",
          "md5": "ec86ede6c0f8d4ed547ba21766b8e1f1"
        }
      ]
    }
  ]
}
