{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "acmpca",
    "version": "1.31.0-unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "acmpca",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "acmpca-1.31.0-unspecified.jar",
          "url": "acmpca-1.31.0-unspecified.jar",
          "size": 76929,
          "sha512": "62b8c8cbd897fd920b65bd8e3bbfe9bf755966ff2b09d5bfb905bbf87b1b065f4aef15d9f537b83d42eef39b9279e0ccb2417115162409afd55abee9462fbb83",
          "sha256": "dcc7ad30eb0e9fe304beab154b8671a8d0e22557c40cc3149501887626cb97e2",
          "sha1": "1e8a73c9b5ff4102d4680bf9ea21ac14dfc557a7",
          "md5": "05a01f434b214510a80d0a06bf41875d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "acmpca",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "acmpca-1.31.0-unspecified.jar",
          "url": "acmpca-1.31.0-unspecified.jar",
          "size": 76929,
          "sha512": "62b8c8cbd897fd920b65bd8e3bbfe9bf755966ff2b09d5bfb905bbf87b1b065f4aef15d9f537b83d42eef39b9279e0ccb2417115162409afd55abee9462fbb83",
          "sha256": "dcc7ad30eb0e9fe304beab154b8671a8d0e22557c40cc3149501887626cb97e2",
          "sha1": "1e8a73c9b5ff4102d4680bf9ea21ac14dfc557a7",
          "md5": "05a01f434b214510a80d0a06bf41875d"
        }
      ]
    }
  ]
}
