{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "servicecatalog",
    "version": "1.100.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "smkqp7thvbfexba6catfwegxzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "servicecatalog",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "servicecatalog-1.100.0-0.6.21.jar",
          "url": "servicecatalog-1.100.0-0.6.21.jar",
          "size": 209826,
          "sha512": "8273f855f7761b177c560f6067a7a054ce2398b656168d59d9de487c2fc9f7bacc9a37bed25076d4e6134b7546d2b0f5672d04fa740fe9fca37f54bc7a5b0c75",
          "sha256": "7c3697c4fc207b6a78faf88391d6aca0764198965aa84ac7992d17946702a0b0",
          "sha1": "226726227aaa81f59562f97584a1cb3cf0fa12e0",
          "md5": "f2a080c1743e42c06af953804d4e5427"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "servicecatalog",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "servicecatalog-1.100.0-0.6.21.jar",
          "url": "servicecatalog-1.100.0-0.6.21.jar",
          "size": 209826,
          "sha512": "8273f855f7761b177c560f6067a7a054ce2398b656168d59d9de487c2fc9f7bacc9a37bed25076d4e6134b7546d2b0f5672d04fa740fe9fca37f54bc7a5b0c75",
          "sha256": "7c3697c4fc207b6a78faf88391d6aca0764198965aa84ac7992d17946702a0b0",
          "sha1": "226726227aaa81f59562f97584a1cb3cf0fa12e0",
          "md5": "f2a080c1743e42c06af953804d4e5427"
        }
      ]
    }
  ]
}
