{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-lambda-layer-kubectl",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-lambda-layer-kubectl",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-lambda-layer-kubectl-1.109.0-0.6.21.jar",
          "url": "cdk-lambda-layer-kubectl-1.109.0-0.6.21.jar",
          "size": 450,
          "sha512": "aea004a1bfc7b023133c0497e0a698341c795da51e58088724c9165c6680dd8fe0e589415ceb07ea123504fb4c77598f7ea009831beda146a03c17ba8ffde54",
          "sha256": "42b46d03c08bcf2c5b06df7a1380ba85a25bff6d830d782085196fce7a479adb",
          "sha1": "46998c506b00db126b92b572dec7896c8e989824",
          "md5": "abfc5d5b8228892ab81ce758ba6dbd36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-lambda-layer-kubectl",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-lambda-layer-kubectl-1.109.0-0.6.21.jar",
          "url": "cdk-lambda-layer-kubectl-1.109.0-0.6.21.jar",
          "size": 450,
          "sha512": "aea004a1bfc7b023133c0497e0a698341c795da51e58088724c9165c6680dd8fe0e589415ceb07ea123504fb4c77598f7ea009831beda146a03c17ba8ffde54",
          "sha256": "42b46d03c08bcf2c5b06df7a1380ba85a25bff6d830d782085196fce7a479adb",
          "sha1": "46998c506b00db126b92b572dec7896c8e989824",
          "md5": "abfc5d5b8228892ab81ce758ba6dbd36"
        }
      ]
    }
  ]
}
