{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codeartifact",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codeartifact",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codeartifact-1.116.0-0.6.21.jar",
          "url": "codeartifact-1.116.0-0.6.21.jar",
          "size": 17921,
          "sha512": "ee82f1bddc1b0bbdebc9aab0a279b811952a0785ac5fd876bb4ab8257081fedc4b9dee7390e8f0e1d042621add491d2494a77185acec4f8c845c42b42f298325",
          "sha256": "9b3300b64de104a63b70076c8f8ac8644b88201181034b699e9b979ba62fc0f",
          "sha1": "7f6ac2b1406d38a5e56f253ea0890df96b0dd9ca",
          "md5": "701b181ed2b7738eb8533e4251431514"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codeartifact",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codeartifact-1.116.0-0.6.21.jar",
          "url": "codeartifact-1.116.0-0.6.21.jar",
          "size": 17921,
          "sha512": "ee82f1bddc1b0bbdebc9aab0a279b811952a0785ac5fd876bb4ab8257081fedc4b9dee7390e8f0e1d042621add491d2494a77185acec4f8c845c42b42f298325",
          "sha256": "9b3300b64de104a63b70076c8f8ac8644b88201181034b699e9b979ba62fc0f",
          "sha1": "7f6ac2b1406d38a5e56f253ea0890df96b0dd9ca",
          "md5": "701b181ed2b7738eb8533e4251431514"
        }
      ]
    }
  ]
}
