{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sns-subscriptions",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sns-subscriptions",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sns-subscriptions-1.108.1-0.6.21.jar",
          "url": "sns-subscriptions-1.108.1-0.6.21.jar",
          "size": 23711,
          "sha512": "a851732c52e1c74c5c61c1eb8d144ba784e4f159c32a46c70f1842f13f14c4156075fa9097b6c1db497724e8ec32bea1e1e87dd08687052d76c358bfa4bffcc7",
          "sha256": "a0a5864f4c057388604ecdc491abdd8690df211dbec15a90b1e86087104b0203",
          "sha1": "279e28bfc84ceb2d39f88e261aa2e28d1aa5b890",
          "md5": "2076574108ae1176863d90d86c8d9bb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sns-subscriptions",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sns-subscriptions-1.108.1-0.6.21.jar",
          "url": "sns-subscriptions-1.108.1-0.6.21.jar",
          "size": 23711,
          "sha512": "a851732c52e1c74c5c61c1eb8d144ba784e4f159c32a46c70f1842f13f14c4156075fa9097b6c1db497724e8ec32bea1e1e87dd08687052d76c358bfa4bffcc7",
          "sha256": "a0a5864f4c057388604ecdc491abdd8690df211dbec15a90b1e86087104b0203",
          "sha1": "279e28bfc84ceb2d39f88e261aa2e28d1aa5b890",
          "md5": "2076574108ae1176863d90d86c8d9bb8"
        }
      ]
    }
  ]
}
