{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "kendra",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "kendra",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kendra-1.105.0-0.6.21.jar",
          "url": "kendra-1.105.0-0.6.21.jar",
          "size": 554749,
          "sha512": "1940058f946576d934375791bd31e11e4902cd1bf072649ecfa47559d2bfeb7c4804e509932d922c69e2fbd4b4a1b6b380520f6df3ca9909e4d53bc86be11ed1",
          "sha256": "6ed4cbf0b4e0caae7cb799631ab4219ee8f1691e7d7b3cc72c7c92467120ff6e",
          "sha1": "44b352cbb0f5126cae8a7eeed72686b960ceccbb",
          "md5": "f907f1532334fe6ed10954249a821048"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "kendra",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kendra-1.105.0-0.6.21.jar",
          "url": "kendra-1.105.0-0.6.21.jar",
          "size": 554749,
          "sha512": "1940058f946576d934375791bd31e11e4902cd1bf072649ecfa47559d2bfeb7c4804e509932d922c69e2fbd4b4a1b6b380520f6df3ca9909e4d53bc86be11ed1",
          "sha256": "6ed4cbf0b4e0caae7cb799631ab4219ee8f1691e7d7b3cc72c7c92467120ff6e",
          "sha1": "44b352cbb0f5126cae8a7eeed72686b960ceccbb",
          "md5": "f907f1532334fe6ed10954249a821048"
        }
      ]
    }
  ]
}
