{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "fms",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "fms",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fms-1.102.0-0.6.21.jar",
          "url": "fms-1.102.0-0.6.21.jar",
          "size": 75054,
          "sha512": "2e230d73b3c7133dfd7252d2202d997dd200dd128fd1611d2353647ac0d12f4ac3735b6e426c8c0db52701bc0846912f3611be2514689aa4e71fe98492ac9a8a",
          "sha256": "c22c8cb6ad0c8ebcf381ed4ae4c4d5bbd38a3fd488410b681582177f5830ac4b",
          "sha1": "305d71b60e82f32f7ae925d6f5d58a110a266008",
          "md5": "ae5290d69c69d7a07ce232ad1d4ad584"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "fms",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fms-1.102.0-0.6.21.jar",
          "url": "fms-1.102.0-0.6.21.jar",
          "size": 75054,
          "sha512": "2e230d73b3c7133dfd7252d2202d997dd200dd128fd1611d2353647ac0d12f4ac3735b6e426c8c0db52701bc0846912f3611be2514689aa4e71fe98492ac9a8a",
          "sha256": "c22c8cb6ad0c8ebcf381ed4ae4c4d5bbd38a3fd488410b681582177f5830ac4b",
          "sha1": "305d71b60e82f32f7ae925d6f5d58a110a266008",
          "md5": "ae5290d69c69d7a07ce232ad1d4ad584"
        }
      ]
    }
  ]
}
