{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-lambda-layer-kubectl",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-lambda-layer-kubectl",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-lambda-layer-kubectl-1.115.0-0.6.21.jar",
          "url": "cdk-lambda-layer-kubectl-1.115.0-0.6.21.jar",
          "size": 450,
          "sha512": "33f637a994fac6f99d1724ed2af805e3778b876e43905747facfc2f061ff76f35abb865b5c450c3a4d187502e4e35e8ac8c8a737427abfef107d8132c13edf9e",
          "sha256": "894e8229a890f494b670e0e335758e97417a39984d6ed3b59a82e0c328e42bae",
          "sha1": "675ead146bcfda30f71b366434f4009a3ad8a62a",
          "md5": "2ec7b870b4f09cf3c8efed725f4c515f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-lambda-layer-kubectl",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-lambda-layer-kubectl-1.115.0-0.6.21.jar",
          "url": "cdk-lambda-layer-kubectl-1.115.0-0.6.21.jar",
          "size": 450,
          "sha512": "33f637a994fac6f99d1724ed2af805e3778b876e43905747facfc2f061ff76f35abb865b5c450c3a4d187502e4e35e8ac8c8a737427abfef107d8132c13edf9e",
          "sha256": "894e8229a890f494b670e0e335758e97417a39984d6ed3b59a82e0c328e42bae",
          "sha1": "675ead146bcfda30f71b366434f4009a3ad8a62a",
          "md5": "2ec7b870b4f09cf3c8efed725f4c515f"
        }
      ]
    }
  ]
}
