{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "appintegrations",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "appintegrations",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appintegrations-1.104.0-0.6.21.jar",
          "url": "appintegrations-1.104.0-0.6.21.jar",
          "size": 35104,
          "sha512": "210afa382dde0b25d4e5a2115a7e8e8188d40945d905bb760376ba837c6fb8aaf17e6dd1cb73d04361fc3297601748ed266ac35bacaedd759d786132bcbc3255",
          "sha256": "17af0f2a80e766898fb3833cef92a60d6e754746c2f694a630d7077d31a053ce",
          "sha1": "3e81f51ec511a213f0f4e23576aabb33396e629e",
          "md5": "36aa0f88a8ea237fa60e5bc3c40c531d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "appintegrations",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appintegrations-1.104.0-0.6.21.jar",
          "url": "appintegrations-1.104.0-0.6.21.jar",
          "size": 35104,
          "sha512": "210afa382dde0b25d4e5a2115a7e8e8188d40945d905bb760376ba837c6fb8aaf17e6dd1cb73d04361fc3297601748ed266ac35bacaedd759d786132bcbc3255",
          "sha256": "17af0f2a80e766898fb3833cef92a60d6e754746c2f694a630d7077d31a053ce",
          "sha1": "3e81f51ec511a213f0f4e23576aabb33396e629e",
          "md5": "36aa0f88a8ea237fa60e5bc3c40c531d"
        }
      ]
    }
  ]
}
