{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ses",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ses",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ses-1.114.0-0.6.21.jar",
          "url": "ses-1.114.0-0.6.21.jar",
          "size": 299912,
          "sha512": "2a3bed2c26dea6dea40adfdd40a2a47b3ba85e03e4b86b705ab8b695b79ed5374c6c0f9a01c4334cd6e87a6906a6340ccd8629352775b92a1ce8bba115e99c70",
          "sha256": "b8508ae6926cfecca3df9c30bf86e557ca4d08fa18d6f99bddd42c0e87fd8775",
          "sha1": "becff9e219f5a7fb64537cf5860491aa7c907ef0",
          "md5": "c7ab4951a3318d1a8f4ab52a60870b9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ses",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ses-1.114.0-0.6.21.jar",
          "url": "ses-1.114.0-0.6.21.jar",
          "size": 299912,
          "sha512": "2a3bed2c26dea6dea40adfdd40a2a47b3ba85e03e4b86b705ab8b695b79ed5374c6c0f9a01c4334cd6e87a6906a6340ccd8629352775b92a1ce8bba115e99c70",
          "sha256": "b8508ae6926cfecca3df9c30bf86e557ca4d08fa18d6f99bddd42c0e87fd8775",
          "sha1": "becff9e219f5a7fb64537cf5860491aa7c907ef0",
          "md5": "c7ab4951a3318d1a8f4ab52a60870b9d"
        }
      ]
    }
  ]
}
