{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "eventschemas",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.112.0-0.6.21.jar",
          "url": "eventschemas-1.112.0-0.6.21.jar",
          "size": 43009,
          "sha512": "4e3c5def601e8d5dcaa6a26e2adbcdbbc5fe3bb6b0d4c5a3835687ea06696361762fef3e07dfb6e3f75aa08d4387ce7f262420410ecf6064a7dc02a9f867b116",
          "sha256": "864cb3abb8840e254b4356de41cd5113e52d2f78085f7047d93abbd35be36097",
          "sha1": "5ea597ac5f04a49ff3cefb5c83f85fd13a7195ab",
          "md5": "e877630bb12e3be1436db65b6fef8b6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.112.0-0.6.21.jar",
          "url": "eventschemas-1.112.0-0.6.21.jar",
          "size": 43009,
          "sha512": "4e3c5def601e8d5dcaa6a26e2adbcdbbc5fe3bb6b0d4c5a3835687ea06696361762fef3e07dfb6e3f75aa08d4387ce7f262420410ecf6064a7dc02a9f867b116",
          "sha256": "864cb3abb8840e254b4356de41cd5113e52d2f78085f7047d93abbd35be36097",
          "sha1": "5ea597ac5f04a49ff3cefb5c83f85fd13a7195ab",
          "md5": "e877630bb12e3be1436db65b6fef8b6e"
        }
      ]
    }
  ]
}
