{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "certificatemanager",
    "version": "1.34.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "certificatemanager",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudformation",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "certificatemanager-1.34.0-0.6.22.jar",
          "url": "certificatemanager-1.34.0-0.6.22.jar",
          "size": 39942,
          "sha512": "da8ba87ab1d3306bb439d4ed9560a0735cd7a4df84f698f878b2bf0c811da7dab5e33671f4b3ee799c0aaad5e33be11b1f19157c61518567640259dd3bae54c8",
          "sha256": "30bbefc42763a061c5d0bba53d8de2826d4eca97b544a8f16e1882844f28f91e",
          "sha1": "7403dab8a0591227f62dacb902b0fd324a70c50b",
          "md5": "fac5a2099592c43b9c763b1d49cd2ef7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "certificatemanager",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudformation",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "certificatemanager-1.34.0-0.6.22.jar",
          "url": "certificatemanager-1.34.0-0.6.22.jar",
          "size": 39942,
          "sha512": "da8ba87ab1d3306bb439d4ed9560a0735cd7a4df84f698f878b2bf0c811da7dab5e33671f4b3ee799c0aaad5e33be11b1f19157c61518567640259dd3bae54c8",
          "sha256": "30bbefc42763a061c5d0bba53d8de2826d4eca97b544a8f16e1882844f28f91e",
          "sha1": "7403dab8a0591227f62dacb902b0fd324a70c50b",
          "md5": "fac5a2099592c43b9c763b1d49cd2ef7"
        }
      ]
    }
  ]
}
