{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-cx-api",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cx-api-1.114.0-0.6.21.jar",
          "url": "cdk-cx-api-1.114.0-0.6.21.jar",
          "size": 76023,
          "sha512": "970f900bbe7f9223dc78aee8217da7ba863cb70f3e90eae93e01a078fe6de24e89e9a6fc183a3651b1469510e32023a04573e4fadced1d0e1a9995bf954e21fe",
          "sha256": "65a17bb1de83966548992ed4827a101d2915f125c4136d2f622e8c8d8ef03848",
          "sha1": "8fb85f580f6aa1703afb3007eacd6273e3dc9bec",
          "md5": "8b6fc2bcdb29835896512c751c95e272"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cx-api-1.114.0-0.6.21.jar",
          "url": "cdk-cx-api-1.114.0-0.6.21.jar",
          "size": 76023,
          "sha512": "970f900bbe7f9223dc78aee8217da7ba863cb70f3e90eae93e01a078fe6de24e89e9a6fc183a3651b1469510e32023a04573e4fadced1d0e1a9995bf954e21fe",
          "sha256": "65a17bb1de83966548992ed4827a101d2915f125c4136d2f622e8c8d8ef03848",
          "sha1": "8fb85f580f6aa1703afb3007eacd6273e3dc9bec",
          "md5": "8b6fc2bcdb29835896512c751c95e272"
        }
      ]
    }
  ]
}
