{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestarnotifications",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarnotifications-1.105.0-0.6.21.jar",
          "url": "codestarnotifications-1.105.0-0.6.21.jar",
          "size": 23613,
          "sha512": "26aa8277843659f359b5d9b92b08f4f61c4a08268950f8b65fd2f5bd370f02836c40f05f8ff421f24993b737fcc0005cfaa51df473766a4ef464fff7ee6e3d9d",
          "sha256": "3d52f6092a2c49058fb62d87851b8a4828f7ba8e0b98bc987352b3be3d4315b1",
          "sha1": "34a5460d22c0ca2344253c2b3003115d9b1f069b",
          "md5": "b0515b75e0349f7f09373ad64984afd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarnotifications-1.105.0-0.6.21.jar",
          "url": "codestarnotifications-1.105.0-0.6.21.jar",
          "size": 23613,
          "sha512": "26aa8277843659f359b5d9b92b08f4f61c4a08268950f8b65fd2f5bd370f02836c40f05f8ff421f24993b737fcc0005cfaa51df473766a4ef464fff7ee6e3d9d",
          "sha256": "3d52f6092a2c49058fb62d87851b8a4828f7ba8e0b98bc987352b3be3d4315b1",
          "sha1": "34a5460d22c0ca2344253c2b3003115d9b1f069b",
          "md5": "b0515b75e0349f7f09373ad64984afd8"
        }
      ]
    }
  ]
}
