{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "dax",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "dax",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dax-1.108.1-0.6.21.jar",
          "url": "dax-1.108.1-0.6.21.jar",
          "size": 42585,
          "sha512": "1bbe69b2d63880c79a7ab158fe3e8f171c4608c113d23991ee8517430f6d058dc58ddf267577c94879b9ea5b1e2cafcc8b785523e4b31bc3d41c50db3a007c49",
          "sha256": "53e9a05c4677d76fc5e02d5e6f9aa04d2793bd566b5b7dcb6fed1123e090d034",
          "sha1": "2140953e0dad5d5b993c15dd065dbd651cdda175",
          "md5": "1ec5c7b06af8a7b079244b1a7a447afa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "dax",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dax-1.108.1-0.6.21.jar",
          "url": "dax-1.108.1-0.6.21.jar",
          "size": 42585,
          "sha512": "1bbe69b2d63880c79a7ab158fe3e8f171c4608c113d23991ee8517430f6d058dc58ddf267577c94879b9ea5b1e2cafcc8b785523e4b31bc3d41c50db3a007c49",
          "sha256": "53e9a05c4677d76fc5e02d5e6f9aa04d2793bd566b5b7dcb6fed1123e090d034",
          "sha1": "2140953e0dad5d5b993c15dd065dbd651cdda175",
          "md5": "1ec5c7b06af8a7b079244b1a7a447afa"
        }
      ]
    }
  ]
}
