{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lambda-python",
    "version": "1.110.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cnrjfrtzdvad5bhmsg7msamtuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-python",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-python-1.110.0-0.6.21.jar",
          "url": "lambda-python-1.110.0-0.6.21.jar",
          "size": 28043,
          "sha512": "7a73b026afb997ee6e1441ca3dfe2ea38e3f31a03f39f1332db5e906177bc6dcdc194964cc55c3cc4e33f8f4dcf6882ae2a00f05972d3828c1f8c8d79794fca1",
          "sha256": "51fc05742fc2b4a75e2a2024785317542f657c1473bc95059cc92184557cce4c",
          "sha1": "7e6ec67aaf0485cd49eaa6da881b98e5b93b86d7",
          "md5": "997c87e1aa9c5f36109fd24217b35406"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-python",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-python-1.110.0-0.6.21.jar",
          "url": "lambda-python-1.110.0-0.6.21.jar",
          "size": 28043,
          "sha512": "7a73b026afb997ee6e1441ca3dfe2ea38e3f31a03f39f1332db5e906177bc6dcdc194964cc55c3cc4e33f8f4dcf6882ae2a00f05972d3828c1f8c8d79794fca1",
          "sha256": "51fc05742fc2b4a75e2a2024785317542f657c1473bc95059cc92184557cce4c",
          "sha1": "7e6ec67aaf0485cd49eaa6da881b98e5b93b86d7",
          "md5": "997c87e1aa9c5f36109fd24217b35406"
        }
      ]
    }
  ]
}
