{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lakeformation",
    "version": "1.64.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lakeformation",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "lakeformation-1.64.0-0.6.23.jar",
          "url": "lakeformation-1.64.0-0.6.23.jar",
          "size": 109927,
          "sha512": "5084033573b4d59d62ac84d51aefd9239a0782e033bc9d66f0351e1542282fa15838dcc13d225644ebdf42ee90ffc99e5d741c01abc39e842bf417202755bfcc",
          "sha256": "a9b4433e2fb096df5718309e25ec7fe73f037fa324762fafa046f476d22e749d",
          "sha1": "28feb619969fdb76d7601b43efcae9b65dbd2d1b",
          "md5": "af8d0a7b2494bbec7cf329662d810610"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lakeformation",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "lakeformation-1.64.0-0.6.23.jar",
          "url": "lakeformation-1.64.0-0.6.23.jar",
          "size": 109927,
          "sha512": "5084033573b4d59d62ac84d51aefd9239a0782e033bc9d66f0351e1542282fa15838dcc13d225644ebdf42ee90ffc99e5d741c01abc39e842bf417202755bfcc",
          "sha256": "a9b4433e2fb096df5718309e25ec7fe73f037fa324762fafa046f476d22e749d",
          "sha1": "28feb619969fdb76d7601b43efcae9b65dbd2d1b",
          "md5": "af8d0a7b2494bbec7cf329662d810610"
        }
      ]
    }
  ]
}
