{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "quicksight",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "quicksight",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "quicksight-1.107.0-0.6.21.jar",
          "url": "quicksight-1.107.0-0.6.21.jar",
          "size": 977718,
          "sha512": "599b7527c0a65949684411ba589d91f57e5d014e3f084f3072697b6885d1d57b7aa12de1c2b864f26f15a9ee2b13af472253224f26702fefddcb3f539f49cf95",
          "sha256": "dd1a3c92e3cd7c77080ceb1eba9ea2ec3101ca36eba394386b67e35fd7a989c7",
          "sha1": "95a22ac7ff064417a62eee84be1f0b3f84577bd6",
          "md5": "2314a6cd5d40ad5ab119c81f3e05a699"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "quicksight",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "quicksight-1.107.0-0.6.21.jar",
          "url": "quicksight-1.107.0-0.6.21.jar",
          "size": 977718,
          "sha512": "599b7527c0a65949684411ba589d91f57e5d014e3f084f3072697b6885d1d57b7aa12de1c2b864f26f15a9ee2b13af472253224f26702fefddcb3f539f49cf95",
          "sha256": "dd1a3c92e3cd7c77080ceb1eba9ea2ec3101ca36eba394386b67e35fd7a989c7",
          "sha1": "95a22ac7ff064417a62eee84be1f0b3f84577bd6",
          "md5": "2314a6cd5d40ad5ab119c81f3e05a699"
        }
      ]
    }
  ]
}
