{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticbeanstalk",
    "version": "1.64.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticbeanstalk",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "elasticbeanstalk-1.64.0-0.6.23.jar",
          "url": "elasticbeanstalk-1.64.0-0.6.23.jar",
          "size": 154932,
          "sha512": "983485e09fdba22cee66ba2e9b5ce0382278f79b2fc6581b190e0f7ade9303c18281baeca99ea86f868b37e0d4f3bda0cb067ab73ddb2cc13c80956f780a286f",
          "sha256": "da713965210493e1d8479f2cd1c9e781dade468b2cfea64dd448f885df661a11",
          "sha1": "29c0812179ca08862395569b26c074e1f9b32493",
          "md5": "1c0fdc69c07a10e64257006debd155ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticbeanstalk",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "elasticbeanstalk-1.64.0-0.6.23.jar",
          "url": "elasticbeanstalk-1.64.0-0.6.23.jar",
          "size": 154932,
          "sha512": "983485e09fdba22cee66ba2e9b5ce0382278f79b2fc6581b190e0f7ade9303c18281baeca99ea86f868b37e0d4f3bda0cb067ab73ddb2cc13c80956f780a286f",
          "sha256": "da713965210493e1d8479f2cd1c9e781dade468b2cfea64dd448f885df661a11",
          "sha1": "29c0812179ca08862395569b26c074e1f9b32493",
          "md5": "1c0fdc69c07a10e64257006debd155ae"
        }
      ]
    }
  ]
}
