{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iot",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "pksuzuox3ne6pgnvsva7g32w2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iot",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iot-1.110.1-0.6.21.jar",
          "url": "iot-1.110.1-0.6.21.jar",
          "size": 795002,
          "sha512": "1ba6c10a4ae5493399c24fe39de4690d38226fd5e2d31b2b61cc54f2e80a2654bbd383a3cb1568ab38828634cf8f9dc999e8fc5bccd0568a0c63030c1f7deb3e",
          "sha256": "cbae7625521193d6db793a1a361eb88b2ae19f360c3c5aea4a4b7c697c200a6a",
          "sha1": "64133d1eea0957d9a3de36a9e3eae986557a4295",
          "md5": "f509400f958c23062828326f9bc2dffe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iot",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iot-1.110.1-0.6.21.jar",
          "url": "iot-1.110.1-0.6.21.jar",
          "size": 795002,
          "sha512": "1ba6c10a4ae5493399c24fe39de4690d38226fd5e2d31b2b61cc54f2e80a2654bbd383a3cb1568ab38828634cf8f9dc999e8fc5bccd0568a0c63030c1f7deb3e",
          "sha256": "cbae7625521193d6db793a1a361eb88b2ae19f360c3c5aea4a4b7c697c200a6a",
          "sha1": "64133d1eea0957d9a3de36a9e3eae986557a4295",
          "md5": "f509400f958c23062828326f9bc2dffe"
        }
      ]
    }
  ]
}
