{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "managedblockchain",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "managedblockchain",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "managedblockchain-1.118.0-0.6.25.jar",
          "url": "managedblockchain-1.118.0-0.6.25.jar",
          "size": 105014,
          "sha512": "c0c4085276aaa4a6c8d27bf3c41b0e492db8066c3dfabd628477df8dc66fdc137678e8a7a0b32f64e5486bed67c25c0b5948e64b889a302cf699dd3385b65c0c",
          "sha256": "422597c8da5993c0852b147862e942ba01ade60d9057f9ea31496b54a6186fdc",
          "sha1": "9095ff366014db257e2ad60f6e34c8a36108d898",
          "md5": "4670eed2370480c4bda58de0049c97e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "managedblockchain",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "managedblockchain-1.118.0-0.6.25.jar",
          "url": "managedblockchain-1.118.0-0.6.25.jar",
          "size": 105014,
          "sha512": "c0c4085276aaa4a6c8d27bf3c41b0e492db8066c3dfabd628477df8dc66fdc137678e8a7a0b32f64e5486bed67c25c0b5948e64b889a302cf699dd3385b65c0c",
          "sha256": "422597c8da5993c0852b147862e942ba01ade60d9057f9ea31496b54a6186fdc",
          "sha1": "9095ff366014db257e2ad60f6e34c8a36108d898",
          "md5": "4670eed2370480c4bda58de0049c97e1"
        }
      ]
    }
  ]
}
