{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "emr",
    "version": "1.34.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "emr",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "emr-1.34.0-0.6.22.jar",
          "url": "emr-1.34.0-0.6.22.jar",
          "size": 565955,
          "sha512": "d4f09af2f62021339eca20963feb7b1838156c1462e0a66fcf88ba7a84e8471ed169ec40da711903dc4c38476ab2c0808e1d95188f23fb1f129d249a6db1abdc",
          "sha256": "fd2597af7f7eb210d4ba66d0e8277d0731273507bca0a84d5b80f49ee3470cf6",
          "sha1": "c2f95b815b3c86cf8526b5f4b2c607f3a85558c6",
          "md5": "018839ced7fdb714991d73e29bfe6c43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "emr",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "emr-1.34.0-0.6.22.jar",
          "url": "emr-1.34.0-0.6.22.jar",
          "size": 565955,
          "sha512": "d4f09af2f62021339eca20963feb7b1838156c1462e0a66fcf88ba7a84e8471ed169ec40da711903dc4c38476ab2c0808e1d95188f23fb1f129d249a6db1abdc",
          "sha256": "fd2597af7f7eb210d4ba66d0e8277d0731273507bca0a84d5b80f49ee3470cf6",
          "sha1": "c2f95b815b3c86cf8526b5f4b2c607f3a85558c6",
          "md5": "018839ced7fdb714991d73e29bfe6c43"
        }
      ]
    }
  ]
}
