{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "kinesisfirehose",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "kinesisfirehose",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesisfirehose-1.114.0-0.6.21.jar",
          "url": "kinesisfirehose-1.114.0-0.6.21.jar",
          "size": 471127,
          "sha512": "3b92b7a245ddf92e3838539ab4cd44d33f68a795cab7cba3c86529dbe4eaa6a6f0166a09f8f314cff71bbb0063ab0270d4a9c895915d01fd452daee819d7f58c",
          "sha256": "5972c4ea09a73e4bc3ffb5143e4d5ecee6b581485d49d32dff25ed880316f823",
          "sha1": "321eb9e367505b5d3f60b2309e3a42ad7280fae8",
          "md5": "715da0706ed604b70155fe37d9c52d02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "kinesisfirehose",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesisfirehose-1.114.0-0.6.21.jar",
          "url": "kinesisfirehose-1.114.0-0.6.21.jar",
          "size": 471127,
          "sha512": "3b92b7a245ddf92e3838539ab4cd44d33f68a795cab7cba3c86529dbe4eaa6a6f0166a09f8f314cff71bbb0063ab0270d4a9c895915d01fd452daee819d7f58c",
          "sha256": "5972c4ea09a73e4bc3ffb5143e4d5ecee6b581485d49d32dff25ed880316f823",
          "sha1": "321eb9e367505b5d3f60b2309e3a42ad7280fae8",
          "md5": "715da0706ed604b70155fe37d9c52d02"
        }
      ]
    }
  ]
}
