{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "autoscalingplans",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "autoscalingplans",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscalingplans-1.113.0-0.6.21.jar",
          "url": "autoscalingplans-1.113.0-0.6.21.jar",
          "size": 109983,
          "sha512": "cb13711b7d13039f1b073e4dae5a04b6dca6c85077568e2c48b36678bd997ee5dc168af2001d0fdb592da7da9535114104ab263bb9c15cbffcb497c1c5b44f41",
          "sha256": "adeca942a1aeebd053fc969616027a9e099755232f1f7c292ebf16ab90a25a71",
          "sha1": "6512221dcd485a0c0c8c29607b24104074317d48",
          "md5": "aed5db79e08e9b092268360a62f3c98e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "autoscalingplans",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscalingplans-1.113.0-0.6.21.jar",
          "url": "autoscalingplans-1.113.0-0.6.21.jar",
          "size": 109983,
          "sha512": "cb13711b7d13039f1b073e4dae5a04b6dca6c85077568e2c48b36678bd997ee5dc168af2001d0fdb592da7da9535114104ab263bb9c15cbffcb497c1c5b44f41",
          "sha256": "adeca942a1aeebd053fc969616027a9e099755232f1f7c292ebf16ab90a25a71",
          "sha1": "6512221dcd485a0c0c8c29607b24104074317d48",
          "md5": "aed5db79e08e9b092268360a62f3c98e"
        }
      ]
    }
  ]
}
