{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "pinpoint",
    "version": "1.34.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "pinpoint",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "pinpoint-1.34.0-0.6.22.jar",
          "url": "pinpoint-1.34.0-0.6.22.jar",
          "size": 629208,
          "sha512": "297fd2f0a32482a3f2c3addca1e9efec7428589d50a54cc8fd9852d5c797b3e364ce590016c6d4233f0ec4ccec1c509092fe95bbcaf2c13554ec7f29b222e9a6",
          "sha256": "1d776a4e4d006f6723ccb221bae6aba4c8546c06c94dd11cd1cce702ae7d136d",
          "sha1": "6d90e05aac71bb3c50c6be98b379ec10fc9cbb54",
          "md5": "cf12a188a932a8419dc195f56a79dcb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "pinpoint",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "pinpoint-1.34.0-0.6.22.jar",
          "url": "pinpoint-1.34.0-0.6.22.jar",
          "size": 629208,
          "sha512": "297fd2f0a32482a3f2c3addca1e9efec7428589d50a54cc8fd9852d5c797b3e364ce590016c6d4233f0ec4ccec1c509092fe95bbcaf2c13554ec7f29b222e9a6",
          "sha256": "1d776a4e4d006f6723ccb221bae6aba4c8546c06c94dd11cd1cce702ae7d136d",
          "sha1": "6d90e05aac71bb3c50c6be98b379ec10fc9cbb54",
          "md5": "cf12a188a932a8419dc195f56a79dcb4"
        }
      ]
    }
  ]
}
