{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "macie",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "macie",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "macie-1.116.0-0.6.21.jar",
          "url": "macie-1.116.0-0.6.21.jar",
          "size": 47717,
          "sha512": "19e6e5bd26092bcbc42e662f350ca7fc8ad80c6db141a92b188b02053261481570f143cf0b618c494a9273031d4b67a7a78c3cb426ad8042afbbfd00b611b991",
          "sha256": "b7f435b81aa420c61e0d6bb1009ca5287a785168f6d34a490164d34b3bf05fdb",
          "sha1": "5bfa318e3d57c53631ac8983e06d3ba5cdfc7cef",
          "md5": "f8e6dc19fc52792258c78cdd3e269543"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "macie",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "macie-1.116.0-0.6.21.jar",
          "url": "macie-1.116.0-0.6.21.jar",
          "size": 47717,
          "sha512": "19e6e5bd26092bcbc42e662f350ca7fc8ad80c6db141a92b188b02053261481570f143cf0b618c494a9273031d4b67a7a78c3cb426ad8042afbbfd00b611b991",
          "sha256": "b7f435b81aa420c61e0d6bb1009ca5287a785168f6d34a490164d34b3bf05fdb",
          "sha1": "5bfa318e3d57c53631ac8983e06d3ba5cdfc7cef",
          "md5": "f8e6dc19fc52792258c78cdd3e269543"
        }
      ]
    }
  ]
}
