{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "autoscaling-hooktargets",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling-hooktargets",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns-subscriptions",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-hooktargets-1.112.0-0.6.21.jar",
          "url": "autoscaling-hooktargets-1.112.0-0.6.21.jar",
          "size": 448,
          "sha512": "15da267e570cb435fc7b7876960a9498e7c9a6cdfed5791f8fe32dcaa8572f66247b2ebf2a2a3a86044fdbf895fecf01d6de802beed63db52237653da3fb1059",
          "sha256": "b0f7b94bea2775a1da103e428f52e3d97c951f9ba5f134b8a9b25600c3841a38",
          "sha1": "ae349dc530a740ce6ee15fc4705e01aa760450e5",
          "md5": "6f190e9e3717e6fe8d8f74fed47e78f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling-hooktargets",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns-subscriptions",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-hooktargets-1.112.0-0.6.21.jar",
          "url": "autoscaling-hooktargets-1.112.0-0.6.21.jar",
          "size": 448,
          "sha512": "15da267e570cb435fc7b7876960a9498e7c9a6cdfed5791f8fe32dcaa8572f66247b2ebf2a2a3a86044fdbf895fecf01d6de802beed63db52237653da3fb1059",
          "sha256": "b0f7b94bea2775a1da103e428f52e3d97c951f9ba5f134b8a9b25600c3841a38",
          "sha1": "ae349dc530a740ce6ee15fc4705e01aa760450e5",
          "md5": "6f190e9e3717e6fe8d8f74fed47e78f7"
        }
      ]
    }
  ]
}
