{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "alexa-ask",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "alexa-ask",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "alexa-ask-1.99.0-0.6.21.jar",
          "url": "alexa-ask-1.99.0-0.6.21.jar",
          "size": 41761,
          "sha512": "2c14e4c4aa8821a8db784a36140c25ff4c61272ad4dc033d956c870a8565df9b068e96112f665c6a3b2d39047ebf18f3557cb3e063e78745fd2e056cc9acfa30",
          "sha256": "7d69cf36ca56f7d32883143a39d66b22f3fc01aaa9ff69c265d43f773a1e8100",
          "sha1": "22b83def07a852a8ac35adc7939e16d5d8993431",
          "md5": "e788cdf78427dd346a5d07020d573542"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "alexa-ask",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "alexa-ask-1.99.0-0.6.21.jar",
          "url": "alexa-ask-1.99.0-0.6.21.jar",
          "size": 41761,
          "sha512": "2c14e4c4aa8821a8db784a36140c25ff4c61272ad4dc033d956c870a8565df9b068e96112f665c6a3b2d39047ebf18f3557cb3e063e78745fd2e056cc9acfa30",
          "sha256": "7d69cf36ca56f7d32883143a39d66b22f3fc01aaa9ff69c265d43f773a1e8100",
          "sha1": "22b83def07a852a8ac35adc7939e16d5d8993431",
          "md5": "e788cdf78427dd346a5d07020d573542"
        }
      ]
    }
  ]
}
