{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "licensemanager",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "licensemanager",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "licensemanager-1.103.0-0.6.21.jar",
          "url": "licensemanager-1.103.0-0.6.21.jar",
          "size": 110303,
          "sha512": "ae42638f8c38c296cfe22beba9d60f0c3de5798b49ac5c5caeb4336923d193c75f286aa21ae9c7fe3b5ed3acda51bb02bec13913da556b7db4ebd282293f58d",
          "sha256": "5a408d57e9e8d0bed1152f1b4caed83729c2873cc7cbb17dbcc28c8b46acd2e5",
          "sha1": "c874a9dfff8cf3eb2c1cbe8b6400a877a329cf1d",
          "md5": "10bd60ffaabb6e831e6932e409e6a87d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "licensemanager",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "licensemanager-1.103.0-0.6.21.jar",
          "url": "licensemanager-1.103.0-0.6.21.jar",
          "size": 110303,
          "sha512": "ae42638f8c38c296cfe22beba9d60f0c3de5798b49ac5c5caeb4336923d193c75f286aa21ae9c7fe3b5ed3acda51bb02bec13913da556b7db4ebd282293f58d",
          "sha256": "5a408d57e9e8d0bed1152f1b4caed83729c2873cc7cbb17dbcc28c8b46acd2e5",
          "sha1": "c874a9dfff8cf3eb2c1cbe8b6400a877a329cf1d",
          "md5": "10bd60ffaabb6e831e6932e409e6a87d"
        }
      ]
    }
  ]
}
