{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "databrew",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "databrew",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "databrew-1.117.0-0.6.25.jar",
          "url": "databrew-1.117.0-0.6.25.jar",
          "size": 497135,
          "sha512": "05b70805cce4d7672ec695ceeeb9faf2b3075c7aba2e7172e48145402c4db83fe2c916ecaa3a8daf2e64d6ad07b8b4a882902632248359ee20fd30a2cadb8981",
          "sha256": "de0ea93b12fb938297f4241a10c59f3b141fa9ea0243be9e60308d37aab31583",
          "sha1": "65768e6209d2eb5b5272cd77d63f3c34f702d17f",
          "md5": "df8b94b8916aeec9d212e99415b7341f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "databrew",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "databrew-1.117.0-0.6.25.jar",
          "url": "databrew-1.117.0-0.6.25.jar",
          "size": 497135,
          "sha512": "05b70805cce4d7672ec695ceeeb9faf2b3075c7aba2e7172e48145402c4db83fe2c916ecaa3a8daf2e64d6ad07b8b4a882902632248359ee20fd30a2cadb8981",
          "sha256": "de0ea93b12fb938297f4241a10c59f3b141fa9ea0243be9e60308d37aab31583",
          "sha1": "65768e6209d2eb5b5272cd77d63f3c34f702d17f",
          "md5": "df8b94b8916aeec9d212e99415b7341f"
        }
      ]
    }
  ]
}
