{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "devopsguru",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "devopsguru",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "devopsguru-1.103.0-0.6.21.jar",
          "url": "devopsguru-1.103.0-0.6.21.jar",
          "size": 56982,
          "sha512": "7ac4a775427b7907a0659bd62ead58f8b90a2f9e7395ae75c8871d26d9e1f8790850a9867944ac323484707af1af38ddbbdd6968fa615257af318e5a43fd3d7f",
          "sha256": "38fb3e4603d48b0edd90d43dae6162ac2cd668396a099adf7ab8528d8379ef37",
          "sha1": "375bb394ef7f34b3760b9c5567a61d50a7088397",
          "md5": "7da4ac8b11ee6369339cc64a1659822e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "devopsguru",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "devopsguru-1.103.0-0.6.21.jar",
          "url": "devopsguru-1.103.0-0.6.21.jar",
          "size": 56982,
          "sha512": "7ac4a775427b7907a0659bd62ead58f8b90a2f9e7395ae75c8871d26d9e1f8790850a9867944ac323484707af1af38ddbbdd6968fa615257af318e5a43fd3d7f",
          "sha256": "38fb3e4603d48b0edd90d43dae6162ac2cd668396a099adf7ab8528d8379ef37",
          "sha1": "375bb394ef7f34b3760b9c5567a61d50a7088397",
          "md5": "7da4ac8b11ee6369339cc64a1659822e"
        }
      ]
    }
  ]
}
