{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ram",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ram",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ram-1.114.0-0.6.21.jar",
          "url": "ram-1.114.0-0.6.21.jar",
          "size": 18732,
          "sha512": "a80408935b93963930f0108e5d7501dfca31a6adb2b84d88e329deb2282a0f78a6fe487e26b0bfc877eecc6092a0d43e771093d6ce7db9e0cccaccf96b2ceea5",
          "sha256": "6824540c2ce1cd3bcee504131a6ca1e638aeff03b904014c73fd1df627f7cc06",
          "sha1": "e90d22dbbe103108a88509b7d9018a24b4ac97ea",
          "md5": "3e465607b3a54294e87aeed2749d18f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ram",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ram-1.114.0-0.6.21.jar",
          "url": "ram-1.114.0-0.6.21.jar",
          "size": 18732,
          "sha512": "a80408935b93963930f0108e5d7501dfca31a6adb2b84d88e329deb2282a0f78a6fe487e26b0bfc877eecc6092a0d43e771093d6ce7db9e0cccaccf96b2ceea5",
          "sha256": "6824540c2ce1cd3bcee504131a6ca1e638aeff03b904014c73fd1df627f7cc06",
          "sha1": "e90d22dbbe103108a88509b7d9018a24b4ac97ea",
          "md5": "3e465607b3a54294e87aeed2749d18f9"
        }
      ]
    }
  ]
}
