{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "mediaconnect",
    "version": "1.110.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cnrjfrtzdvad5bhmsg7msamtuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "mediaconnect",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediaconnect-1.110.0-0.6.21.jar",
          "url": "mediaconnect-1.110.0-0.6.21.jar",
          "size": 130886,
          "sha512": "4b44d926ed404fbb31e2b6f054b47f3717f616ad0bca41d52c0887374366b532bf88faeedda0b4b29e4b77033cc3e4c163697f727eb03e0764dcc4db4ea54819",
          "sha256": "759c4bc7a87e76edc4ab70f577a27caac75b878919fe8b8a1622d73fa7d74694",
          "sha1": "4e7251b94815e46805232ce97aa5d16a6413c0d5",
          "md5": "ed266b96dc6234fd1602a343bc2a8d55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "mediaconnect",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediaconnect-1.110.0-0.6.21.jar",
          "url": "mediaconnect-1.110.0-0.6.21.jar",
          "size": 130886,
          "sha512": "4b44d926ed404fbb31e2b6f054b47f3717f616ad0bca41d52c0887374366b532bf88faeedda0b4b29e4b77033cc3e4c163697f727eb03e0764dcc4db4ea54819",
          "sha256": "759c4bc7a87e76edc4ab70f577a27caac75b878919fe8b8a1622d73fa7d74694",
          "sha1": "4e7251b94815e46805232ce97aa5d16a6413c0d5",
          "md5": "ed266b96dc6234fd1602a343bc2a8d55"
        }
      ]
    }
  ]
}
