{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "apigatewayv2-integrations",
    "version": "1.98.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "iburyfrpozhnhehtcwiqubp4u4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "apigatewayv2-integrations",
          "version": {
            "requires": "1.98.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "apigatewayv2",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "servicediscovery",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apigatewayv2-integrations-1.98.0-0.6.21.jar",
          "url": "apigatewayv2-integrations-1.98.0-0.6.21.jar",
          "size": 47923,
          "sha512": "b7648657cb9c9e189a85c024f6a733dc4993b540db88816b9ff42137be5ab670eb6d3c3f6efd50026cc4b5e911c214da1353bd25885f6cfccc118e021d8d178e",
          "sha256": "1332ea3ce703e341d6c616ce66168761f8f69ea1c3fcd0ab8a1042b3b1663aff",
          "sha1": "2f3e0ee3ba34ff38165c8fb1d959188436773833",
          "md5": "5430be113e2cb9826516917719747330"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.98.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "apigatewayv2-integrations",
          "version": {
            "requires": "1.98.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "apigatewayv2",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "servicediscovery",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apigatewayv2-integrations-1.98.0-0.6.21.jar",
          "url": "apigatewayv2-integrations-1.98.0-0.6.21.jar",
          "size": 47923,
          "sha512": "b7648657cb9c9e189a85c024f6a733dc4993b540db88816b9ff42137be5ab670eb6d3c3f6efd50026cc4b5e911c214da1353bd25885f6cfccc118e021d8d178e",
          "sha256": "1332ea3ce703e341d6c616ce66168761f8f69ea1c3fcd0ab8a1042b3b1663aff",
          "sha1": "2f3e0ee3ba34ff38165c8fb1d959188436773833",
          "md5": "5430be113e2cb9826516917719747330"
        }
      ]
    }
  ]
}
