{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "apigatewayv2-authorizers",
    "version": "1.106.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "apa3jttzlbgsjbklj7vcehaque"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "apigatewayv2-authorizers",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "apigatewayv2",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cognito",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apigatewayv2-authorizers-1.106.1-0.6.21.jar",
          "url": "apigatewayv2-authorizers-1.106.1-0.6.21.jar",
          "size": 25377,
          "sha512": "cf521f23c6435295b12c715eb994b18d4ca3711bb973f11346291fa3800e51b7ffab1255e13f6dec53a3c40ef63bdaffa0b23e956dcc99e8c18f5c1ed300b674",
          "sha256": "6fce66a2e98f5f5936d8f5c7a11d4c5d36404b1a46aa07a04b1a86c2310cd630",
          "sha1": "7034e7083119cc66b1141adbbea80fcea56f0dbf",
          "md5": "6e048403dde7b0128fd4c814e7a70d0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "apigatewayv2-authorizers",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "apigatewayv2",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cognito",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apigatewayv2-authorizers-1.106.1-0.6.21.jar",
          "url": "apigatewayv2-authorizers-1.106.1-0.6.21.jar",
          "size": 25377,
          "sha512": "cf521f23c6435295b12c715eb994b18d4ca3711bb973f11346291fa3800e51b7ffab1255e13f6dec53a3c40ef63bdaffa0b23e956dcc99e8c18f5c1ed300b674",
          "sha256": "6fce66a2e98f5f5936d8f5c7a11d4c5d36404b1a46aa07a04b1a86c2310cd630",
          "sha1": "7034e7083119cc66b1141adbbea80fcea56f0dbf",
          "md5": "6e048403dde7b0128fd4c814e7a70d0b"
        }
      ]
    }
  ]
}
