{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "guardduty",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "guardduty",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "guardduty-1.112.0-0.6.21.jar",
          "url": "guardduty-1.112.0-0.6.21.jar",
          "size": 126481,
          "sha512": "8790751034d485cbab8dbec82832708bbecbb94440c8c1d69c85d93e77aa321b17c68fb86c7dfc88154b92b2eb60d3ca3f46be8f097ab5a4e49453474a7a1eb3",
          "sha256": "e8c12c29474cfc8a1e5d109354fa27d833c5c88b7d9d87bcdb38af9e19ab04eb",
          "sha1": "c071c651f7a7ec577fd0b91ef47bec11470a4636",
          "md5": "f29e7eebcaeae6a612df294bb53935f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "guardduty",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "guardduty-1.112.0-0.6.21.jar",
          "url": "guardduty-1.112.0-0.6.21.jar",
          "size": 126481,
          "sha512": "8790751034d485cbab8dbec82832708bbecbb94440c8c1d69c85d93e77aa321b17c68fb86c7dfc88154b92b2eb60d3ca3f46be8f097ab5a4e49453474a7a1eb3",
          "sha256": "e8c12c29474cfc8a1e5d109354fa27d833c5c88b7d9d87bcdb38af9e19ab04eb",
          "sha1": "c071c651f7a7ec577fd0b91ef47bec11470a4636",
          "md5": "f29e7eebcaeae6a612df294bb53935f5"
        }
      ]
    }
  ]
}
