{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lambda-destinations",
    "version": "1.101.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "jaowebu54rhl3bnpwvdhdg2v5y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-destinations",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events-targets",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-destinations-1.101.0-0.6.21.jar",
          "url": "lambda-destinations-1.101.0-0.6.21.jar",
          "size": 5569,
          "sha512": "99dfdfde6c899652937fa769ee09c94f47bc6f9b5fa6df75e305da9846b96e9bfda5f8a26d4ad67c9a1b16497b08cfc06fbf9e0896e649c34ae441e85f98dd86",
          "sha256": "38a408f9f536b5da943fc0d9247db9ae1b07f1b91d3cd8474534589352f05468",
          "sha1": "23d9330f32e8f266ae4c1c61a4f9b6acd10d4cbc",
          "md5": "e5ed398cd61d9049e18f24df673dd450"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-destinations",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events-targets",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-destinations-1.101.0-0.6.21.jar",
          "url": "lambda-destinations-1.101.0-0.6.21.jar",
          "size": 5569,
          "sha512": "99dfdfde6c899652937fa769ee09c94f47bc6f9b5fa6df75e305da9846b96e9bfda5f8a26d4ad67c9a1b16497b08cfc06fbf9e0896e649c34ae441e85f98dd86",
          "sha256": "38a408f9f536b5da943fc0d9247db9ae1b07f1b91d3cd8474534589352f05468",
          "sha1": "23d9330f32e8f266ae4c1c61a4f9b6acd10d4cbc",
          "md5": "e5ed398cd61d9049e18f24df673dd450"
        }
      ]
    }
  ]
}
