{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "route53-patterns",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "route53-patterns",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "certificatemanager",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudfront",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53-targets",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "route53-patterns-1.109.0-0.6.21.jar",
          "url": "route53-patterns-1.109.0-0.6.21.jar",
          "size": 10040,
          "sha512": "18db5bc25c9f421e918e4f71f6a982243569773638e3370f9a8ad66474cc638ee45eb0d494200e03934d844afbf13596be854f2fb1c7304040ab090eeea7c92f",
          "sha256": "f4dda2e52f0256d38f494f553baaaf37b9ffe881f9abbe1a28d70673c90434a0",
          "sha1": "96b5f01a4392de70cc2795da6d43a3f93199c88d",
          "md5": "709f9f40e506b962d678b44b3f1fcf21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "route53-patterns",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "certificatemanager",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudfront",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53-targets",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "route53-patterns-1.109.0-0.6.21.jar",
          "url": "route53-patterns-1.109.0-0.6.21.jar",
          "size": 10040,
          "sha512": "18db5bc25c9f421e918e4f71f6a982243569773638e3370f9a8ad66474cc638ee45eb0d494200e03934d844afbf13596be854f2fb1c7304040ab090eeea7c92f",
          "sha256": "f4dda2e52f0256d38f494f553baaaf37b9ffe881f9abbe1a28d70673c90434a0",
          "sha1": "96b5f01a4392de70cc2795da6d43a3f93199c88d",
          "md5": "709f9f40e506b962d678b44b3f1fcf21"
        }
      ]
    }
  ]
}
