{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iot1click",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iot1click",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iot1click-1.112.0-0.6.21.jar",
          "url": "iot1click-1.112.0-0.6.21.jar",
          "size": 52556,
          "sha512": "301a1320b4dac7f2c16301a563a8ae4a02ddc93a5688cdd8b40a0cba90d00850b7deb4d04387a66f23ef58979f793f0cb24283175348e1fdcc0b80e5a0066aeb",
          "sha256": "fb46db39f3fbed805e3ad84f91881d8b5fadd1e455b2438624e2fb37ccf29f23",
          "sha1": "15319b0d4a2348cf82d339b61aa7159494eee20c",
          "md5": "816ab064d4d334d2b36789b19b71e898"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iot1click",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iot1click-1.112.0-0.6.21.jar",
          "url": "iot1click-1.112.0-0.6.21.jar",
          "size": 52556,
          "sha512": "301a1320b4dac7f2c16301a563a8ae4a02ddc93a5688cdd8b40a0cba90d00850b7deb4d04387a66f23ef58979f793f0cb24283175348e1fdcc0b80e5a0066aeb",
          "sha256": "fb46db39f3fbed805e3ad84f91881d8b5fadd1e455b2438624e2fb37ccf29f23",
          "sha1": "15319b0d4a2348cf82d339b61aa7159494eee20c",
          "md5": "816ab064d4d334d2b36789b19b71e898"
        }
      ]
    }
  ]
}
