{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "emr",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "emr",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emr-1.104.0-0.6.21.jar",
          "url": "emr-1.104.0-0.6.21.jar",
          "size": 619076,
          "sha512": "9836956fd1f2f9117dd4cf16e79d225ff92584019f9dc1e3c262a8aed3907ee779d241a2aa002b28a8b3579b0c74351ea7f32347cb885a0353d5c09326d0cfa0",
          "sha256": "42903335fefbef7186a9464f8d4f1828a86b46dd9a8a627660b6b286bb87cc23",
          "sha1": "12a28f308473a65695bb4058f515231e6f49edf3",
          "md5": "1dc291a3e54b1c48de8226995b63b5e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "emr",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emr-1.104.0-0.6.21.jar",
          "url": "emr-1.104.0-0.6.21.jar",
          "size": 619076,
          "sha512": "9836956fd1f2f9117dd4cf16e79d225ff92584019f9dc1e3c262a8aed3907ee779d241a2aa002b28a8b3579b0c74351ea7f32347cb885a0353d5c09326d0cfa0",
          "sha256": "42903335fefbef7186a9464f8d4f1828a86b46dd9a8a627660b6b286bb87cc23",
          "sha1": "12a28f308473a65695bb4058f515231e6f49edf3",
          "md5": "1dc291a3e54b1c48de8226995b63b5e6"
        }
      ]
    }
  ]
}
