{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "s3-deployment",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "s3-deployment",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudfront",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-lambda-layer-awscli",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "s3-deployment-1.109.0-0.6.21.jar",
          "url": "s3-deployment-1.109.0-0.6.21.jar",
          "size": 24895,
          "sha512": "e59cec186dd9ea1317b8da390fc2143858ae1c8ec63aca457c4f8afd7c8604da766276b9ac8c50a7cda85418306f8252407dc220a85e54581c6cf437763002fb",
          "sha256": "4ca403900eabd6494f5b184707cde4f109d11ff210f484906f23dce9f1a6c9a0",
          "sha1": "9147cdc0cee3fcf611b5acd1853f3dffef1d6e0f",
          "md5": "a0d7e35374de393c67905e1bcc643807"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "s3-deployment",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudfront",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-lambda-layer-awscli",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "s3-deployment-1.109.0-0.6.21.jar",
          "url": "s3-deployment-1.109.0-0.6.21.jar",
          "size": 24895,
          "sha512": "e59cec186dd9ea1317b8da390fc2143858ae1c8ec63aca457c4f8afd7c8604da766276b9ac8c50a7cda85418306f8252407dc220a85e54581c6cf437763002fb",
          "sha256": "4ca403900eabd6494f5b184707cde4f109d11ff210f484906f23dce9f1a6c9a0",
          "sha1": "9147cdc0cee3fcf611b5acd1853f3dffef1d6e0f",
          "md5": "a0d7e35374de393c67905e1bcc643807"
        }
      ]
    }
  ]
}
