{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "servicecatalogappregistry",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "servicecatalogappregistry",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "servicecatalogappregistry-1.99.0-0.6.21.jar",
          "url": "servicecatalogappregistry-1.99.0-0.6.21.jar",
          "size": 31187,
          "sha512": "244d68fc5e9365b8d5e344e885ecdd5f08f667c6af2e3bfa71bd32918cf29cf548c9fd720bf8806a5f63088b9bd38f0425d59de88cdbb97dfd886f2cc272f886",
          "sha256": "61f382e47660e916d8f4f8ba1d54aac957257a94b503708419b51a28f4a78188",
          "sha1": "2871dfa7440e7f862a9c87a001fe34d2c6551f1a",
          "md5": "47dbf0523fa77455dc9aec588b367167"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "servicecatalogappregistry",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "servicecatalogappregistry-1.99.0-0.6.21.jar",
          "url": "servicecatalogappregistry-1.99.0-0.6.21.jar",
          "size": 31187,
          "sha512": "244d68fc5e9365b8d5e344e885ecdd5f08f667c6af2e3bfa71bd32918cf29cf548c9fd720bf8806a5f63088b9bd38f0425d59de88cdbb97dfd886f2cc272f886",
          "sha256": "61f382e47660e916d8f4f8ba1d54aac957257a94b503708419b51a28f4a78188",
          "sha1": "2871dfa7440e7f862a9c87a001fe34d2c6551f1a",
          "md5": "47dbf0523fa77455dc9aec588b367167"
        }
      ]
    }
  ]
}
