{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "budgets",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "budgets",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "budgets-1.112.0-0.6.21.jar",
          "url": "budgets-1.112.0-0.6.21.jar",
          "size": 190267,
          "sha512": "5dd5d923aefdbad6b1945f42161962edf1b25394d21dd03d4e57d2404ea48824418b5edcab3ab7f37d9653c721d36b15c8f5ca59848326d9a299bb265f5c0b98",
          "sha256": "1e8762fb24da046e0d07c527eaee0035f6f6cb92159df7a286fe8c74f8590134",
          "sha1": "82c1181e1876e0afef3ef881ac412bcdb497aa9e",
          "md5": "b0b372165a659c7e6827271ba8974902"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "budgets",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "budgets-1.112.0-0.6.21.jar",
          "url": "budgets-1.112.0-0.6.21.jar",
          "size": 190267,
          "sha512": "5dd5d923aefdbad6b1945f42161962edf1b25394d21dd03d4e57d2404ea48824418b5edcab3ab7f37d9653c721d36b15c8f5ca59848326d9a299bb265f5c0b98",
          "sha256": "1e8762fb24da046e0d07c527eaee0035f6f6cb92159df7a286fe8c74f8590134",
          "sha1": "82c1181e1876e0afef3ef881ac412bcdb497aa9e",
          "md5": "b0b372165a659c7e6827271ba8974902"
        }
      ]
    }
  ]
}
