{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codeguruprofiler",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codeguruprofiler",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codeguruprofiler-1.102.0-0.6.21.jar",
          "url": "codeguruprofiler-1.102.0-0.6.21.jar",
          "size": 30582,
          "sha512": "bf04fd6712a469fc82c92785c70491559674465472ab4d602c986b411108d4ef850793c19f11dfd509cc278710c3c262ddc21d259b3b2693b36a2ecbfab9e09d",
          "sha256": "26b923bb8df0bd48aeaecf4324625058bf60951b8c8e17945cb8a7b51e7bcf27",
          "sha1": "bdb2346f040a4c636ec75c71cd4239febc6c2435",
          "md5": "bef6660a1f623c238914da4126ed8439"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codeguruprofiler",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codeguruprofiler-1.102.0-0.6.21.jar",
          "url": "codeguruprofiler-1.102.0-0.6.21.jar",
          "size": 30582,
          "sha512": "bf04fd6712a469fc82c92785c70491559674465472ab4d602c986b411108d4ef850793c19f11dfd509cc278710c3c262ddc21d259b3b2693b36a2ecbfab9e09d",
          "sha256": "26b923bb8df0bd48aeaecf4324625058bf60951b8c8e17945cb8a7b51e7bcf27",
          "sha1": "bdb2346f040a4c636ec75c71cd4239febc6c2435",
          "md5": "bef6660a1f623c238914da4126ed8439"
        }
      ]
    }
  ]
}
