{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "appconfig",
    "version": "1.110.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cnrjfrtzdvad5bhmsg7msamtuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "appconfig",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appconfig-1.110.0-0.6.21.jar",
          "url": "appconfig-1.110.0-0.6.21.jar",
          "size": 93451,
          "sha512": "c80ec3a93bba5da3734184a8479485880062ca1125e2164aedfed0fa7520b02444e80744c498c86623afe899e429271ac5caf614dfec536ac5b9f38f2dfd0bd7",
          "sha256": "e85989f657e5cfce16ba4357d70961c8ab088351d9b9c355ab9a84ee9fa5d6fc",
          "sha1": "bfb1d41c8fa6bd405c5dc9296d9a11ca09609dee",
          "md5": "afef70482a4ef353e384bae92e634f17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "appconfig",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appconfig-1.110.0-0.6.21.jar",
          "url": "appconfig-1.110.0-0.6.21.jar",
          "size": 93451,
          "sha512": "c80ec3a93bba5da3734184a8479485880062ca1125e2164aedfed0fa7520b02444e80744c498c86623afe899e429271ac5caf614dfec536ac5b9f38f2dfd0bd7",
          "sha256": "e85989f657e5cfce16ba4357d70961c8ab088351d9b9c355ab9a84ee9fa5d6fc",
          "sha1": "bfb1d41c8fa6bd405c5dc9296d9a11ca09609dee",
          "md5": "afef70482a4ef353e384bae92e634f17"
        }
      ]
    }
  ]
}
