{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "wafv2",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "wafv2",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "wafv2-1.118.0-0.6.25.jar",
          "url": "wafv2-1.118.0-0.6.25.jar",
          "size": 695801,
          "sha512": "d91749c1aa57552e1004a1049d99f470db0862a75f73f0c398d76938a3d56603963830e3d967ec45b918a7add7cd5d903c92188c022a96bcb0118619cc16cc66",
          "sha256": "88982cdd52e1a83446a98cba3ce9d6c3afd39388e107e22156c9416e65052c55",
          "sha1": "dbab0d22f6a2edcefe51490d9d2d659f369be970",
          "md5": "1c5a58f5dfe5fb4a919f3e4b24261adb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "wafv2",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "wafv2-1.118.0-0.6.25.jar",
          "url": "wafv2-1.118.0-0.6.25.jar",
          "size": 695801,
          "sha512": "d91749c1aa57552e1004a1049d99f470db0862a75f73f0c398d76938a3d56603963830e3d967ec45b918a7add7cd5d903c92188c022a96bcb0118619cc16cc66",
          "sha256": "88982cdd52e1a83446a98cba3ce9d6c3afd39388e107e22156c9416e65052c55",
          "sha1": "dbab0d22f6a2edcefe51490d9d2d659f369be970",
          "md5": "1c5a58f5dfe5fb4a919f3e4b24261adb"
        }
      ]
    }
  ]
}
