{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cassandra",
    "version": "1.106.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "apa3jttzlbgsjbklj7vcehaque"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cassandra",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cassandra-1.106.1-0.6.21.jar",
          "url": "cassandra-1.106.1-0.6.21.jar",
          "size": 83768,
          "sha512": "82bd28435f7aac94e983d37fb42b3331938ab1e7ee16ef8331210d6050fa8e3272f06baaab075bab478f9fce3a43375d5657923a488a3525278fa71bcd6c2512",
          "sha256": "8cd1ff93f48d82cc4154bf8a584113a0ff8f75f77d4d17cd8ad172972976c6b9",
          "sha1": "ee800b708f38a8f046c0b2cf7d049b6c5b5cca1",
          "md5": "3e8e10310b23d8b325f8154be5433a3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cassandra",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cassandra-1.106.1-0.6.21.jar",
          "url": "cassandra-1.106.1-0.6.21.jar",
          "size": 83768,
          "sha512": "82bd28435f7aac94e983d37fb42b3331938ab1e7ee16ef8331210d6050fa8e3272f06baaab075bab478f9fce3a43375d5657923a488a3525278fa71bcd6c2512",
          "sha256": "8cd1ff93f48d82cc4154bf8a584113a0ff8f75f77d4d17cd8ad172972976c6b9",
          "sha1": "ee800b708f38a8f046c0b2cf7d049b6c5b5cca1",
          "md5": "3e8e10310b23d8b325f8154be5433a3b"
        }
      ]
    }
  ]
}
