{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "waf",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "waf",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "waf-1.117.0-0.6.25.jar",
          "url": "waf-1.117.0-0.6.25.jar",
          "size": 188937,
          "sha512": "8d6b05665d198403ca477424748f0901aeb9c9a575b5f2d54faacf26ff771cef4bcfe3f4afbbd3ea7c229f9bc09957efe514b4ccde4c2c152893860f38c222aa",
          "sha256": "fdb125307dbb16352f297c1126cc855678efe078fbca593a66a67302b85792c5",
          "sha1": "e9f03da517a3a9046ea729a6f5a3efb8a429e363",
          "md5": "386c43f2e0973c59be7473dc0db90ba1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "waf",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "waf-1.117.0-0.6.25.jar",
          "url": "waf-1.117.0-0.6.25.jar",
          "size": 188937,
          "sha512": "8d6b05665d198403ca477424748f0901aeb9c9a575b5f2d54faacf26ff771cef4bcfe3f4afbbd3ea7c229f9bc09957efe514b4ccde4c2c152893860f38c222aa",
          "sha256": "fdb125307dbb16352f297c1126cc855678efe078fbca593a66a67302b85792c5",
          "sha1": "e9f03da517a3a9046ea729a6f5a3efb8a429e363",
          "md5": "386c43f2e0973c59be7473dc0db90ba1"
        }
      ]
    }
  ]
}
