{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "mediaconnect",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "mediaconnect",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediaconnect-1.111.0-0.6.21.jar",
          "url": "mediaconnect-1.111.0-0.6.21.jar",
          "size": 130899,
          "sha512": "d38fa1be958b504770e601cd9611fa90a5132bb6fe24e52cb7077e8f91b650e70e2b0e4efa3dc02847ae8d0d15a39070d9bcea06d5f52617ba91b4983cc7c517",
          "sha256": "aec6c02765c4d3778bf548b3885d7ea1ef89ae67eadedafa4566c1d205a6e72a",
          "sha1": "55d31303381dc3eadca8e0cb15a53be7824cdbbd",
          "md5": "500bd49de67e55afaa65ea7a508ea2ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "mediaconnect",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediaconnect-1.111.0-0.6.21.jar",
          "url": "mediaconnect-1.111.0-0.6.21.jar",
          "size": 130899,
          "sha512": "d38fa1be958b504770e601cd9611fa90a5132bb6fe24e52cb7077e8f91b650e70e2b0e4efa3dc02847ae8d0d15a39070d9bcea06d5f52617ba91b4983cc7c517",
          "sha256": "aec6c02765c4d3778bf548b3885d7ea1ef89ae67eadedafa4566c1d205a6e72a",
          "sha1": "55d31303381dc3eadca8e0cb15a53be7824cdbbd",
          "md5": "500bd49de67e55afaa65ea7a508ea2ee"
        }
      ]
    }
  ]
}
