{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ce",
    "version": "1.64.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ce",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ce-1.64.0-0.6.21.jar",
          "url": "ce-1.64.0-0.6.21.jar",
          "size": 8898,
          "sha512": "0db08889311e089b66ba40cd89a6969acc3e69fd8277e34917e1edad1e43a869a39182afb67ec854b79397a3963e4e98498892365ccdb2014ff13f05866f832d",
          "sha256": "d3ba22036924a71ec1410dd0268b88eca985609c007f50cf2769ba658639099f",
          "sha1": "4ecf4de9f6ae998e3351232af0251934925cee32",
          "md5": "4ced582c8d0543da7d685f70857bb0df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ce",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ce-1.64.0-0.6.21.jar",
          "url": "ce-1.64.0-0.6.21.jar",
          "size": 8898,
          "sha512": "0db08889311e089b66ba40cd89a6969acc3e69fd8277e34917e1edad1e43a869a39182afb67ec854b79397a3963e4e98498892365ccdb2014ff13f05866f832d",
          "sha256": "d3ba22036924a71ec1410dd0268b88eca985609c007f50cf2769ba658639099f",
          "sha1": "4ecf4de9f6ae998e3351232af0251934925cee32",
          "md5": "4ced582c8d0543da7d685f70857bb0df"
        }
      ]
    }
  ]
}
