{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "devopsguru",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "devopsguru",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "devopsguru-1.106.0-0.6.21.jar",
          "url": "devopsguru-1.106.0-0.6.21.jar",
          "size": 56993,
          "sha512": "d9d84c9a71ee5abd570a5c8779eb10c928cf3fe64e15b30001c128f965b9d4bd609727fd52f17930ac1c2dee5307b5aca0ae32e24a3e429ce1b1b5ad8a3e2aa8",
          "sha256": "e77f8190af9138327d8803759d848089ad0c6c77a55e0c5e47f7eec9a3e2e0e5",
          "sha1": "2d41f12613c4e081d21b7c1df70538c34d862b3e",
          "md5": "9a66a8dbcc363b72ee361d9938caa103"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "devopsguru",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "devopsguru-1.106.0-0.6.21.jar",
          "url": "devopsguru-1.106.0-0.6.21.jar",
          "size": 56993,
          "sha512": "d9d84c9a71ee5abd570a5c8779eb10c928cf3fe64e15b30001c128f965b9d4bd609727fd52f17930ac1c2dee5307b5aca0ae32e24a3e429ce1b1b5ad8a3e2aa8",
          "sha256": "e77f8190af9138327d8803759d848089ad0c6c77a55e0c5e47f7eec9a3e2e0e5",
          "sha1": "2d41f12613c4e081d21b7c1df70538c34d862b3e",
          "md5": "9a66a8dbcc363b72ee361d9938caa103"
        }
      ]
    }
  ]
}
