{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "opsworks",
    "version": "1.64.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "opsworks",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "opsworks-1.64.0-0.6.22.jar",
          "url": "opsworks-1.64.0-0.6.22.jar",
          "size": 465538,
          "sha512": "6a64808b8205890bcb4ad9454228ba157431716c18f44abbd0ae7140bfbdc25a933f2742b14ef3dc34d5faede6f7049967a05f6e3d01c944127bf92920de81bd",
          "sha256": "da87fbde531bf5c2421f81743536e5bc3657a0b61ca66b65b03ad5ba1c8898d0",
          "sha1": "108b1fca0086b69f07b6ac40cb5324a255e4ef81",
          "md5": "e70463ae2cafb180516f3fa50dc5a464"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "opsworks",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "opsworks-1.64.0-0.6.22.jar",
          "url": "opsworks-1.64.0-0.6.22.jar",
          "size": 465538,
          "sha512": "6a64808b8205890bcb4ad9454228ba157431716c18f44abbd0ae7140bfbdc25a933f2742b14ef3dc34d5faede6f7049967a05f6e3d01c944127bf92920de81bd",
          "sha256": "da87fbde531bf5c2421f81743536e5bc3657a0b61ca66b65b03ad5ba1c8898d0",
          "sha1": "108b1fca0086b69f07b6ac40cb5324a255e4ef81",
          "md5": "e70463ae2cafb180516f3fa50dc5a464"
        }
      ]
    }
  ]
}
