{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "qldb",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "k23roxkwqjbs5i6arr4lg4r4xm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "qldb",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "qldb-1.110.1-0.6.21.jar",
          "url": "qldb-1.110.1-0.6.21.jar",
          "size": 43389,
          "sha512": "29d3d003fc704117877ff8bebec2924b01111d2c69d1a6783dd2464559dba31ed62ace0897b7303bdc548a5ef4d72bb939d9dcc2b6ca751feecb71ce3020da41",
          "sha256": "68d513f037be7401ea0c97fd711a6c215255a454064172f0aebeb66531925b37",
          "sha1": "6329053907331f92ab820813c482cc8b8dc426e0",
          "md5": "fb0376b6e6411efb74f533995a2d3b67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "qldb",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "qldb-1.110.1-0.6.21.jar",
          "url": "qldb-1.110.1-0.6.21.jar",
          "size": 43389,
          "sha512": "29d3d003fc704117877ff8bebec2924b01111d2c69d1a6783dd2464559dba31ed62ace0897b7303bdc548a5ef4d72bb939d9dcc2b6ca751feecb71ce3020da41",
          "sha256": "68d513f037be7401ea0c97fd711a6c215255a454064172f0aebeb66531925b37",
          "sha1": "6329053907331f92ab820813c482cc8b8dc426e0",
          "md5": "fb0376b6e6411efb74f533995a2d3b67"
        }
      ]
    }
  ]
}
