{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-customresources",
    "version": "1.31.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudformation",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "stepfunctions",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "stepfunctions-tasks",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-customresources-1.31.0-0.6.22.jar",
          "url": "cdk-customresources-1.31.0-0.6.22.jar",
          "size": 24924,
          "sha512": "8761cb5c0b68610e81c42014fc65c3828d268578e7319d5df27e18ed4f26dce1bd11c93a96086247ddabe19dc62fd40a368bed13ec3b6aaf3de4c15132864b6a",
          "sha256": "713f38b4ed49cfe0a4b18a280ef5e579e527b8806bb8d244e5e1242722290f9b",
          "sha1": "036b3d86ae14a9b17a2436bec454f401371d4d5f",
          "md5": "ae22372d32c8209aa70fa63282b05417"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudformation",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "stepfunctions",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "stepfunctions-tasks",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-customresources-1.31.0-0.6.22.jar",
          "url": "cdk-customresources-1.31.0-0.6.22.jar",
          "size": 24924,
          "sha512": "8761cb5c0b68610e81c42014fc65c3828d268578e7319d5df27e18ed4f26dce1bd11c93a96086247ddabe19dc62fd40a368bed13ec3b6aaf3de4c15132864b6a",
          "sha256": "713f38b4ed49cfe0a4b18a280ef5e579e527b8806bb8d244e5e1242722290f9b",
          "sha1": "036b3d86ae14a9b17a2436bec454f401371d4d5f",
          "md5": "ae22372d32c8209aa70fa63282b05417"
        }
      ]
    }
  ]
}
