{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ecs",
    "version": "1.34.1-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ecs",
          "version": {
            "requires": "1.34.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "applicationautoscaling",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling-hooktargets",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "certificatemanager",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudformation",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ecr",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ecr-assets",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancing",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53-targets",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "secretsmanager",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "servicediscovery",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ssm",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "ecs-1.34.1-0.6.23.jar",
          "url": "ecs-1.34.1-0.6.23.jar",
          "size": 846526,
          "sha512": "4699f9a3a93314ad24f8364a48e0893bbcaeb9776feeb4d23354e8beda5028fb30530cd2351402dc79e81b7548783f2bd9ac44a44ac6d7a4b1a02852aa452e47",
          "sha256": "d9be00dd57cfd6f983626f83f26bfd58034cd8b97b63fcc9a6062685d7e2bd8f",
          "sha1": "7db86d74a690777b4f1a3b060cf053e98a52d959",
          "md5": "108c7e54f091fbe5514dc94765aad465"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.34.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ecs",
          "version": {
            "requires": "1.34.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "applicationautoscaling",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling-hooktargets",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "certificatemanager",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudformation",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ecr",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ecr-assets",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancing",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "route53-targets",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "secretsmanager",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "servicediscovery",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ssm",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "ecs-1.34.1-0.6.23.jar",
          "url": "ecs-1.34.1-0.6.23.jar",
          "size": 846526,
          "sha512": "4699f9a3a93314ad24f8364a48e0893bbcaeb9776feeb4d23354e8beda5028fb30530cd2351402dc79e81b7548783f2bd9ac44a44ac6d7a4b1a02852aa452e47",
          "sha256": "d9be00dd57cfd6f983626f83f26bfd58034cd8b97b63fcc9a6062685d7e2bd8f",
          "sha1": "7db86d74a690777b4f1a3b060cf053e98a52d959",
          "md5": "108c7e54f091fbe5514dc94765aad465"
        }
      ]
    }
  ]
}
