{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "wafregional",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.112.0-0.6.21.jar",
          "url": "wafregional-1.112.0-0.6.21.jar",
          "size": 251031,
          "sha512": "942e7bee01651852d5b00ed4fc759598c056106dbef23f8081fd447e750998a6f1b039b42bab6cb856448b3104b3a6b22662fdc9092a8ad4d26d6c95ace4c652",
          "sha256": "97f055c6881cfbe188bd693950265a6e6f747af0912018c70106b9051688e3a8",
          "sha1": "738d0e3135954af02c77787e8d9bd895357f3e60",
          "md5": "f2beda7da6a6e013e47f8b4d0bb1529d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.112.0-0.6.21.jar",
          "url": "wafregional-1.112.0-0.6.21.jar",
          "size": 251031,
          "sha512": "942e7bee01651852d5b00ed4fc759598c056106dbef23f8081fd447e750998a6f1b039b42bab6cb856448b3104b3a6b22662fdc9092a8ad4d26d6c95ace4c652",
          "sha256": "97f055c6881cfbe188bd693950265a6e6f747af0912018c70106b9051688e3a8",
          "sha1": "738d0e3135954af02c77787e8d9bd895357f3e60",
          "md5": "f2beda7da6a6e013e47f8b4d0bb1529d"
        }
      ]
    }
  ]
}
