{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "emrcontainers",
    "version": "1.106.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "apa3jttzlbgsjbklj7vcehaque"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "emrcontainers",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emrcontainers-1.106.1-0.6.21.jar",
          "url": "emrcontainers-1.106.1-0.6.21.jar",
          "size": 38497,
          "sha512": "b8d30bbe936809a2998473f9f926af2f6c58980d5b87cb880735c4e0312a1d290836126a9179f57a029005b24b01da92aec3ee94cd9df9aee91ecb102cfee32",
          "sha256": "b2f398d1e3d3a51b285208e065642f08d2db2567bbaaf0c6e9225cb8122079a5",
          "sha1": "39996d0e7b208850058d914f098701d541e16c14",
          "md5": "7fa35c868ccc168cfd74f341a8c0b41d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "emrcontainers",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emrcontainers-1.106.1-0.6.21.jar",
          "url": "emrcontainers-1.106.1-0.6.21.jar",
          "size": 38497,
          "sha512": "b8d30bbe936809a2998473f9f926af2f6c58980d5b87cb880735c4e0312a1d290836126a9179f57a029005b24b01da92aec3ee94cd9df9aee91ecb102cfee32",
          "sha256": "b2f398d1e3d3a51b285208e065642f08d2db2567bbaaf0c6e9225cb8122079a5",
          "sha1": "39996d0e7b208850058d914f098701d541e16c14",
          "md5": "7fa35c868ccc168cfd74f341a8c0b41d"
        }
      ]
    }
  ]
}
