{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "appsync",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "appsync",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cognito",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dynamodb",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticsearch",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "rds",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "secretsmanager",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appsync-1.115.0-0.6.21.jar",
          "url": "appsync-1.115.0-0.6.21.jar",
          "size": 532768,
          "sha512": "55edf18ab06cb7f60222bb01a3abca3b8ead22e608194c1349eba7f8a65d96f0f06857cb7f24e5989961e6012a97f8074b39690f169814b9579bb7c171d5ad17",
          "sha256": "2dd9930ca875dfe97401d2caf999606d7a1eacfbc4449c2b2b9aa863aa8f5053",
          "sha1": "529cc33091db7a7c391d55f7d3b5eb90ba50bcaa",
          "md5": "649443744f3224f2767d1ef039fa1b6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "appsync",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cognito",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dynamodb",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticsearch",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "rds",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "secretsmanager",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appsync-1.115.0-0.6.21.jar",
          "url": "appsync-1.115.0-0.6.21.jar",
          "size": 532768,
          "sha512": "55edf18ab06cb7f60222bb01a3abca3b8ead22e608194c1349eba7f8a65d96f0f06857cb7f24e5989961e6012a97f8074b39690f169814b9579bb7c171d5ad17",
          "sha256": "2dd9930ca875dfe97401d2caf999606d7a1eacfbc4449c2b2b9aa863aa8f5053",
          "sha1": "529cc33091db7a7c391d55f7d3b5eb90ba50bcaa",
          "md5": "649443744f3224f2767d1ef039fa1b6a"
        }
      ]
    }
  ]
}
