{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "kinesisfirehose",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "kinesisfirehose",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesisfirehose-1.112.0-0.6.21.jar",
          "url": "kinesisfirehose-1.112.0-0.6.21.jar",
          "size": 471235,
          "sha512": "2f072e306bc8c5e609f97702feb0a38886fb2734450041523759a30df5b46602a50726b60f755b850642f2ea1f8f346859618531afbb918be264b808edb4e289",
          "sha256": "b5cd2a3518acb2ca584a4276f9cc3cc383ab4c17d6e35187e6a5b822f8a890d1",
          "sha1": "3f851028b91b64f899cd915c88f0dc06597a7ee8",
          "md5": "a5fe2692f16300aacd59aea6432ec8de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "kinesisfirehose",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesisfirehose-1.112.0-0.6.21.jar",
          "url": "kinesisfirehose-1.112.0-0.6.21.jar",
          "size": 471235,
          "sha512": "2f072e306bc8c5e609f97702feb0a38886fb2734450041523759a30df5b46602a50726b60f755b850642f2ea1f8f346859618531afbb918be264b808edb4e289",
          "sha256": "b5cd2a3518acb2ca584a4276f9cc3cc383ab4c17d6e35187e6a5b822f8a890d1",
          "sha1": "3f851028b91b64f899cd915c88f0dc06597a7ee8",
          "md5": "a5fe2692f16300aacd59aea6432ec8de"
        }
      ]
    }
  ]
}
