{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "datapipeline",
    "version": "1.31.0-unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "datapipeline",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "datapipeline-1.31.0-unspecified.jar",
          "url": "datapipeline-1.31.0-unspecified.jar",
          "size": 83432,
          "sha512": "e1ece1f9c0ba34419331e5ba1b8df3a3f541413344099e013686b422d114e24c1cd28a8067652a5867182f65608084a6814d9b84a8883e8637653b5725cf7e1d",
          "sha256": "f0644e58699df69989d653c1b58c27ce805a6f3155d200635ac55cf2fc0daca3",
          "sha1": "e842a279d1fbd59c289ee78642b8c55a1b173bca",
          "md5": "da23215a97628c43d69c3cd42b608748"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "datapipeline",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "datapipeline-1.31.0-unspecified.jar",
          "url": "datapipeline-1.31.0-unspecified.jar",
          "size": 83432,
          "sha512": "e1ece1f9c0ba34419331e5ba1b8df3a3f541413344099e013686b422d114e24c1cd28a8067652a5867182f65608084a6814d9b84a8883e8637653b5725cf7e1d",
          "sha256": "f0644e58699df69989d653c1b58c27ce805a6f3155d200635ac55cf2fc0daca3",
          "sha1": "e842a279d1fbd59c289ee78642b8c55a1b173bca",
          "md5": "da23215a97628c43d69c3cd42b608748"
        }
      ]
    }
  ]
}
