{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sam",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sam",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sam-1.106.0-0.6.21.jar",
          "url": "sam-1.106.0-0.6.21.jar",
          "size": 799692,
          "sha512": "25ec6a73990c61537ec4032f9f8b5b665251790601b8481da7e1cf53f21d494bfd9e9b770451f91a57ab9d1825baad2f06f210e2c6a67f7fa56c2d2f27ad256c",
          "sha256": "cc9906ff7a2b9d42dd4c194a6b4e42ec236feea49a109b7dfdcf73939694c62e",
          "sha1": "a4e79567fd85cb29b7bd7a9eef86b27617f60a4f",
          "md5": "f615b77fd89edcdbdbfaf62e932b5bd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sam",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sam-1.106.0-0.6.21.jar",
          "url": "sam-1.106.0-0.6.21.jar",
          "size": 799692,
          "sha512": "25ec6a73990c61537ec4032f9f8b5b665251790601b8481da7e1cf53f21d494bfd9e9b770451f91a57ab9d1825baad2f06f210e2c6a67f7fa56c2d2f27ad256c",
          "sha256": "cc9906ff7a2b9d42dd4c194a6b4e42ec236feea49a109b7dfdcf73939694c62e",
          "sha1": "a4e79567fd85cb29b7bd7a9eef86b27617f60a4f",
          "md5": "f615b77fd89edcdbdbfaf62e932b5bd8"
        }
      ]
    }
  ]
}
