{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "imagebuilder",
    "version": "1.101.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "d5vusioiqzbnxk6vuwjeusvgpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.101.0-0.6.21.jar",
          "url": "imagebuilder-1.101.0-0.6.21.jar",
          "size": 240705,
          "sha512": "d18ca7f9d39c7006b7c616a1561210c469e46ee8ff52c67fe045e64ce14dd2897465affb7bcbf0fbba3cf63776debcc67521d2bfbc4efb21e3f3df1df0c9cf61",
          "sha256": "3dea87d71c2c6e07f8d03c417dd3c154255a6ed35c9507122c9c3c7589513679",
          "sha1": "5cf72311148ed871247865b05cfb12ccb854f781",
          "md5": "63dbbd232e6475003ae880a904df914c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.101.0-0.6.21.jar",
          "url": "imagebuilder-1.101.0-0.6.21.jar",
          "size": 240705,
          "sha512": "d18ca7f9d39c7006b7c616a1561210c469e46ee8ff52c67fe045e64ce14dd2897465affb7bcbf0fbba3cf63776debcc67521d2bfbc4efb21e3f3df1df0c9cf61",
          "sha256": "3dea87d71c2c6e07f8d03c417dd3c154255a6ed35c9507122c9c3c7589513679",
          "sha1": "5cf72311148ed871247865b05cfb12ccb854f781",
          "md5": "63dbbd232e6475003ae880a904df914c"
        }
      ]
    }
  ]
}
