{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "docdb",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "docdb",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "efs",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "secretsmanager",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "docdb-1.114.0-0.6.21.jar",
          "url": "docdb-1.114.0-0.6.21.jar",
          "size": 113237,
          "sha512": "99bee30ea2d077219dc338a753cc6b9c2b772e6385490f47b36a18ec259eb48498c1fb18ee5152b53312dc73b94500a9c7c6b7a68e4b2588e05820179c773284",
          "sha256": "84c8f4035d0b76e436b326e22ab58157dc24c13e312ad70bb4f67fad8cbbb1d",
          "sha1": "9fdcd424b5c9f874a2bdf90f68644d74af7ef9a2",
          "md5": "8774801e4116e9ef3308064092e3d9d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "docdb",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "efs",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "secretsmanager",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "docdb-1.114.0-0.6.21.jar",
          "url": "docdb-1.114.0-0.6.21.jar",
          "size": 113237,
          "sha512": "99bee30ea2d077219dc338a753cc6b9c2b772e6385490f47b36a18ec259eb48498c1fb18ee5152b53312dc73b94500a9c7c6b7a68e4b2588e05820179c773284",
          "sha256": "84c8f4035d0b76e436b326e22ab58157dc24c13e312ad70bb4f67fad8cbbb1d",
          "sha1": "9fdcd424b5c9f874a2bdf90f68644d74af7ef9a2",
          "md5": "8774801e4116e9ef3308064092e3d9d8"
        }
      ]
    }
  ]
}
