{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ivs",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ivs",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ivs-1.106.0-0.6.21.jar",
          "url": "ivs-1.106.0-0.6.21.jar",
          "size": 80931,
          "sha512": "54b946b8892094222921325a4a136fb407f78232a5c1a802703e2ba4e7bfbe4b283d40515de4be882c24c5375bfd74c02117c868199aad0798dcf5c9d3ec54c4",
          "sha256": "2d6fb9d195133022faf1de441679cbf154a1576d7f5c93820a62e133318b7e54",
          "sha1": "36f8f34cfc00b237a501e468ce2ed5a70595ec49",
          "md5": "1326ee1f2e46407922f9cebb6deb37d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ivs",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ivs-1.106.0-0.6.21.jar",
          "url": "ivs-1.106.0-0.6.21.jar",
          "size": 80931,
          "sha512": "54b946b8892094222921325a4a136fb407f78232a5c1a802703e2ba4e7bfbe4b283d40515de4be882c24c5375bfd74c02117c868199aad0798dcf5c9d3ec54c4",
          "sha256": "2d6fb9d195133022faf1de441679cbf154a1576d7f5c93820a62e133318b7e54",
          "sha1": "36f8f34cfc00b237a501e468ce2ed5a70595ec49",
          "md5": "1326ee1f2e46407922f9cebb6deb37d6"
        }
      ]
    }
  ]
}
