{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sagemaker",
    "version": "1.59.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sagemaker",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "sagemaker-1.59.0-0.6.23.jar",
          "url": "sagemaker-1.59.0-0.6.23.jar",
          "size": 227708,
          "sha512": "a48e8a7dad0d65d24ed3b28e92999b86aa1bc268479c95ffed2a7fc3b04584d1fdfdba7ee234e2ea02b2af3fc9192ae23dcade3323bf0dce293a6ec3d97f7120",
          "sha256": "be0cccb7decd5ebdb494b4830db22144755230083f51b196143985a6523e4e33",
          "sha1": "d672505bb0d89c9ef519dbaf7c2563110fae3314",
          "md5": "1f28b55adbb75492f4bf7e3ad6cb7be1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sagemaker",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "sagemaker-1.59.0-0.6.23.jar",
          "url": "sagemaker-1.59.0-0.6.23.jar",
          "size": 227708,
          "sha512": "a48e8a7dad0d65d24ed3b28e92999b86aa1bc268479c95ffed2a7fc3b04584d1fdfdba7ee234e2ea02b2af3fc9192ae23dcade3323bf0dce293a6ec3d97f7120",
          "sha256": "be0cccb7decd5ebdb494b4830db22144755230083f51b196143985a6523e4e33",
          "sha1": "d672505bb0d89c9ef519dbaf7c2563110fae3314",
          "md5": "1f28b55adbb75492f4bf7e3ad6cb7be1"
        }
      ]
    }
  ]
}
