{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iot1click",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iot1click",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iot1click-1.107.0-0.6.21.jar",
          "url": "iot1click-1.107.0-0.6.21.jar",
          "size": 52568,
          "sha512": "3ae226b362fb865cd3c2c6b234e276c2745f373a72a06b14b501ad8cff41307ffc29862e1ca2854037d0211618b14fb49de438c37153bb553203feb3e4b5e452",
          "sha256": "3c06c4d92479d7db4374108b1c23c792a03a6d6acbd642fc323c53293ddd66f7",
          "sha1": "c6b0b0e29c13f6f62162778252730dcdc4329760",
          "md5": "716443a3212da5d0f6590b692d87cdcb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iot1click",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iot1click-1.107.0-0.6.21.jar",
          "url": "iot1click-1.107.0-0.6.21.jar",
          "size": 52568,
          "sha512": "3ae226b362fb865cd3c2c6b234e276c2745f373a72a06b14b501ad8cff41307ffc29862e1ca2854037d0211618b14fb49de438c37153bb553203feb3e4b5e452",
          "sha256": "3c06c4d92479d7db4374108b1c23c792a03a6d6acbd642fc323c53293ddd66f7",
          "sha1": "c6b0b0e29c13f6f62162778252730dcdc4329760",
          "md5": "716443a3212da5d0f6590b692d87cdcb"
        }
      ]
    }
  ]
}
