{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "apprunner",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "apprunner",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apprunner-1.109.0-0.6.21.jar",
          "url": "apprunner-1.109.0-0.6.21.jar",
          "size": 134995,
          "sha512": "1f42b90fe637748eeb0c61ebe4d2bb03dac831daf1601b1cfc07ff6c820987c23d43fdeb99c9fa7d9545fbf51cd98bd11c080b58ddc3ea7d70688e81425a18f7",
          "sha256": "dbc9cef9cbdbbd0747f1838730bc23f83232f773605f786f081c806361ebe1d0",
          "sha1": "36bbf814313cd7bbdb6f1dc8fc7a825a855aa003",
          "md5": "73ce292938df42a2f88aa9029ef8dbd4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "apprunner",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apprunner-1.109.0-0.6.21.jar",
          "url": "apprunner-1.109.0-0.6.21.jar",
          "size": 134995,
          "sha512": "1f42b90fe637748eeb0c61ebe4d2bb03dac831daf1601b1cfc07ff6c820987c23d43fdeb99c9fa7d9545fbf51cd98bd11c080b58ddc3ea7d70688e81425a18f7",
          "sha256": "dbc9cef9cbdbbd0747f1838730bc23f83232f773605f786f081c806361ebe1d0",
          "sha1": "36bbf814313cd7bbdb6f1dc8fc7a825a855aa003",
          "md5": "73ce292938df42a2f88aa9029ef8dbd4"
        }
      ]
    }
  ]
}
