{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-region-info",
    "version": "1.59.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.59.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-region-info-1.59.0-0.6.23.jar",
          "url": "cdk-region-info-1.59.0-0.6.23.jar",
          "size": 432,
          "sha512": "fe61305f28cc0f1f99843d2ee38d8d4f15285e6d356681be2fc3bbfc58efb121ce8d90cf92fb0d23965bdf0f39be565e2be17d2dc1af300322a641fe61c55eba",
          "sha256": "5e15d8100e56b7cfa939f9f6be7fdef6c0dc7e7a3428ed0444b6eef837fdf24d",
          "sha1": "ade338af05bf305c155a122a30cd9511705b3575",
          "md5": "37d1e61f0d476162a34b8554f6ce81f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.59.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-region-info-1.59.0-0.6.23.jar",
          "url": "cdk-region-info-1.59.0-0.6.23.jar",
          "size": 432,
          "sha512": "fe61305f28cc0f1f99843d2ee38d8d4f15285e6d356681be2fc3bbfc58efb121ce8d90cf92fb0d23965bdf0f39be565e2be17d2dc1af300322a641fe61c55eba",
          "sha256": "5e15d8100e56b7cfa939f9f6be7fdef6c0dc7e7a3428ed0444b6eef837fdf24d",
          "sha1": "ade338af05bf305c155a122a30cd9511705b3575",
          "md5": "37d1e61f0d476162a34b8554f6ce81f6"
        }
      ]
    }
  ]
}
