{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "fis",
    "version": "1.101.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "d5vusioiqzbnxk6vuwjeusvgpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "fis",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fis-1.101.0-0.6.21.jar",
          "url": "fis-1.101.0-0.6.21.jar",
          "size": 119505,
          "sha512": "63502d199f90ed635d7a76119e32e61680f2d1314273fc2315495fa197f1c72953d5bb49a5b6e381f9692b0e1056c9d95858cc165b3e57dfe7031414f10029df",
          "sha256": "ab640e59eb4b9d8fcd4a4bde09ce6f41edc06e92e99a11be2bf8895423ce6d7f",
          "sha1": "150a6a837071d63594f83a3ad1bba275eb2d16d9",
          "md5": "17d910762cdc30b0f8f8190e2940dff7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "fis",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fis-1.101.0-0.6.21.jar",
          "url": "fis-1.101.0-0.6.21.jar",
          "size": 119505,
          "sha512": "63502d199f90ed635d7a76119e32e61680f2d1314273fc2315495fa197f1c72953d5bb49a5b6e381f9692b0e1056c9d95858cc165b3e57dfe7031414f10029df",
          "sha256": "ab640e59eb4b9d8fcd4a4bde09ce6f41edc06e92e99a11be2bf8895423ce6d7f",
          "sha1": "150a6a837071d63594f83a3ad1bba275eb2d16d9",
          "md5": "17d910762cdc30b0f8f8190e2940dff7"
        }
      ]
    }
  ]
}
