{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "dlm",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "pksuzuox3ne6pgnvsva7g32w2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "dlm",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dlm-1.110.1-0.6.21.jar",
          "url": "dlm-1.110.1-0.6.21.jar",
          "size": 173789,
          "sha512": "a830c8f72684d4bbe419e33f18afecaa9a47fc3b185dd7139bf62b6536a03144dcf954800b536723510710b40c7feff76a024cc0e1627e3ffaed450e6acd15f2",
          "sha256": "ecc371b5f69e1aaf79113c2b231a70a81a5cd541303e9241da88e22596033282",
          "sha1": "23b7a06779be2066a29b159408af5c8dba1f855",
          "md5": "8ca25bb6cf461bfc67b6bbb0b7324596"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "dlm",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dlm-1.110.1-0.6.21.jar",
          "url": "dlm-1.110.1-0.6.21.jar",
          "size": 173789,
          "sha512": "a830c8f72684d4bbe419e33f18afecaa9a47fc3b185dd7139bf62b6536a03144dcf954800b536723510710b40c7feff76a024cc0e1627e3ffaed450e6acd15f2",
          "sha256": "ecc371b5f69e1aaf79113c2b231a70a81a5cd541303e9241da88e22596033282",
          "sha1": "23b7a06779be2066a29b159408af5c8dba1f855",
          "md5": "8ca25bb6cf461bfc67b6bbb0b7324596"
        }
      ]
    }
  ]
}
