{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticloadbalancing",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticloadbalancing",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticloadbalancing-1.114.0-0.6.21.jar",
          "url": "elasticloadbalancing-1.114.0-0.6.21.jar",
          "size": 153912,
          "sha512": "c9a350c4b3d2ff8d432cbc3c36aa24787048256f3785d18fea63d501199f09de08f3206bed68e8e6e71b673d380907d74e3cd65fb7fdd5323bb2f91da6cbc89",
          "sha256": "d96bab359de1379b302b9c277d2ee1417a4b575c2bea74a05201e8fcf0a4a5dd",
          "sha1": "932cfc9b7c5d85bdfff1a0a59069567ff678dd93",
          "md5": "13c6078869813de933d6704db82a6d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticloadbalancing",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticloadbalancing-1.114.0-0.6.21.jar",
          "url": "elasticloadbalancing-1.114.0-0.6.21.jar",
          "size": 153912,
          "sha512": "c9a350c4b3d2ff8d432cbc3c36aa24787048256f3785d18fea63d501199f09de08f3206bed68e8e6e71b673d380907d74e3cd65fb7fdd5323bb2f91da6cbc89",
          "sha256": "d96bab359de1379b302b9c277d2ee1417a4b575c2bea74a05201e8fcf0a4a5dd",
          "sha1": "932cfc9b7c5d85bdfff1a0a59069567ff678dd93",
          "md5": "13c6078869813de933d6704db82a6d6"
        }
      ]
    }
  ]
}
