{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "devopsguru",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "devopsguru",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "devopsguru-1.102.0-0.6.21.jar",
          "url": "devopsguru-1.102.0-0.6.21.jar",
          "size": 57009,
          "sha512": "cfca16bb9dfa3148f3f5ffd72422aa3272181e7006310b14ec12df2d1489a2e680dfeb7676541689aaec6a5ab22949ac4bd55962f4b4594ed908d1345d0e1831",
          "sha256": "1cd5b68c7d4852865561f0be81252daaf5b3a550568b5178803aeb30e54c47d6",
          "sha1": "7800ad65c9add646b7ac75cd0a0df3f161232b6",
          "md5": "2ccc19e71e0d7e86ec2680cf76be5880"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "devopsguru",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "devopsguru-1.102.0-0.6.21.jar",
          "url": "devopsguru-1.102.0-0.6.21.jar",
          "size": 57009,
          "sha512": "cfca16bb9dfa3148f3f5ffd72422aa3272181e7006310b14ec12df2d1489a2e680dfeb7676541689aaec6a5ab22949ac4bd55962f4b4594ed908d1345d0e1831",
          "sha256": "1cd5b68c7d4852865561f0be81252daaf5b3a550568b5178803aeb30e54c47d6",
          "sha1": "7800ad65c9add646b7ac75cd0a0df3f161232b6",
          "md5": "2ccc19e71e0d7e86ec2680cf76be5880"
        }
      ]
    }
  ]
}
