{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-cx-api",
    "version": "1.31.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.31.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cx-api-1.31.0-0.6.22.jar",
          "url": "cdk-cx-api-1.31.0-0.6.22.jar",
          "size": 71849,
          "sha512": "a01341dac4e433d6879b931ad6c644b8f7ee618bbae0ff87bddb93a14f7c5d210838903bc4b5f7fbe1280f7f5986b974c7e9da02317e7dfa9cf0e424112f0e7a",
          "sha256": "7c7e88d39cee3761e6d433c88f5a7b36329d9a7ea5f920f907db46a044973319",
          "sha1": "5d5eec8b1494092fd6a5dac9b180ec8c370cf91f",
          "md5": "d7daaa4d9279dcd72533259a2006657a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.31.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cx-api-1.31.0-0.6.22.jar",
          "url": "cdk-cx-api-1.31.0-0.6.22.jar",
          "size": 71849,
          "sha512": "a01341dac4e433d6879b931ad6c644b8f7ee618bbae0ff87bddb93a14f7c5d210838903bc4b5f7fbe1280f7f5986b974c7e9da02317e7dfa9cf0e424112f0e7a",
          "sha256": "7c7e88d39cee3761e6d433c88f5a7b36329d9a7ea5f920f907db46a044973319",
          "sha1": "5d5eec8b1494092fd6a5dac9b180ec8c370cf91f",
          "md5": "d7daaa4d9279dcd72533259a2006657a"
        }
      ]
    }
  ]
}
