{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "customerprofiles",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "customerprofiles",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "customerprofiles-1.113.0-0.6.21.jar",
          "url": "customerprofiles-1.113.0-0.6.21.jar",
          "size": 214522,
          "sha512": "3a4c9089cff91c7c9820539271c78d0e7bcd3c44e2b7001c75056963ba61a4dea7cbe0511c583dc5c6d73091b2d6a1c796bc82644aa32a8d17fccd2b5ccff9cd",
          "sha256": "3cf7cd8b8e393e83bbedbeab602795445d1636c2a0cff047070b5978efc74c0e",
          "sha1": "16deb4f04b1bc908f51caae05371d28ec938f8a0",
          "md5": "af30efbe3420880fae69fa21c409e9e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "customerprofiles",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "customerprofiles-1.113.0-0.6.21.jar",
          "url": "customerprofiles-1.113.0-0.6.21.jar",
          "size": 214522,
          "sha512": "3a4c9089cff91c7c9820539271c78d0e7bcd3c44e2b7001c75056963ba61a4dea7cbe0511c583dc5c6d73091b2d6a1c796bc82644aa32a8d17fccd2b5ccff9cd",
          "sha256": "3cf7cd8b8e393e83bbedbeab602795445d1636c2a0cff047070b5978efc74c0e",
          "sha1": "16deb4f04b1bc908f51caae05371d28ec938f8a0",
          "md5": "af30efbe3420880fae69fa21c409e9e0"
        }
      ]
    }
  ]
}
