{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "s3-assets",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "s3-assets",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-assets",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "s3-assets-1.105.0-0.6.21.jar",
          "url": "s3-assets-1.105.0-0.6.21.jar",
          "size": 15950,
          "sha512": "cfba7714d1fab6294b6b47df70ae7cd8e21ae234501ae48eb875f4e77e896e90ffa6f9c11151be89a444202217b608d11b37476c3117c43f071e37b1d81214a0",
          "sha256": "af2ff14f598874568e2d8d57b4ceb4017f8d84eb85317baf551d44c2829ce0e4",
          "sha1": "81addc40474f64a57c704135e330ff126eeed10",
          "md5": "7508b861ccbeb2b5b9755376a87d13fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "s3-assets",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-assets",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "s3-assets-1.105.0-0.6.21.jar",
          "url": "s3-assets-1.105.0-0.6.21.jar",
          "size": 15950,
          "sha512": "cfba7714d1fab6294b6b47df70ae7cd8e21ae234501ae48eb875f4e77e896e90ffa6f9c11151be89a444202217b608d11b37476c3117c43f071e37b1d81214a0",
          "sha256": "af2ff14f598874568e2d8d57b4ceb4017f8d84eb85317baf551d44c2829ce0e4",
          "sha1": "81addc40474f64a57c704135e330ff126eeed10",
          "md5": "7508b861ccbeb2b5b9755376a87d13fd"
        }
      ]
    }
  ]
}
