{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "mediapackage",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "mediapackage",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediapackage-1.104.0-0.6.21.jar",
          "url": "mediapackage-1.104.0-0.6.21.jar",
          "size": 405124,
          "sha512": "7ea7fcc0e5f27501d24d9c0fdc1c534dff13e9e2b5f582c458dbdfe0434a8b8607dfcc5494f41142075f001ea013a6103f178093a716aabc575585ea3928031c",
          "sha256": "eb476487d0dc71d7ab190ba8d7fb71b88f374f8f9d95df79457b35af357fb368",
          "sha1": "80a4c57010c593b98793f9570ec7fecc6341f73f",
          "md5": "92c2e74b681e97587582709d3922f9be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "mediapackage",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediapackage-1.104.0-0.6.21.jar",
          "url": "mediapackage-1.104.0-0.6.21.jar",
          "size": 405124,
          "sha512": "7ea7fcc0e5f27501d24d9c0fdc1c534dff13e9e2b5f582c458dbdfe0434a8b8607dfcc5494f41142075f001ea013a6103f178093a716aabc575585ea3928031c",
          "sha256": "eb476487d0dc71d7ab190ba8d7fb71b88f374f8f9d95df79457b35af357fb368",
          "sha1": "80a4c57010c593b98793f9570ec7fecc6341f73f",
          "md5": "92c2e74b681e97587582709d3922f9be"
        }
      ]
    }
  ]
}
