{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticbeanstalk",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticbeanstalk",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticbeanstalk-1.109.0-0.6.21.jar",
          "url": "elasticbeanstalk-1.109.0-0.6.21.jar",
          "size": 155128,
          "sha512": "b4f93e3dcda5d747f62ac4f4456fb94b1108e0b3c86d8ff1b20f974dad6ef72ba37d1e45864e2990ab72cd3d954a38a06edd07ae104514538de6c6b458b57322",
          "sha256": "39a9180169e940d19b6d4be976cd903870412db530845e88ef0b721833c518d9",
          "sha1": "798e5c0ea5241c00f387bdbe3adc422c3d7bef25",
          "md5": "36b9f4f43aac920110562979353227e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticbeanstalk",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticbeanstalk-1.109.0-0.6.21.jar",
          "url": "elasticbeanstalk-1.109.0-0.6.21.jar",
          "size": 155128,
          "sha512": "b4f93e3dcda5d747f62ac4f4456fb94b1108e0b3c86d8ff1b20f974dad6ef72ba37d1e45864e2990ab72cd3d954a38a06edd07ae104514538de6c6b458b57322",
          "sha256": "39a9180169e940d19b6d4be976cd903870412db530845e88ef0b721833c518d9",
          "sha1": "798e5c0ea5241c00f387bdbe3adc422c3d7bef25",
          "md5": "36b9f4f43aac920110562979353227e5"
        }
      ]
    }
  ]
}
