{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-pipelines",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-pipelines",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codebuild",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codepipeline",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codepipeline-actions",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-pipelines-1.99.0-0.6.21.jar",
          "url": "cdk-pipelines-1.99.0-0.6.21.jar",
          "size": 108274,
          "sha512": "21d8e5e88cef88583839cd31af3b4c3f5ff260da510fdc4bed3fbd72021ac31899c966d0814fbf06c8c1460d4746693335d42e661333f1328ec16749edcf47f4",
          "sha256": "82e9f484f72093fd94e72cb57759c38176f059d6a5f82e83622901e51b7dbc9c",
          "sha1": "e7ebfb57555d7a2a33f60834caba1a1991e3379",
          "md5": "32c753a8bd78a5b0556f60a3bda631cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-pipelines",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codebuild",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codepipeline",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codepipeline-actions",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-pipelines-1.99.0-0.6.21.jar",
          "url": "cdk-pipelines-1.99.0-0.6.21.jar",
          "size": 108274,
          "sha512": "21d8e5e88cef88583839cd31af3b4c3f5ff260da510fdc4bed3fbd72021ac31899c966d0814fbf06c8c1460d4746693335d42e661333f1328ec16749edcf47f4",
          "sha256": "82e9f484f72093fd94e72cb57759c38176f059d6a5f82e83622901e51b7dbc9c",
          "sha1": "e7ebfb57555d7a2a33f60834caba1a1991e3379",
          "md5": "32c753a8bd78a5b0556f60a3bda631cf"
        }
      ]
    }
  ]
}
