{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "dynamodb",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "dynamodb",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "applicationautoscaling",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kinesis",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamodb-1.115.0-0.6.21.jar",
          "url": "dynamodb-1.115.0-0.6.21.jar",
          "size": 488945,
          "sha512": "c82272df44c734d101be050033206c3ef493a230ff3d1e7292c0fa124227cb518fceaf243ce05405f6c5a51f95b87b31ddb7b77bf43f648f417972f423324e7d",
          "sha256": "a03bc15b7fd87ab729828df7c234c21a3078702eb5e41d79b0777fa305d1568b",
          "sha1": "b72445312df122e2de86beda13ad45bbced25e8a",
          "md5": "bf3aec6f5f8e74b88ea604be53e19df4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "dynamodb",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "applicationautoscaling",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kinesis",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamodb-1.115.0-0.6.21.jar",
          "url": "dynamodb-1.115.0-0.6.21.jar",
          "size": 488945,
          "sha512": "c82272df44c734d101be050033206c3ef493a230ff3d1e7292c0fa124227cb518fceaf243ce05405f6c5a51f95b87b31ddb7b77bf43f648f417972f423324e7d",
          "sha256": "a03bc15b7fd87ab729828df7c234c21a3078702eb5e41d79b0777fa305d1568b",
          "sha1": "b72445312df122e2de86beda13ad45bbced25e8a",
          "md5": "bf3aec6f5f8e74b88ea604be53e19df4"
        }
      ]
    }
  ]
}
