{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "greengrass",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "greengrass",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrass-1.108.1-0.6.21.jar",
          "url": "greengrass-1.108.1-0.6.21.jar",
          "size": 685660,
          "sha512": "daa7b10df3d18ba775cdb1d76ea04ff815adc6a9c71f288af5daef5f876af005d87dfc9817b5230c13d106a605d8884a78a416ab2965b82a775b94a2d3c6773a",
          "sha256": "b85e0f9cd5b48e40c02bb4965174fd93b1232b6a854bc535f6b42a091037dd31",
          "sha1": "2fc8e029a19356405ed4338bc93c87062da3d169",
          "md5": "3a6dcccae67f0cfcdd034e9c70a21100"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "greengrass",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrass-1.108.1-0.6.21.jar",
          "url": "greengrass-1.108.1-0.6.21.jar",
          "size": 685660,
          "sha512": "daa7b10df3d18ba775cdb1d76ea04ff815adc6a9c71f288af5daef5f876af005d87dfc9817b5230c13d106a605d8884a78a416ab2965b82a775b94a2d3c6773a",
          "sha256": "b85e0f9cd5b48e40c02bb4965174fd93b1232b6a854bc535f6b42a091037dd31",
          "sha1": "2fc8e029a19356405ed4338bc93c87062da3d169",
          "md5": "3a6dcccae67f0cfcdd034e9c70a21100"
        }
      ]
    }
  ]
}
