{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "appintegrations",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "appintegrations",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appintegrations-1.108.1-0.6.21.jar",
          "url": "appintegrations-1.108.1-0.6.21.jar",
          "size": 35107,
          "sha512": "f48c9a1a78b8e4fcb08f9cbe0c99292127d50337de61048d27d398a1a6db8aa375b7852de3d2288053eb14dfeba47ce462bd112459686a415f8a16d6391fa945",
          "sha256": "412aabbc1d5331d8b5079080ee9d05e2d857c37263d3fab51b372df5fd4140f0",
          "sha1": "2bbea8d34db48613a4d68def91e81bfd0fdaf1f8",
          "md5": "4f20d52f9ef4b2c5e6580e23ab2047e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "appintegrations",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appintegrations-1.108.1-0.6.21.jar",
          "url": "appintegrations-1.108.1-0.6.21.jar",
          "size": 35107,
          "sha512": "f48c9a1a78b8e4fcb08f9cbe0c99292127d50337de61048d27d398a1a6db8aa375b7852de3d2288053eb14dfeba47ce462bd112459686a415f8a16d6391fa945",
          "sha256": "412aabbc1d5331d8b5079080ee9d05e2d857c37263d3fab51b372df5fd4140f0",
          "sha1": "2bbea8d34db48613a4d68def91e81bfd0fdaf1f8",
          "md5": "4f20d52f9ef4b2c5e6580e23ab2047e5"
        }
      ]
    }
  ]
}
