{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lambda-python",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-python",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-python-1.111.0-0.6.21.jar",
          "url": "lambda-python-1.111.0-0.6.21.jar",
          "size": 28080,
          "sha512": "dfe0fddeb58204fde5069116413b0cb5df74d5c6ceb0fcc549450921237289b4ff0750bd1232e29e2720cd1cf65b10c555171b2eff3aaf56dfdf8aad451ac8fd",
          "sha256": "696e8e695f6dac208da4cbed4923836f4bd3baf4f3f7f0a8043fe14acd40cd02",
          "sha1": "49a8b0a6c2db59790ab65add3793459f8c65c40c",
          "md5": "3ff9ec6a22aeab69c2b010f84e8afe5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-python",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-python-1.111.0-0.6.21.jar",
          "url": "lambda-python-1.111.0-0.6.21.jar",
          "size": 28080,
          "sha512": "dfe0fddeb58204fde5069116413b0cb5df74d5c6ceb0fcc549450921237289b4ff0750bd1232e29e2720cd1cf65b10c555171b2eff3aaf56dfdf8aad451ac8fd",
          "sha256": "696e8e695f6dac208da4cbed4923836f4bd3baf4f3f7f0a8043fe14acd40cd02",
          "sha1": "49a8b0a6c2db59790ab65add3793459f8c65c40c",
          "md5": "3ff9ec6a22aeab69c2b010f84e8afe5e"
        }
      ]
    }
  ]
}
