{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-assets",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-1.106.0-0.6.21.jar",
          "url": "cdk-assets-1.106.0-0.6.21.jar",
          "size": 16450,
          "sha512": "b851e3a283347a3cbb1642d26c9b11b07fded59670370c57a79fef22b8c0984ba72741c438dbd73721799ed63e7c09fed3c5aec3f7c978d95b9346b8e1d63873",
          "sha256": "95e26a6b54f61d75bf2bc14ea5144d14e096d07cc6e08dcb14ebb2fd761a2b34",
          "sha1": "878f3d1a147a7b53c164a9e3e7156a686f6b4cd8",
          "md5": "45fcf671a5cb34cce0910fb596820ada"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-1.106.0-0.6.21.jar",
          "url": "cdk-assets-1.106.0-0.6.21.jar",
          "size": 16450,
          "sha512": "b851e3a283347a3cbb1642d26c9b11b07fded59670370c57a79fef22b8c0984ba72741c438dbd73721799ed63e7c09fed3c5aec3f7c978d95b9346b8e1d63873",
          "sha256": "95e26a6b54f61d75bf2bc14ea5144d14e096d07cc6e08dcb14ebb2fd761a2b34",
          "sha1": "878f3d1a147a7b53c164a9e3e7156a686f6b4cd8",
          "md5": "45fcf671a5cb34cce0910fb596820ada"
        }
      ]
    }
  ]
}
