{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cassandra",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cassandra",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cassandra-1.104.0-0.6.21.jar",
          "url": "cassandra-1.104.0-0.6.21.jar",
          "size": 83787,
          "sha512": "b4ed86afc39b1c4a7ccac28155cec6005d68c05fb1ba6bfbef2765828bee445be885cf2b04620e5342cbd0232846dcc94098e3d05dae1888e5f474c12572cedf",
          "sha256": "6ace5b7bdc90eeae5445131880661d05b410612ee0f79c5171495e485e176f76",
          "sha1": "c7506ebbbdef70c12d660c1b62815f47bb78116",
          "md5": "d83e677b71a46d3d4d587d754bb51e02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cassandra",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cassandra-1.104.0-0.6.21.jar",
          "url": "cassandra-1.104.0-0.6.21.jar",
          "size": 83787,
          "sha512": "b4ed86afc39b1c4a7ccac28155cec6005d68c05fb1ba6bfbef2765828bee445be885cf2b04620e5342cbd0232846dcc94098e3d05dae1888e5f474c12572cedf",
          "sha256": "6ace5b7bdc90eeae5445131880661d05b410612ee0f79c5171495e485e176f76",
          "sha1": "c7506ebbbdef70c12d660c1b62815f47bb78116",
          "md5": "d83e677b71a46d3d4d587d754bb51e02"
        }
      ]
    }
  ]
}
