{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cloudwatch",
    "version": "1.34.1-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cloudwatch",
          "version": {
            "requires": "1.34.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "cloudwatch-1.34.1-0.6.23.jar",
          "url": "cloudwatch-1.34.1-0.6.23.jar",
          "size": 279323,
          "sha512": "1dd4aba007090930865bbaedd7ebc85d592f25ee502734f8eb9fe04beb5623e889fe182a3543dcfd51d4b8710ad8978bbbd003a6ddc3dff7d9bf07abab48b9ad",
          "sha256": "bee3f3a54f17034c537fd41f31a0e4fa1f1ce0e42b6b1618b5c86d52027c0535",
          "sha1": "142e17e49cca1d0f969b7c41f59fd5b0603a04e9",
          "md5": "bb4fc35819a07a6df245dea0e41f7233"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.34.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cloudwatch",
          "version": {
            "requires": "1.34.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "cloudwatch-1.34.1-0.6.23.jar",
          "url": "cloudwatch-1.34.1-0.6.23.jar",
          "size": 279323,
          "sha512": "1dd4aba007090930865bbaedd7ebc85d592f25ee502734f8eb9fe04beb5623e889fe182a3543dcfd51d4b8710ad8978bbbd003a6ddc3dff7d9bf07abab48b9ad",
          "sha256": "bee3f3a54f17034c537fd41f31a0e4fa1f1ce0e42b6b1618b5c86d52027c0535",
          "sha1": "142e17e49cca1d0f969b7c41f59fd5b0603a04e9",
          "md5": "bb4fc35819a07a6df245dea0e41f7233"
        }
      ]
    }
  ]
}
