{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "greengrassv2",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "greengrassv2",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrassv2-1.105.0-0.6.21.jar",
          "url": "greengrassv2-1.105.0-0.6.21.jar",
          "size": 119305,
          "sha512": "eeb108158fe48aed76cd79830bf7c0aef53149e91b9ef60deda226d41700c131df2954a38be7874713c121ecb24cab530b62bee8b443ccb453b4c05333e77fb2",
          "sha256": "b739e6499b8aab463ce3a4e68e98dc51328382946447369be2447781c6ab207",
          "sha1": "2dbaaa51d9261ec093570798f4f2f30711203863",
          "md5": "ea7b5474270b6fee639c462c765e513a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "greengrassv2",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrassv2-1.105.0-0.6.21.jar",
          "url": "greengrassv2-1.105.0-0.6.21.jar",
          "size": 119305,
          "sha512": "eeb108158fe48aed76cd79830bf7c0aef53149e91b9ef60deda226d41700c131df2954a38be7874713c121ecb24cab530b62bee8b443ccb453b4c05333e77fb2",
          "sha256": "b739e6499b8aab463ce3a4e68e98dc51328382946447369be2447781c6ab207",
          "sha1": "2dbaaa51d9261ec093570798f4f2f30711203863",
          "md5": "ea7b5474270b6fee639c462c765e513a"
        }
      ]
    }
  ]
}
