{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-yaml-cfn",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "k23roxkwqjbs5i6arr4lg4r4xm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-yaml-cfn",
          "version": {
            "requires": "1.110.1"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-yaml-cfn-1.110.1-0.6.21.jar",
          "url": "cdk-yaml-cfn-1.110.1-0.6.21.jar",
          "size": 426,
          "sha512": "ada03c39a7d94540713d85a530f01e9e87956115073536e7a91d3ebdac93f0bc63481276441b8412fa52467168a84691a200d9311b5eb1b051888ddd11b8b2e4",
          "sha256": "986e0da465ab392c8bb249c3a99daa9d477f46b0e46bd5a807ebf810fcd593b8",
          "sha1": "f343377c8ecea1d31bf83c590406a9841c85961d",
          "md5": "689e4232a05fe0d56111cdfef94d83c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-yaml-cfn",
          "version": {
            "requires": "1.110.1"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-yaml-cfn-1.110.1-0.6.21.jar",
          "url": "cdk-yaml-cfn-1.110.1-0.6.21.jar",
          "size": 426,
          "sha512": "ada03c39a7d94540713d85a530f01e9e87956115073536e7a91d3ebdac93f0bc63481276441b8412fa52467168a84691a200d9311b5eb1b051888ddd11b8b2e4",
          "sha256": "986e0da465ab392c8bb249c3a99daa9d477f46b0e46bd5a807ebf810fcd593b8",
          "sha1": "f343377c8ecea1d31bf83c590406a9841c85961d",
          "md5": "689e4232a05fe0d56111cdfef94d83c0"
        }
      ]
    }
  ]
}
