{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sdb",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sdb",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "sdb-1.118.0-0.6.25.jar",
          "url": "sdb-1.118.0-0.6.25.jar",
          "size": 8453,
          "sha512": "61bc8d41e5cd69589d3b7d2e6c9e8383018e88cee870c1518e18c1dcaa843f16abd5095952cde19a1162620b9ed71c0d51e3d4f52a2fdc9075388f92576f4d91",
          "sha256": "8f1552506310bad6a92e21895b8b84dfaac05e91575b7226b0bf4c8456c941d1",
          "sha1": "d7ec8fdb1623ddfe8918e451d94ec582208fe25d",
          "md5": "fc95b83903c905696f9706aba9fc37cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sdb",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "sdb-1.118.0-0.6.25.jar",
          "url": "sdb-1.118.0-0.6.25.jar",
          "size": 8453,
          "sha512": "61bc8d41e5cd69589d3b7d2e6c9e8383018e88cee870c1518e18c1dcaa843f16abd5095952cde19a1162620b9ed71c0d51e3d4f52a2fdc9075388f92576f4d91",
          "sha256": "8f1552506310bad6a92e21895b8b84dfaac05e91575b7226b0bf4c8456c941d1",
          "sha1": "d7ec8fdb1623ddfe8918e451d94ec582208fe25d",
          "md5": "fc95b83903c905696f9706aba9fc37cf"
        }
      ]
    }
  ]
}
