{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "opsworkscm",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "opsworkscm",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "opsworkscm-1.111.0-0.6.21.jar",
          "url": "opsworkscm-1.111.0-0.6.21.jar",
          "size": 43066,
          "sha512": "d451b4a424281fa3f10b44c2689f9aab05eafbf8721bf9547dbdee54ef91bfc91fa8b7479451596b93877e9d813ae4eeec7d55a766c9bf429ecc7720bad49943",
          "sha256": "1efda78c67e2931d7b07c27b22bd5edfaa8ce8c5507432cf16175353b3632e37",
          "sha1": "b728da1a8d32a29e1b3d6ef2423f42bb57d0aa1",
          "md5": "79575df3a509559d255878241301011b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "opsworkscm",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "opsworkscm-1.111.0-0.6.21.jar",
          "url": "opsworkscm-1.111.0-0.6.21.jar",
          "size": 43066,
          "sha512": "d451b4a424281fa3f10b44c2689f9aab05eafbf8721bf9547dbdee54ef91bfc91fa8b7479451596b93877e9d813ae4eeec7d55a766c9bf429ecc7720bad49943",
          "sha256": "1efda78c67e2931d7b07c27b22bd5edfaa8ce8c5507432cf16175353b3632e37",
          "sha1": "b728da1a8d32a29e1b3d6ef2423f42bb57d0aa1",
          "md5": "79575df3a509559d255878241301011b"
        }
      ]
    }
  ]
}
