{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "wafregional",
    "version": "1.31.0-unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.31.0-unspecified.jar",
          "url": "wafregional-1.31.0-unspecified.jar",
          "size": 251389,
          "sha512": "5a6bce195a2af05bd0f0572790f6049061e5e0fb8a947fc26511212e00ecd0fa1980087350e37ffcaab04acdd62130e3500ee5837070e18c174c87733a2f223e",
          "sha256": "fca6c3efad99ec9dcb06800ac36c846f4b2a58981a240946f881745d6fe37ff4",
          "sha1": "7015402005ae53c6d911bfea0f08e37babb4bf2d",
          "md5": "71f4a954dca9e0e95ff58fde6064f928"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.31.0-unspecified.jar",
          "url": "wafregional-1.31.0-unspecified.jar",
          "size": 251389,
          "sha512": "5a6bce195a2af05bd0f0572790f6049061e5e0fb8a947fc26511212e00ecd0fa1980087350e37ffcaab04acdd62130e3500ee5837070e18c174c87733a2f223e",
          "sha256": "fca6c3efad99ec9dcb06800ac36c846f4b2a58981a240946f881745d6fe37ff4",
          "sha1": "7015402005ae53c6d911bfea0f08e37babb4bf2d",
          "md5": "71f4a954dca9e0e95ff58fde6064f928"
        }
      ]
    }
  ]
}
