{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "nimblestudio",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "nimblestudio",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "nimblestudio-1.105.0-0.6.21.jar",
          "url": "nimblestudio-1.105.0-0.6.21.jar",
          "size": 142403,
          "sha512": "9a9f2d984bdb3ff2dd66c63263a74d7dceeabc55cd0c87838b1c0fef38d92950e4366f8c1b798963772605054f78f693e87393f898217b9e7497c1495e498ce7",
          "sha256": "f126af23de926433ad9e45b36f61c59f356860c71ae5124035f7ad9311081824",
          "sha1": "837a9bfbc7a414b0a8858e197587a7def28f4ff0",
          "md5": "c24b8e9151cf480903dcf0507f7f71e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "nimblestudio",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "nimblestudio-1.105.0-0.6.21.jar",
          "url": "nimblestudio-1.105.0-0.6.21.jar",
          "size": 142403,
          "sha512": "9a9f2d984bdb3ff2dd66c63263a74d7dceeabc55cd0c87838b1c0fef38d92950e4366f8c1b798963772605054f78f693e87393f898217b9e7497c1495e498ce7",
          "sha256": "f126af23de926433ad9e45b36f61c59f356860c71ae5124035f7ad9311081824",
          "sha1": "837a9bfbc7a414b0a8858e197587a7def28f4ff0",
          "md5": "c24b8e9151cf480903dcf0507f7f71e5"
        }
      ]
    }
  ]
}
