{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "timestream",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "timestream",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "timestream-1.103.0-0.6.21.jar",
          "url": "timestream-1.103.0-0.6.21.jar",
          "size": 16528,
          "sha512": "394b4246af609d2c6a96c5d9a2b65dcdb4e5bc487cbb180e8216bf35f2e8a4ecb2fefb6f174f18880b487282aee803bbbbda49c406fac14e06539f55da5ad793",
          "sha256": "e83200b5337d770a178b81bcce445b28e43d0cf148d82b17d22ffae56b1cefe8",
          "sha1": "52f36b9c23c9f7a72a8408e372639e381fa236a",
          "md5": "9c965909c8b04af618c04876f91657e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "timestream",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "timestream-1.103.0-0.6.21.jar",
          "url": "timestream-1.103.0-0.6.21.jar",
          "size": 16528,
          "sha512": "394b4246af609d2c6a96c5d9a2b65dcdb4e5bc487cbb180e8216bf35f2e8a4ecb2fefb6f174f18880b487282aee803bbbbda49c406fac14e06539f55da5ad793",
          "sha256": "e83200b5337d770a178b81bcce445b28e43d0cf148d82b17d22ffae56b1cefe8",
          "sha1": "52f36b9c23c9f7a72a8408e372639e381fa236a",
          "md5": "9c965909c8b04af618c04876f91657e2"
        }
      ]
    }
  ]
}
