{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "applicationinsights",
    "version": "1.106.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "apa3jttzlbgsjbklj7vcehaque"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "applicationinsights",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "applicationinsights-1.106.1-0.6.21.jar",
          "url": "applicationinsights-1.106.1-0.6.21.jar",
          "size": 177352,
          "sha512": "bcc0ad9256638d50b54b854520c17412062bbacb830c3532830028a026f143a63af95a5a4538d4da5ff69740bfddbdbd1ea8ceca0d18fda48a6f3b88f2b316e1",
          "sha256": "1748dbf54257cb3acafb33dd6eb87007d9d449ce4fb13dc87e3a288db1b7f818",
          "sha1": "273bd8ab72e9a7da2ddc77a15ebb24769cc05cc5",
          "md5": "62a5519c2b3c4102b6bd26897d2ae903"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "applicationinsights",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "applicationinsights-1.106.1-0.6.21.jar",
          "url": "applicationinsights-1.106.1-0.6.21.jar",
          "size": 177352,
          "sha512": "bcc0ad9256638d50b54b854520c17412062bbacb830c3532830028a026f143a63af95a5a4538d4da5ff69740bfddbdbd1ea8ceca0d18fda48a6f3b88f2b316e1",
          "sha256": "1748dbf54257cb3acafb33dd6eb87007d9d449ce4fb13dc87e3a288db1b7f818",
          "sha1": "273bd8ab72e9a7da2ddc77a15ebb24769cc05cc5",
          "md5": "62a5519c2b3c4102b6bd26897d2ae903"
        }
      ]
    }
  ]
}
