{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "auditmanager",
    "version": "1.101.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "d5vusioiqzbnxk6vuwjeusvgpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "auditmanager",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "auditmanager-1.101.0-0.6.21.jar",
          "url": "auditmanager-1.101.0-0.6.21.jar",
          "size": 76351,
          "sha512": "c3d54be87adc0de8b7281db94276ef7aee5b27c4e47f7e0a0a264e30978e568af2022fec5ff193d9e6aca8cec6a09701064c97f76f51d713f1d331d60c67d32b",
          "sha256": "a30af205d7cf48904ab0e3c760052c56a606fc6c161bced5575e7e387f0ccc77",
          "sha1": "83baa6ef480caecedb346a7d946b59918a43bb70",
          "md5": "5138194a5f23656acee6dd81adf6729"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "auditmanager",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "auditmanager-1.101.0-0.6.21.jar",
          "url": "auditmanager-1.101.0-0.6.21.jar",
          "size": 76351,
          "sha512": "c3d54be87adc0de8b7281db94276ef7aee5b27c4e47f7e0a0a264e30978e568af2022fec5ff193d9e6aca8cec6a09701064c97f76f51d713f1d331d60c67d32b",
          "sha256": "a30af205d7cf48904ab0e3c760052c56a606fc6c161bced5575e7e387f0ccc77",
          "sha1": "83baa6ef480caecedb346a7d946b59918a43bb70",
          "md5": "5138194a5f23656acee6dd81adf6729"
        }
      ]
    }
  ]
}
