{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lambda-event-sources",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-event-sources",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "apigateway",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dynamodb",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kinesis",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-notifications",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "secretsmanager",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns-subscriptions",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-event-sources-1.102.0-0.6.21.jar",
          "url": "lambda-event-sources-1.102.0-0.6.21.jar",
          "size": 52822,
          "sha512": "ed1c0712339408b1dd6c74e2fac726e597c527ed77e696f71da85dae5023547d9876cef6c99dbcccf8639ace7a827ba8954d9bce05cfc2d2f5c9da452d8fbea",
          "sha256": "b9b4eb3f1ddee51327566a213bc829a6aaca939a50d1c5cb4e44ae144a32869e",
          "sha1": "33106be1368a57e6daa0544fe26c3fc42055550f",
          "md5": "e0dc1ef5fc56e097a8ccb295220a2290"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-event-sources",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "apigateway",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dynamodb",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kinesis",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-notifications",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "secretsmanager",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns-subscriptions",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-event-sources-1.102.0-0.6.21.jar",
          "url": "lambda-event-sources-1.102.0-0.6.21.jar",
          "size": 52822,
          "sha512": "ed1c0712339408b1dd6c74e2fac726e597c527ed77e696f71da85dae5023547d9876cef6c99dbcccf8639ace7a827ba8954d9bce05cfc2d2f5c9da452d8fbea",
          "sha256": "b9b4eb3f1ddee51327566a213bc829a6aaca939a50d1c5cb4e44ae144a32869e",
          "sha1": "33106be1368a57e6daa0544fe26c3fc42055550f",
          "md5": "e0dc1ef5fc56e097a8ccb295220a2290"
        }
      ]
    }
  ]
}
