{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotsitewise",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotsitewise",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotsitewise-1.111.0-0.6.21.jar",
          "url": "iotsitewise-1.111.0-0.6.21.jar",
          "size": 287672,
          "sha512": "1b3b31a4d272dc5bd4bf014b8acb52e201752ed6ec0ddd86e503fa3b476c6d559c06ae9f7e5b136425df6dd58bd73e64244f50f79d9eab8cdc712273fbf450e7",
          "sha256": "6d7e6b3ab24f3a830db5b9a17e2cea5f493443113041166d7b2330b2aae4fb80",
          "sha1": "312f5315101cba9637861895881f9014ea767ccf",
          "md5": "ab107187821c93a5371f680890ed7335"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotsitewise",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotsitewise-1.111.0-0.6.21.jar",
          "url": "iotsitewise-1.111.0-0.6.21.jar",
          "size": 287672,
          "sha512": "1b3b31a4d272dc5bd4bf014b8acb52e201752ed6ec0ddd86e503fa3b476c6d559c06ae9f7e5b136425df6dd58bd73e64244f50f79d9eab8cdc712273fbf450e7",
          "sha256": "6d7e6b3ab24f3a830db5b9a17e2cea5f493443113041166d7b2330b2aae4fb80",
          "sha1": "312f5315101cba9637861895881f9014ea767ccf",
          "md5": "ab107187821c93a5371f680890ed7335"
        }
      ]
    }
  ]
}
