{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticloadbalancing",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticloadbalancing",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticloadbalancing-1.108.1-0.6.21.jar",
          "url": "elasticloadbalancing-1.108.1-0.6.21.jar",
          "size": 153878,
          "sha512": "81beb69628202082f36a14954331fa4d8a188693b2fb544f0874a393b4a22c44e4048ce3929257bf3b6c3784f169b884b5ce4e2b63e2f262e13b57cb5f1b4592",
          "sha256": "1fd104e4aa078ba493e5f1d1ae050bf7fd9f4cdd5b8d5731a13a5873dc2f799f",
          "sha1": "18a49316f7f253182cb2fac00f6255e52999f3f1",
          "md5": "3ecdb6bb9ba114242578165e2fc11508"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticloadbalancing",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticloadbalancing-1.108.1-0.6.21.jar",
          "url": "elasticloadbalancing-1.108.1-0.6.21.jar",
          "size": 153878,
          "sha512": "81beb69628202082f36a14954331fa4d8a188693b2fb544f0874a393b4a22c44e4048ce3929257bf3b6c3784f169b884b5ce4e2b63e2f262e13b57cb5f1b4592",
          "sha256": "1fd104e4aa078ba493e5f1d1ae050bf7fd9f4cdd5b8d5731a13a5873dc2f799f",
          "sha1": "18a49316f7f253182cb2fac00f6255e52999f3f1",
          "md5": "3ecdb6bb9ba114242578165e2fc11508"
        }
      ]
    }
  ]
}
