{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "emr",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "emr",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emr-1.102.0-0.6.21.jar",
          "url": "emr-1.102.0-0.6.21.jar",
          "size": 619034,
          "sha512": "5d3f522152e1ebca4f61c65aaac5de39f0d24aa9c38bcf5594a0c7da3d82ef64c6513299342a9e314f0106e9098af316ababae147ad8611ab097b6a8cf22b124",
          "sha256": "3f5d1b06b44a16c559576695412d109f80e44cb93ebd95689aedf0ca963aeee4",
          "sha1": "fb5d1501edab525b610807ed13fb14c0346f8fb8",
          "md5": "7073954d306a4ecbbb0331cdb4916053"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "emr",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emr-1.102.0-0.6.21.jar",
          "url": "emr-1.102.0-0.6.21.jar",
          "size": 619034,
          "sha512": "5d3f522152e1ebca4f61c65aaac5de39f0d24aa9c38bcf5594a0c7da3d82ef64c6513299342a9e314f0106e9098af316ababae147ad8611ab097b6a8cf22b124",
          "sha256": "3f5d1b06b44a16c559576695412d109f80e44cb93ebd95689aedf0ca963aeee4",
          "sha1": "fb5d1501edab525b610807ed13fb14c0346f8fb8",
          "md5": "7073954d306a4ecbbb0331cdb4916053"
        }
      ]
    }
  ]
}
