{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestarnotifications",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarnotifications-1.108.1-0.6.21.jar",
          "url": "codestarnotifications-1.108.1-0.6.21.jar",
          "size": 23604,
          "sha512": "72cb5235b3c2a8f557087d53854336edd9c724a69e683e3a26abd09035e94eade0edff72cd12ddf72c47115028b538286037da4f2d632f0f933533c6ae075d7b",
          "sha256": "e917956c4a040c6082f613283d68be47a985a5324b490a1ae860b472cfe3c439",
          "sha1": "df05b827b988605b696b79688ed72751b84c7cda",
          "md5": "74f8dbc8eac18f000c5656890cb9cb2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarnotifications-1.108.1-0.6.21.jar",
          "url": "codestarnotifications-1.108.1-0.6.21.jar",
          "size": 23604,
          "sha512": "72cb5235b3c2a8f557087d53854336edd9c724a69e683e3a26abd09035e94eade0edff72cd12ddf72c47115028b538286037da4f2d632f0f933533c6ae075d7b",
          "sha256": "e917956c4a040c6082f613283d68be47a985a5324b490a1ae860b472cfe3c439",
          "sha1": "df05b827b988605b696b79688ed72751b84c7cda",
          "md5": "74f8dbc8eac18f000c5656890cb9cb2d"
        }
      ]
    }
  ]
}
