{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ecr",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ecr",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "ecr-1.118.0-0.6.25.jar",
          "url": "ecr-1.118.0-0.6.25.jar",
          "size": 123893,
          "sha512": "f69ab5a92b62f3dd91bbfbd4b5fe44a512a172df513f3e030835e6dd77ab2289773a372eaa8c25c0516840d6759464c8ad833e1a597d6946ff2b69ea16eafc8b",
          "sha256": "8c8b261603ef4fecca359402610219bbe2cccbad2f8462fcdd429f482c863fe7",
          "sha1": "c2b8d570d71bfabd5f4fae1b522dad1fb9797ec7",
          "md5": "ecf9c54d1d0595ee2262890dcb63a45b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ecr",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "ecr-1.118.0-0.6.25.jar",
          "url": "ecr-1.118.0-0.6.25.jar",
          "size": 123893,
          "sha512": "f69ab5a92b62f3dd91bbfbd4b5fe44a512a172df513f3e030835e6dd77ab2289773a372eaa8c25c0516840d6759464c8ad833e1a597d6946ff2b69ea16eafc8b",
          "sha256": "8c8b261603ef4fecca359402610219bbe2cccbad2f8462fcdd429f482c863fe7",
          "sha1": "c2b8d570d71bfabd5f4fae1b522dad1fb9797ec7",
          "md5": "ecf9c54d1d0595ee2262890dcb63a45b"
        }
      ]
    }
  ]
}
