{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "detective",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "detective",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "detective-1.111.0-0.6.21.jar",
          "url": "detective-1.111.0-0.6.21.jar",
          "size": 24992,
          "sha512": "6a60431e9a637673225a36180e3ffb3ac5e6a37ce5068f51c1f2fc5f28cc0b01a70526d96be47798fed031dcf94a627acea7bf0d08d4a1087337ba39de269402",
          "sha256": "5480b17b51f407135a0b1097c3168f8ea3ea7f87c9e448242c719767770b70d5",
          "sha1": "88d471ccb7542bbd421eb9aaffaa1a1f11c217bb",
          "md5": "bccb2fd71bcd8af1e8f0489fe84f1452"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "detective",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "detective-1.111.0-0.6.21.jar",
          "url": "detective-1.111.0-0.6.21.jar",
          "size": 24992,
          "sha512": "6a60431e9a637673225a36180e3ffb3ac5e6a37ce5068f51c1f2fc5f28cc0b01a70526d96be47798fed031dcf94a627acea7bf0d08d4a1087337ba39de269402",
          "sha256": "5480b17b51f407135a0b1097c3168f8ea3ea7f87c9e448242c719767770b70d5",
          "sha1": "88d471ccb7542bbd421eb9aaffaa1a1f11c217bb",
          "md5": "bccb2fd71bcd8af1e8f0489fe84f1452"
        }
      ]
    }
  ]
}
