{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "nimblestudio",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "nimblestudio",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "nimblestudio-1.108.1-0.6.21.jar",
          "url": "nimblestudio-1.108.1-0.6.21.jar",
          "size": 142410,
          "sha512": "4911104ff753c800d58af7fa62a39683dca43c995ad3046f85f7ace2dd2b6b96785fc3948bfcbb8eebfbf3555947eacf7476f719e578568a33207ccd14153825",
          "sha256": "d796a4c470698aebea59aed7f03d2b5e39c0ebebc7df00cdeaf207d6277bdf1d",
          "sha1": "583a92a0dac3a6d4921f01fad5138a8f2f2fbc01",
          "md5": "dd606b37e97b6a1cddecdf13bfe6ca51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "nimblestudio",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "nimblestudio-1.108.1-0.6.21.jar",
          "url": "nimblestudio-1.108.1-0.6.21.jar",
          "size": 142410,
          "sha512": "4911104ff753c800d58af7fa62a39683dca43c995ad3046f85f7ace2dd2b6b96785fc3948bfcbb8eebfbf3555947eacf7476f719e578568a33207ccd14153825",
          "sha256": "d796a4c470698aebea59aed7f03d2b5e39c0ebebc7df00cdeaf207d6277bdf1d",
          "sha1": "583a92a0dac3a6d4921f01fad5138a8f2f2fbc01",
          "md5": "dd606b37e97b6a1cddecdf13bfe6ca51"
        }
      ]
    }
  ]
}
