{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "amazonmq",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "amazonmq",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "amazonmq-1.112.0-0.6.21.jar",
          "url": "amazonmq-1.112.0-0.6.21.jar",
          "size": 164751,
          "sha512": "c5087f2fabae0251343e400de829cd433ffe6f704fd2cf49e3536e9ef7f27a5f1002444200c69453473e9b954cfb72443ab27761841fc21a76b4d980541d5be8",
          "sha256": "a36ae5df1bbae628b13df8035083e043e93e58840c0588acfe594fa2f3da74f",
          "sha1": "1399e59139a6af7085944a2d561c712730bd327a",
          "md5": "a6404d94cc5682eee3ccb7ed303e1e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "amazonmq",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "amazonmq-1.112.0-0.6.21.jar",
          "url": "amazonmq-1.112.0-0.6.21.jar",
          "size": 164751,
          "sha512": "c5087f2fabae0251343e400de829cd433ffe6f704fd2cf49e3536e9ef7f27a5f1002444200c69453473e9b954cfb72443ab27761841fc21a76b4d980541d5be8",
          "sha256": "a36ae5df1bbae628b13df8035083e043e93e58840c0588acfe594fa2f3da74f",
          "sha1": "1399e59139a6af7085944a2d561c712730bd327a",
          "md5": "a6404d94cc5682eee3ccb7ed303e1e2"
        }
      ]
    }
  ]
}
