{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-assets-schema",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets-schema",
          "version": {
            "requires": "1.116.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-schema-1.116.0-0.6.21.jar",
          "url": "cdk-assets-schema-1.116.0-0.6.21.jar",
          "size": 436,
          "sha512": "c332eb30a354dc1bebdd76e6f74594f91ddff84919c348691dea6db0726a73100b5934b082285d758ff71bd807a1a1eafe510f7bf6d51159821f0717d1dc3e04",
          "sha256": "3df6627a145d19a68fdb3e4e1989d4e30880f48f4b5b3f904a4254f49f2c330a",
          "sha1": "383dd23bc8a9207212b2327663afb7a69ff505ae",
          "md5": "8cfd93054387594240a9b22a433b897e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets-schema",
          "version": {
            "requires": "1.116.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-schema-1.116.0-0.6.21.jar",
          "url": "cdk-assets-schema-1.116.0-0.6.21.jar",
          "size": 436,
          "sha512": "c332eb30a354dc1bebdd76e6f74594f91ddff84919c348691dea6db0726a73100b5934b082285d758ff71bd807a1a1eafe510f7bf6d51159821f0717d1dc3e04",
          "sha256": "3df6627a145d19a68fdb3e4e1989d4e30880f48f4b5b3f904a4254f49f2c330a",
          "sha1": "383dd23bc8a9207212b2327663afb7a69ff505ae",
          "md5": "8cfd93054387594240a9b22a433b897e"
        }
      ]
    }
  ]
}
