{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "kinesisfirehose",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "kinesisfirehose",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesisfirehose-1.111.0-0.6.21.jar",
          "url": "kinesisfirehose-1.111.0-0.6.21.jar",
          "size": 471278,
          "sha512": "a360500c9a2d6cbde4942f3f81ec69727a6f5b68f97c17edd74973db0c05b216c21d048759d4404c8d1f80a02b8210944416ebf600fea6be12dba7c38be030c3",
          "sha256": "bb2bec2493b003be68a321fab3ebc231b5e8ab0f2620abbcaa70f59c63dc5a",
          "sha1": "d7dde29f04ae52eb2b7bf6467e456c98a5654168",
          "md5": "df91524fcf3c3af8390e1bb7254044a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "kinesisfirehose",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesisfirehose-1.111.0-0.6.21.jar",
          "url": "kinesisfirehose-1.111.0-0.6.21.jar",
          "size": 471278,
          "sha512": "a360500c9a2d6cbde4942f3f81ec69727a6f5b68f97c17edd74973db0c05b216c21d048759d4404c8d1f80a02b8210944416ebf600fea6be12dba7c38be030c3",
          "sha256": "bb2bec2493b003be68a321fab3ebc231b5e8ab0f2620abbcaa70f59c63dc5a",
          "sha1": "d7dde29f04ae52eb2b7bf6467e456c98a5654168",
          "md5": "df91524fcf3c3af8390e1bb7254044a7"
        }
      ]
    }
  ]
}
