{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ssmincidents",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ssmincidents",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ssmincidents-1.109.0-0.6.21.jar",
          "url": "ssmincidents-1.109.0-0.6.21.jar",
          "size": 108456,
          "sha512": "74331b70c2b3e7f17f145136fe3bab41a22ab71950e8067212e784967aec18734d1212cf948790a0830612bc0c58035601e842d4e6283ba1a626d44ae7e06dbf",
          "sha256": "8274716a52db1b4052c78a1853f81b47e706f63428c325fd71cc940e9902f30d",
          "sha1": "cd7814cef2d5b4b0f0fc5e2d7af5ddb78ec365c9",
          "md5": "9c48efda5fd5ea86a53cd7fa11eb3524"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ssmincidents",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ssmincidents-1.109.0-0.6.21.jar",
          "url": "ssmincidents-1.109.0-0.6.21.jar",
          "size": 108456,
          "sha512": "74331b70c2b3e7f17f145136fe3bab41a22ab71950e8067212e784967aec18734d1212cf948790a0830612bc0c58035601e842d4e6283ba1a626d44ae7e06dbf",
          "sha256": "8274716a52db1b4052c78a1853f81b47e706f63428c325fd71cc940e9902f30d",
          "sha1": "cd7814cef2d5b4b0f0fc5e2d7af5ddb78ec365c9",
          "md5": "9c48efda5fd5ea86a53cd7fa11eb3524"
        }
      ]
    }
  ]
}
