{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-assets-schema",
    "version": "1.31.0-unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets-schema",
          "version": {
            "requires": "1.31.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-schema-1.31.0-unspecified.jar",
          "url": "cdk-assets-schema-1.31.0-unspecified.jar",
          "size": 29340,
          "sha512": "904374d08e779bf6fc05e70c34ce94a277be731349abde3dda938cf054f2b97f0e76cf9c9aef4569de25c64a02c7fb3f9d15e9d159f61721ac54893d0ec90e80",
          "sha256": "faeb514657bd69c795cb8179f543252dc2eaacbff9fc5d95fba9f306d12743d3",
          "sha1": "f75682209ae562c7efdcc246e5dd4ce5cba31c8e",
          "md5": "3c1ed8906434dde5988fe10e5ee1022c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets-schema",
          "version": {
            "requires": "1.31.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-schema-1.31.0-unspecified.jar",
          "url": "cdk-assets-schema-1.31.0-unspecified.jar",
          "size": 29340,
          "sha512": "904374d08e779bf6fc05e70c34ce94a277be731349abde3dda938cf054f2b97f0e76cf9c9aef4569de25c64a02c7fb3f9d15e9d159f61721ac54893d0ec90e80",
          "sha256": "faeb514657bd69c795cb8179f543252dc2eaacbff9fc5d95fba9f306d12743d3",
          "sha1": "f75682209ae562c7efdcc246e5dd4ce5cba31c8e",
          "md5": "3c1ed8906434dde5988fe10e5ee1022c"
        }
      ]
    }
  ]
}
