{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "fis",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "k23roxkwqjbs5i6arr4lg4r4xm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "fis",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fis-1.110.1-0.6.21.jar",
          "url": "fis-1.110.1-0.6.21.jar",
          "size": 70029,
          "sha512": "25613f47209980f267cad2c11191b830dc074745958728f5f664234879af69bf9ac494ef201536f3a5b2a115964c936481e09680ab39e5fe42eeef56c4190de",
          "sha256": "18dc9a759a53b1e5103b2ffc57924f59b9b59d2a09b38d244dcd9b1e02690975",
          "sha1": "c6c63fb97a68ceff2771b51f8748edec127b29fb",
          "md5": "f2ff8430bf1dcecc35498a136d2d83d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "fis",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fis-1.110.1-0.6.21.jar",
          "url": "fis-1.110.1-0.6.21.jar",
          "size": 70029,
          "sha512": "25613f47209980f267cad2c11191b830dc074745958728f5f664234879af69bf9ac494ef201536f3a5b2a115964c936481e09680ab39e5fe42eeef56c4190de",
          "sha256": "18dc9a759a53b1e5103b2ffc57924f59b9b59d2a09b38d244dcd9b1e02690975",
          "sha1": "c6c63fb97a68ceff2771b51f8748edec127b29fb",
          "md5": "f2ff8430bf1dcecc35498a136d2d83d6"
        }
      ]
    }
  ]
}
