{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "wafregional",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.116.0-0.6.21.jar",
          "url": "wafregional-1.116.0-0.6.21.jar",
          "size": 251038,
          "sha512": "8d26e79c0dc83ff17b62bb30b74789acc43e429b033e1981d2fa3ad0a289fce25cd24812fd1ede503bfd0c30adef2acdd6694914f0ffd08e0986b5737375de4a",
          "sha256": "cde8a890c7967cc416a22f294736fcd2654a60be0b3c373b4e4f5819738e6a2d",
          "sha1": "342f17dcabe50754a605224f650bf915086061c3",
          "md5": "36fe81afb5521d82934a33d913279588"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.116.0-0.6.21.jar",
          "url": "wafregional-1.116.0-0.6.21.jar",
          "size": 251038,
          "sha512": "8d26e79c0dc83ff17b62bb30b74789acc43e429b033e1981d2fa3ad0a289fce25cd24812fd1ede503bfd0c30adef2acdd6694914f0ffd08e0986b5737375de4a",
          "sha256": "cde8a890c7967cc416a22f294736fcd2654a60be0b3c373b4e4f5819738e6a2d",
          "sha1": "342f17dcabe50754a605224f650bf915086061c3",
          "md5": "36fe81afb5521d82934a33d913279588"
        }
      ]
    }
  ]
}
