{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "eventschemas",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.118.0-0.6.25.jar",
          "url": "eventschemas-1.118.0-0.6.25.jar",
          "size": 43025,
          "sha512": "ff77ed5a74a2328284a39b884087edf53636fb6544a5718bb30a32d24691d240c5bb2bca753f61b8081577efca018610183bfd958c715760ba25e353b5ba8375",
          "sha256": "9e507043491b7eeb28624628bfa4d072795e5f49d08fb351bdbf28539756f723",
          "sha1": "7f094bf1cf826ebe7417dd54490133979b4d3d1c",
          "md5": "07544801bc1b438b7658af8a81a08e2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.118.0-0.6.25.jar",
          "url": "eventschemas-1.118.0-0.6.25.jar",
          "size": 43025,
          "sha512": "ff77ed5a74a2328284a39b884087edf53636fb6544a5718bb30a32d24691d240c5bb2bca753f61b8081577efca018610183bfd958c715760ba25e353b5ba8375",
          "sha256": "9e507043491b7eeb28624628bfa4d072795e5f49d08fb351bdbf28539756f723",
          "sha1": "7f094bf1cf826ebe7417dd54490133979b4d3d1c",
          "md5": "07544801bc1b438b7658af8a81a08e2c"
        }
      ]
    }
  ]
}
