{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-lambda-layer-awscli",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-lambda-layer-awscli",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-lambda-layer-awscli-1.116.0-0.6.21.jar",
          "url": "cdk-lambda-layer-awscli-1.116.0-0.6.21.jar",
          "size": 448,
          "sha512": "176f845450701b0d9466219ca2dfcfd11310339c163ab59142a766ddf5c07ee507a4990322db39f39703d29a4af70f6a0da5542bf8844138e3ccde56f4d6275a",
          "sha256": "81e99cfbad2e9383bd3e879764cb0595ccc965b751a258a94a9cfb054747591c",
          "sha1": "9c08ed4b22164b76581d1fb5676675cb1b8dfd7b",
          "md5": "acb43d88bf75cabf52b6d0a07ebf49af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-lambda-layer-awscli",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-lambda-layer-awscli-1.116.0-0.6.21.jar",
          "url": "cdk-lambda-layer-awscli-1.116.0-0.6.21.jar",
          "size": 448,
          "sha512": "176f845450701b0d9466219ca2dfcfd11310339c163ab59142a766ddf5c07ee507a4990322db39f39703d29a4af70f6a0da5542bf8844138e3ccde56f4d6275a",
          "sha256": "81e99cfbad2e9383bd3e879764cb0595ccc965b751a258a94a9cfb054747591c",
          "sha1": "9c08ed4b22164b76581d1fb5676675cb1b8dfd7b",
          "md5": "acb43d88bf75cabf52b6d0a07ebf49af"
        }
      ]
    }
  ]
}
