{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-cx-api",
    "version": "1.101.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "d5vusioiqzbnxk6vuwjeusvgpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cx-api-1.101.0-0.6.21.jar",
          "url": "cdk-cx-api-1.101.0-0.6.21.jar",
          "size": 76037,
          "sha512": "661c88f11e21f08b56658207cef3a7893e98b21bd4e5428e34516a0ba0cf0a3f2a0b9ea1a9ec10edf18c4c7589e826791840a8fe002adba468e48ac9155622c1",
          "sha256": "fbbd22a907d347ea644e61f398d53debb652480dd6a5016d35df36a6a1d828f4",
          "sha1": "527a6e7d2d5483f4b653a53bde03a64f9d8da1a8",
          "md5": "9e9a5cf0d2dd144731c2fa9a3f07a8af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cx-api-1.101.0-0.6.21.jar",
          "url": "cdk-cx-api-1.101.0-0.6.21.jar",
          "size": 76037,
          "sha512": "661c88f11e21f08b56658207cef3a7893e98b21bd4e5428e34516a0ba0cf0a3f2a0b9ea1a9ec10edf18c4c7589e826791840a8fe002adba468e48ac9155622c1",
          "sha256": "fbbd22a907d347ea644e61f398d53debb652480dd6a5016d35df36a6a1d828f4",
          "sha1": "527a6e7d2d5483f4b653a53bde03a64f9d8da1a8",
          "md5": "9e9a5cf0d2dd144731c2fa9a3f07a8af"
        }
      ]
    }
  ]
}
