{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "imagebuilder",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "pksuzuox3ne6pgnvsva7g32w2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.110.1-0.6.21.jar",
          "url": "imagebuilder-1.110.1-0.6.21.jar",
          "size": 284970,
          "sha512": "904963f79f98b2e1cccbfaf365264a01d980e4f471458e9efbbd8d14fa6e66fda7865a550ae7e7336f44a04f5036f14894f403ef1f31eb656f5da1de90e9aee2",
          "sha256": "4fdb7c6ab90dbb93e030c0ac4591df39b6759d5437fdd8feaec1b55bac49d6c9",
          "sha1": "29914023de2fe8dc993376ba6e811b36a94b37da",
          "md5": "e240ecd0604daefee8f033775cd3308a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.110.1-0.6.21.jar",
          "url": "imagebuilder-1.110.1-0.6.21.jar",
          "size": 284970,
          "sha512": "904963f79f98b2e1cccbfaf365264a01d980e4f471458e9efbbd8d14fa6e66fda7865a550ae7e7336f44a04f5036f14894f403ef1f31eb656f5da1de90e9aee2",
          "sha256": "4fdb7c6ab90dbb93e030c0ac4591df39b6759d5437fdd8feaec1b55bac49d6c9",
          "sha1": "29914023de2fe8dc993376ba6e811b36a94b37da",
          "md5": "e240ecd0604daefee8f033775cd3308a"
        }
      ]
    }
  ]
}
