{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "budgets",
    "version": "1.64.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "budgets",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "budgets-1.64.0-0.6.21.jar",
          "url": "budgets-1.64.0-0.6.21.jar",
          "size": 120965,
          "sha512": "29d4fdc33f4f8d9e2069b41a48bcb0e8961aa5c2e25ac310fa2ab723860feadf6b5448e0777d322eca32c15db12c5d0d6476575e9d3b7f23d682435dd76af67a",
          "sha256": "a3c5fde637c095cb0af94cff56ecc450ce29e52dbfb8503d8af1d9df0fc07a33",
          "sha1": "d86325e974706e5e66f749d074db8643803b6528",
          "md5": "10e82a976c21c31aa05ee151b24687c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "budgets",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "budgets-1.64.0-0.6.21.jar",
          "url": "budgets-1.64.0-0.6.21.jar",
          "size": 120965,
          "sha512": "29d4fdc33f4f8d9e2069b41a48bcb0e8961aa5c2e25ac310fa2ab723860feadf6b5448e0777d322eca32c15db12c5d0d6476575e9d3b7f23d682435dd76af67a",
          "sha256": "a3c5fde637c095cb0af94cff56ecc450ce29e52dbfb8503d8af1d9df0fc07a33",
          "sha1": "d86325e974706e5e66f749d074db8643803b6528",
          "md5": "10e82a976c21c31aa05ee151b24687c9"
        }
      ]
    }
  ]
}
