{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "transfer",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "transfer",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "transfer-1.113.0-0.6.21.jar",
          "url": "transfer-1.113.0-0.6.21.jar",
          "size": 86795,
          "sha512": "10afc0f182b23ee238fff375b08f996c76a297f3e21a02a30c5daa6ca5a30972816123ea43ea29c2af7b379cb9aeb0472584632be5752b035f28937847d9c364",
          "sha256": "c38fbdef86ccd0c54bf508d61c0c4af4628a7ec8e81ffb769de989a059c93548",
          "sha1": "6457ab803dfce8733f60187550f7392ca5eed677",
          "md5": "45ebd2d073b4584255ef2281df201bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "transfer",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "transfer-1.113.0-0.6.21.jar",
          "url": "transfer-1.113.0-0.6.21.jar",
          "size": 86795,
          "sha512": "10afc0f182b23ee238fff375b08f996c76a297f3e21a02a30c5daa6ca5a30972816123ea43ea29c2af7b379cb9aeb0472584632be5752b035f28937847d9c364",
          "sha256": "c38fbdef86ccd0c54bf508d61c0c4af4628a7ec8e81ffb769de989a059c93548",
          "sha1": "6457ab803dfce8733f60187550f7392ca5eed677",
          "md5": "45ebd2d073b4584255ef2281df201bc"
        }
      ]
    }
  ]
}
