{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "logs",
    "version": "1.64.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "logs",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "logs-1.64.0-0.6.22.jar",
          "url": "logs-1.64.0-0.6.22.jar",
          "size": 116210,
          "sha512": "98d3f72ec2ccf9ef4f70bd6b7cf2f91283725280e27674e7d396e57e2ba7f4113894bc9ad91292e54d535ac84fafd1dcdedb6c5b14ed39502cb1a3f7ab97db99",
          "sha256": "61e0af53b97c5d69224faaa83884c050357e3f4e04236449dc3767248a4d7c67",
          "sha1": "65be4c2493e7a98d4ac1248b271f498737624700",
          "md5": "8ab3716bf531750260da377d40ff13a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "logs",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "logs-1.64.0-0.6.22.jar",
          "url": "logs-1.64.0-0.6.22.jar",
          "size": 116210,
          "sha512": "98d3f72ec2ccf9ef4f70bd6b7cf2f91283725280e27674e7d396e57e2ba7f4113894bc9ad91292e54d535ac84fafd1dcdedb6c5b14ed39502cb1a3f7ab97db99",
          "sha256": "61e0af53b97c5d69224faaa83884c050357e3f4e04236449dc3767248a4d7c67",
          "sha1": "65be4c2493e7a98d4ac1248b271f498737624700",
          "md5": "8ab3716bf531750260da377d40ff13a0"
        }
      ]
    }
  ]
}
