{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ram",
    "version": "1.100.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "smkqp7thvbfexba6catfwegxzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ram",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ram-1.100.0-0.6.21.jar",
          "url": "ram-1.100.0-0.6.21.jar",
          "size": 18530,
          "sha512": "9f4f4d26d011f56d37587cee94ec09933d22b3df33be5d17dfd3ee71534c1392ab61634b746c19f75fd5f7b6bfa423de2be01c7f54fb52fc2d086c22b75d8db5",
          "sha256": "5064ce10acd9f20d8ef487ba7d2e4b2d48f8b089bdbe965fa906c56f2d6e701f",
          "sha1": "a5b573cca24dfe5bc0326313bb397fa276a525e7",
          "md5": "f0b9a99670a046ce925f501022625fd2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ram",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ram-1.100.0-0.6.21.jar",
          "url": "ram-1.100.0-0.6.21.jar",
          "size": 18530,
          "sha512": "9f4f4d26d011f56d37587cee94ec09933d22b3df33be5d17dfd3ee71534c1392ab61634b746c19f75fd5f7b6bfa423de2be01c7f54fb52fc2d086c22b75d8db5",
          "sha256": "5064ce10acd9f20d8ef487ba7d2e4b2d48f8b089bdbe965fa906c56f2d6e701f",
          "sha1": "a5b573cca24dfe5bc0326313bb397fa276a525e7",
          "md5": "f0b9a99670a046ce925f501022625fd2"
        }
      ]
    }
  ]
}
