{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "pinpoint",
    "version": "1.101.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "jaowebu54rhl3bnpwvdhdg2v5y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "pinpoint",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "pinpoint-1.101.0-0.6.21.jar",
          "url": "pinpoint-1.101.0-0.6.21.jar",
          "size": 629501,
          "sha512": "b1cbdae0aac105c142bd1cf2c92d77f580d7a784f56f1102529f3b688aa056fb61b7822aad2955efcdf2f2d9982da5538dd3ce6a6373ca966a8a31d2d55e355d",
          "sha256": "16de061a9c2b73993a1852766bfc282a47a7a715afc08a05c06cb84a07d36490",
          "sha1": "91cce8719c316c6f4d083bc7224a76a168dbc8",
          "md5": "9c53cd995acef9264f004d10bfd79f64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "pinpoint",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "pinpoint-1.101.0-0.6.21.jar",
          "url": "pinpoint-1.101.0-0.6.21.jar",
          "size": 629501,
          "sha512": "b1cbdae0aac105c142bd1cf2c92d77f580d7a784f56f1102529f3b688aa056fb61b7822aad2955efcdf2f2d9982da5538dd3ce6a6373ca966a8a31d2d55e355d",
          "sha256": "16de061a9c2b73993a1852766bfc282a47a7a715afc08a05c06cb84a07d36490",
          "sha1": "91cce8719c316c6f4d083bc7224a76a168dbc8",
          "md5": "9c53cd995acef9264f004d10bfd79f64"
        }
      ]
    }
  ]
}
