{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "autoscaling-common",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling-common",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-common-1.111.0-0.6.21.jar",
          "url": "autoscaling-common-1.111.0-0.6.21.jar",
          "size": 15766,
          "sha512": "d94e7ccd0503bc191595c4df8a269b1ef50eb87ba7d1aac90f8483dedb2d1b563fe113e7ffcee274a11a2169cd0fea9917b794faa93bc8b7b2fbc011b7289bd5",
          "sha256": "1f99addf25602125b33a4aff4f572c6570ccda9aa986c05af62ca90a2463c76b",
          "sha1": "b118756b81b1108b9e7137b0209f7dfaca3caf4",
          "md5": "52173d01a1770128a8463206adf211aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling-common",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-common-1.111.0-0.6.21.jar",
          "url": "autoscaling-common-1.111.0-0.6.21.jar",
          "size": 15766,
          "sha512": "d94e7ccd0503bc191595c4df8a269b1ef50eb87ba7d1aac90f8483dedb2d1b563fe113e7ffcee274a11a2169cd0fea9917b794faa93bc8b7b2fbc011b7289bd5",
          "sha256": "1f99addf25602125b33a4aff4f572c6570ccda9aa986c05af62ca90a2463c76b",
          "sha1": "b118756b81b1108b9e7137b0209f7dfaca3caf4",
          "md5": "52173d01a1770128a8463206adf211aa"
        }
      ]
    }
  ]
}
