{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotsitewise",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotsitewise",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotsitewise-1.106.0-0.6.21.jar",
          "url": "iotsitewise-1.106.0-0.6.21.jar",
          "size": 287662,
          "sha512": "2bf3cffbb2410d26e4f7a9cf18785a3fa16f320a5ca2d01e1045920f135e9c251bf5d96bf23a2adf675357634951ac0e2475fcd7ba237a7382c99135a99ba56e",
          "sha256": "fbe2a7a51583bdbebd1beb3ce7f66e5c04d94fef5d715281ea74a8207ccc0646",
          "sha1": "6a102a8372536ae2a8eb817e5056ee7c79346bd",
          "md5": "5dee0cf835bf4996cae8e17cc7d371e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotsitewise",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotsitewise-1.106.0-0.6.21.jar",
          "url": "iotsitewise-1.106.0-0.6.21.jar",
          "size": 287662,
          "sha512": "2bf3cffbb2410d26e4f7a9cf18785a3fa16f320a5ca2d01e1045920f135e9c251bf5d96bf23a2adf675357634951ac0e2475fcd7ba237a7382c99135a99ba56e",
          "sha256": "fbe2a7a51583bdbebd1beb3ce7f66e5c04d94fef5d715281ea74a8207ccc0646",
          "sha1": "6a102a8372536ae2a8eb817e5056ee7c79346bd",
          "md5": "5dee0cf835bf4996cae8e17cc7d371e6"
        }
      ]
    }
  ]
}
