{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "docdb",
    "version": "1.31.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "docdb",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "docdb-1.31.0-0.6.22.jar",
          "url": "docdb-1.31.0-0.6.22.jar",
          "size": 52968,
          "sha512": "b27cb3a265c095e8d091c246033cfd027f262845e96d5159fb8a4b7a6fe3a2dc73cd2a5892065ff3ef8b6d1205175577b4b92757a5b0c04a09b5b721cb0da4f0",
          "sha256": "d70c9bbf7347c92b9a06c407b2a46d32d80b8f67ce8f0cb2b7358948169bc227",
          "sha1": "7ea61147cba96219b899f1e18d8fcedeb23a45a5",
          "md5": "eead0e9e705d9300e8107a8971ff838f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "docdb",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "docdb-1.31.0-0.6.22.jar",
          "url": "docdb-1.31.0-0.6.22.jar",
          "size": 52968,
          "sha512": "b27cb3a265c095e8d091c246033cfd027f262845e96d5159fb8a4b7a6fe3a2dc73cd2a5892065ff3ef8b6d1205175577b4b92757a5b0c04a09b5b721cb0da4f0",
          "sha256": "d70c9bbf7347c92b9a06c407b2a46d32d80b8f67ce8f0cb2b7358948169bc227",
          "sha1": "7ea61147cba96219b899f1e18d8fcedeb23a45a5",
          "md5": "eead0e9e705d9300e8107a8971ff838f"
        }
      ]
    }
  ]
}
