{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "kendra",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "kendra",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kendra-1.114.0-0.6.21.jar",
          "url": "kendra-1.114.0-0.6.21.jar",
          "size": 554825,
          "sha512": "42e8916e28c73bca4dd4e1864cd1154f4cf0ba8eb6d8b9bb14c1538114d67ba4f277310e0f8307e4d6499e2b7c83365943eec7aa38fcaad922c56d6725dd5482",
          "sha256": "ed6ede4e5a9c23c0f4ce917e6fa12912e1731213933406acecabb5c18ad1ff43",
          "sha1": "f36c3e7bc26470a674a42f76a0d1084e28675f05",
          "md5": "60169880000c091b61d774bcb7771a97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "kendra",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kendra-1.114.0-0.6.21.jar",
          "url": "kendra-1.114.0-0.6.21.jar",
          "size": 554825,
          "sha512": "42e8916e28c73bca4dd4e1864cd1154f4cf0ba8eb6d8b9bb14c1538114d67ba4f277310e0f8307e4d6499e2b7c83365943eec7aa38fcaad922c56d6725dd5482",
          "sha256": "ed6ede4e5a9c23c0f4ce917e6fa12912e1731213933406acecabb5c18ad1ff43",
          "sha1": "f36c3e7bc26470a674a42f76a0d1084e28675f05",
          "md5": "60169880000c091b61d774bcb7771a97"
        }
      ]
    }
  ]
}
