{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cloudwatch-actions",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cloudwatch-actions",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "applicationautoscaling",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cloudwatch-actions-1.108.1-0.6.21.jar",
          "url": "cloudwatch-actions-1.108.1-0.6.21.jar",
          "size": 438,
          "sha512": "49130ddbf88e54bd20ea0c3f2919e3ab26dc92a16834618499c3a873e6c9ebf72248a257c1a6036fff6ad54f32984abddcdc688039a4c422b3be173c00f15377",
          "sha256": "e486159cd65c1d9e0fe355155308137ae7d545c97887be323994bfe223ff870b",
          "sha1": "f21c2a83db8caf5eb234a5a96d1dc4a48e475db3",
          "md5": "8cc5bdf126075aea05602fc27f5b66dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cloudwatch-actions",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "applicationautoscaling",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cloudwatch-actions-1.108.1-0.6.21.jar",
          "url": "cloudwatch-actions-1.108.1-0.6.21.jar",
          "size": 438,
          "sha512": "49130ddbf88e54bd20ea0c3f2919e3ab26dc92a16834618499c3a873e6c9ebf72248a257c1a6036fff6ad54f32984abddcdc688039a4c422b3be173c00f15377",
          "sha256": "e486159cd65c1d9e0fe355155308137ae7d545c97887be323994bfe223ff870b",
          "sha1": "f21c2a83db8caf5eb234a5a96d1dc4a48e475db3",
          "md5": "8cc5bdf126075aea05602fc27f5b66dd"
        }
      ]
    }
  ]
}
