{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sso",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sso",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sso-1.104.0-0.6.21.jar",
          "url": "sso-1.104.0-0.6.21.jar",
          "size": 46898,
          "sha512": "da3c9cdac02ccd343684e677b361cb37c73ae9c1403c90afd36dc4a8f374c8ae72a92bb9bb1eae5e15f6bdcf9c495f6fc734238da77bbb2b1cd07e5b76a3d9f9",
          "sha256": "5cb668957b4d228f8aae7ea99fb4208d5e7ab4b3c81e2feb31340e37f2ab0dc",
          "sha1": "ee60ca6be1bdfb4df14f89cd44f9a9f53cbb6621",
          "md5": "af2c09f6a55bc04e5f37a41597da0740"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sso",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sso-1.104.0-0.6.21.jar",
          "url": "sso-1.104.0-0.6.21.jar",
          "size": 46898,
          "sha512": "da3c9cdac02ccd343684e677b361cb37c73ae9c1403c90afd36dc4a8f374c8ae72a92bb9bb1eae5e15f6bdcf9c495f6fc734238da77bbb2b1cd07e5b76a3d9f9",
          "sha256": "5cb668957b4d228f8aae7ea99fb4208d5e7ab4b3c81e2feb31340e37f2ab0dc",
          "sha1": "ee60ca6be1bdfb4df14f89cd44f9a9f53cbb6621",
          "md5": "af2c09f6a55bc04e5f37a41597da0740"
        }
      ]
    }
  ]
}
