{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "logs-destinations",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "logs-destinations",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kinesis",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "logs-destinations-1.116.0-0.6.21.jar",
          "url": "logs-destinations-1.116.0-0.6.21.jar",
          "size": 5540,
          "sha512": "88325019275b8f3913551c4d144ec606806b7c8e0b29ea75320a79dac75a5fa3d0dfb39f38426bcba98e05f3413fd635a873ab056dd0f4533b8d0b0f2eb5c145",
          "sha256": "e43fe76b14a0072ce347dc963d613518f6f5bfb36be8c7e54435ecf7d3b448cc",
          "sha1": "67c963ae97097cd02638e92e3d9ad3648c8d9118",
          "md5": "1ad55306a3aadb5d313ece6ba359b5b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "logs-destinations",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kinesis",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "logs-destinations-1.116.0-0.6.21.jar",
          "url": "logs-destinations-1.116.0-0.6.21.jar",
          "size": 5540,
          "sha512": "88325019275b8f3913551c4d144ec606806b7c8e0b29ea75320a79dac75a5fa3d0dfb39f38426bcba98e05f3413fd635a873ab056dd0f4533b8d0b0f2eb5c145",
          "sha256": "e43fe76b14a0072ce347dc963d613518f6f5bfb36be8c7e54435ecf7d3b448cc",
          "sha1": "67c963ae97097cd02638e92e3d9ad3648c8d9118",
          "md5": "1ad55306a3aadb5d313ece6ba359b5b0"
        }
      ]
    }
  ]
}
