{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticloadbalancingv2",
    "version": "1.64.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "certificatemanager",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "elasticloadbalancingv2-1.64.0-0.6.22.jar",
          "url": "elasticloadbalancingv2-1.64.0-0.6.22.jar",
          "size": 584342,
          "sha512": "5591f83ffa5f75dfadbb1174d7bb5501c9ecc41a07c076667eef983cd5e1e243a7d4665d95a51dbbda92bdc929a50cdebfe734d9810179bda74e8e1a95616e73",
          "sha256": "528f007d5e8be0b01f07ecfc61677c9e72d809350a4a1f193d1f388c5854de02",
          "sha1": "44e71a908675d69868f9bb2f671190fbc0be6f2a",
          "md5": "7957ec4c654107e4b1b6c986542c6fb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "certificatemanager",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "elasticloadbalancingv2-1.64.0-0.6.22.jar",
          "url": "elasticloadbalancingv2-1.64.0-0.6.22.jar",
          "size": 584342,
          "sha512": "5591f83ffa5f75dfadbb1174d7bb5501c9ecc41a07c076667eef983cd5e1e243a7d4665d95a51dbbda92bdc929a50cdebfe734d9810179bda74e8e1a95616e73",
          "sha256": "528f007d5e8be0b01f07ecfc61677c9e72d809350a4a1f193d1f388c5854de02",
          "sha1": "44e71a908675d69868f9bb2f671190fbc0be6f2a",
          "md5": "7957ec4c654107e4b1b6c986542c6fb0"
        }
      ]
    }
  ]
}
