{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codeguruprofiler",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codeguruprofiler",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codeguruprofiler-1.111.0-0.6.21.jar",
          "url": "codeguruprofiler-1.111.0-0.6.21.jar",
          "size": 30619,
          "sha512": "8707d45fde4240aecf1d85386687e7c99bf7841ad69b7be91e756ebc40e26e35c13c0f644ea12df57f3da82f73047d840a09fff8cfc3d98223d1728614e97ad",
          "sha256": "188ea4ce127b50131e5751208c6ac325594e5aa689fdc198ca36c0837bd5814b",
          "sha1": "137fc57e5491972a258e1b06ea410a5f216abc04",
          "md5": "7a166caf1586f06cda82bb8a0f3dc127"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codeguruprofiler",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codeguruprofiler-1.111.0-0.6.21.jar",
          "url": "codeguruprofiler-1.111.0-0.6.21.jar",
          "size": 30619,
          "sha512": "8707d45fde4240aecf1d85386687e7c99bf7841ad69b7be91e756ebc40e26e35c13c0f644ea12df57f3da82f73047d840a09fff8cfc3d98223d1728614e97ad",
          "sha256": "188ea4ce127b50131e5751208c6ac325594e5aa689fdc198ca36c0837bd5814b",
          "sha1": "137fc57e5491972a258e1b06ea410a5f216abc04",
          "md5": "7a166caf1586f06cda82bb8a0f3dc127"
        }
      ]
    }
  ]
}
