{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "appstream",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "pksuzuox3ne6pgnvsva7g32w2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "appstream",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appstream-1.110.1-0.6.21.jar",
          "url": "appstream-1.110.1-0.6.21.jar",
          "size": 234560,
          "sha512": "6ff71b142edd6b5e08123e83eaaf1f97eb3c9aadcb8724b2a1442f16c69d81e23e4bae18a8509c9b9f78eb0e3f44a24839b31964263ce091f1cc8efde0382c32",
          "sha256": "73105f6962b175fd040b233a0a0ca90587cc135b1c7cb1c8b17e3dc98948ea2",
          "sha1": "4b16e0c75eaf858078194a7989c43c4d41f0858b",
          "md5": "3b340cc40424467ca9f06a1541140add"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "appstream",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appstream-1.110.1-0.6.21.jar",
          "url": "appstream-1.110.1-0.6.21.jar",
          "size": 234560,
          "sha512": "6ff71b142edd6b5e08123e83eaaf1f97eb3c9aadcb8724b2a1442f16c69d81e23e4bae18a8509c9b9f78eb0e3f44a24839b31964263ce091f1cc8efde0382c32",
          "sha256": "73105f6962b175fd040b233a0a0ca90587cc135b1c7cb1c8b17e3dc98948ea2",
          "sha1": "4b16e0c75eaf858078194a7989c43c4d41f0858b",
          "md5": "3b340cc40424467ca9f06a1541140add"
        }
      ]
    }
  ]
}
