{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-cloud-assembly-schema",
    "version": "1.101.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "d5vusioiqzbnxk6vuwjeusvgpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.101.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cloud-assembly-schema-1.101.0-0.6.21.jar",
          "url": "cdk-cloud-assembly-schema-1.101.0-0.6.21.jar",
          "size": 142472,
          "sha512": "8984c6cc2d059c00f38750fedbb3a12b61604052115a1f1d5c14e6f4eef31ae6a2bb816c6abaf3bb7af17053622d9d2d54381539109f68f3f4d9e80782096826",
          "sha256": "3a51af6eefda88d7bdfd889c8ce92817fe3f55333a756ad6a2eeaa4f2d86e196",
          "sha1": "cce9515bc1bfc314d0b05b645887575c268b3ac3",
          "md5": "d697d5e38eaf91b0a260595de8e04452"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.101.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cloud-assembly-schema-1.101.0-0.6.21.jar",
          "url": "cdk-cloud-assembly-schema-1.101.0-0.6.21.jar",
          "size": 142472,
          "sha512": "8984c6cc2d059c00f38750fedbb3a12b61604052115a1f1d5c14e6f4eef31ae6a2bb816c6abaf3bb7af17053622d9d2d54381539109f68f3f4d9e80782096826",
          "sha256": "3a51af6eefda88d7bdfd889c8ce92817fe3f55333a756ad6a2eeaa4f2d86e196",
          "sha1": "cce9515bc1bfc314d0b05b645887575c268b3ac3",
          "md5": "d697d5e38eaf91b0a260595de8e04452"
        }
      ]
    }
  ]
}
