{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "opsworks",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "opsworks",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "opsworks-1.114.0-0.6.21.jar",
          "url": "opsworks-1.114.0-0.6.21.jar",
          "size": 465564,
          "sha512": "225da55dc356c5f52598aca2953922d1e3c3c87b639ac75c69200685e0bbe4d3390f3b04306a94550bc8696daea1bb4bc94a08eebc6c51193a900bd1c570bb85",
          "sha256": "8d68d86913b53c55ca7ecf0bb4cc0370640d160471472cf26977f126ac505823",
          "sha1": "9e7eeeeac225153a08c9f32c42c714955f3c58bf",
          "md5": "3ab8dc1af7351039464f07582b33d508"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "opsworks",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "opsworks-1.114.0-0.6.21.jar",
          "url": "opsworks-1.114.0-0.6.21.jar",
          "size": 465564,
          "sha512": "225da55dc356c5f52598aca2953922d1e3c3c87b639ac75c69200685e0bbe4d3390f3b04306a94550bc8696daea1bb4bc94a08eebc6c51193a900bd1c570bb85",
          "sha256": "8d68d86913b53c55ca7ecf0bb4cc0370640d160471472cf26977f126ac505823",
          "sha1": "9e7eeeeac225153a08c9f32c42c714955f3c58bf",
          "md5": "3ab8dc1af7351039464f07582b33d508"
        }
      ]
    }
  ]
}
