{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "networkmanager",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "networkmanager",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "networkmanager-1.116.0-0.6.21.jar",
          "url": "networkmanager-1.116.0-0.6.21.jar",
          "size": 92799,
          "sha512": "3ee0886c52148166ea18420d500e04ebcbcc5a99924991e3ff3d6ad69b4d903320514f7132ed09412518fea95abc8262f40068148643a02874bc8a505b773ec8",
          "sha256": "459e342f91cedc85d9bbfe383525814ace3728e2b36ed7a88083e4196b43aed2",
          "sha1": "6407449e2cf88ad8454f96ff31a27f0bf2d15350",
          "md5": "8120b55a1284593e4acb0ca23bdc96e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "networkmanager",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "networkmanager-1.116.0-0.6.21.jar",
          "url": "networkmanager-1.116.0-0.6.21.jar",
          "size": 92799,
          "sha512": "3ee0886c52148166ea18420d500e04ebcbcc5a99924991e3ff3d6ad69b4d903320514f7132ed09412518fea95abc8262f40068148643a02874bc8a505b773ec8",
          "sha256": "459e342f91cedc85d9bbfe383525814ace3728e2b36ed7a88083e4196b43aed2",
          "sha1": "6407449e2cf88ad8454f96ff31a27f0bf2d15350",
          "md5": "8120b55a1284593e4acb0ca23bdc96e3"
        }
      ]
    }
  ]
}
