{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "emrcontainers",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "emrcontainers",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emrcontainers-1.104.0-0.6.21.jar",
          "url": "emrcontainers-1.104.0-0.6.21.jar",
          "size": 38490,
          "sha512": "4e7571a33e427daa5990578ebb39f1115b46677692e7f2c3936fa31406c0583bd568f698f28fde6029f01009373a4d1722a1bf58db046950ce494734752f3e3a",
          "sha256": "5f3ec67a143c0a44ef8d38a081a3348c6e81acc8925d3174d6fbf8ec215f2682",
          "sha1": "ea70b2d1ef3dfd213b1c5609121e9bb4dd8e91c5",
          "md5": "a60fda039df5fdae435abf1530772011"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "emrcontainers",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emrcontainers-1.104.0-0.6.21.jar",
          "url": "emrcontainers-1.104.0-0.6.21.jar",
          "size": 38490,
          "sha512": "4e7571a33e427daa5990578ebb39f1115b46677692e7f2c3936fa31406c0583bd568f698f28fde6029f01009373a4d1722a1bf58db046950ce494734752f3e3a",
          "sha256": "5f3ec67a143c0a44ef8d38a081a3348c6e81acc8925d3174d6fbf8ec215f2682",
          "sha1": "ea70b2d1ef3dfd213b1c5609121e9bb4dd8e91c5",
          "md5": "a60fda039df5fdae435abf1530772011"
        }
      ]
    }
  ]
}
