{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "medialive",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "medialive",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "medialive-1.103.0-0.6.21.jar",
          "url": "medialive-1.103.0-0.6.21.jar",
          "size": 1423506,
          "sha512": "f837dff8b0e844871ba35d8c3b845ed836d13bc94620617e787b5b4a151d670374f44f1bd2eecca9f4c0f66797a635439627320ee0befa49be55c4b396c737a",
          "sha256": "b359aa8b9c706722b924f8308c7e9f74a6753181c005f79d7af3937cb7000cbe",
          "sha1": "e625bb5a405fa318a05143f03610fdbd71fe9f80",
          "md5": "ad6971cf2429635031d3402aa4575764"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "medialive",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "medialive-1.103.0-0.6.21.jar",
          "url": "medialive-1.103.0-0.6.21.jar",
          "size": 1423506,
          "sha512": "f837dff8b0e844871ba35d8c3b845ed836d13bc94620617e787b5b4a151d670374f44f1bd2eecca9f4c0f66797a635439627320ee0befa49be55c4b396c737a",
          "sha256": "b359aa8b9c706722b924f8308c7e9f74a6753181c005f79d7af3937cb7000cbe",
          "sha1": "e625bb5a405fa318a05143f03610fdbd71fe9f80",
          "md5": "ad6971cf2429635031d3402aa4575764"
        }
      ]
    }
  ]
}
