{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotanalytics",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotanalytics",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotanalytics-1.107.0-0.6.21.jar",
          "url": "iotanalytics-1.107.0-0.6.21.jar",
          "size": 472814,
          "sha512": "482804c72d4f126dc2afdbc1482bc01a3bbb1971d0a8031827cc3d0cbb6cdcf25301537c612046a01f784608b21ab7ba1ff8313424137a0b81ab39e7b4409f49",
          "sha256": "656aa6b38cd3a026b3293553f27d43ae65cc68f1a9074e087c1a2d4aa3cb69c8",
          "sha1": "67a89b3581c776a5799260ce0cf7c0948c3977b7",
          "md5": "bad88981d4d957f311a2e7398bbd6be0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotanalytics",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotanalytics-1.107.0-0.6.21.jar",
          "url": "iotanalytics-1.107.0-0.6.21.jar",
          "size": 472814,
          "sha512": "482804c72d4f126dc2afdbc1482bc01a3bbb1971d0a8031827cc3d0cbb6cdcf25301537c612046a01f784608b21ab7ba1ff8313424137a0b81ab39e7b4409f49",
          "sha256": "656aa6b38cd3a026b3293553f27d43ae65cc68f1a9074e087c1a2d4aa3cb69c8",
          "sha1": "67a89b3581c776a5799260ce0cf7c0948c3977b7",
          "md5": "bad88981d4d957f311a2e7398bbd6be0"
        }
      ]
    }
  ]
}
