{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "applicationinsights",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "applicationinsights",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "applicationinsights-1.114.0-0.6.21.jar",
          "url": "applicationinsights-1.114.0-0.6.21.jar",
          "size": 177351,
          "sha512": "d9626e27d9e4ef27f50e23c8aff76152bb77f419c87e3417f3a3ab3fc2eddcd9bc2cf3b782674801df2b0e72c4c0c1626568d89bdbd101852680a2282b17d920",
          "sha256": "c3be4bb2a584cc1eef99184845deb33f32459af8d90bb553048a3117c99b2a8b",
          "sha1": "ae58a3b1d93589d630e3e53587c5cc98ff3d4bd2",
          "md5": "dc8e8c4631dcc899818637f5160a82c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "applicationinsights",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "applicationinsights-1.114.0-0.6.21.jar",
          "url": "applicationinsights-1.114.0-0.6.21.jar",
          "size": 177351,
          "sha512": "d9626e27d9e4ef27f50e23c8aff76152bb77f419c87e3417f3a3ab3fc2eddcd9bc2cf3b782674801df2b0e72c4c0c1626568d89bdbd101852680a2282b17d920",
          "sha256": "c3be4bb2a584cc1eef99184845deb33f32459af8d90bb553048a3117c99b2a8b",
          "sha1": "ae58a3b1d93589d630e3e53587c5cc98ff3d4bd2",
          "md5": "dc8e8c4631dcc899818637f5160a82c5"
        }
      ]
    }
  ]
}
