{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "s3objectlambda",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "s3objectlambda",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "s3objectlambda-1.102.0-0.6.21.jar",
          "url": "s3objectlambda-1.102.0-0.6.21.jar",
          "size": 42840,
          "sha512": "e21c50f790b9207bbb524b76dc8dc3ff76fb2dead31452ce57cd8d3c4a6464f79557bf3959911fd347570f24effee30f6c87304e1a3b85507f44e37c65c42f55",
          "sha256": "1f1fd66a04aa48e5be39c0a7e145e0a9b75df0285f75cea1edd6889b19d84125",
          "sha1": "d6a42885e045ffd2432d5edefc310a389231c5dd",
          "md5": "d2c93a283b60f91fc96720e0b8486d91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "s3objectlambda",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "s3objectlambda-1.102.0-0.6.21.jar",
          "url": "s3objectlambda-1.102.0-0.6.21.jar",
          "size": 42840,
          "sha512": "e21c50f790b9207bbb524b76dc8dc3ff76fb2dead31452ce57cd8d3c4a6464f79557bf3959911fd347570f24effee30f6c87304e1a3b85507f44e37c65c42f55",
          "sha256": "1f1fd66a04aa48e5be39c0a7e145e0a9b75df0285f75cea1edd6889b19d84125",
          "sha1": "d6a42885e045ffd2432d5edefc310a389231c5dd",
          "md5": "d2c93a283b60f91fc96720e0b8486d91"
        }
      ]
    }
  ]
}
