{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lookoutvision",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lookoutvision",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lookoutvision-1.102.0-0.6.21.jar",
          "url": "lookoutvision-1.102.0-0.6.21.jar",
          "size": 8632,
          "sha512": "f16c34d36c710e3d892896fe902114577ae1ed95f7767df492cb35e9b0efb7bb5f48439e28ae1be89610c8163d3f674b31ce80e93faba8944615af77e1da4ef3",
          "sha256": "41ba56f20fb5333cb06585c688a4826fc45db8656a8b7113e59f53c76ee0ca9",
          "sha1": "ce72bf3b4e578d4a52d89cdf7430aa9b674feccd",
          "md5": "c74a4cdc2449f0415d5dfc2e6d498638"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lookoutvision",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lookoutvision-1.102.0-0.6.21.jar",
          "url": "lookoutvision-1.102.0-0.6.21.jar",
          "size": 8632,
          "sha512": "f16c34d36c710e3d892896fe902114577ae1ed95f7767df492cb35e9b0efb7bb5f48439e28ae1be89610c8163d3f674b31ce80e93faba8944615af77e1da4ef3",
          "sha256": "41ba56f20fb5333cb06585c688a4826fc45db8656a8b7113e59f53c76ee0ca9",
          "sha1": "ce72bf3b4e578d4a52d89cdf7430aa9b674feccd",
          "md5": "c74a4cdc2449f0415d5dfc2e6d498638"
        }
      ]
    }
  ]
}
