{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "waf",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "waf",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "waf-1.108.1-0.6.21.jar",
          "url": "waf-1.108.1-0.6.21.jar",
          "size": 188896,
          "sha512": "cc9abf974649512f39cc91cb43dea4386f375f9a32569622022cde7f0ef6916a9712bc9f97fa5972ea02e956283a9335d6ac5a5e251635caef32999e7a770b59",
          "sha256": "906b72d466a7727acf6b89adad3cd29b90522611a45a46cca8ecd9ab81f6b5d",
          "sha1": "83feb0f513deafdc600ce286b20564109ef8194f",
          "md5": "272dfc67020761983456bb0573efb8dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "waf",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "waf-1.108.1-0.6.21.jar",
          "url": "waf-1.108.1-0.6.21.jar",
          "size": 188896,
          "sha512": "cc9abf974649512f39cc91cb43dea4386f375f9a32569622022cde7f0ef6916a9712bc9f97fa5972ea02e956283a9335d6ac5a5e251635caef32999e7a770b59",
          "sha256": "906b72d466a7727acf6b89adad3cd29b90522611a45a46cca8ecd9ab81f6b5d",
          "sha1": "83feb0f513deafdc600ce286b20564109ef8194f",
          "md5": "272dfc67020761983456bb0573efb8dc"
        }
      ]
    }
  ]
}
