{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "securityhub",
    "version": "1.100.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "smkqp7thvbfexba6catfwegxzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "securityhub",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "securityhub-1.100.0-0.6.21.jar",
          "url": "securityhub-1.100.0-0.6.21.jar",
          "size": 8521,
          "sha512": "50841960527a0d6457007ea96877f093ff2d9989cdcd9b2e289e28ee6b25a4a2bfa8f61ceb7c5f16c844c334b5a38d01361b089087deb759d97133638dda5db8",
          "sha256": "c376bff585dd6ed2146926c87a8f9ef4b52a76b5d4e549249e1128ec94b0dfa5",
          "sha1": "10dac769be1a611ad3403ab8e97d45eecbabac26",
          "md5": "e96f835b6d2127dd31b88a288f7cadb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "securityhub",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "securityhub-1.100.0-0.6.21.jar",
          "url": "securityhub-1.100.0-0.6.21.jar",
          "size": 8521,
          "sha512": "50841960527a0d6457007ea96877f093ff2d9989cdcd9b2e289e28ee6b25a4a2bfa8f61ceb7c5f16c844c334b5a38d01361b089087deb759d97133638dda5db8",
          "sha256": "c376bff585dd6ed2146926c87a8f9ef4b52a76b5d4e549249e1128ec94b0dfa5",
          "sha1": "10dac769be1a611ad3403ab8e97d45eecbabac26",
          "md5": "e96f835b6d2127dd31b88a288f7cadb5"
        }
      ]
    }
  ]
}
