{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cassandra",
    "version": "1.117.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ka4pthfoybhvvnwbwaxmu2dbry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cassandra",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cassandra-1.117.0-0.6.21.jar",
          "url": "cassandra-1.117.0-0.6.21.jar",
          "size": 96264,
          "sha512": "988bf96eb14b932a7c0d09fc19b10dab06f5b0b59c341639d3538f302b0820ee741cb7dd34934ff31a41ab0876113566a71348a7ea4247f9130d15a4bc4a74fc",
          "sha256": "af231399f26afa29c22f030570484b454459e377a11b1bdd175e387d9a5af37e",
          "sha1": "182a49d6a1f76401203bc11ed34ff95f520fbc33",
          "md5": "4629e5d0cf7cff062e3a4bab0b3a6c80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cassandra",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cassandra-1.117.0-0.6.21.jar",
          "url": "cassandra-1.117.0-0.6.21.jar",
          "size": 96264,
          "sha512": "988bf96eb14b932a7c0d09fc19b10dab06f5b0b59c341639d3538f302b0820ee741cb7dd34934ff31a41ab0876113566a71348a7ea4247f9130d15a4bc4a74fc",
          "sha256": "af231399f26afa29c22f030570484b454459e377a11b1bdd175e387d9a5af37e",
          "sha1": "182a49d6a1f76401203bc11ed34ff95f520fbc33",
          "md5": "4629e5d0cf7cff062e3a4bab0b3a6c80"
        }
      ]
    }
  ]
}
