{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "budgets",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "k23roxkwqjbs5i6arr4lg4r4xm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "budgets",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "budgets-1.110.1-0.6.21.jar",
          "url": "budgets-1.110.1-0.6.21.jar",
          "size": 190263,
          "sha512": "3a5f04764f5d6a2aa6fb7d391ee33d0360fae30e54a5d21a4778910f43f47caffcc7d5dd98fa7ab42dbd99d06a089e30ebacb053b0d3f5a256969851e631bac2",
          "sha256": "5aafd9400b44445b4d3209763140d97f3ef451ea72729868a4c69a5ee5732f6a",
          "sha1": "715035ecbb3299de62848f51f5781579ff54fec4",
          "md5": "b6c7d47d57807d155475c399786ba630"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "budgets",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "budgets-1.110.1-0.6.21.jar",
          "url": "budgets-1.110.1-0.6.21.jar",
          "size": 190263,
          "sha512": "3a5f04764f5d6a2aa6fb7d391ee33d0360fae30e54a5d21a4778910f43f47caffcc7d5dd98fa7ab42dbd99d06a089e30ebacb053b0d3f5a256969851e631bac2",
          "sha256": "5aafd9400b44445b4d3209763140d97f3ef451ea72729868a4c69a5ee5732f6a",
          "sha1": "715035ecbb3299de62848f51f5781579ff54fec4",
          "md5": "b6c7d47d57807d155475c399786ba630"
        }
      ]
    }
  ]
}
