{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestarconnections",
    "version": "1.64.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestarconnections",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "codestarconnections-1.64.0-0.6.22.jar",
          "url": "codestarconnections-1.64.0-0.6.22.jar",
          "size": 9594,
          "sha512": "ec279b16b4789ebee55c50575130e200c91ed589f13fca3c66073e1ff87e735c9740a58ea5981e4b12c0b31fadcb46d9a51b65119165566b7e27c7411965fdee",
          "sha256": "9bfe59919cc56374ef58f2a7a99483ad11b579ccc306514011969f4d17e939da",
          "sha1": "a29745e231ce4b147d5f22ad35119fe70097541b",
          "md5": "7d26596e63c8457c2c51b5c56b3c592f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestarconnections",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "codestarconnections-1.64.0-0.6.22.jar",
          "url": "codestarconnections-1.64.0-0.6.22.jar",
          "size": 9594,
          "sha512": "ec279b16b4789ebee55c50575130e200c91ed589f13fca3c66073e1ff87e735c9740a58ea5981e4b12c0b31fadcb46d9a51b65119165566b7e27c7411965fdee",
          "sha256": "9bfe59919cc56374ef58f2a7a99483ad11b579ccc306514011969f4d17e939da",
          "sha1": "a29745e231ce4b147d5f22ad35119fe70097541b",
          "md5": "7d26596e63c8457c2c51b5c56b3c592f"
        }
      ]
    }
  ]
}
