{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-region-info",
    "version": "1.100.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "smkqp7thvbfexba6catfwegxzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.100.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-region-info-1.100.0-0.6.21.jar",
          "url": "cdk-region-info-1.100.0-0.6.21.jar",
          "size": 432,
          "sha512": "20e611799820fb2e32cc20c2b4ab86c0dae65fbe8416e877e882364b98ba247ef573f764fd48890f685ebd558a684e60260629872cb430644a5e97488a62ee2b",
          "sha256": "592228275195aa3ff46e110df77e6d61d4f426def5c39eed799e187332c7ecf7",
          "sha1": "60205a6d21e98b1099fae56af0bbf0ff27ae9722",
          "md5": "fd57c50011843bdff80a08b6748a1520"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.100.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-region-info-1.100.0-0.6.21.jar",
          "url": "cdk-region-info-1.100.0-0.6.21.jar",
          "size": 432,
          "sha512": "20e611799820fb2e32cc20c2b4ab86c0dae65fbe8416e877e882364b98ba247ef573f764fd48890f685ebd558a684e60260629872cb430644a5e97488a62ee2b",
          "sha256": "592228275195aa3ff46e110df77e6d61d4f426def5c39eed799e187332c7ecf7",
          "sha1": "60205a6d21e98b1099fae56af0bbf0ff27ae9722",
          "md5": "fd57c50011843bdff80a08b6748a1520"
        }
      ]
    }
  ]
}
