{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "wafv2",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "wafv2",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "wafv2-1.103.0-0.6.21.jar",
          "url": "wafv2-1.103.0-0.6.21.jar",
          "size": 695752,
          "sha512": "68feff27da322a2439649cc622bf353a5ece605cae3b7954beb576c34abe6adb9997fd66da11bd12b9bf26924292a22021b63df080fdefa85c4afc3b189aa155",
          "sha256": "ea1a22f5c31650ea4db97d8decf1988c1b7043fc48a5176abe4523af55333e85",
          "sha1": "20ee6f53e73895a020e864b7075e6bb731e35f06",
          "md5": "11de34a1b971c11a01f3508569be8c4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "wafv2",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "wafv2-1.103.0-0.6.21.jar",
          "url": "wafv2-1.103.0-0.6.21.jar",
          "size": 695752,
          "sha512": "68feff27da322a2439649cc622bf353a5ece605cae3b7954beb576c34abe6adb9997fd66da11bd12b9bf26924292a22021b63df080fdefa85c4afc3b189aa155",
          "sha256": "ea1a22f5c31650ea4db97d8decf1988c1b7043fc48a5176abe4523af55333e85",
          "sha1": "20ee6f53e73895a020e864b7075e6bb731e35f06",
          "md5": "11de34a1b971c11a01f3508569be8c4a"
        }
      ]
    }
  ]
}
