{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotfleethub",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotfleethub",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotfleethub-1.108.0-0.6.21.jar",
          "url": "iotfleethub-1.108.0-0.6.21.jar",
          "size": 9519,
          "sha512": "490fa295d28c46a425a3b69ebeac9a135704febf48aabd6d12456732cdd379c700c6b981a1ca362dd4cc853c3ea533364f0126eae419bba4c2d9dec78a150a14",
          "sha256": "546f4932645b9b75a66969ccc0405e4641c57508117ea72b56b13631edd7bd2b",
          "sha1": "e9928083fdf69c43f4b67fa985c8e950f25eb2ab",
          "md5": "9e75b23b8ea6da606bc28005e48be2ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotfleethub",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotfleethub-1.108.0-0.6.21.jar",
          "url": "iotfleethub-1.108.0-0.6.21.jar",
          "size": 9519,
          "sha512": "490fa295d28c46a425a3b69ebeac9a135704febf48aabd6d12456732cdd379c700c6b981a1ca362dd4cc853c3ea533364f0126eae419bba4c2d9dec78a150a14",
          "sha256": "546f4932645b9b75a66969ccc0405e4641c57508117ea72b56b13631edd7bd2b",
          "sha1": "e9928083fdf69c43f4b67fa985c8e950f25eb2ab",
          "md5": "9e75b23b8ea6da606bc28005e48be2ce"
        }
      ]
    }
  ]
}
