{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-yaml-cfn",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-yaml-cfn",
          "version": {
            "requires": "1.116.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-yaml-cfn-1.116.0-0.6.21.jar",
          "url": "cdk-yaml-cfn-1.116.0-0.6.21.jar",
          "size": 426,
          "sha512": "3d2a6c7734e40ba4e5b3bd2eb20a55c154f07046e62b6207675f4773f2823e10a7294edef79d0f876abc11e646b8ce66e3f37aa0435b5df789a04d20a44b3042",
          "sha256": "b218b0624c9d1935a83131fda0aac6565b339c0cd1059b1a073788d30a6a1ee9",
          "sha1": "431d8a8b6133451495f2440b0d0376756406da06",
          "md5": "a41ff45a1662c51e9941d53f1cdb30bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-yaml-cfn",
          "version": {
            "requires": "1.116.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-yaml-cfn-1.116.0-0.6.21.jar",
          "url": "cdk-yaml-cfn-1.116.0-0.6.21.jar",
          "size": 426,
          "sha512": "3d2a6c7734e40ba4e5b3bd2eb20a55c154f07046e62b6207675f4773f2823e10a7294edef79d0f876abc11e646b8ce66e3f37aa0435b5df789a04d20a44b3042",
          "sha256": "b218b0624c9d1935a83131fda0aac6565b339c0cd1059b1a073788d30a6a1ee9",
          "sha1": "431d8a8b6133451495f2440b0d0376756406da06",
          "md5": "a41ff45a1662c51e9941d53f1cdb30bb"
        }
      ]
    }
  ]
}
