{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-assets",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-1.108.1-0.6.21.jar",
          "url": "cdk-assets-1.108.1-0.6.21.jar",
          "size": 16455,
          "sha512": "9ba156ee290eaaeca0f4f27fd23cbe104cd756ccdd19e6934d4343e5c9671697dea0065686c9c4f177aebb51f00b07c115a6c4238acc13dc118d0cd4abf51a05",
          "sha256": "bab947ebe2aa562e21c29744fedbaca5fc79948d6b7005488d86e4511a228ac",
          "sha1": "d1b1de0aef1be70f75b8e49bf9d1e508b91ca0b5",
          "md5": "a6b07dea9e0fb24354c8ac04250bb090"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-1.108.1-0.6.21.jar",
          "url": "cdk-assets-1.108.1-0.6.21.jar",
          "size": 16455,
          "sha512": "9ba156ee290eaaeca0f4f27fd23cbe104cd756ccdd19e6934d4343e5c9671697dea0065686c9c4f177aebb51f00b07c115a6c4238acc13dc118d0cd4abf51a05",
          "sha256": "bab947ebe2aa562e21c29744fedbaca5fc79948d6b7005488d86e4511a228ac",
          "sha1": "d1b1de0aef1be70f75b8e49bf9d1e508b91ca0b5",
          "md5": "a6b07dea9e0fb24354c8ac04250bb090"
        }
      ]
    }
  ]
}
