{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "managedblockchain",
    "version": "1.31.0-unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "managedblockchain",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "managedblockchain-1.31.0-unspecified.jar",
          "url": "managedblockchain-1.31.0-unspecified.jar",
          "size": 105036,
          "sha512": "a6b0ced56e5e4c8601529a7c1eb769e205a830cc80f2949455f28d847cfb2203985725d48866e4a9d019795329ad806bf689064e45cc0548b7f7f46bc7658671",
          "sha256": "e25573fc505584732f625e610c6f7ace09211bd1926a11290e76c31602e38438",
          "sha1": "5c95b8df6dc90964e6d626590e1b6925d948df00",
          "md5": "1a759d6746497cdeca42639b94bb4f11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "managedblockchain",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "managedblockchain-1.31.0-unspecified.jar",
          "url": "managedblockchain-1.31.0-unspecified.jar",
          "size": 105036,
          "sha512": "a6b0ced56e5e4c8601529a7c1eb769e205a830cc80f2949455f28d847cfb2203985725d48866e4a9d019795329ad806bf689064e45cc0548b7f7f46bc7658671",
          "sha256": "e25573fc505584732f625e610c6f7ace09211bd1926a11290e76c31602e38438",
          "sha1": "5c95b8df6dc90964e6d626590e1b6925d948df00",
          "md5": "1a759d6746497cdeca42639b94bb4f11"
        }
      ]
    }
  ]
}
