{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "appmesh",
    "version": "1.34.1-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "appmesh",
          "version": {
            "requires": "1.34.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.34.1-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.34.1-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "servicediscovery",
          "version": {
            "requires": "1.34.1-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.1-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "appmesh-1.34.1-0.6.22.jar",
          "url": "appmesh-1.34.1-0.6.22.jar",
          "size": 587529,
          "sha512": "384be28ad9a48d03050e52839d0a8a07dee666dfae98e1e02a51ba595412514d932191b1f3d339c2eeee244d3aca246cd3f018c05627d9130b533e1de8bad836",
          "sha256": "661f9cbe4c77678557ed1b99eac710721db6fec935bc238b4df1e341522c65ea",
          "sha1": "9dcddae2d42f8ef3f263b2021cbe8c08f06a5cda",
          "md5": "d220ced4db43631cefe5393f3e302aae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.34.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "appmesh",
          "version": {
            "requires": "1.34.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.34.1-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.34.1-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "servicediscovery",
          "version": {
            "requires": "1.34.1-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.1-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "appmesh-1.34.1-0.6.22.jar",
          "url": "appmesh-1.34.1-0.6.22.jar",
          "size": 587529,
          "sha512": "384be28ad9a48d03050e52839d0a8a07dee666dfae98e1e02a51ba595412514d932191b1f3d339c2eeee244d3aca246cd3f018c05627d9130b533e1de8bad836",
          "sha256": "661f9cbe4c77678557ed1b99eac710721db6fec935bc238b4df1e341522c65ea",
          "sha1": "9dcddae2d42f8ef3f263b2021cbe8c08f06a5cda",
          "md5": "d220ced4db43631cefe5393f3e302aae"
        }
      ]
    }
  ]
}
