{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "dms",
    "version": "1.110.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cnrjfrtzdvad5bhmsg7msamtuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "dms",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dms-1.110.0-0.6.21.jar",
          "url": "dms-1.110.0-0.6.21.jar",
          "size": 285915,
          "sha512": "d2b2227eb6573e3768219de328daae72c9b08743469d583f0259c3a62a67a6d5fb94699b227dd0334582c8377397262c77f399d805c562deba2f3a1b66bc499e",
          "sha256": "fed77ceeecd73719e315dd5a88032f525a7d27838bd8786413c9f29ec6596377",
          "sha1": "cdcc16942d82541a42115fb2b2bf8570873bc1e4",
          "md5": "1fe1828656e9c926f6a7212abe888fa1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "dms",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dms-1.110.0-0.6.21.jar",
          "url": "dms-1.110.0-0.6.21.jar",
          "size": 285915,
          "sha512": "d2b2227eb6573e3768219de328daae72c9b08743469d583f0259c3a62a67a6d5fb94699b227dd0334582c8377397262c77f399d805c562deba2f3a1b66bc499e",
          "sha256": "fed77ceeecd73719e315dd5a88032f525a7d27838bd8786413c9f29ec6596377",
          "sha1": "cdcc16942d82541a42115fb2b2bf8570873bc1e4",
          "md5": "1fe1828656e9c926f6a7212abe888fa1"
        }
      ]
    }
  ]
}
