{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "dynamodb-global",
    "version": "1.106.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "apa3jttzlbgsjbklj7vcehaque"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "dynamodb-global",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dynamodb",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamodb-global-1.106.1-0.6.21.jar",
          "url": "dynamodb-global-1.106.1-0.6.21.jar",
          "size": 15701,
          "sha512": "1da0f0f1c077da6f3251866618b09c1319290232af2e3ed17a18afe662ecf1ff21420f047ad324741ecbfa37b6077019a7b6d1767fe8d8e336130ac98bb0865",
          "sha256": "8dcda63d05a1d99617f691ee4d65da5faeb939422416232a3d2f29b520df33ca",
          "sha1": "7a88ef21b7dadcfe6780a72c72fcdcf02d1d22b5",
          "md5": "ecf140f15a0c7734157e79e14a78eff4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "dynamodb-global",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dynamodb",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamodb-global-1.106.1-0.6.21.jar",
          "url": "dynamodb-global-1.106.1-0.6.21.jar",
          "size": 15701,
          "sha512": "1da0f0f1c077da6f3251866618b09c1319290232af2e3ed17a18afe662ecf1ff21420f047ad324741ecbfa37b6077019a7b6d1767fe8d8e336130ac98bb0865",
          "sha256": "8dcda63d05a1d99617f691ee4d65da5faeb939422416232a3d2f29b520df33ca",
          "sha1": "7a88ef21b7dadcfe6780a72c72fcdcf02d1d22b5",
          "md5": "ecf140f15a0c7734157e79e14a78eff4"
        }
      ]
    }
  ]
}
