{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestarconnections",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestarconnections",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarconnections-1.99.0-0.6.21.jar",
          "url": "codestarconnections-1.99.0-0.6.21.jar",
          "size": 9591,
          "sha512": "4dcfaa499cf28ece60d7153b49b9102d6f9a4699e5bb9059472fb12266a89cd878bc88ef5dd18ad9269b759784e28a525c7b191cc86d10d2e9a97f3cc71c96b4",
          "sha256": "2d9cb3c7056344646bbe78f4b73f8154ee97e6b0e1c878c42ada2135752f0792",
          "sha1": "54dfc489cc312944d8d9b3a563bc840658858d1b",
          "md5": "57918528451f706913a15b874cc7a9db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestarconnections",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarconnections-1.99.0-0.6.21.jar",
          "url": "codestarconnections-1.99.0-0.6.21.jar",
          "size": 9591,
          "sha512": "4dcfaa499cf28ece60d7153b49b9102d6f9a4699e5bb9059472fb12266a89cd878bc88ef5dd18ad9269b759784e28a525c7b191cc86d10d2e9a97f3cc71c96b4",
          "sha256": "2d9cb3c7056344646bbe78f4b73f8154ee97e6b0e1c878c42ada2135752f0792",
          "sha1": "54dfc489cc312944d8d9b3a563bc840658858d1b",
          "md5": "57918528451f706913a15b874cc7a9db"
        }
      ]
    }
  ]
}
