{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotanalytics",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotanalytics",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "iotanalytics-1.118.0-0.6.25.jar",
          "url": "iotanalytics-1.118.0-0.6.25.jar",
          "size": 508877,
          "sha512": "8115603b933bf92adeef18cf10fd6f40a16eab86e5079a0c3441deb8cfd82d41284d6ede7517da5dc343ae3bcc0f2940fcb1aecd9c02d88e0928787fb41ce05c",
          "sha256": "846edb9cd352114144d74f5201888c7bb591895352013218ce14bbd95f8683cd",
          "sha1": "c2357e0e51b1e34a96876536c27941b6549fe811",
          "md5": "9cd618bc3126990d7420bfe3ba121972"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotanalytics",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "iotanalytics-1.118.0-0.6.25.jar",
          "url": "iotanalytics-1.118.0-0.6.25.jar",
          "size": 508877,
          "sha512": "8115603b933bf92adeef18cf10fd6f40a16eab86e5079a0c3441deb8cfd82d41284d6ede7517da5dc343ae3bcc0f2940fcb1aecd9c02d88e0928787fb41ce05c",
          "sha256": "846edb9cd352114144d74f5201888c7bb591895352013218ce14bbd95f8683cd",
          "sha1": "c2357e0e51b1e34a96876536c27941b6549fe811",
          "md5": "9cd618bc3126990d7420bfe3ba121972"
        }
      ]
    }
  ]
}
