{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-region-info",
    "version": "1.117.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ka4pthfoybhvvnwbwaxmu2dbry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.117.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-region-info-1.117.0-0.6.21.jar",
          "url": "cdk-region-info-1.117.0-0.6.21.jar",
          "size": 432,
          "sha512": "8b57a3c6cf154ff74fa0ecbfb13d7412fe98dd8fd3e10dd8e9ac8a3ac6366180f9a25985cb63753bf49a4202c8069fc31cde40b98a0ceceafde797e3b3e1f577",
          "sha256": "96835f0a0589c1035b79155bccfea1ff1600e113eb42bc31c9e256b10c2a57f5",
          "sha1": "2af6207d688091c18ec25a18bd27fc783e73d46",
          "md5": "404d7f1b811bbcdca8c2c867e777773c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.117.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-region-info-1.117.0-0.6.21.jar",
          "url": "cdk-region-info-1.117.0-0.6.21.jar",
          "size": 432,
          "sha512": "8b57a3c6cf154ff74fa0ecbfb13d7412fe98dd8fd3e10dd8e9ac8a3ac6366180f9a25985cb63753bf49a4202c8069fc31cde40b98a0ceceafde797e3b3e1f577",
          "sha256": "96835f0a0589c1035b79155bccfea1ff1600e113eb42bc31c9e256b10c2a57f5",
          "sha1": "2af6207d688091c18ec25a18bd27fc783e73d46",
          "md5": "404d7f1b811bbcdca8c2c867e777773c"
        }
      ]
    }
  ]
}
