{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ivs",
    "version": "1.100.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "smkqp7thvbfexba6catfwegxzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ivs",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ivs-1.100.0-0.6.21.jar",
          "url": "ivs-1.100.0-0.6.21.jar",
          "size": 52327,
          "sha512": "1d85d1fea338a5fd27bc5fc15ac3c39ef59b940aedf4e112505bfa5d421a5ec1bbd3d86e7454d2ca3cc62b623a61548b002ce52aeb56b3dbc9f2a49473db4739",
          "sha256": "75ed825ddc906270e7071b173ef026421839e466b700438e2a364b9debf73f87",
          "sha1": "add291553e89da1d9756be504d319652672a7b90",
          "md5": "5f4c77bad58d6f2ac5577435120a050a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ivs",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ivs-1.100.0-0.6.21.jar",
          "url": "ivs-1.100.0-0.6.21.jar",
          "size": 52327,
          "sha512": "1d85d1fea338a5fd27bc5fc15ac3c39ef59b940aedf4e112505bfa5d421a5ec1bbd3d86e7454d2ca3cc62b623a61548b002ce52aeb56b3dbc9f2a49473db4739",
          "sha256": "75ed825ddc906270e7071b173ef026421839e466b700438e2a364b9debf73f87",
          "sha1": "add291553e89da1d9756be504d319652672a7b90",
          "md5": "5f4c77bad58d6f2ac5577435120a050a"
        }
      ]
    }
  ]
}
