{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iam",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iam",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iam-1.108.1-0.6.21.jar",
          "url": "iam-1.108.1-0.6.21.jar",
          "size": 269151,
          "sha512": "a881894d60a05ad336e4edfdfc2ce7dadf1d1b6e0a137b2d6bff5e17e26865a571b83d37732c8550b89e27b57954ee94dce722c07e0f6069d2c886efb59bfdb0",
          "sha256": "8b673fde07eb89b3ac444b8b1adf20037cb3c1c707e37bec4d92a90099fdc44c",
          "sha1": "3d04a162be3ffb587a980ba27ad4cbaab4c7d10e",
          "md5": "7ba03077ab8ecbb6f7f3266557695347"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iam",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iam-1.108.1-0.6.21.jar",
          "url": "iam-1.108.1-0.6.21.jar",
          "size": 269151,
          "sha512": "a881894d60a05ad336e4edfdfc2ce7dadf1d1b6e0a137b2d6bff5e17e26865a571b83d37732c8550b89e27b57954ee94dce722c07e0f6069d2c886efb59bfdb0",
          "sha256": "8b673fde07eb89b3ac444b8b1adf20037cb3c1c707e37bec4d92a90099fdc44c",
          "sha1": "3d04a162be3ffb587a980ba27ad4cbaab4c7d10e",
          "md5": "7ba03077ab8ecbb6f7f3266557695347"
        }
      ]
    }
  ]
}
