{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "eventschemas",
    "version": "1.100.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "smkqp7thvbfexba6catfwegxzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.100.0-0.6.21.jar",
          "url": "eventschemas-1.100.0-0.6.21.jar",
          "size": 43048,
          "sha512": "d1df4206ee8634e0ad9e42cc39504dd849386d020f63bf3fd227e5124bf855eee7446b8f6bdcb88d960ea6d1d26ba776a67aeb74c1de547c4d1f4a0fe1f7a9dd",
          "sha256": "45be9d2fd3a6ac787c67e5bf4d72988fe07ed1979be996c5693dff07ac31ce13",
          "sha1": "e4db3bca45acbb34ab4b72d3b43ead2bc0a17dcf",
          "md5": "ad15da4dfb7845d5b9dba1088984c476"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.100.0-0.6.21.jar",
          "url": "eventschemas-1.100.0-0.6.21.jar",
          "size": 43048,
          "sha512": "d1df4206ee8634e0ad9e42cc39504dd849386d020f63bf3fd227e5124bf855eee7446b8f6bdcb88d960ea6d1d26ba776a67aeb74c1de547c4d1f4a0fe1f7a9dd",
          "sha256": "45be9d2fd3a6ac787c67e5bf4d72988fe07ed1979be996c5693dff07ac31ce13",
          "sha1": "e4db3bca45acbb34ab4b72d3b43ead2bc0a17dcf",
          "md5": "ad15da4dfb7845d5b9dba1088984c476"
        }
      ]
    }
  ]
}
