{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "apigatewayv2-authorizers",
    "version": "1.100.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "smkqp7thvbfexba6catfwegxzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "apigatewayv2-authorizers",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "apigatewayv2",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cognito",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apigatewayv2-authorizers-1.100.0-0.6.21.jar",
          "url": "apigatewayv2-authorizers-1.100.0-0.6.21.jar",
          "size": 17410,
          "sha512": "9f7a93b177f8c827f88675634db32c3cd4cef5ea3458eff5c1a46aff663e2035ab1a1bcb098353e9ef57705b813c2bdae70c41642b0b31d0ecc3fb9626c9f6b8",
          "sha256": "ca4824308f32bb80fc465bcbf87333f89aa03e4aa3fecaab6dbb5a46c0414ad3",
          "sha1": "eed2945a250b04d2162a1bacc8c57bfad8fbf269",
          "md5": "c61d7dbb3aacdc2969051b712a047c8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "apigatewayv2-authorizers",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "apigatewayv2",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cognito",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apigatewayv2-authorizers-1.100.0-0.6.21.jar",
          "url": "apigatewayv2-authorizers-1.100.0-0.6.21.jar",
          "size": 17410,
          "sha512": "9f7a93b177f8c827f88675634db32c3cd4cef5ea3458eff5c1a46aff663e2035ab1a1bcb098353e9ef57705b813c2bdae70c41642b0b31d0ecc3fb9626c9f6b8",
          "sha256": "ca4824308f32bb80fc465bcbf87333f89aa03e4aa3fecaab6dbb5a46c0414ad3",
          "sha1": "eed2945a250b04d2162a1bacc8c57bfad8fbf269",
          "md5": "c61d7dbb3aacdc2969051b712a047c8e"
        }
      ]
    }
  ]
}
