{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "alexa-ask",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "alexa-ask",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "alexa-ask-1.106.0-0.6.21.jar",
          "url": "alexa-ask-1.106.0-0.6.21.jar",
          "size": 41747,
          "sha512": "a9c6cb5d044552406bbb2fa443d82962e101c4372c0b845901732fe121b6bdedb871e82274c198f27ae0d0a2f8de611e3fd4025f0c72256a8dd25fb4897d0708",
          "sha256": "64986c81c1a8699629a17cb46182a7e0316194b4565a2f0b467e043a4a1ea833",
          "sha1": "5456712351cf97cf975ed69e86e3eca80f6cdc9b",
          "md5": "ee1555da6ae25c9981120066d9ce4d63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "alexa-ask",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "alexa-ask-1.106.0-0.6.21.jar",
          "url": "alexa-ask-1.106.0-0.6.21.jar",
          "size": 41747,
          "sha512": "a9c6cb5d044552406bbb2fa443d82962e101c4372c0b845901732fe121b6bdedb871e82274c198f27ae0d0a2f8de611e3fd4025f0c72256a8dd25fb4897d0708",
          "sha256": "64986c81c1a8699629a17cb46182a7e0316194b4565a2f0b467e043a4a1ea833",
          "sha1": "5456712351cf97cf975ed69e86e3eca80f6cdc9b",
          "md5": "ee1555da6ae25c9981120066d9ce4d63"
        }
      ]
    }
  ]
}
