{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-assets-schema",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "k23roxkwqjbs5i6arr4lg4r4xm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets-schema",
          "version": {
            "requires": "1.110.1"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-schema-1.110.1-0.6.21.jar",
          "url": "cdk-assets-schema-1.110.1-0.6.21.jar",
          "size": 436,
          "sha512": "1f6f3931d96568c81e6c2c1866018d601c70df63240b169b9b70276fa486568375e8ac76e957031d8c7f19779b00d7d4dbb5dafd591149636624eb46a607ba75",
          "sha256": "b32830f998be136542dfd07f8664a4ea57868a759bfe3b906accdb4ce49fe2b8",
          "sha1": "b661542a4ce7defcb803f94c0b2cabac1482f0e8",
          "md5": "af07101b8f70da17414e22604ae9c57f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets-schema",
          "version": {
            "requires": "1.110.1"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-schema-1.110.1-0.6.21.jar",
          "url": "cdk-assets-schema-1.110.1-0.6.21.jar",
          "size": 436,
          "sha512": "1f6f3931d96568c81e6c2c1866018d601c70df63240b169b9b70276fa486568375e8ac76e957031d8c7f19779b00d7d4dbb5dafd591149636624eb46a607ba75",
          "sha256": "b32830f998be136542dfd07f8664a4ea57868a759bfe3b906accdb4ce49fe2b8",
          "sha1": "b661542a4ce7defcb803f94c0b2cabac1482f0e8",
          "md5": "af07101b8f70da17414e22604ae9c57f"
        }
      ]
    }
  ]
}
