{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestarnotifications",
    "version": "1.31.0-unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "codestarnotifications-1.31.0-unspecified.jar",
          "url": "codestarnotifications-1.31.0-unspecified.jar",
          "size": 23637,
          "sha512": "929390708644c8efe63f8830a51e9449c871415802927627441ae088d908d57953d87c161598a94e260a75ebbafd6962df1483f5c5822926fc3d81d9ee7a97f7",
          "sha256": "aef2cc46ad31c594e08a7bd6ddf2e3d46e9a0bcbee2d8b1d5c8d3ef12bc0a046",
          "sha1": "9ac87c2c0be1cd469a7918be0f53e15dfc2a353d",
          "md5": "9b5c1df23002374b664db2653650644c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "codestarnotifications-1.31.0-unspecified.jar",
          "url": "codestarnotifications-1.31.0-unspecified.jar",
          "size": 23637,
          "sha512": "929390708644c8efe63f8830a51e9449c871415802927627441ae088d908d57953d87c161598a94e260a75ebbafd6962df1483f5c5822926fc3d81d9ee7a97f7",
          "sha256": "aef2cc46ad31c594e08a7bd6ddf2e3d46e9a0bcbee2d8b1d5c8d3ef12bc0a046",
          "sha1": "9ac87c2c0be1cd469a7918be0f53e15dfc2a353d",
          "md5": "9b5c1df23002374b664db2653650644c"
        }
      ]
    }
  ]
}
