{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-cloud-assembly-schema",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.108.1"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cloud-assembly-schema-1.108.1-0.6.21.jar",
          "url": "cdk-cloud-assembly-schema-1.108.1-0.6.21.jar",
          "size": 143605,
          "sha512": "ec318361200356be115e32fc18205947c545b65a7864ab27fb09f2b00c9ce1b5d948b36cd7fccd078f4723f853d04240699c223a99e8feb291755fd8f3365426",
          "sha256": "ed6e55491d36467259d2b1b4c561e9051be76727c46be04ee3ced3b33ba7c140",
          "sha1": "ee16dfd01b7073282b136936fcda094869fcfd2f",
          "md5": "6583fe322d500e7c0f01b3a04aeb2297"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.108.1"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cloud-assembly-schema-1.108.1-0.6.21.jar",
          "url": "cdk-cloud-assembly-schema-1.108.1-0.6.21.jar",
          "size": 143605,
          "sha512": "ec318361200356be115e32fc18205947c545b65a7864ab27fb09f2b00c9ce1b5d948b36cd7fccd078f4723f853d04240699c223a99e8feb291755fd8f3365426",
          "sha256": "ed6e55491d36467259d2b1b4c561e9051be76727c46be04ee3ced3b33ba7c140",
          "sha1": "ee16dfd01b7073282b136936fcda094869fcfd2f",
          "md5": "6583fe322d500e7c0f01b3a04aeb2297"
        }
      ]
    }
  ]
}
