{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "kendra",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "kendra",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kendra-1.111.0-0.6.21.jar",
          "url": "kendra-1.111.0-0.6.21.jar",
          "size": 555048,
          "sha512": "fc3d61c3f20fbef9c00e3a8d55eabf054388eb2fa6fe09dcae5df075b8e7e16df79375b2ddc56db5984bb8c6e28bdab457f87627f140d546757c09b1f76596ee",
          "sha256": "e9ca847ed94b32f698a9776a84b35970fb5b83e97ed2b256d4b67179d96d6314",
          "sha1": "388aeb03dae3138ee38fcdf9ec030c33acaae3d6",
          "md5": "547be5d4d8eae92623756267ba2439c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "kendra",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kendra-1.111.0-0.6.21.jar",
          "url": "kendra-1.111.0-0.6.21.jar",
          "size": 555048,
          "sha512": "fc3d61c3f20fbef9c00e3a8d55eabf054388eb2fa6fe09dcae5df075b8e7e16df79375b2ddc56db5984bb8c6e28bdab457f87627f140d546757c09b1f76596ee",
          "sha256": "e9ca847ed94b32f698a9776a84b35970fb5b83e97ed2b256d4b67179d96d6314",
          "sha1": "388aeb03dae3138ee38fcdf9ec030c33acaae3d6",
          "md5": "547be5d4d8eae92623756267ba2439c6"
        }
      ]
    }
  ]
}
