{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "medialive",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "medialive",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "medialive-1.108.1-0.6.21.jar",
          "url": "medialive-1.108.1-0.6.21.jar",
          "size": 1423725,
          "sha512": "1af9204f12a763324292bda544380eb29e8ecbd4b6bc3c474dba1445c33d1be66bebaa0966772586cd262133fc4904452195b7709250e874cafd3ee5b2a7b74d",
          "sha256": "eff4b1a61c8bfb1d685fa0a80c0d0be3ca3ea7874aadc97fc3ff773110c8bf1f",
          "sha1": "9d93ff96494a859d8ccd5c640d537896d5df8211",
          "md5": "a2f0888e511dc3702fb946db7e733db0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "medialive",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "medialive-1.108.1-0.6.21.jar",
          "url": "medialive-1.108.1-0.6.21.jar",
          "size": 1423725,
          "sha512": "1af9204f12a763324292bda544380eb29e8ecbd4b6bc3c474dba1445c33d1be66bebaa0966772586cd262133fc4904452195b7709250e874cafd3ee5b2a7b74d",
          "sha256": "eff4b1a61c8bfb1d685fa0a80c0d0be3ca3ea7874aadc97fc3ff773110c8bf1f",
          "sha1": "9d93ff96494a859d8ccd5c640d537896d5df8211",
          "md5": "a2f0888e511dc3702fb946db7e733db0"
        }
      ]
    }
  ]
}
