{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "nimblestudio",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "nimblestudio",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "nimblestudio-1.103.0-0.6.21.jar",
          "url": "nimblestudio-1.103.0-0.6.21.jar",
          "size": 142476,
          "sha512": "6c198587eda08d98a09767e6d6b489510c70acb338c567e5c0a2a2fbd91dda0077de3f0a6824ef7288d676f5ed20fa5977ee1e603d5ae3644f81f0155e736353",
          "sha256": "cd1f536f6ab927dc560a23c9da9c197b21bee8d9f9c1ef0bf59085410467b33b",
          "sha1": "a9443334dd14ee8644ab48327237fce899485353",
          "md5": "4dc237306035add4b4ede540cb259448"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "nimblestudio",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "nimblestudio-1.103.0-0.6.21.jar",
          "url": "nimblestudio-1.103.0-0.6.21.jar",
          "size": 142476,
          "sha512": "6c198587eda08d98a09767e6d6b489510c70acb338c567e5c0a2a2fbd91dda0077de3f0a6824ef7288d676f5ed20fa5977ee1e603d5ae3644f81f0155e736353",
          "sha256": "cd1f536f6ab927dc560a23c9da9c197b21bee8d9f9c1ef0bf59085410467b33b",
          "sha1": "a9443334dd14ee8644ab48327237fce899485353",
          "md5": "4dc237306035add4b4ede540cb259448"
        }
      ]
    }
  ]
}
