{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "xray",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "xray",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "xray-1.112.0-0.6.21.jar",
          "url": "xray-1.112.0-0.6.21.jar",
          "size": 91818,
          "sha512": "96f172b7ce0c73f7a6390fe24b99aeeeb530686d7573436ac05603a1c18801f434e93ec4df0d77efd8871ddf185c8cd6d1aa748722843930c8cd59d835d79938",
          "sha256": "821eb228f1f391f30394dee8504eace16f5944e28862dadcb954df86eea4b88d",
          "sha1": "789a8ca69436f3ecf5d8dd6183244be663c2f7f5",
          "md5": "7c0f3231246c8b132dfffd5b24a52b60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "xray",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "xray-1.112.0-0.6.21.jar",
          "url": "xray-1.112.0-0.6.21.jar",
          "size": 91818,
          "sha512": "96f172b7ce0c73f7a6390fe24b99aeeeb530686d7573436ac05603a1c18801f434e93ec4df0d77efd8871ddf185c8cd6d1aa748722843930c8cd59d835d79938",
          "sha256": "821eb228f1f391f30394dee8504eace16f5944e28862dadcb954df86eea4b88d",
          "sha1": "789a8ca69436f3ecf5d8dd6183244be663c2f7f5",
          "md5": "7c0f3231246c8b132dfffd5b24a52b60"
        }
      ]
    }
  ]
}
