{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "appconfig",
    "version": "1.31.0-unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "appconfig",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "appconfig-1.31.0-unspecified.jar",
          "url": "appconfig-1.31.0-unspecified.jar",
          "size": 85612,
          "sha512": "772b9b5ec9b7d0780ce0ab4ff0f041fe3aabdfed20e86214f5a69a10b869a0d7eb1dee76b832601634b66f695d8893e0c365713c6069e64b2fad970b544aa483",
          "sha256": "a4a845631c926ce95a93d62fb105d1fc8deb4bc482e433cc13d9267e42c893d0",
          "sha1": "a3d30971982710c7c97af51b378f75bff4047f97",
          "md5": "ef19a643daa3273b661da3520cfb1b49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "appconfig",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "appconfig-1.31.0-unspecified.jar",
          "url": "appconfig-1.31.0-unspecified.jar",
          "size": 85612,
          "sha512": "772b9b5ec9b7d0780ce0ab4ff0f041fe3aabdfed20e86214f5a69a10b869a0d7eb1dee76b832601634b66f695d8893e0c365713c6069e64b2fad970b544aa483",
          "sha256": "a4a845631c926ce95a93d62fb105d1fc8deb4bc482e433cc13d9267e42c893d0",
          "sha1": "a3d30971982710c7c97af51b378f75bff4047f97",
          "md5": "ef19a643daa3273b661da3520cfb1b49"
        }
      ]
    }
  ]
}
