{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-pipelines",
    "version": "1.59.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-pipelines",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudformation",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codebuild",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codepipeline",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codepipeline-actions",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-pipelines-1.59.0-0.6.23.jar",
          "url": "cdk-pipelines-1.59.0-0.6.23.jar",
          "size": 100381,
          "sha512": "e4d621ebc30789e34a1e709cc858cb98e4e92188cb4105c0d750db61c7caf8b9f7e18e9ab19a6e6f832ee367ef9c25ca7dd25e16d8d30eebe0f72fc44e2d56a6",
          "sha256": "4e8852eced4837eaf01704eaf636eb88b76e341885d11fbeb27ac2abf5bd648a",
          "sha1": "0a21c91797372f6b31d04d8f35164122a6b345d3",
          "md5": "4ff02fae11acbba8a97e8177dac36773"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-pipelines",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudformation",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codebuild",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codepipeline",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codepipeline-actions",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-pipelines-1.59.0-0.6.23.jar",
          "url": "cdk-pipelines-1.59.0-0.6.23.jar",
          "size": 100381,
          "sha512": "e4d621ebc30789e34a1e709cc858cb98e4e92188cb4105c0d750db61c7caf8b9f7e18e9ab19a6e6f832ee367ef9c25ca7dd25e16d8d30eebe0f72fc44e2d56a6",
          "sha256": "4e8852eced4837eaf01704eaf636eb88b76e341885d11fbeb27ac2abf5bd648a",
          "sha1": "0a21c91797372f6b31d04d8f35164122a6b345d3",
          "md5": "4ff02fae11acbba8a97e8177dac36773"
        }
      ]
    }
  ]
}
