{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codecommit",
    "version": "1.64.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codecommit",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codecommit-1.64.0-0.6.21.jar",
          "url": "codecommit-1.64.0-0.6.21.jar",
          "size": 56706,
          "sha512": "7b37d28463e32772ffa31775f8c677a2dd9231fd6feef02bbb36b0c4463bedbc5672344f1f7221127fbbbfaebb10e6e14098c209ed0931fe18c58381fb223450",
          "sha256": "cdf7208a1729127b5ce510de25ecb85354babe4168b3f037d6c324aa90eb1bde",
          "sha1": "d463cbbd41cbea4911ba317300b693c5fc94e702",
          "md5": "43ccd75a622c330489f2a7903b598ea3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codecommit",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codecommit-1.64.0-0.6.21.jar",
          "url": "codecommit-1.64.0-0.6.21.jar",
          "size": 56706,
          "sha512": "7b37d28463e32772ffa31775f8c677a2dd9231fd6feef02bbb36b0c4463bedbc5672344f1f7221127fbbbfaebb10e6e14098c209ed0931fe18c58381fb223450",
          "sha256": "cdf7208a1729127b5ce510de25ecb85354babe4168b3f037d6c324aa90eb1bde",
          "sha1": "d463cbbd41cbea4911ba317300b693c5fc94e702",
          "md5": "43ccd75a622c330489f2a7903b598ea3"
        }
      ]
    }
  ]
}
