{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "events",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "events",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "events-1.116.0-0.6.21.jar",
          "url": "events-1.116.0-0.6.21.jar",
          "size": 259572,
          "sha512": "8faedb374c653e60de5e322c366f41ace87c514b4ccc902134daee3d41b9ad8439b4409f096973b9727cdb5bdb817cf83ebcb264e2790bf08ef11ca2d0c19d6",
          "sha256": "1c9f1493f84f6d9039dd2954a89b9b1205c42e99f084891aa52664871100173e",
          "sha1": "96165fb50d28aa45626bb314adc8bcf84205979f",
          "md5": "3eb3668030215296b6675ec1e6cecc8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "events",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "events-1.116.0-0.6.21.jar",
          "url": "events-1.116.0-0.6.21.jar",
          "size": 259572,
          "sha512": "8faedb374c653e60de5e322c366f41ace87c514b4ccc902134daee3d41b9ad8439b4409f096973b9727cdb5bdb817cf83ebcb264e2790bf08ef11ca2d0c19d6",
          "sha256": "1c9f1493f84f6d9039dd2954a89b9b1205c42e99f084891aa52664871100173e",
          "sha1": "96165fb50d28aa45626bb314adc8bcf84205979f",
          "md5": "3eb3668030215296b6675ec1e6cecc8a"
        }
      ]
    }
  ]
}
