{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "signer",
    "version": "1.110.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cnrjfrtzdvad5bhmsg7msamtuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "signer",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "signer-1.110.0-0.6.21.jar",
          "url": "signer-1.110.0-0.6.21.jar",
          "size": 40313,
          "sha512": "1594d27178edd0d033be3816076cc29444772b5c064f0c86ec1d12489759a5fa9b8ec76c9902ae6ff8479b75404f00d50117f86e97f82d4aa9d0a90c8f824020",
          "sha256": "cf13f23091e3aa6b032e507ae0e35c13000f98c5a0ebb8b2777d0eaab4f8b387",
          "sha1": "89f98ad2e346e38935bd75c5409bf15d8988e4b0",
          "md5": "6dacc9c113146c5784faab9ae633dc17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "signer",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "signer-1.110.0-0.6.21.jar",
          "url": "signer-1.110.0-0.6.21.jar",
          "size": 40313,
          "sha512": "1594d27178edd0d033be3816076cc29444772b5c064f0c86ec1d12489759a5fa9b8ec76c9902ae6ff8479b75404f00d50117f86e97f82d4aa9d0a90c8f824020",
          "sha256": "cf13f23091e3aa6b032e507ae0e35c13000f98c5a0ebb8b2777d0eaab4f8b387",
          "sha1": "89f98ad2e346e38935bd75c5409bf15d8988e4b0",
          "md5": "6dacc9c113146c5784faab9ae633dc17"
        }
      ]
    }
  ]
}
