{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "customerprofiles",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "customerprofiles",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "customerprofiles-1.108.0-0.6.21.jar",
          "url": "customerprofiles-1.108.0-0.6.21.jar",
          "size": 214522,
          "sha512": "2e30f4f043f705bfd72e096faf854ff0be0d2ec71aee06d8d8a04abf01be0f84c876f35fb6e39ac407db91bf85149d6694f0a539dbbf22b8e45fb3b37d57e379",
          "sha256": "98a93ae6f4d3ab440fef24ccd0d23243adb34d6218e98fe380f161c04256bec1",
          "sha1": "8078a99d17637299742a1fa97ef94999e0987b13",
          "md5": "ff3bb3a670bd9cacb1b10bc8b51550c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "customerprofiles",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "customerprofiles-1.108.0-0.6.21.jar",
          "url": "customerprofiles-1.108.0-0.6.21.jar",
          "size": 214522,
          "sha512": "2e30f4f043f705bfd72e096faf854ff0be0d2ec71aee06d8d8a04abf01be0f84c876f35fb6e39ac407db91bf85149d6694f0a539dbbf22b8e45fb3b37d57e379",
          "sha256": "98a93ae6f4d3ab440fef24ccd0d23243adb34d6218e98fe380f161c04256bec1",
          "sha1": "8078a99d17637299742a1fa97ef94999e0987b13",
          "md5": "ff3bb3a670bd9cacb1b10bc8b51550c1"
        }
      ]
    }
  ]
}
