{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cassandra",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "k23roxkwqjbs5i6arr4lg4r4xm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cassandra",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cassandra-1.110.1-0.6.21.jar",
          "url": "cassandra-1.110.1-0.6.21.jar",
          "size": 83810,
          "sha512": "c65732e52073fa5b7c71da99769d50647348e433a303fa6a2f647bac6901fa370968bee59de08764c8dfa585194b308d1cf9215113a20c4b37633dfbd93c66cc",
          "sha256": "3fbf878ebebb9a7139122b7f248b8c38b3741a7d87c83fd310821c9cbcc4d54",
          "sha1": "ca5db2d0c65ecf98fdedc518e4003b75471ec0ad",
          "md5": "9a456516d518104b514642e46e0bbe7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cassandra",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cassandra-1.110.1-0.6.21.jar",
          "url": "cassandra-1.110.1-0.6.21.jar",
          "size": 83810,
          "sha512": "c65732e52073fa5b7c71da99769d50647348e433a303fa6a2f647bac6901fa370968bee59de08764c8dfa585194b308d1cf9215113a20c4b37633dfbd93c66cc",
          "sha256": "3fbf878ebebb9a7139122b7f248b8c38b3741a7d87c83fd310821c9cbcc4d54",
          "sha1": "ca5db2d0c65ecf98fdedc518e4003b75471ec0ad",
          "md5": "9a456516d518104b514642e46e0bbe7f"
        }
      ]
    }
  ]
}
