{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "auditmanager",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "auditmanager",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "auditmanager-1.104.0-0.6.21.jar",
          "url": "auditmanager-1.104.0-0.6.21.jar",
          "size": 76360,
          "sha512": "1ea24c84a165f2b6987944cd6e29235975b34ec26ee7ac7c9c0330fff103e60c6bee94ff217cd627b83ebfc20b6a4b56c887626704c5f4d03bc4e93737396c86",
          "sha256": "6274bf0b780b37bd1a328d2341aecdaadd6aa0896438db7813f205d549fd58f5",
          "sha1": "a218e1f032c2cfff2c1f66f7feb653ea67343689",
          "md5": "96fe035bdbb34c1a7b9bdc1fe3797edc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "auditmanager",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "auditmanager-1.104.0-0.6.21.jar",
          "url": "auditmanager-1.104.0-0.6.21.jar",
          "size": 76360,
          "sha512": "1ea24c84a165f2b6987944cd6e29235975b34ec26ee7ac7c9c0330fff103e60c6bee94ff217cd627b83ebfc20b6a4b56c887626704c5f4d03bc4e93737396c86",
          "sha256": "6274bf0b780b37bd1a328d2341aecdaadd6aa0896438db7813f205d549fd58f5",
          "sha1": "a218e1f032c2cfff2c1f66f7feb653ea67343689",
          "md5": "96fe035bdbb34c1a7b9bdc1fe3797edc"
        }
      ]
    }
  ]
}
