{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "emrcontainers",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "emrcontainers",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emrcontainers-1.114.0-0.6.21.jar",
          "url": "emrcontainers-1.114.0-0.6.21.jar",
          "size": 38504,
          "sha512": "3827918ba7f0bfd0cea8ddcea1123506e3890dbeea45d8186ed71424322432ab10e6f98c29d6873facae7b08938ee11a1fad23d91297f3ff981f7e976b66e347",
          "sha256": "31e0d6532840382d0d985c231eea9be2ad77675d4da77b8f09b37884994b931e",
          "sha1": "c731205a316e28e914dd4ee010972d13cd653c71",
          "md5": "48de9a45918e9902a98701b43ffb6664"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "emrcontainers",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emrcontainers-1.114.0-0.6.21.jar",
          "url": "emrcontainers-1.114.0-0.6.21.jar",
          "size": 38504,
          "sha512": "3827918ba7f0bfd0cea8ddcea1123506e3890dbeea45d8186ed71424322432ab10e6f98c29d6873facae7b08938ee11a1fad23d91297f3ff981f7e976b66e347",
          "sha256": "31e0d6532840382d0d985c231eea9be2ad77675d4da77b8f09b37884994b931e",
          "sha1": "c731205a316e28e914dd4ee010972d13cd653c71",
          "md5": "48de9a45918e9902a98701b43ffb6664"
        }
      ]
    }
  ]
}
