{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "auditmanager",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "auditmanager",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "auditmanager-1.118.0-0.6.25.jar",
          "url": "auditmanager-1.118.0-0.6.25.jar",
          "size": 76340,
          "sha512": "09d87532e129faf13ab236daa4965f3ce7a54df32488d544d661331dd9b9bea7d0dc2149547adc7cbf23757edb6811f91f0e2a610a226c7662023c78292a324c",
          "sha256": "56fe394166ddda466261df133375d6ca51e7e315192fb4541d5ed32973f155fa",
          "sha1": "624cd99558f45746513000c27b1bcd83e1c98545",
          "md5": "90185dbf3398f1a486ebaa3f17440244"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "auditmanager",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "auditmanager-1.118.0-0.6.25.jar",
          "url": "auditmanager-1.118.0-0.6.25.jar",
          "size": 76340,
          "sha512": "09d87532e129faf13ab236daa4965f3ce7a54df32488d544d661331dd9b9bea7d0dc2149547adc7cbf23757edb6811f91f0e2a610a226c7662023c78292a324c",
          "sha256": "56fe394166ddda466261df133375d6ca51e7e315192fb4541d5ed32973f155fa",
          "sha1": "624cd99558f45746513000c27b1bcd83e1c98545",
          "md5": "90185dbf3398f1a486ebaa3f17440244"
        }
      ]
    }
  ]
}
