{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestarconnections",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestarconnections",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarconnections-1.107.0-0.6.21.jar",
          "url": "codestarconnections-1.107.0-0.6.21.jar",
          "size": 9600,
          "sha512": "3d0a3fb1fe3a3ec433b562cdd11c47cbb9365b2083551d7f3734356281fb8243c070ad3154115e9a8cb4a4532fae190a1409e066f818bcd8eb33a015e4993f2e",
          "sha256": "f10c4ff8affeee15982c18c03b4a35d48ce3701c0f8a15c32cbe714f916106c",
          "sha1": "28802426a66d46ac923a043c7371b6800b53fc57",
          "md5": "35f7a70afd4cf19a2c52df422a4b8a9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestarconnections",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarconnections-1.107.0-0.6.21.jar",
          "url": "codestarconnections-1.107.0-0.6.21.jar",
          "size": 9600,
          "sha512": "3d0a3fb1fe3a3ec433b562cdd11c47cbb9365b2083551d7f3734356281fb8243c070ad3154115e9a8cb4a4532fae190a1409e066f818bcd8eb33a015e4993f2e",
          "sha256": "f10c4ff8affeee15982c18c03b4a35d48ce3701c0f8a15c32cbe714f916106c",
          "sha1": "28802426a66d46ac923a043c7371b6800b53fc57",
          "md5": "35f7a70afd4cf19a2c52df422a4b8a9f"
        }
      ]
    }
  ]
}
