{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "amazonmq",
    "version": "1.101.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "d5vusioiqzbnxk6vuwjeusvgpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "amazonmq",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "amazonmq-1.101.0-0.6.21.jar",
          "url": "amazonmq-1.101.0-0.6.21.jar",
          "size": 164821,
          "sha512": "350e5bc1b96f75fb0b4cb84892e0c723495488484eac138ec80524ab23b1f6658332ea44770133582498f14678b16391f22dc00df0c331522af966a168ae835a",
          "sha256": "9b755e8f35dbfda23211be6adaa67c7c556412ec8b404546d434bf3439fcdc17",
          "sha1": "172709efdc56e0dd8210d28fd5c9fdbadc317652",
          "md5": "791e3aa1f1cd7fdef542ef40c518cd4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "amazonmq",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "amazonmq-1.101.0-0.6.21.jar",
          "url": "amazonmq-1.101.0-0.6.21.jar",
          "size": 164821,
          "sha512": "350e5bc1b96f75fb0b4cb84892e0c723495488484eac138ec80524ab23b1f6658332ea44770133582498f14678b16391f22dc00df0c331522af966a168ae835a",
          "sha256": "9b755e8f35dbfda23211be6adaa67c7c556412ec8b404546d434bf3439fcdc17",
          "sha1": "172709efdc56e0dd8210d28fd5c9fdbadc317652",
          "md5": "791e3aa1f1cd7fdef542ef40c518cd4f"
        }
      ]
    }
  ]
}
