{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestarnotifications",
    "version": "1.34.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "codestarnotifications-1.34.0-0.6.22.jar",
          "url": "codestarnotifications-1.34.0-0.6.22.jar",
          "size": 23627,
          "sha512": "019ebf86de35425a46db45681c2a4118d16a3baf33118bbe80da880dc8ab54b20e91626012973756d5d195b3f9b748b12584707653b4eb94d375e2e98a0f0e7a",
          "sha256": "672fb28d561bc65a35791ac95fc4c112d6612ee25bd3501aff151a7fbf6b1688",
          "sha1": "92a6b392661f4e740ff993ef735df6e05568fc0f",
          "md5": "9af91c9d54ab387b467d5db48eb70372"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "codestarnotifications-1.34.0-0.6.22.jar",
          "url": "codestarnotifications-1.34.0-0.6.22.jar",
          "size": 23627,
          "sha512": "019ebf86de35425a46db45681c2a4118d16a3baf33118bbe80da880dc8ab54b20e91626012973756d5d195b3f9b748b12584707653b4eb94d375e2e98a0f0e7a",
          "sha256": "672fb28d561bc65a35791ac95fc4c112d6612ee25bd3501aff151a7fbf6b1688",
          "sha1": "92a6b392661f4e740ff993ef735df6e05568fc0f",
          "md5": "9af91c9d54ab387b467d5db48eb70372"
        }
      ]
    }
  ]
}
