{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "connect",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "connect",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "connect-1.115.0-0.6.21.jar",
          "url": "connect-1.115.0-0.6.21.jar",
          "size": 46832,
          "sha512": "fb8be9879b9f0f1a4083750a24bb9053151329153bfd95334963f368fd42cc8e30680bcdf8069ea5794ee747cf558313bf5404b1ab18432d524a5fad0871d100",
          "sha256": "f4c8cd7cdad99b2ec7bbf8299c608c207e6c053c8455993d673d09c2a7335403",
          "sha1": "e78474c3ba421dffe0cd0c537910fd32c178ea28",
          "md5": "322573785f8ef126c4606d7cf56bcb1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "connect",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "connect-1.115.0-0.6.21.jar",
          "url": "connect-1.115.0-0.6.21.jar",
          "size": 46832,
          "sha512": "fb8be9879b9f0f1a4083750a24bb9053151329153bfd95334963f368fd42cc8e30680bcdf8069ea5794ee747cf558313bf5404b1ab18432d524a5fad0871d100",
          "sha256": "f4c8cd7cdad99b2ec7bbf8299c608c207e6c053c8455993d673d09c2a7335403",
          "sha1": "e78474c3ba421dffe0cd0c537910fd32c178ea28",
          "md5": "322573785f8ef126c4606d7cf56bcb1e"
        }
      ]
    }
  ]
}
