{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sso",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sso",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sso-1.108.0-0.6.21.jar",
          "url": "sso-1.108.0-0.6.21.jar",
          "size": 46888,
          "sha512": "9ce7f8b3b13ca31e78dc8a93965f8fef22f4e2864561f9fd19e1117bcd3a9ffba55d43cc85ab22eeb947acd9d07aa1cd66c8773f07b6f214e5501eb4ff00b1d9",
          "sha256": "c58b3051ef44d14d7688357a18dafc368672a9f78b3216d734be4a65c448aa55",
          "sha1": "f276b04c3bc937cfc1adee6a1ddbbe58145c9e38",
          "md5": "e9235df6da5293a3852ac67a55eadc77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sso",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sso-1.108.0-0.6.21.jar",
          "url": "sso-1.108.0-0.6.21.jar",
          "size": 46888,
          "sha512": "9ce7f8b3b13ca31e78dc8a93965f8fef22f4e2864561f9fd19e1117bcd3a9ffba55d43cc85ab22eeb947acd9d07aa1cd66c8773f07b6f214e5501eb4ff00b1d9",
          "sha256": "c58b3051ef44d14d7688357a18dafc368672a9f78b3216d734be4a65c448aa55",
          "sha1": "f276b04c3bc937cfc1adee6a1ddbbe58145c9e38",
          "md5": "e9235df6da5293a3852ac67a55eadc77"
        }
      ]
    }
  ]
}
