{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "waf",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "waf",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "waf-1.102.0-0.6.21.jar",
          "url": "waf-1.102.0-0.6.21.jar",
          "size": 188902,
          "sha512": "7f991049ad25f5a376b79ec1fb92e6e4b547015920126bfb0bb8777654f3861d51d53530a59327b4182cf7417c17045983dec16e62eb8e399996b47ab642418e",
          "sha256": "cc82ec2555ea52168cfdf3e0c1dfe507f1e51f474c362d6758df5f1a6bc1a4b8",
          "sha1": "9a1ccf826de4f06ca2c479dcafeac6d80e9369a",
          "md5": "154e0840c7cc5d056486b369887fbe58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "waf",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "waf-1.102.0-0.6.21.jar",
          "url": "waf-1.102.0-0.6.21.jar",
          "size": 188902,
          "sha512": "7f991049ad25f5a376b79ec1fb92e6e4b547015920126bfb0bb8777654f3861d51d53530a59327b4182cf7417c17045983dec16e62eb8e399996b47ab642418e",
          "sha256": "cc82ec2555ea52168cfdf3e0c1dfe507f1e51f474c362d6758df5f1a6bc1a4b8",
          "sha1": "9a1ccf826de4f06ca2c479dcafeac6d80e9369a",
          "md5": "154e0840c7cc5d056486b369887fbe58"
        }
      ]
    }
  ]
}
