{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "amazonmq",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "amazonmq",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "amazonmq-1.111.0-0.6.21.jar",
          "url": "amazonmq-1.111.0-0.6.21.jar",
          "size": 164855,
          "sha512": "36135b8b4b51f8bb6295e1f7c05d6cc09d5a67faf1a17601ea2d9ce5f4cc24e0b0cce3912cde24bbcac4013a4f984b39a4b6de85b180d74c6491b7279df7b8c2",
          "sha256": "9677d7d7aa848ccee1fd8d981d7a5954f43d3ce77731a4154980bdc8d881702b",
          "sha1": "e5c00fa316b2530990225493084c748d282b84dd",
          "md5": "a4d7a38f2d9302ae26a75d045f872093"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "amazonmq",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "amazonmq-1.111.0-0.6.21.jar",
          "url": "amazonmq-1.111.0-0.6.21.jar",
          "size": 164855,
          "sha512": "36135b8b4b51f8bb6295e1f7c05d6cc09d5a67faf1a17601ea2d9ce5f4cc24e0b0cce3912cde24bbcac4013a4f984b39a4b6de85b180d74c6491b7279df7b8c2",
          "sha256": "9677d7d7aa848ccee1fd8d981d7a5954f43d3ce77731a4154980bdc8d881702b",
          "sha1": "e5c00fa316b2530990225493084c748d282b84dd",
          "md5": "a4d7a38f2d9302ae26a75d045f872093"
        }
      ]
    }
  ]
}
