{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "pinpoint",
    "version": "1.59.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "pinpoint",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "pinpoint-1.59.0-0.6.23.jar",
          "url": "pinpoint-1.59.0-0.6.23.jar",
          "size": 629283,
          "sha512": "f3064425440dbe26529a5e1f11de889bdcdcacfc414be3b6cf14b3585266aefe52294290e96326ccbfc09f41999a70654b7dfb6a8fd1e4d9b6a4ed7199b49eed",
          "sha256": "7b96c12e3f387e50a5293db7f274514a24994dfb5e1c6d33463285124a63ee6b",
          "sha1": "8cb7ee6c7baf0157199380529b0d1152793791fd",
          "md5": "45ebb4f7cdd56cf18411f885700a5864"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "pinpoint",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "pinpoint-1.59.0-0.6.23.jar",
          "url": "pinpoint-1.59.0-0.6.23.jar",
          "size": 629283,
          "sha512": "f3064425440dbe26529a5e1f11de889bdcdcacfc414be3b6cf14b3585266aefe52294290e96326ccbfc09f41999a70654b7dfb6a8fd1e4d9b6a4ed7199b49eed",
          "sha256": "7b96c12e3f387e50a5293db7f274514a24994dfb5e1c6d33463285124a63ee6b",
          "sha1": "8cb7ee6c7baf0157199380529b0d1152793791fd",
          "md5": "45ebb4f7cdd56cf18411f885700a5864"
        }
      ]
    }
  ]
}
