{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "resourcegroups",
    "version": "1.117.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ka4pthfoybhvvnwbwaxmu2dbry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "resourcegroups",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "resourcegroups-1.117.0-0.6.21.jar",
          "url": "resourcegroups-1.117.0-0.6.21.jar",
          "size": 59371,
          "sha512": "36ed761164106a9198527c41e2799c908145c259ea922c62a26c43585c9ac57752830d7fc2b4b0a3ab38993bc1e919a59bfcd1330f456d8e51e48564ba3bec11",
          "sha256": "133e2f155bf01934cb77f2ddd530d51d432ea500d9bf9b5a727c272c0cacac87",
          "sha1": "3448eb657433c72876c9d0f1bc5c8152db733c7b",
          "md5": "9e96e448b239d523194ac2cdb2fa604f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "resourcegroups",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "resourcegroups-1.117.0-0.6.21.jar",
          "url": "resourcegroups-1.117.0-0.6.21.jar",
          "size": 59371,
          "sha512": "36ed761164106a9198527c41e2799c908145c259ea922c62a26c43585c9ac57752830d7fc2b4b0a3ab38993bc1e919a59bfcd1330f456d8e51e48564ba3bec11",
          "sha256": "133e2f155bf01934cb77f2ddd530d51d432ea500d9bf9b5a727c272c0cacac87",
          "sha1": "3448eb657433c72876c9d0f1bc5c8152db733c7b",
          "md5": "9e96e448b239d523194ac2cdb2fa604f"
        }
      ]
    }
  ]
}
