{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "guardduty",
    "version": "1.31.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "guardduty",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "guardduty-1.31.0-0.6.23.jar",
          "url": "guardduty-1.31.0-0.6.23.jar",
          "size": 101290,
          "sha512": "fb8d436b6360d3ab03a9af6b311d6596cb44486aa5869d71f4b80f32ca06486349f5b138343e475bd6e458647905719bc02bd2ebdf25a896a136b3b23e63a8bc",
          "sha256": "62a20dab74bbc59c1bac2d4cc0d376490db606af68bbbf183f6c5169b4191961",
          "sha1": "6d77132e103392ae4b225de481765f640f1bd8a0",
          "md5": "67b43c4052bacfbb96d4363dfe8cd66a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "guardduty",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "guardduty-1.31.0-0.6.23.jar",
          "url": "guardduty-1.31.0-0.6.23.jar",
          "size": 101290,
          "sha512": "fb8d436b6360d3ab03a9af6b311d6596cb44486aa5869d71f4b80f32ca06486349f5b138343e475bd6e458647905719bc02bd2ebdf25a896a136b3b23e63a8bc",
          "sha256": "62a20dab74bbc59c1bac2d4cc0d376490db606af68bbbf183f6c5169b4191961",
          "sha1": "6d77132e103392ae4b225de481765f640f1bd8a0",
          "md5": "67b43c4052bacfbb96d4363dfe8cd66a"
        }
      ]
    }
  ]
}
