{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "securityhub",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "securityhub",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "securityhub-1.106.0-0.6.21.jar",
          "url": "securityhub-1.106.0-0.6.21.jar",
          "size": 8521,
          "sha512": "2cb76ca957570733985b92108b5ccaef8b6db1fe80e2a9b0f0f6ab9f1c0790153edd771efeebbaf4e5f6dcc2002270df2bd8e4d0dddc3107add24094f57f644",
          "sha256": "15a7be77bca977fbd61927c16c08f7bb37f554ff9dc1f8a9167fd015132e2cc4",
          "sha1": "18bfd12f9ee50218a7d8c7fa3914a7edc46c8f30",
          "md5": "c5c6a00b8f0459ef6c790691fb790299"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "securityhub",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "securityhub-1.106.0-0.6.21.jar",
          "url": "securityhub-1.106.0-0.6.21.jar",
          "size": 8521,
          "sha512": "2cb76ca957570733985b92108b5ccaef8b6db1fe80e2a9b0f0f6ab9f1c0790153edd771efeebbaf4e5f6dcc2002270df2bd8e4d0dddc3107add24094f57f644",
          "sha256": "15a7be77bca977fbd61927c16c08f7bb37f554ff9dc1f8a9167fd015132e2cc4",
          "sha1": "18bfd12f9ee50218a7d8c7fa3914a7edc46c8f30",
          "md5": "c5c6a00b8f0459ef6c790691fb790299"
        }
      ]
    }
  ]
}
