{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "workspaces",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "workspaces",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "workspaces-1.108.0-0.6.21.jar",
          "url": "workspaces-1.108.0-0.6.21.jar",
          "size": 52123,
          "sha512": "af6b9fd36350043be8e8f8c17ad622ab45560b9b92b631453c94f39a65b14c71920b94ca63bdf709876614ec6dd77bbe6cb6a06322995d27ef073e30771273d1",
          "sha256": "4bf93bf085d2f895b873a4edf0c3c2f3846d48797672e2b1971cf0355eb2984c",
          "sha1": "e8021c22635028e7e03c7a50cb42c73646622150",
          "md5": "80a454aa2cd08b13a168534d54a9b278"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "workspaces",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "workspaces-1.108.0-0.6.21.jar",
          "url": "workspaces-1.108.0-0.6.21.jar",
          "size": 52123,
          "sha512": "af6b9fd36350043be8e8f8c17ad622ab45560b9b92b631453c94f39a65b14c71920b94ca63bdf709876614ec6dd77bbe6cb6a06322995d27ef073e30771273d1",
          "sha256": "4bf93bf085d2f895b873a4edf0c3c2f3846d48797672e2b1971cf0355eb2984c",
          "sha1": "e8021c22635028e7e03c7a50cb42c73646622150",
          "md5": "80a454aa2cd08b13a168534d54a9b278"
        }
      ]
    }
  ]
}
