{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotanalytics",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotanalytics",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotanalytics-1.115.0-0.6.21.jar",
          "url": "iotanalytics-1.115.0-0.6.21.jar",
          "size": 508821,
          "sha512": "397fecdb3976d7f080b95834739b5404844b65b8b0d65c6a4e3a46e415d8daadaadeacb3726fd34d20ac63f75b48d7802ef35d3af38a24e3bf1e5fd3a9819189",
          "sha256": "fef0a3b6b21be5e08fb950955ba8697df6c032b4dcf9a20c0adb285512939809",
          "sha1": "b988f5c824c079c532b54d23f0bec95a2a4e568e",
          "md5": "84ea76a326d307397616da8361086664"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotanalytics",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotanalytics-1.115.0-0.6.21.jar",
          "url": "iotanalytics-1.115.0-0.6.21.jar",
          "size": 508821,
          "sha512": "397fecdb3976d7f080b95834739b5404844b65b8b0d65c6a4e3a46e415d8daadaadeacb3726fd34d20ac63f75b48d7802ef35d3af38a24e3bf1e5fd3a9819189",
          "sha256": "fef0a3b6b21be5e08fb950955ba8697df6c032b4dcf9a20c0adb285512939809",
          "sha1": "b988f5c824c079c532b54d23f0bec95a2a4e568e",
          "md5": "84ea76a326d307397616da8361086664"
        }
      ]
    }
  ]
}
