{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "stepfunctions",
    "version": "1.34.1-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "stepfunctions",
          "version": {
            "requires": "1.34.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "stepfunctions-1.34.1-0.6.23.jar",
          "url": "stepfunctions-1.34.1-0.6.23.jar",
          "size": 175859,
          "sha512": "6ed791e0d8d089a69136f557907eebc17b659609bf531718dede54e31f4ec50abca217d540c1cb66ef9e27e017338c1d297564fb0cede0f9dda5e7e6fc0b4ba3",
          "sha256": "ebb537f014b5c8db1869e18da86d7720856db168b95cfa0ff3673508d968f627",
          "sha1": "92c9913e13a16da4bc48c0911ba740216b365ab7",
          "md5": "80d2c5a7e90e8ed18dbe2c2f53ccdc3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.34.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "stepfunctions",
          "version": {
            "requires": "1.34.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.1-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "stepfunctions-1.34.1-0.6.23.jar",
          "url": "stepfunctions-1.34.1-0.6.23.jar",
          "size": 175859,
          "sha512": "6ed791e0d8d089a69136f557907eebc17b659609bf531718dede54e31f4ec50abca217d540c1cb66ef9e27e017338c1d297564fb0cede0f9dda5e7e6fc0b4ba3",
          "sha256": "ebb537f014b5c8db1869e18da86d7720856db168b95cfa0ff3673508d968f627",
          "sha1": "92c9913e13a16da4bc48c0911ba740216b365ab7",
          "md5": "80d2c5a7e90e8ed18dbe2c2f53ccdc3d"
        }
      ]
    }
  ]
}
