{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotanalytics",
    "version": "1.117.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ka4pthfoybhvvnwbwaxmu2dbry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotanalytics",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotanalytics-1.117.0-0.6.21.jar",
          "url": "iotanalytics-1.117.0-0.6.21.jar",
          "size": 508843,
          "sha512": "46b95e08be3c0558d89892b2faae9ae6f49a3411697b316312c2b81931ed01b05e0e29fa5020d077704d86f8ccad90183433da1559362574ccee2bb3d9671d04",
          "sha256": "375c89064eb314034c20c4f9d3e308f15f3aa99f26d66cc28c44b6c68f5081a1",
          "sha1": "bfadfe82e3461e836c4a7e3a3768654bc508201d",
          "md5": "d0960c4a7d2fc203f7138c9811c8a1ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotanalytics",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotanalytics-1.117.0-0.6.21.jar",
          "url": "iotanalytics-1.117.0-0.6.21.jar",
          "size": 508843,
          "sha512": "46b95e08be3c0558d89892b2faae9ae6f49a3411697b316312c2b81931ed01b05e0e29fa5020d077704d86f8ccad90183433da1559362574ccee2bb3d9671d04",
          "sha256": "375c89064eb314034c20c4f9d3e308f15f3aa99f26d66cc28c44b6c68f5081a1",
          "sha1": "bfadfe82e3461e836c4a7e3a3768654bc508201d",
          "md5": "d0960c4a7d2fc203f7138c9811c8a1ec"
        }
      ]
    }
  ]
}
