{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "eks",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "eks",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ssm",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-lambda-layer-awscli",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-lambda-layer-kubectl",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eks-1.108.1-0.6.21.jar",
          "url": "eks-1.108.1-0.6.21.jar",
          "size": 332131,
          "sha512": "31f075a3e4e903a7838b3ccc486942ddb6ea9fb5f2cbb90027584493e1c1070c1d8eed8a90bb84af03045eb37787eaa950b7d9fb00c8820f111caf27d12b7f29",
          "sha256": "f03dbffa91319dc91b0b52b0422703b3bc0d2efb49c648921be7ed9a493d3eb8",
          "sha1": "2b5eee119a568e956661129901667c46f9f7048d",
          "md5": "64a56f14b909252639ddfe1a57bd6cd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "eks",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ssm",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-lambda-layer-awscli",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-lambda-layer-kubectl",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eks-1.108.1-0.6.21.jar",
          "url": "eks-1.108.1-0.6.21.jar",
          "size": 332131,
          "sha512": "31f075a3e4e903a7838b3ccc486942ddb6ea9fb5f2cbb90027584493e1c1070c1d8eed8a90bb84af03045eb37787eaa950b7d9fb00c8820f111caf27d12b7f29",
          "sha256": "f03dbffa91319dc91b0b52b0422703b3bc0d2efb49c648921be7ed9a493d3eb8",
          "sha1": "2b5eee119a568e956661129901667c46f9f7048d",
          "md5": "64a56f14b909252639ddfe1a57bd6cd7"
        }
      ]
    }
  ]
}
