{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "pinpointemail",
    "version": "1.98.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "iburyfrpozhnhehtcwiqubp4u4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "pinpointemail",
          "version": {
            "requires": "1.98.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "pinpointemail-1.98.0-0.6.21.jar",
          "url": "pinpointemail-1.98.0-0.6.21.jar",
          "size": 191980,
          "sha512": "ae20e25a6bb2947e235d0be9e2e1aba3d038451b6f116467d45bfb60cf5a4a2a463ec6963e3d845ec553f839063c2bfadecb3a138351bbff0049162b996df665",
          "sha256": "b1f0174b2fb1d9dd4d47007e134e55484cbfc441dc350f3e949d9a1d2ac3adb1",
          "sha1": "67355a4367a92c949f47e95671e84d88c9786640",
          "md5": "ca701af9d487fe617e3d874e4e66b0a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.98.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "pinpointemail",
          "version": {
            "requires": "1.98.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.98.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "pinpointemail-1.98.0-0.6.21.jar",
          "url": "pinpointemail-1.98.0-0.6.21.jar",
          "size": 191980,
          "sha512": "ae20e25a6bb2947e235d0be9e2e1aba3d038451b6f116467d45bfb60cf5a4a2a463ec6963e3d845ec553f839063c2bfadecb3a138351bbff0049162b996df665",
          "sha256": "b1f0174b2fb1d9dd4d47007e134e55484cbfc441dc350f3e949d9a1d2ac3adb1",
          "sha1": "67355a4367a92c949f47e95671e84d88c9786640",
          "md5": "ca701af9d487fe617e3d874e4e66b0a0"
        }
      ]
    }
  ]
}
