{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cloud9",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cloud9",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codecommit",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cloud9-1.116.0-0.6.21.jar",
          "url": "cloud9-1.116.0-0.6.21.jar",
          "size": 32005,
          "sha512": "7aa3c431d2dce083aeffcbf0bfd5474dd103bd1f483e6d5e5a03047ee2b62cc151c8dbc0b04f6498bd08f0c80a1f957d17659eaca58f5220d7de18ba09ef5b01",
          "sha256": "15090c585c63f8d16500fafbb22a39b93a532cbaf175f80579da674fa6aa7450",
          "sha1": "26fc63e885be96a1534bf2a25a1d8b977af40cec",
          "md5": "b888cebc660abd3d7e380ed181d2e04c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cloud9",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "codecommit",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cloud9-1.116.0-0.6.21.jar",
          "url": "cloud9-1.116.0-0.6.21.jar",
          "size": 32005,
          "sha512": "7aa3c431d2dce083aeffcbf0bfd5474dd103bd1f483e6d5e5a03047ee2b62cc151c8dbc0b04f6498bd08f0c80a1f957d17659eaca58f5220d7de18ba09ef5b01",
          "sha256": "15090c585c63f8d16500fafbb22a39b93a532cbaf175f80579da674fa6aa7450",
          "sha1": "26fc63e885be96a1534bf2a25a1d8b977af40cec",
          "md5": "b888cebc660abd3d7e380ed181d2e04c"
        }
      ]
    }
  ]
}
