{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "core",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.114.0-0.6.21.jar",
          "url": "core-1.114.0-0.6.21.jar",
          "size": 547143,
          "sha512": "9c8c628004bc299066bc1a2a05212930455d8fb7658c9715c925abf2e7c5e71d924651d13e6ccb94947f88367ec6616dd33b1a4af5893af7516f0d49fc5211fb",
          "sha256": "85d9f9ccb530a9e0985ce213baea053e4f39469e24f80e9173680967f0fb0f2a",
          "sha1": "ad317c8b6877fb7f7c04ce1f4e8f39d0ba94139f",
          "md5": "65b79b4b8d866ff446acfd00c93dc01f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.114.0-0.6.21.jar",
          "url": "core-1.114.0-0.6.21.jar",
          "size": 547143,
          "sha512": "9c8c628004bc299066bc1a2a05212930455d8fb7658c9715c925abf2e7c5e71d924651d13e6ccb94947f88367ec6616dd33b1a4af5893af7516f0d49fc5211fb",
          "sha256": "85d9f9ccb530a9e0985ce213baea053e4f39469e24f80e9173680967f0fb0f2a",
          "sha1": "ad317c8b6877fb7f7c04ce1f4e8f39d0ba94139f",
          "md5": "65b79b4b8d866ff446acfd00c93dc01f"
        }
      ]
    }
  ]
}
