{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "guardduty",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "guardduty",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "guardduty-1.111.0-0.6.21.jar",
          "url": "guardduty-1.111.0-0.6.21.jar",
          "size": 126573,
          "sha512": "36f560101fe32d316bd75e3870ec26131a962ed6e5b1cf0bcbc8c2f1fb1f9092dd0e5e81669df5ae51825be7120db72942dc1a0131efaf8472db8dcbae850e69",
          "sha256": "248c49c8a58941bc2b06eec3ebf48712964ab76c9630fb272f6b539d521d7b9e",
          "sha1": "f04a5004b0103039a615cd2e792c5baa3644ee9a",
          "md5": "5fc79bbbe564e68f6d06729577dd8223"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "guardduty",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "guardduty-1.111.0-0.6.21.jar",
          "url": "guardduty-1.111.0-0.6.21.jar",
          "size": 126573,
          "sha512": "36f560101fe32d316bd75e3870ec26131a962ed6e5b1cf0bcbc8c2f1fb1f9092dd0e5e81669df5ae51825be7120db72942dc1a0131efaf8472db8dcbae850e69",
          "sha256": "248c49c8a58941bc2b06eec3ebf48712964ab76c9630fb272f6b539d521d7b9e",
          "sha1": "f04a5004b0103039a615cd2e792c5baa3644ee9a",
          "md5": "5fc79bbbe564e68f6d06729577dd8223"
        }
      ]
    }
  ]
}
