{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cloudfront-origins",
    "version": "1.59.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cloudfront-origins",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudfront",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "cloudfront-origins-1.59.0-0.6.22.jar",
          "url": "cloudfront-origins-1.59.0-0.6.22.jar",
          "size": 21106,
          "sha512": "67184429d92e7f8ed0d202350e4ce373de7f06b6e04d219703a7fe1aecb1ae27a80aa69b1949ed136cd72d2977fea3198462961423f63e18db39223f6553f1a8",
          "sha256": "550f0424771a05f6a0d30b82dd1494a5d3c7c94be6fe12bb31d73eaf3829ad45",
          "sha1": "f562e52770eec2a963416da117f56acc1a8aa480",
          "md5": "92f4fd7c001ad282b0e3fda9f8f94928"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cloudfront-origins",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudfront",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "cloudfront-origins-1.59.0-0.6.22.jar",
          "url": "cloudfront-origins-1.59.0-0.6.22.jar",
          "size": 21106,
          "sha512": "67184429d92e7f8ed0d202350e4ce373de7f06b6e04d219703a7fe1aecb1ae27a80aa69b1949ed136cd72d2977fea3198462961423f63e18db39223f6553f1a8",
          "sha256": "550f0424771a05f6a0d30b82dd1494a5d3c7c94be6fe12bb31d73eaf3829ad45",
          "sha1": "f562e52770eec2a963416da117f56acc1a8aa480",
          "md5": "92f4fd7c001ad282b0e3fda9f8f94928"
        }
      ]
    }
  ]
}
