{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "globalaccelerator",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "globalaccelerator",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "globalaccelerator-1.99.0-0.6.21.jar",
          "url": "globalaccelerator-1.99.0-0.6.21.jar",
          "size": 128348,
          "sha512": "aa62a448f415e46d20b1c35c0ca7f0eb6f4a19bb37347662e5d7aa7c20c30f38f5593dc42428e671b16809813368fa5c70f1e2f55d382f79b9b0ff751e2ee348",
          "sha256": "d238ebbd7bb08411f7eb956969cf9158baba85e45956afee0c5ed66afc761f44",
          "sha1": "7797cbc8f5ac21d27c292b8f9fc643f81513ae40",
          "md5": "fcc5c3e41ea002e5af4148a0f90c806b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "globalaccelerator",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "globalaccelerator-1.99.0-0.6.21.jar",
          "url": "globalaccelerator-1.99.0-0.6.21.jar",
          "size": 128348,
          "sha512": "aa62a448f415e46d20b1c35c0ca7f0eb6f4a19bb37347662e5d7aa7c20c30f38f5593dc42428e671b16809813368fa5c70f1e2f55d382f79b9b0ff751e2ee348",
          "sha256": "d238ebbd7bb08411f7eb956969cf9158baba85e45956afee0c5ed66afc761f44",
          "sha1": "7797cbc8f5ac21d27c292b8f9fc643f81513ae40",
          "md5": "fcc5c3e41ea002e5af4148a0f90c806b"
        }
      ]
    }
  ]
}
