{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-assets",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-1.107.0-0.6.21.jar",
          "url": "cdk-assets-1.107.0-0.6.21.jar",
          "size": 16457,
          "sha512": "46770da054d096b574fb6259d442c6cf79123060d04b6f43ad3ec66287847f92ea7567874f446dd0dd590cfa767a851498c112e891f0c00736a61ff17548d280",
          "sha256": "e187fbafddb3df1288e20d28c01a023b69ba9c11235af2f5e02de35b64c956d0",
          "sha1": "2e6c9feb77f9965aab1b6e6db174722fb55ddd01",
          "md5": "387e0aac53bcbcb954c5a9183761fabc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-1.107.0-0.6.21.jar",
          "url": "cdk-assets-1.107.0-0.6.21.jar",
          "size": 16457,
          "sha512": "46770da054d096b574fb6259d442c6cf79123060d04b6f43ad3ec66287847f92ea7567874f446dd0dd590cfa767a851498c112e891f0c00736a61ff17548d280",
          "sha256": "e187fbafddb3df1288e20d28c01a023b69ba9c11235af2f5e02de35b64c956d0",
          "sha1": "2e6c9feb77f9965aab1b6e6db174722fb55ddd01",
          "md5": "387e0aac53bcbcb954c5a9183761fabc"
        }
      ]
    }
  ]
}
