{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "medialive",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "medialive",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "medialive-1.105.0-0.6.21.jar",
          "url": "medialive-1.105.0-0.6.21.jar",
          "size": 1423557,
          "sha512": "f698ceaa445760688911f11a19f7fd43d256a590d6447b50188acc69240b059958d6e123f871ff77bc533d778cca48a9f90f789a57393091d8bca3a2387e7d77",
          "sha256": "cef9e0481028c791a9c51580c3612d742fcdf2d9c379ee32bca384bf09656fd1",
          "sha1": "aa02e6ee47fe7386b4cc24d32617ae4f49ed4bb7",
          "md5": "b9e5de5f3f9320ef98165295b860c878"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "medialive",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "medialive-1.105.0-0.6.21.jar",
          "url": "medialive-1.105.0-0.6.21.jar",
          "size": 1423557,
          "sha512": "f698ceaa445760688911f11a19f7fd43d256a590d6447b50188acc69240b059958d6e123f871ff77bc533d778cca48a9f90f789a57393091d8bca3a2387e7d77",
          "sha256": "cef9e0481028c791a9c51580c3612d742fcdf2d9c379ee32bca384bf09656fd1",
          "sha1": "aa02e6ee47fe7386b4cc24d32617ae4f49ed4bb7",
          "md5": "b9e5de5f3f9320ef98165295b860c878"
        }
      ]
    }
  ]
}
