{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codegurureviewer",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codegurureviewer",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codegurureviewer-1.108.1-0.6.21.jar",
          "url": "codegurureviewer-1.108.1-0.6.21.jar",
          "size": 9906,
          "sha512": "92b001e4f3b12ad55106e22644de49b2da74907e163b011f9ceecd859b21cab3e18a6b37ab22996f43c7754216bb7e96c99f908c3b8ca355fc2bd3d687d6c2a5",
          "sha256": "5d1d34416f697923eceb532d43e03b058e0dc6dba10b4139ce8df95a4b8c5958",
          "sha1": "f21addb6c49200dd34316984f01a5587ae7c4a91",
          "md5": "2eac2a002ba00a7bec07e180edfa0954"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codegurureviewer",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codegurureviewer-1.108.1-0.6.21.jar",
          "url": "codegurureviewer-1.108.1-0.6.21.jar",
          "size": 9906,
          "sha512": "92b001e4f3b12ad55106e22644de49b2da74907e163b011f9ceecd859b21cab3e18a6b37ab22996f43c7754216bb7e96c99f908c3b8ca355fc2bd3d687d6c2a5",
          "sha256": "5d1d34416f697923eceb532d43e03b058e0dc6dba10b4139ce8df95a4b8c5958",
          "sha1": "f21addb6c49200dd34316984f01a5587ae7c4a91",
          "md5": "2eac2a002ba00a7bec07e180edfa0954"
        }
      ]
    }
  ]
}
