{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "autoscaling-common",
    "version": "1.64.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling-common",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-common-1.64.0-0.6.23.jar",
          "url": "autoscaling-common-1.64.0-0.6.23.jar",
          "size": 15783,
          "sha512": "75a9f4edb9bf9bcfef592f5f89831ba65c0d577551ffebd0f748622d33eb14318191f2ffa2f9ff0386d7c9df0e11f47d133d8e56b532ad6572774007b6f99a49",
          "sha256": "ab127c580825d34d722aabc416a47cd8b8211dbdc27d206638b8426a77d82a56",
          "sha1": "01a6d101569e6d95e16b78d71893b542cddf4ff8",
          "md5": "3de3c883c4ac250c884c3bc37e4cbf80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling-common",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-common-1.64.0-0.6.23.jar",
          "url": "autoscaling-common-1.64.0-0.6.23.jar",
          "size": 15783,
          "sha512": "75a9f4edb9bf9bcfef592f5f89831ba65c0d577551ffebd0f748622d33eb14318191f2ffa2f9ff0386d7c9df0e11f47d133d8e56b532ad6572774007b6f99a49",
          "sha256": "ab127c580825d34d722aabc416a47cd8b8211dbdc27d206638b8426a77d82a56",
          "sha1": "01a6d101569e6d95e16b78d71893b542cddf4ff8",
          "md5": "3de3c883c4ac250c884c3bc37e4cbf80"
        }
      ]
    }
  ]
}
