{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "autoscaling",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling-common",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancing",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-1.107.0-0.6.21.jar",
          "url": "autoscaling-1.107.0-0.6.21.jar",
          "size": 475723,
          "sha512": "e8b678a86599bc1d527ef24c69ce1fbd4596b2b3d503b296759381aa28e2800c0089c39c300d536a9c1fe18220ea54ee0fdcd4e14fbca36ef6553a712b601774",
          "sha256": "5fd80ee95f6227370a969ef23396503594cd49f619ad42b43ccec0fe856e1300",
          "sha1": "254594afb7fd8d8612eaab8a3685f3631a3d8700",
          "md5": "87fe9f9e7ed444b77645b5e10aa36d56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling-common",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancing",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-1.107.0-0.6.21.jar",
          "url": "autoscaling-1.107.0-0.6.21.jar",
          "size": 475723,
          "sha512": "e8b678a86599bc1d527ef24c69ce1fbd4596b2b3d503b296759381aa28e2800c0089c39c300d536a9c1fe18220ea54ee0fdcd4e14fbca36ef6553a712b601774",
          "sha256": "5fd80ee95f6227370a969ef23396503594cd49f619ad42b43ccec0fe856e1300",
          "sha1": "254594afb7fd8d8612eaab8a3685f3631a3d8700",
          "md5": "87fe9f9e7ed444b77645b5e10aa36d56"
        }
      ]
    }
  ]
}
