{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "events",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "events",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "events-1.106.0-0.6.21.jar",
          "url": "events-1.106.0-0.6.21.jar",
          "size": 259587,
          "sha512": "c274acb6cf8cbc2886588910f010b91545c8c5ac2dec0eb99f0d473a7445a3cbc3aa68a8a7940e2bde0c09439e2215ca70826428ceee23d5af1ed349fdb5d40f",
          "sha256": "1597d32f0fd4cbb6d90881a20634ed7aabbc3c65ae0b38de1caba36b84e6a6d4",
          "sha1": "9060fade45a42012895754c5433db4a20ddde8a7",
          "md5": "aa59b71215d9cd307f8f69ae646758af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "events",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "events-1.106.0-0.6.21.jar",
          "url": "events-1.106.0-0.6.21.jar",
          "size": 259587,
          "sha512": "c274acb6cf8cbc2886588910f010b91545c8c5ac2dec0eb99f0d473a7445a3cbc3aa68a8a7940e2bde0c09439e2215ca70826428ceee23d5af1ed349fdb5d40f",
          "sha256": "1597d32f0fd4cbb6d90881a20634ed7aabbc3c65ae0b38de1caba36b84e6a6d4",
          "sha1": "9060fade45a42012895754c5433db4a20ddde8a7",
          "md5": "aa59b71215d9cd307f8f69ae646758af"
        }
      ]
    }
  ]
}
