{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "imagebuilder",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.106.0-0.6.21.jar",
          "url": "imagebuilder-1.106.0-0.6.21.jar",
          "size": 284968,
          "sha512": "9ce037b7f384daf9dec7c4d4dbdb1e927f5ad944e9213a7892d5336c0f9011a24eba29bf651699187d95f9c212ddc97f54ed95b59db534172b52949602823222",
          "sha256": "929c8e7c1979f83d43e1344ed84fb05e73d8b2e5224531f7611d6bd56ad53d01",
          "sha1": "6604205f24268ec0045ce2d355c393863dcf48d7",
          "md5": "d676b818332b009ed1b058b01261bc6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.106.0-0.6.21.jar",
          "url": "imagebuilder-1.106.0-0.6.21.jar",
          "size": 284968,
          "sha512": "9ce037b7f384daf9dec7c4d4dbdb1e927f5ad944e9213a7892d5336c0f9011a24eba29bf651699187d95f9c212ddc97f54ed95b59db534172b52949602823222",
          "sha256": "929c8e7c1979f83d43e1344ed84fb05e73d8b2e5224531f7611d6bd56ad53d01",
          "sha1": "6604205f24268ec0045ce2d355c393863dcf48d7",
          "md5": "d676b818332b009ed1b058b01261bc6e"
        }
      ]
    }
  ]
}
