{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "appsync",
    "version": "1.64.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "appsync",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cognito",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dynamodb",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "appsync-1.64.0-0.6.23.jar",
          "url": "appsync-1.64.0-0.6.23.jar",
          "size": 475880,
          "sha512": "8a04d26e761a20c2653e4fbb5942888fe3b06473351df9d1675a8ee73a98d6b7c292d5aacfbd0a66d57caf2d69d1416c306c761d4a0f8d3b7027a347b17b24f6",
          "sha256": "8ee64dd3bda621a53be8e1e63dd41d1fd4910064b09477380a36eb2207b5e012",
          "sha1": "130770737d591e78eab0c328634978437801e30f",
          "md5": "36d72b93afcf70a18f3011f6aaf98e7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "appsync",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cognito",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dynamodb",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "appsync-1.64.0-0.6.23.jar",
          "url": "appsync-1.64.0-0.6.23.jar",
          "size": 475880,
          "sha512": "8a04d26e761a20c2653e4fbb5942888fe3b06473351df9d1675a8ee73a98d6b7c292d5aacfbd0a66d57caf2d69d1416c306c761d4a0f8d3b7027a347b17b24f6",
          "sha256": "8ee64dd3bda621a53be8e1e63dd41d1fd4910064b09477380a36eb2207b5e012",
          "sha1": "130770737d591e78eab0c328634978437801e30f",
          "md5": "36d72b93afcf70a18f3011f6aaf98e7d"
        }
      ]
    }
  ]
}
