{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sns",
    "version": "1.59.0-0.6.23.jdk8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sns",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.59.0-0.6.23.jdk8"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.59.0-0.6.23.jdk8"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.59.0-0.6.23.jdk8"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.59.0-0.6.23.jdk8"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.59.0-0.6.23.jdk8"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.23.jdk8"
          }
        }
      ],
      "files": [
        {
          "name": "sns-1.59.0-0.6.23.jdk8.jar",
          "url": "sns-1.59.0-0.6.23.jdk8.jar",
          "size": 103006,
          "sha512": "7d7423b3991251782085fa7ffd51a612715ca77dc5f1b0d1d3531a1a581d64777d19cf8fe86945cc3e6a3886a245a0676497b8a4e8af5423279ad91b71ad205a",
          "sha256": "0c6bc69a03d33f4d91cdb57a80b64b7c11342413cc6445db57852c8da5b3d6ee",
          "sha1": "7b9dc8776da4a58afa3f9463e8046c88b187d5ff",
          "md5": "0538bfc63ebbaafa02a8730e3323df5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23.jdk8"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sns",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.59.0-0.6.23.jdk8"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.59.0-0.6.23.jdk8"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.59.0-0.6.23.jdk8"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.59.0-0.6.23.jdk8"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.59.0-0.6.23.jdk8"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.23.jdk8"
          }
        }
      ],
      "files": [
        {
          "name": "sns-1.59.0-0.6.23.jdk8.jar",
          "url": "sns-1.59.0-0.6.23.jdk8.jar",
          "size": 103006,
          "sha512": "7d7423b3991251782085fa7ffd51a612715ca77dc5f1b0d1d3531a1a581d64777d19cf8fe86945cc3e6a3886a245a0676497b8a4e8af5423279ad91b71ad205a",
          "sha256": "0c6bc69a03d33f4d91cdb57a80b64b7c11342413cc6445db57852c8da5b3d6ee",
          "sha1": "7b9dc8776da4a58afa3f9463e8046c88b187d5ff",
          "md5": "0538bfc63ebbaafa02a8730e3323df5c"
        }
      ]
    }
  ]
}
