{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticache",
    "version": "1.117.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ka4pthfoybhvvnwbwaxmu2dbry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticache",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticache-1.117.0-0.6.21.jar",
          "url": "elasticache-1.117.0-0.6.21.jar",
          "size": 281342,
          "sha512": "e7903233f2d794959625ca04d3e8c7e492a2562188c41ec1970e7048e57549dc0dfaea97b59e4c75a9c4067e869248f4c7aa3a33ca109769ddd4e20ed86df023",
          "sha256": "3428fd1f0ff3c4ec4112f012aa2792358529fcce31f79224edf58b2caff360c5",
          "sha1": "1a82d10c4ad1d2a4c7ca8e3e6c01edc7ee41cf94",
          "md5": "6c21d12a7a0db428a6c6964f96b2d40d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticache",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticache-1.117.0-0.6.21.jar",
          "url": "elasticache-1.117.0-0.6.21.jar",
          "size": 281342,
          "sha512": "e7903233f2d794959625ca04d3e8c7e492a2562188c41ec1970e7048e57549dc0dfaea97b59e4c75a9c4067e869248f4c7aa3a33ca109769ddd4e20ed86df023",
          "sha256": "3428fd1f0ff3c4ec4112f012aa2792358529fcce31f79224edf58b2caff360c5",
          "sha1": "1a82d10c4ad1d2a4c7ca8e3e6c01edc7ee41cf94",
          "md5": "6c21d12a7a0db428a6c6964f96b2d40d"
        }
      ]
    }
  ]
}
