{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "apigatewayv2",
    "version": "1.59.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "apigatewayv2",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "certificatemanager",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "apigatewayv2-1.59.0-0.6.22.jar",
          "url": "apigatewayv2-1.59.0-0.6.22.jar",
          "size": 428431,
          "sha512": "c2d909ca7781a79f5dded7e89c81bae034a67701c53e3ebda2c092efa30729c1089cb80a52ee7f969eaad631b2d56c462c560f452d51835578a530a289a01afa",
          "sha256": "35698d22d8d814c509b9883c04858b4e46a3ad7d12cf7d398d35fde48c26ad1c",
          "sha1": "1dcd93cb96e04e0f8dcb873507d40611eff0915e",
          "md5": "824de40d3ffd60b59349955661bde3d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "apigatewayv2",
          "version": {
            "requires": "1.59.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "certificatemanager",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.59.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "apigatewayv2-1.59.0-0.6.22.jar",
          "url": "apigatewayv2-1.59.0-0.6.22.jar",
          "size": 428431,
          "sha512": "c2d909ca7781a79f5dded7e89c81bae034a67701c53e3ebda2c092efa30729c1089cb80a52ee7f969eaad631b2d56c462c560f452d51835578a530a289a01afa",
          "sha256": "35698d22d8d814c509b9883c04858b4e46a3ad7d12cf7d398d35fde48c26ad1c",
          "sha1": "1dcd93cb96e04e0f8dcb873507d40611eff0915e",
          "md5": "824de40d3ffd60b59349955661bde3d7"
        }
      ]
    }
  ]
}
