{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticbeanstalk",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticbeanstalk",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "elasticbeanstalk-1.117.0-0.6.25.jar",
          "url": "elasticbeanstalk-1.117.0-0.6.25.jar",
          "size": 155082,
          "sha512": "ada619d5ce991eb224ac8a744960ef56cf4624feb08d04cc302b991ee67c8b647faefde7b52831be22dd0fa48719fc9b93b5aa68cb27ffd2a551f1e139123c8f",
          "sha256": "1dc8378343c94014161e6f105e64a9f4c82fada7c878fc42ad85a112f5bce92f",
          "sha1": "8d7394c8fd2ada682ba8216ab49000e5f20494b3",
          "md5": "29dd757bbbcf6a6afa179cef234d34e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticbeanstalk",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "elasticbeanstalk-1.117.0-0.6.25.jar",
          "url": "elasticbeanstalk-1.117.0-0.6.25.jar",
          "size": 155082,
          "sha512": "ada619d5ce991eb224ac8a744960ef56cf4624feb08d04cc302b991ee67c8b647faefde7b52831be22dd0fa48719fc9b93b5aa68cb27ffd2a551f1e139123c8f",
          "sha256": "1dc8378343c94014161e6f105e64a9f4c82fada7c878fc42ad85a112f5bce92f",
          "sha1": "8d7394c8fd2ada682ba8216ab49000e5f20494b3",
          "md5": "29dd757bbbcf6a6afa179cef234d34e8"
        }
      ]
    }
  ]
}
