{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "kinesisanalytics",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "kinesisanalytics",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesisanalytics-1.99.0-0.6.21.jar",
          "url": "kinesisanalytics-1.99.0-0.6.21.jar",
          "size": 623092,
          "sha512": "254ed99ac7c914bb89e9189d07877b024fae0461b566abe83eed0e07aa4670636d754b68b97e664b3ebed637ff6c7c24945f86d4e7670a9dbf1272f7b446ce84",
          "sha256": "1517909e3dcfaff4161ca455a05ac140b00e64be43d8a4fabb919755d983dcc8",
          "sha1": "5cf86606e2edda0ad8c3f5a4b03b576542841f5d",
          "md5": "64ddcf963fa8bef6b60f36d6f85f197c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "kinesisanalytics",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesisanalytics-1.99.0-0.6.21.jar",
          "url": "kinesisanalytics-1.99.0-0.6.21.jar",
          "size": 623092,
          "sha512": "254ed99ac7c914bb89e9189d07877b024fae0461b566abe83eed0e07aa4670636d754b68b97e664b3ebed637ff6c7c24945f86d4e7670a9dbf1272f7b446ce84",
          "sha256": "1517909e3dcfaff4161ca455a05ac140b00e64be43d8a4fabb919755d983dcc8",
          "sha1": "5cf86606e2edda0ad8c3f5a4b03b576542841f5d",
          "md5": "64ddcf963fa8bef6b60f36d6f85f197c"
        }
      ]
    }
  ]
}
