{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticloadbalancingv2",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "certificatemanager",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticloadbalancingv2-1.111.0-0.6.21.jar",
          "url": "elasticloadbalancingv2-1.111.0-0.6.21.jar",
          "size": 613003,
          "sha512": "1c74717e8128b2222a49a5d8268dea6c6416f02c5bfde1131cd85d1ad634148151ba3ad462a9477825c0be0f5789c182926c85bdd58aaea4d4d5bda8ece83a25",
          "sha256": "8a246910c557fef5414c13171375286bdf77592a24eb3e3449cdb727a9d94829",
          "sha1": "cda81a30ce2152629bd9e90d569fae37a1479c82",
          "md5": "45a3530f5a6f16c024fe205a5cdeb6ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "certificatemanager",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticloadbalancingv2-1.111.0-0.6.21.jar",
          "url": "elasticloadbalancingv2-1.111.0-0.6.21.jar",
          "size": 613003,
          "sha512": "1c74717e8128b2222a49a5d8268dea6c6416f02c5bfde1131cd85d1ad634148151ba3ad462a9477825c0be0f5789c182926c85bdd58aaea4d4d5bda8ece83a25",
          "sha256": "8a246910c557fef5414c13171375286bdf77592a24eb3e3449cdb727a9d94829",
          "sha1": "cda81a30ce2152629bd9e90d569fae37a1479c82",
          "md5": "45a3530f5a6f16c024fe205a5cdeb6ab"
        }
      ]
    }
  ]
}
