{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "glue",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "k23roxkwqjbs5i6arr4lg4r4xm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "glue",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "glue-1.110.1-0.6.21.jar",
          "url": "glue-1.110.1-0.6.21.jar",
          "size": 812319,
          "sha512": "3ef2f6dfac5bd36b4fe03d92a60e2f9b52900a626897ac18c69fb4d840cc94200121af079b84bfec2b04f815089a6697bbf7cfc453ff0100b22393f3fba6046a",
          "sha256": "c3f1ab87a47ff77dab76e8e359b5a8be18b2c52ecee905a236e841e692d2b3d",
          "sha1": "f933d82238e4d2f927d13c4c7e4e11cd21e85bba",
          "md5": "15c02fa7a24d005b4d5d5a3db51a47c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "glue",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "glue-1.110.1-0.6.21.jar",
          "url": "glue-1.110.1-0.6.21.jar",
          "size": 812319,
          "sha512": "3ef2f6dfac5bd36b4fe03d92a60e2f9b52900a626897ac18c69fb4d840cc94200121af079b84bfec2b04f815089a6697bbf7cfc453ff0100b22393f3fba6046a",
          "sha256": "c3f1ab87a47ff77dab76e8e359b5a8be18b2c52ecee905a236e841e692d2b3d",
          "sha1": "f933d82238e4d2f927d13c4c7e4e11cd21e85bba",
          "md5": "15c02fa7a24d005b4d5d5a3db51a47c4"
        }
      ]
    }
  ]
}
