{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ce",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ce",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ce-1.107.0-0.6.21.jar",
          "url": "ce-1.107.0-0.6.21.jar",
          "size": 36793,
          "sha512": "9e7579efa1ad04e90dd51aefce680b7c5bc460a7a97c1d2448a98f0a66e6f2fee01c977c8505d1d66f22c99355a3116a467222abf2e9e40e886deaef55a0c9bb",
          "sha256": "1fa322b17e0449ffa881c2aee7be8f38a7a53d78956c3bd1a47cfa9652990498",
          "sha1": "ff733176558c737ad20cc78c72805219cba3b158",
          "md5": "2018feb548e1da82d3b6849c9883b889"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ce",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ce-1.107.0-0.6.21.jar",
          "url": "ce-1.107.0-0.6.21.jar",
          "size": 36793,
          "sha512": "9e7579efa1ad04e90dd51aefce680b7c5bc460a7a97c1d2448a98f0a66e6f2fee01c977c8505d1d66f22c99355a3116a467222abf2e9e40e886deaef55a0c9bb",
          "sha256": "1fa322b17e0449ffa881c2aee7be8f38a7a53d78956c3bd1a47cfa9652990498",
          "sha1": "ff733176558c737ad20cc78c72805219cba3b158",
          "md5": "2018feb548e1da82d3b6849c9883b889"
        }
      ]
    }
  ]
}
