{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotevents",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotevents",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotevents-1.102.0-0.6.21.jar",
          "url": "iotevents-1.102.0-0.6.21.jar",
          "size": 292837,
          "sha512": "bf29eb08c0658e306939b9cbde632509ec2c3ea773dbe71743ea5dc9c64740d0f6d08dbc492872fd4b8131761a00deda775fde1900f12e03d9b5c9eb1fbfac2c",
          "sha256": "c70bbe26c74db90441d5e6c2b20684bd8d2689668062221c7c8425097b0f169",
          "sha1": "5aa6264748a5bfee291f5b02d795227525e3bab0",
          "md5": "7bbda95d0813148e7a2ccb488bab8c1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotevents",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotevents-1.102.0-0.6.21.jar",
          "url": "iotevents-1.102.0-0.6.21.jar",
          "size": 292837,
          "sha512": "bf29eb08c0658e306939b9cbde632509ec2c3ea773dbe71743ea5dc9c64740d0f6d08dbc492872fd4b8131761a00deda775fde1900f12e03d9b5c9eb1fbfac2c",
          "sha256": "c70bbe26c74db90441d5e6c2b20684bd8d2689668062221c7c8425097b0f169",
          "sha1": "5aa6264748a5bfee291f5b02d795227525e3bab0",
          "md5": "7bbda95d0813148e7a2ccb488bab8c1d"
        }
      ]
    }
  ]
}
