{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "budgets",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "budgets",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "budgets-1.108.0-0.6.21.jar",
          "url": "budgets-1.108.0-0.6.21.jar",
          "size": 190292,
          "sha512": "b3726c903e99e7bd4ccf80b12773dd7f594c45d033c8e5a41253e56b78588dfb42d64e622221641c3fba09174b756ef810f16ac448f27f9e52a761369784c0ce",
          "sha256": "7bfe89dd03bdac7301790c1fad1653c27111804696f292488e95f093d70753b9",
          "sha1": "3cdb19a04db5d95ffcb3e055f92e82cec0dacfc0",
          "md5": "4c0fbb3af3930663b3d108aff74fca89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "budgets",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "budgets-1.108.0-0.6.21.jar",
          "url": "budgets-1.108.0-0.6.21.jar",
          "size": 190292,
          "sha512": "b3726c903e99e7bd4ccf80b12773dd7f594c45d033c8e5a41253e56b78588dfb42d64e622221641c3fba09174b756ef810f16ac448f27f9e52a761369784c0ce",
          "sha256": "7bfe89dd03bdac7301790c1fad1653c27111804696f292488e95f093d70753b9",
          "sha1": "3cdb19a04db5d95ffcb3e055f92e82cec0dacfc0",
          "md5": "4c0fbb3af3930663b3d108aff74fca89"
        }
      ]
    }
  ]
}
