{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "networkmanager",
    "version": "1.101.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "jaowebu54rhl3bnpwvdhdg2v5y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "networkmanager",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "networkmanager-1.101.0-0.6.21.jar",
          "url": "networkmanager-1.101.0-0.6.21.jar",
          "size": 92759,
          "sha512": "21627e3f7ac263a00078cc2180ed231dd7225bd9b668f507b5dafceed0d86a60b6e749e7337fecda31cd5ed195deb436fe6d4b61b76668175cda5df5285ad68c",
          "sha256": "eeff8d571f9ebb1155651790a52f12de29f6111dc9028306df93211165c5a97b",
          "sha1": "f554a4c462497ce31e5e9400e2ced15af1ec75e6",
          "md5": "b99204f8a5179432862ea91ac9a449bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "networkmanager",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "networkmanager-1.101.0-0.6.21.jar",
          "url": "networkmanager-1.101.0-0.6.21.jar",
          "size": 92759,
          "sha512": "21627e3f7ac263a00078cc2180ed231dd7225bd9b668f507b5dafceed0d86a60b6e749e7337fecda31cd5ed195deb436fe6d4b61b76668175cda5df5285ad68c",
          "sha256": "eeff8d571f9ebb1155651790a52f12de29f6111dc9028306df93211165c5a97b",
          "sha1": "f554a4c462497ce31e5e9400e2ced15af1ec75e6",
          "md5": "b99204f8a5179432862ea91ac9a449bb"
        }
      ]
    }
  ]
}
