{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "imagebuilder",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.115.0-0.6.21.jar",
          "url": "imagebuilder-1.115.0-0.6.21.jar",
          "size": 284996,
          "sha512": "3910f709ea3e145c118bb79473b0f4dd7507b83050bcb2c07df16595d27803b499a7969572c39c44207241e1f820bacebb7566a5d22fff3507f906cb938debe5",
          "sha256": "1587f4acb69c8bd5f418d856cdaeec4dec4fb8911df40ab431484f05c42544fd",
          "sha1": "eda47ba117def1f5c0e21293827ec92d4fe86a2f",
          "md5": "c0d4c77ec9f4da7a3018e49cf30e9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.115.0-0.6.21.jar",
          "url": "imagebuilder-1.115.0-0.6.21.jar",
          "size": 284996,
          "sha512": "3910f709ea3e145c118bb79473b0f4dd7507b83050bcb2c07df16595d27803b499a7969572c39c44207241e1f820bacebb7566a5d22fff3507f906cb938debe5",
          "sha256": "1587f4acb69c8bd5f418d856cdaeec4dec4fb8911df40ab431484f05c42544fd",
          "sha1": "eda47ba117def1f5c0e21293827ec92d4fe86a2f",
          "md5": "c0d4c77ec9f4da7a3018e49cf30e9f"
        }
      ]
    }
  ]
}
