{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "transfer",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "transfer",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "transfer-1.116.0-0.6.21.jar",
          "url": "transfer-1.116.0-0.6.21.jar",
          "size": 86824,
          "sha512": "21cadcd1bfbba2f35306f03a9f8041dcc23c1df47075d56714510cb27820498a7d0cf87b5c8e58db3d3c1e81bd98cb0c763b91d64e8f78b0b1e0361060675a6b",
          "sha256": "950ba03ac4ebe6a405112c82daad6f1e75fa0333b8afe663584c90c5242063c5",
          "sha1": "75ce9c0016354d0b6cfb5e3bcc980ac99ea30dbd",
          "md5": "2735a7f75da4d9e1ebf4a55e12172d81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "transfer",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "transfer-1.116.0-0.6.21.jar",
          "url": "transfer-1.116.0-0.6.21.jar",
          "size": 86824,
          "sha512": "21cadcd1bfbba2f35306f03a9f8041dcc23c1df47075d56714510cb27820498a7d0cf87b5c8e58db3d3c1e81bd98cb0c763b91d64e8f78b0b1e0361060675a6b",
          "sha256": "950ba03ac4ebe6a405112c82daad6f1e75fa0333b8afe663584c90c5242063c5",
          "sha1": "75ce9c0016354d0b6cfb5e3bcc980ac99ea30dbd",
          "md5": "2735a7f75da4d9e1ebf4a55e12172d81"
        }
      ]
    }
  ]
}
