{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-cloud-assembly-schema",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.114.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cloud-assembly-schema-1.114.0-0.6.21.jar",
          "url": "cdk-cloud-assembly-schema-1.114.0-0.6.21.jar",
          "size": 143569,
          "sha512": "cdc9cd88022892cdfeb05e84bf16a334cc8c62cac1b141c8b9fbff78b8a62d50bd051538863facf1dd9eea831afd95653d270f1d31a4b8cb55b084f321f4836a",
          "sha256": "c5ac6ccc94eeacbee924acfe73e3ed5758b93711dc0bf0c07ba5fb982703e532",
          "sha1": "d895671a2c5f9bcbc728980a010e7b33afd3340b",
          "md5": "b46956acbdab4e73a4497ffda0eca4a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.114.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cloud-assembly-schema-1.114.0-0.6.21.jar",
          "url": "cdk-cloud-assembly-schema-1.114.0-0.6.21.jar",
          "size": 143569,
          "sha512": "cdc9cd88022892cdfeb05e84bf16a334cc8c62cac1b141c8b9fbff78b8a62d50bd051538863facf1dd9eea831afd95653d270f1d31a4b8cb55b084f321f4836a",
          "sha256": "c5ac6ccc94eeacbee924acfe73e3ed5758b93711dc0bf0c07ba5fb982703e532",
          "sha1": "d895671a2c5f9bcbc728980a010e7b33afd3340b",
          "md5": "b46956acbdab4e73a4497ffda0eca4a4"
        }
      ]
    }
  ]
}
