{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "transfer",
    "version": "1.100.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "smkqp7thvbfexba6catfwegxzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "transfer",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "transfer-1.100.0-0.6.21.jar",
          "url": "transfer-1.100.0-0.6.21.jar",
          "size": 74646,
          "sha512": "7253e1941984b4321d925f3705eb7ea1571e1f8097db618f069278b30acd2afa0cd915c6dbc5f9ee40153898b98459fc91f32f8dda1c5540ccc4d0e4997fcf78",
          "sha256": "a18623ab7a325ffc6ab4433a38124d3403d3bd64ae1878cbdeb6d1c0303ff31",
          "sha1": "1995869dee908d6119252ac92600fb70b72c0aa7",
          "md5": "3a4453e001eaaedbb1202b696ab43752"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "transfer",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "transfer-1.100.0-0.6.21.jar",
          "url": "transfer-1.100.0-0.6.21.jar",
          "size": 74646,
          "sha512": "7253e1941984b4321d925f3705eb7ea1571e1f8097db618f069278b30acd2afa0cd915c6dbc5f9ee40153898b98459fc91f32f8dda1c5540ccc4d0e4997fcf78",
          "sha256": "a18623ab7a325ffc6ab4433a38124d3403d3bd64ae1878cbdeb6d1c0303ff31",
          "sha1": "1995869dee908d6119252ac92600fb70b72c0aa7",
          "md5": "3a4453e001eaaedbb1202b696ab43752"
        }
      ]
    }
  ]
}
