{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "wafregional",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.117.0-0.6.25.jar",
          "url": "wafregional-1.117.0-0.6.25.jar",
          "size": 251086,
          "sha512": "06ad85eccd7a9d4aec560eb056a8c06c074a9bc688676357cca6355634b6bdcf285b7c8fd05982b84c8e77e39f7329c901a6d51d6931147fba93cf6518d7cfe5",
          "sha256": "290d96640f381dd88d032b77b526e912545e03ab120a90266e6e6918e2311fe0",
          "sha1": "6bc951a42f3db3192c1b945f2343233a91f98ce5",
          "md5": "79f5016dcab2363437945edfebc76732"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "wafregional",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "wafregional-1.117.0-0.6.25.jar",
          "url": "wafregional-1.117.0-0.6.25.jar",
          "size": 251086,
          "sha512": "06ad85eccd7a9d4aec560eb056a8c06c074a9bc688676357cca6355634b6bdcf285b7c8fd05982b84c8e77e39f7329c901a6d51d6931147fba93cf6518d7cfe5",
          "sha256": "290d96640f381dd88d032b77b526e912545e03ab120a90266e6e6918e2311fe0",
          "sha1": "6bc951a42f3db3192c1b945f2343233a91f98ce5",
          "md5": "79f5016dcab2363437945edfebc76732"
        }
      ]
    }
  ]
}
