{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "frauddetector",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "frauddetector",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "frauddetector-1.108.0-0.6.21.jar",
          "url": "frauddetector-1.108.0-0.6.21.jar",
          "size": 195224,
          "sha512": "241358cb959d5f3565405d5a82d9209d03648145255d89d98475f465071ff3ec5afcebd8ab643129b70be9abab3553d30b315168935cf516146bf3fa8ac8f5a0",
          "sha256": "b2f9998c470b0180394cf865299c43664fddd72cc35b6e7401612124b0e84d55",
          "sha1": "ea27e8d1020a8c07619cbf2e0eaa0f4767dff6b0",
          "md5": "7731a9e7b0b4da0d09afebc57561d0b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "frauddetector",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "frauddetector-1.108.0-0.6.21.jar",
          "url": "frauddetector-1.108.0-0.6.21.jar",
          "size": 195224,
          "sha512": "241358cb959d5f3565405d5a82d9209d03648145255d89d98475f465071ff3ec5afcebd8ab643129b70be9abab3553d30b315168935cf516146bf3fa8ac8f5a0",
          "sha256": "b2f9998c470b0180394cf865299c43664fddd72cc35b6e7401612124b0e84d55",
          "sha1": "ea27e8d1020a8c07619cbf2e0eaa0f4767dff6b0",
          "md5": "7731a9e7b0b4da0d09afebc57561d0b9"
        }
      ]
    }
  ]
}
