{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "detective",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "detective",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "detective-1.104.0-0.6.21.jar",
          "url": "detective-1.104.0-0.6.21.jar",
          "size": 24981,
          "sha512": "ba2cceb6b39afd2cfe0fd9a9fdfda3eb62096ba97ff8bd568adca4e7f12a6df9a665d74eee4171cfc0ed940d7d15404fc30fab0b122cd2e7492a603e8661b9f8",
          "sha256": "696f070fe9cf6290c3821ea3efc551a844353cdcfab9abc50732eefb61e7b68f",
          "sha1": "c6bdf40db4f9eebe956421e20f3445142c03ae6",
          "md5": "d89ef1f7e02496d6c5fdf696a132daf1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "detective",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "detective-1.104.0-0.6.21.jar",
          "url": "detective-1.104.0-0.6.21.jar",
          "size": 24981,
          "sha512": "ba2cceb6b39afd2cfe0fd9a9fdfda3eb62096ba97ff8bd568adca4e7f12a6df9a665d74eee4171cfc0ed940d7d15404fc30fab0b122cd2e7492a603e8661b9f8",
          "sha256": "696f070fe9cf6290c3821ea3efc551a844353cdcfab9abc50732eefb61e7b68f",
          "sha1": "c6bdf40db4f9eebe956421e20f3445142c03ae6",
          "md5": "d89ef1f7e02496d6c5fdf696a132daf1"
        }
      ]
    }
  ]
}
