{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "stepfunctions",
    "version": "1.117.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ka4pthfoybhvvnwbwaxmu2dbry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "stepfunctions",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "stepfunctions-1.117.0-0.6.21.jar",
          "url": "stepfunctions-1.117.0-0.6.21.jar",
          "size": 224921,
          "sha512": "ab8da5eda3656b36b57a9460b856898a397a433f17e811a26b9b9815706871e57ac4c05af55fdbf928cf7f7789e60c98848df294e05ccebd2d02285194e0ee51",
          "sha256": "ad804d95ee39c503a2dac1c40e7fe52320cebea7c61ad1b770556bab4ddcc6b7",
          "sha1": "ab5eba1d769aa59a21e8539418fbac5aaa5c0c80",
          "md5": "4da0a2106fec2bd4dfdb6365a751363d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "stepfunctions",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "events",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "stepfunctions-1.117.0-0.6.21.jar",
          "url": "stepfunctions-1.117.0-0.6.21.jar",
          "size": 224921,
          "sha512": "ab8da5eda3656b36b57a9460b856898a397a433f17e811a26b9b9815706871e57ac4c05af55fdbf928cf7f7789e60c98848df294e05ccebd2d02285194e0ee51",
          "sha256": "ad804d95ee39c503a2dac1c40e7fe52320cebea7c61ad1b770556bab4ddcc6b7",
          "sha1": "ab5eba1d769aa59a21e8539418fbac5aaa5c0c80",
          "md5": "4da0a2106fec2bd4dfdb6365a751363d"
        }
      ]
    }
  ]
}
