{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "appstream",
    "version": "1.31.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "appstream",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "appstream-1.31.0-0.6.22.jar",
          "url": "appstream-1.31.0-0.6.22.jar",
          "size": 233996,
          "sha512": "904e5ac24824ae0b0fec91c76c29f0e4b27e2b282a61221bc296077e0072b776367e3f67f1b3f01ddfc3dc6cdcb24d4ced3b8b9a321bb98dca174fdbac6ebab7",
          "sha256": "00c1aa708e1ec5e31fffe89bbfaf47784ddc1b72c81f5d552a3d44e8968304d1",
          "sha1": "72427383cb7a09e63cedbaf3cc1928b27e130f7a",
          "md5": "3527b5d93b994eeb1c51a925736830ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "appstream",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "appstream-1.31.0-0.6.22.jar",
          "url": "appstream-1.31.0-0.6.22.jar",
          "size": 233996,
          "sha512": "904e5ac24824ae0b0fec91c76c29f0e4b27e2b282a61221bc296077e0072b776367e3f67f1b3f01ddfc3dc6cdcb24d4ced3b8b9a321bb98dca174fdbac6ebab7",
          "sha256": "00c1aa708e1ec5e31fffe89bbfaf47784ddc1b72c81f5d552a3d44e8968304d1",
          "sha1": "72427383cb7a09e63cedbaf3cc1928b27e130f7a",
          "md5": "3527b5d93b994eeb1c51a925736830ca"
        }
      ]
    }
  ]
}
