{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "athena",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "athena",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "athena-1.104.0-0.6.21.jar",
          "url": "athena-1.104.0-0.6.21.jar",
          "size": 152050,
          "sha512": "5675b67d8a61b432f5cdf7892e7e0792d9f7cdecdaba2f202dc80178bb20a500da9a80a45d06ceea9f4d6d73a28ccc1289b2f5564712ac8066678981c4d5c64d",
          "sha256": "f523bc05fe33cd01f81096d8eeab16ed5555992edd06982b7c6121e4b92b8294",
          "sha1": "85e33d1bc2d97ea3b036417ef91397eccc880b08",
          "md5": "37546de3354c9eb1111ca015d5db77dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "athena",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "athena-1.104.0-0.6.21.jar",
          "url": "athena-1.104.0-0.6.21.jar",
          "size": 152050,
          "sha512": "5675b67d8a61b432f5cdf7892e7e0792d9f7cdecdaba2f202dc80178bb20a500da9a80a45d06ceea9f4d6d73a28ccc1289b2f5564712ac8066678981c4d5c64d",
          "sha256": "f523bc05fe33cd01f81096d8eeab16ed5555992edd06982b7c6121e4b92b8294",
          "sha1": "85e33d1bc2d97ea3b036417ef91397eccc880b08",
          "md5": "37546de3354c9eb1111ca015d5db77dd"
        }
      ]
    }
  ]
}
