{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestarnotifications",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarnotifications-1.109.0-0.6.21.jar",
          "url": "codestarnotifications-1.109.0-0.6.21.jar",
          "size": 42248,
          "sha512": "b8aca7d0a4a22f111c21d3a907aae1114610b0da14134e02df20ccc5a53973d14f45c85400e8bc79aed2bba39c4d4ac15b3f8f642598cc1bc4faf86b343a70f1",
          "sha256": "867709401b6150f805eac5c5b6e995b613f28a34db19460f046452267ce57464",
          "sha1": "f0229669df9fd5bae3c125be51ca1c8b26e3df06",
          "md5": "3fccdd176264289dfa1cf0109457148c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarnotifications-1.109.0-0.6.21.jar",
          "url": "codestarnotifications-1.109.0-0.6.21.jar",
          "size": 42248,
          "sha512": "b8aca7d0a4a22f111c21d3a907aae1114610b0da14134e02df20ccc5a53973d14f45c85400e8bc79aed2bba39c4d4ac15b3f8f642598cc1bc4faf86b343a70f1",
          "sha256": "867709401b6150f805eac5c5b6e995b613f28a34db19460f046452267ce57464",
          "sha1": "f0229669df9fd5bae3c125be51ca1c8b26e3df06",
          "md5": "3fccdd176264289dfa1cf0109457148c"
        }
      ]
    }
  ]
}
