{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ecr-assets",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ecr-assets",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-assets",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ecr",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ecr-assets-1.113.0-0.6.21.jar",
          "url": "ecr-assets-1.113.0-0.6.21.jar",
          "size": 22367,
          "sha512": "83319a306e2398cc4b037744e07ee4b9600a4a8cefaf147bb2b2587822becbe6f4dd25380d5d99a9c360d46aff0249c77ceab0b7de824d64d4772515576176c4",
          "sha256": "27eac068c026c7752e5b198d75727d162d39fe63de87ee78bc03110101912fc9",
          "sha1": "e11ee7d0b20a3bb2d2241c9dbd75acdc60363530",
          "md5": "65df862d8187bbf078c40963a8961730"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ecr-assets",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-assets",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ecr",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ecr-assets-1.113.0-0.6.21.jar",
          "url": "ecr-assets-1.113.0-0.6.21.jar",
          "size": 22367,
          "sha512": "83319a306e2398cc4b037744e07ee4b9600a4a8cefaf147bb2b2587822becbe6f4dd25380d5d99a9c360d46aff0249c77ceab0b7de824d64d4772515576176c4",
          "sha256": "27eac068c026c7752e5b198d75727d162d39fe63de87ee78bc03110101912fc9",
          "sha1": "e11ee7d0b20a3bb2d2241c9dbd75acdc60363530",
          "md5": "65df862d8187bbf078c40963a8961730"
        }
      ]
    }
  ]
}
