{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "athena",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "athena",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "athena-1.106.0-0.6.21.jar",
          "url": "athena-1.106.0-0.6.21.jar",
          "size": 152034,
          "sha512": "90b148383e7e3e1d2613c79433aef21f83c2f7157c8c3f76384cbea9c6ee9897c6b1a123da0b68f91603b407299cdb704319083f4d99dc3b0888a1545cc86195",
          "sha256": "8502916418296e98e95f5f872e0803a6c62479aae21331912ddff7c764659121",
          "sha1": "6bbf5952fce6e5b8d6b131737c8d9c58f9b533a",
          "md5": "2f3401cff1ad735309854e4596768ccd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "athena",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "athena-1.106.0-0.6.21.jar",
          "url": "athena-1.106.0-0.6.21.jar",
          "size": 152034,
          "sha512": "90b148383e7e3e1d2613c79433aef21f83c2f7157c8c3f76384cbea9c6ee9897c6b1a123da0b68f91603b407299cdb704319083f4d99dc3b0888a1545cc86195",
          "sha256": "8502916418296e98e95f5f872e0803a6c62479aae21331912ddff7c764659121",
          "sha1": "6bbf5952fce6e5b8d6b131737c8d9c58f9b533a",
          "md5": "2f3401cff1ad735309854e4596768ccd"
        }
      ]
    }
  ]
}
