{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "globalaccelerator",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "globalaccelerator",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "globalaccelerator-1.115.0-0.6.21.jar",
          "url": "globalaccelerator-1.115.0-0.6.21.jar",
          "size": 128373,
          "sha512": "c4808df3f80d8bc036eca797310576a230c756e842d20663dec435c2c3a6d006e3b0ecb67be9742833f326378d00f4e40d84e4bf30d5a3b2fd0c6c74ecc8c255",
          "sha256": "df55cbcfaa0b7d5503cc117a8b4c8a4020af0a1937453450b1f3a8a30bd24b3f",
          "sha1": "6a1c6406e5805d3db08546ea63df4eebb4a2181c",
          "md5": "ddef804d1598b44ea46ca63892504614"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "globalaccelerator",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "globalaccelerator-1.115.0-0.6.21.jar",
          "url": "globalaccelerator-1.115.0-0.6.21.jar",
          "size": 128373,
          "sha512": "c4808df3f80d8bc036eca797310576a230c756e842d20663dec435c2c3a6d006e3b0ecb67be9742833f326378d00f4e40d84e4bf30d5a3b2fd0c6c74ecc8c255",
          "sha256": "df55cbcfaa0b7d5503cc117a8b4c8a4020af0a1937453450b1f3a8a30bd24b3f",
          "sha1": "6a1c6406e5805d3db08546ea63df4eebb4a2181c",
          "md5": "ddef804d1598b44ea46ca63892504614"
        }
      ]
    }
  ]
}
