{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "medialive",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "medialive",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "medialive-1.99.0-0.6.21.jar",
          "url": "medialive-1.99.0-0.6.21.jar",
          "size": 1330936,
          "sha512": "846ecfa26efbd2be33013482a2f8a06b54c071514cf5dcd019ea828f0e63b0bc9f06cb94736ea2c4d9158486aebfe7d9048ffb28f4a227ec3a21f6f0b4f96c07",
          "sha256": "f6f58789371b33bbd155ad7daf66fefcd3c48ba0a8da4c0e12e9b62158d1be2e",
          "sha1": "14eed08636a92611078979c86336c29a8de2617f",
          "md5": "cac362c93dd9f0a42b62918baa6eed1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "medialive",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "medialive-1.99.0-0.6.21.jar",
          "url": "medialive-1.99.0-0.6.21.jar",
          "size": 1330936,
          "sha512": "846ecfa26efbd2be33013482a2f8a06b54c071514cf5dcd019ea828f0e63b0bc9f06cb94736ea2c4d9158486aebfe7d9048ffb28f4a227ec3a21f6f0b4f96c07",
          "sha256": "f6f58789371b33bbd155ad7daf66fefcd3c48ba0a8da4c0e12e9b62158d1be2e",
          "sha1": "14eed08636a92611078979c86336c29a8de2617f",
          "md5": "cac362c93dd9f0a42b62918baa6eed1b"
        }
      ]
    }
  ]
}
