{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "mwaa",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "mwaa",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "mwaa-1.118.0-0.6.25.jar",
          "url": "mwaa-1.118.0-0.6.25.jar",
          "size": 72087,
          "sha512": "2fff4c49f986f784c7036136630e5695be06f2a8a0524d50c5e27cd6c8bf6beb8fac91ad9e6c0314dc58f8313857f7637e142450f6f40c79f900f1f8aaccd0b4",
          "sha256": "983403f9749557dbef0393436a9519f49e2ad25570a593a606650e3806a41ffe",
          "sha1": "5c3b67d880b265221162c4531975bed0ff82da9a",
          "md5": "9a18758ef5061327d2d2e7c2af251598"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "mwaa",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "mwaa-1.118.0-0.6.25.jar",
          "url": "mwaa-1.118.0-0.6.25.jar",
          "size": 72087,
          "sha512": "2fff4c49f986f784c7036136630e5695be06f2a8a0524d50c5e27cd6c8bf6beb8fac91ad9e6c0314dc58f8313857f7637e142450f6f40c79f900f1f8aaccd0b4",
          "sha256": "983403f9749557dbef0393436a9519f49e2ad25570a593a606650e3806a41ffe",
          "sha1": "5c3b67d880b265221162c4531975bed0ff82da9a",
          "md5": "9a18758ef5061327d2d2e7c2af251598"
        }
      ]
    }
  ]
}
