{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sagemaker",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sagemaker",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sagemaker-1.107.0-0.6.21.jar",
          "url": "sagemaker-1.107.0-0.6.21.jar",
          "size": 1474315,
          "sha512": "ba96fd01469e43caaa93fc1bf8acbd8d1381c356b42d0eea90ef878957683478370a0e2bad48ce67d231a301f5a9301ab1d2e350305a5c61a503e77caf7ea2ba",
          "sha256": "4ac723572fa19ca5eb3ccf235d3b3febd25da9d6b1ce0c31de9b5e478978e654",
          "sha1": "6493c7a5457558f3c0fb0857f8155c2384835ab1",
          "md5": "6f353f65a7200c15e61b85502e717243"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sagemaker",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sagemaker-1.107.0-0.6.21.jar",
          "url": "sagemaker-1.107.0-0.6.21.jar",
          "size": 1474315,
          "sha512": "ba96fd01469e43caaa93fc1bf8acbd8d1381c356b42d0eea90ef878957683478370a0e2bad48ce67d231a301f5a9301ab1d2e350305a5c61a503e77caf7ea2ba",
          "sha256": "4ac723572fa19ca5eb3ccf235d3b3febd25da9d6b1ce0c31de9b5e478978e654",
          "sha1": "6493c7a5457558f3c0fb0857f8155c2384835ab1",
          "md5": "6f353f65a7200c15e61b85502e717243"
        }
      ]
    }
  ]
}
