{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "robomaker",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "robomaker",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "robomaker-1.104.0-0.6.21.jar",
          "url": "robomaker-1.104.0-0.6.21.jar",
          "size": 120986,
          "sha512": "285e9bf4b2dea82dbe575906626982ec6d65156f9b0a5ed4321d757e1f07cac2cadc32c4e75a62331fd695022e2a90fa5cbd33fbedaef09af92a278adf622f06",
          "sha256": "b4aa820772b664f0b253a274dbd4f346a6171ae59487d69707cd840e1952591d",
          "sha1": "da47c7a2b34ee44e7fc1c590dbccd634400655fd",
          "md5": "2ff661d8cb765460f8f04b44a3ed90cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "robomaker",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "robomaker-1.104.0-0.6.21.jar",
          "url": "robomaker-1.104.0-0.6.21.jar",
          "size": 120986,
          "sha512": "285e9bf4b2dea82dbe575906626982ec6d65156f9b0a5ed4321d757e1f07cac2cadc32c4e75a62331fd695022e2a90fa5cbd33fbedaef09af92a278adf622f06",
          "sha256": "b4aa820772b664f0b253a274dbd4f346a6171ae59487d69707cd840e1952591d",
          "sha1": "da47c7a2b34ee44e7fc1c590dbccd634400655fd",
          "md5": "2ff661d8cb765460f8f04b44a3ed90cd"
        }
      ]
    }
  ]
}
