{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "mwaa",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "mwaa",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mwaa-1.104.0-0.6.21.jar",
          "url": "mwaa-1.104.0-0.6.21.jar",
          "size": 71859,
          "sha512": "4ad05a64b364f7b00855a7aba9de8cf13d0a706719d9f7cd9b849fa87fcf0d50279eaceb93e1c01d9b0e06939765bf4417a7531f4ec545d842d87e5eab7bc470",
          "sha256": "fffb4d4a7d02df021421899ee380d437eabcb6a0d69aa67315c98156d7bc84a0",
          "sha1": "138bd64f8ff783a5fc45709bf42d893f5eb7e9cd",
          "md5": "12984128b64c8c07efdee6c9afece2db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "mwaa",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mwaa-1.104.0-0.6.21.jar",
          "url": "mwaa-1.104.0-0.6.21.jar",
          "size": 71859,
          "sha512": "4ad05a64b364f7b00855a7aba9de8cf13d0a706719d9f7cd9b849fa87fcf0d50279eaceb93e1c01d9b0e06939765bf4417a7531f4ec545d842d87e5eab7bc470",
          "sha256": "fffb4d4a7d02df021421899ee380d437eabcb6a0d69aa67315c98156d7bc84a0",
          "sha1": "138bd64f8ff783a5fc45709bf42d893f5eb7e9cd",
          "md5": "12984128b64c8c07efdee6c9afece2db"
        }
      ]
    }
  ]
}
