{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotwireless",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotwireless",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotwireless-1.113.0-0.6.21.jar",
          "url": "iotwireless-1.113.0-0.6.21.jar",
          "size": 308928,
          "sha512": "eb3c53336e8f6afdd6c5c4af8e8d7d06cca2957cf7cf127c031f263c4c7aae8b11db2e9c585c982baa993203f912dbce748baaa67c833156f0d24ad783901f90",
          "sha256": "ea78da7c51b63228c2d1f068c68558f8b75a5c628ba18c966ecb6de86ec479b5",
          "sha1": "eb041851e3b2f613a0c0f4006e5fa80063bcd168",
          "md5": "deca0f0999d630099285884a88028a9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotwireless",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotwireless-1.113.0-0.6.21.jar",
          "url": "iotwireless-1.113.0-0.6.21.jar",
          "size": 308928,
          "sha512": "eb3c53336e8f6afdd6c5c4af8e8d7d06cca2957cf7cf127c031f263c4c7aae8b11db2e9c585c982baa993203f912dbce748baaa67c833156f0d24ad783901f90",
          "sha256": "ea78da7c51b63228c2d1f068c68558f8b75a5c628ba18c966ecb6de86ec479b5",
          "sha1": "eb041851e3b2f613a0c0f4006e5fa80063bcd168",
          "md5": "deca0f0999d630099285884a88028a9a"
        }
      ]
    }
  ]
}
