{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "greengrass",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "greengrass",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrass-1.103.0-0.6.21.jar",
          "url": "greengrass-1.103.0-0.6.21.jar",
          "size": 685737,
          "sha512": "bbb764b5f0800fe5f17c815bbc45cf237f321c4a79a51c22b593618272f4a69bbb55915c0871b71da949bc34c801c53d8c523518c30bb4448cdbe07f36b640cf",
          "sha256": "912a9e53e95e0995ade48874d08b7a3bf46cb7c7d3c9b32bc7710b66e4c25a1e",
          "sha1": "5ca6cd50840eae29c304fdfe3da757ec1eda55c6",
          "md5": "ab7ae9ce38fa0517042ae1b92efe0092"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "greengrass",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrass-1.103.0-0.6.21.jar",
          "url": "greengrass-1.103.0-0.6.21.jar",
          "size": 685737,
          "sha512": "bbb764b5f0800fe5f17c815bbc45cf237f321c4a79a51c22b593618272f4a69bbb55915c0871b71da949bc34c801c53d8c523518c30bb4448cdbe07f36b640cf",
          "sha256": "912a9e53e95e0995ade48874d08b7a3bf46cb7c7d3c9b32bc7710b66e4c25a1e",
          "sha1": "5ca6cd50840eae29c304fdfe3da757ec1eda55c6",
          "md5": "ab7ae9ce38fa0517042ae1b92efe0092"
        }
      ]
    }
  ]
}
