{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "route53resolver",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "route53resolver",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "route53resolver-1.102.0-0.6.21.jar",
          "url": "route53resolver-1.102.0-0.6.21.jar",
          "size": 108521,
          "sha512": "5684b274fa73384c8e4abfc8ad962c4cb73017827da4cc9e5345f1c7bff746d9ddf9cd14fbb2a86556bccb859821178c219bfddd6ea118e14daf3e219a5e3347",
          "sha256": "1318d58590e89718ebc9ff93e6cdc063be62f06186746b2091c34e3542ad9a24",
          "sha1": "a8760ea1113c432330353a64ababaf5c53f889c3",
          "md5": "4d2224cde917c7aa5a69af6ba04f122e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "route53resolver",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "route53resolver-1.102.0-0.6.21.jar",
          "url": "route53resolver-1.102.0-0.6.21.jar",
          "size": 108521,
          "sha512": "5684b274fa73384c8e4abfc8ad962c4cb73017827da4cc9e5345f1c7bff746d9ddf9cd14fbb2a86556bccb859821178c219bfddd6ea118e14daf3e219a5e3347",
          "sha256": "1318d58590e89718ebc9ff93e6cdc063be62f06186746b2091c34e3542ad9a24",
          "sha1": "a8760ea1113c432330353a64ababaf5c53f889c3",
          "md5": "4d2224cde917c7aa5a69af6ba04f122e"
        }
      ]
    }
  ]
}
