{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "emr",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "emr",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emr-1.108.0-0.6.21.jar",
          "url": "emr-1.108.0-0.6.21.jar",
          "size": 618998,
          "sha512": "4bab2797684f797fdb8439e7cfc13074c59b6a41be7f83e6442d953f7c461da654ff9b46c2c68e03b00330411d73a1d91b54385eb87c07b8e1959a1756cd6e01",
          "sha256": "8f67c509f629a78fba4fc1cbe70d102e0cc1d948f506a490d863735a48b83304",
          "sha1": "79f5a85dfbc1fc1f3aabb4a90541b9399e29c7f6",
          "md5": "16d8f15df19219427a667f651b38a495"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "emr",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "emr-1.108.0-0.6.21.jar",
          "url": "emr-1.108.0-0.6.21.jar",
          "size": 618998,
          "sha512": "4bab2797684f797fdb8439e7cfc13074c59b6a41be7f83e6442d953f7c461da654ff9b46c2c68e03b00330411d73a1d91b54385eb87c07b8e1959a1756cd6e01",
          "sha256": "8f67c509f629a78fba4fc1cbe70d102e0cc1d948f506a490d863735a48b83304",
          "sha1": "79f5a85dfbc1fc1f3aabb4a90541b9399e29c7f6",
          "md5": "16d8f15df19219427a667f651b38a495"
        }
      ]
    }
  ]
}
