{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "auditmanager",
    "version": "1.117.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ka4pthfoybhvvnwbwaxmu2dbry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "auditmanager",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "auditmanager-1.117.0-0.6.21.jar",
          "url": "auditmanager-1.117.0-0.6.21.jar",
          "size": 76375,
          "sha512": "ae649e244b1eb8605fd67135931ef7cb57105ecd0812ce6441098ffbbfcee065f4eda6f92e383405e45193d6187f12d6bf3a44e583eef864257fabbb2ab0f908",
          "sha256": "a6203a3906f6c17b662c280e324f403c61bf581cf0ed9de4d488106268da4928",
          "sha1": "128951348f8cede08f33ad41312d6791ce5e0823",
          "md5": "5dd417899bd302893f45ae91c099e93a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "auditmanager",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "auditmanager-1.117.0-0.6.21.jar",
          "url": "auditmanager-1.117.0-0.6.21.jar",
          "size": 76375,
          "sha512": "ae649e244b1eb8605fd67135931ef7cb57105ecd0812ce6441098ffbbfcee065f4eda6f92e383405e45193d6187f12d6bf3a44e583eef864257fabbb2ab0f908",
          "sha256": "a6203a3906f6c17b662c280e324f403c61bf581cf0ed9de4d488106268da4928",
          "sha1": "128951348f8cede08f33ad41312d6791ce5e0823",
          "md5": "5dd417899bd302893f45ae91c099e93a"
        }
      ]
    }
  ]
}
