{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "kinesisanalytics-flink",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "kinesisanalytics-flink",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-assets",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kinesisanalytics",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesisanalytics-flink-1.111.0-0.6.21.jar",
          "url": "kinesisanalytics-flink-1.111.0-0.6.21.jar",
          "size": 20268,
          "sha512": "2d14303d890f123e6274912943c679bd0ff3da08b9b1e79ba80ef106179c55d7a1bd5f58625f88f0874ed82ac2a9537424f08ff7ef4cab35a296d1aee9d1209d",
          "sha256": "59cd1e613265967c634a5fc9d24a504c34105415383850b0b753fb3dac1ac29",
          "sha1": "f40ed1496ca82f67d225072b7e2b10ee09135c09",
          "md5": "fb819844a2a1b89158a58f47c01471d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "kinesisanalytics-flink",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-assets",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kinesisanalytics",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesisanalytics-flink-1.111.0-0.6.21.jar",
          "url": "kinesisanalytics-flink-1.111.0-0.6.21.jar",
          "size": 20268,
          "sha512": "2d14303d890f123e6274912943c679bd0ff3da08b9b1e79ba80ef106179c55d7a1bd5f58625f88f0874ed82ac2a9537424f08ff7ef4cab35a296d1aee9d1209d",
          "sha256": "59cd1e613265967c634a5fc9d24a504c34105415383850b0b753fb3dac1ac29",
          "sha1": "f40ed1496ca82f67d225072b7e2b10ee09135c09",
          "md5": "fb819844a2a1b89158a58f47c01471d0"
        }
      ]
    }
  ]
}
