{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "kinesisanalytics",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "kinesisanalytics",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesisanalytics-1.102.0-0.6.21.jar",
          "url": "kinesisanalytics-1.102.0-0.6.21.jar",
          "size": 623022,
          "sha512": "35e79df05ee64264fffb3e4ab38b46670f1625a7530cc95f07fc53e16b7dbff1fea9d363f6ca5e14f33b702d1ffb1dbd69b4cb4f631229e1f3912340b12fd359",
          "sha256": "e951d0f80b5c061ef3e73d7cd7d77ff5b658936b86369b659b7bc786eb4d3502",
          "sha1": "d4dbeb7648625dde3d2c53eacdbb6bc8472c7e72",
          "md5": "20a21df2b9f41de709347aacd5f08fed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "kinesisanalytics",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesisanalytics-1.102.0-0.6.21.jar",
          "url": "kinesisanalytics-1.102.0-0.6.21.jar",
          "size": 623022,
          "sha512": "35e79df05ee64264fffb3e4ab38b46670f1625a7530cc95f07fc53e16b7dbff1fea9d363f6ca5e14f33b702d1ffb1dbd69b4cb4f631229e1f3912340b12fd359",
          "sha256": "e951d0f80b5c061ef3e73d7cd7d77ff5b658936b86369b659b7bc786eb4d3502",
          "sha1": "d4dbeb7648625dde3d2c53eacdbb6bc8472c7e72",
          "md5": "20a21df2b9f41de709347aacd5f08fed"
        }
      ]
    }
  ]
}
