{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "securityhub",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "securityhub",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "securityhub-1.112.0-0.6.21.jar",
          "url": "securityhub-1.112.0-0.6.21.jar",
          "size": 8533,
          "sha512": "fc91d6ce8b5d72b0ac4a7e490e768ff0facd00b2a8df1e517629803ad23675733553518c01e83eee5019b245cbca1444d34cf194ee664cbaacd8e8b42d747053",
          "sha256": "a3eeaf181a862df29c7c4fdd26ace76e2f222c9d052335566c04f81119a38300",
          "sha1": "b793ef5998684b607d6761a24ebc9a886ad3cc4",
          "md5": "5fa6e8508ab3a00aa8557db4fb73d42e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "securityhub",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "securityhub-1.112.0-0.6.21.jar",
          "url": "securityhub-1.112.0-0.6.21.jar",
          "size": 8533,
          "sha512": "fc91d6ce8b5d72b0ac4a7e490e768ff0facd00b2a8df1e517629803ad23675733553518c01e83eee5019b245cbca1444d34cf194ee664cbaacd8e8b42d747053",
          "sha256": "a3eeaf181a862df29c7c4fdd26ace76e2f222c9d052335566c04f81119a38300",
          "sha1": "b793ef5998684b607d6761a24ebc9a886ad3cc4",
          "md5": "5fa6e8508ab3a00aa8557db4fb73d42e"
        }
      ]
    }
  ]
}
