{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "dlm",
    "version": "1.100.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "smkqp7thvbfexba6catfwegxzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "dlm",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dlm-1.100.0-0.6.21.jar",
          "url": "dlm-1.100.0-0.6.21.jar",
          "size": 173733,
          "sha512": "ada60ae2f40134a9ae903bc91367604487c632dc128a64ac43657ff13e390a91639d3876a8e0205eccf98f16e6e2efb392409bb62161544a47c4c108ae47aaca",
          "sha256": "875e34907465c1d97e571e36ff0a37f826f5eac81b6e6b1a6a455adc042f0f9b",
          "sha1": "f8102ddbb16667a7ba5d8c4b4ddeaf46e682926",
          "md5": "53e4b169a30fbf434581e87b11cc465d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "dlm",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dlm-1.100.0-0.6.21.jar",
          "url": "dlm-1.100.0-0.6.21.jar",
          "size": 173733,
          "sha512": "ada60ae2f40134a9ae903bc91367604487c632dc128a64ac43657ff13e390a91639d3876a8e0205eccf98f16e6e2efb392409bb62161544a47c4c108ae47aaca",
          "sha256": "875e34907465c1d97e571e36ff0a37f826f5eac81b6e6b1a6a455adc042f0f9b",
          "sha1": "f8102ddbb16667a7ba5d8c4b4ddeaf46e682926",
          "md5": "53e4b169a30fbf434581e87b11cc465d"
        }
      ]
    }
  ]
}
