{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cassandra",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cassandra",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "cassandra-1.117.0-0.6.25.jar",
          "url": "cassandra-1.117.0-0.6.25.jar",
          "size": 96264,
          "sha512": "8263d3cd9b72fef610a3930645c2e9163f103133b52a85515931eaba46115efe7d3391b85c008265163c77c9e46eef3c1a70105fbcaa5553723500cc92da8dc4",
          "sha256": "a2bd1d9b488133b7bd6f49c02d0d6c04a10fcc9ba86789d4698a2c3704c6e1a0",
          "sha1": "1e8c54b59f559a33b8a019a41d40c8d54ac25c46",
          "md5": "bc5640866ebb50a7bdb1dfd245aee51c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cassandra",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "cassandra-1.117.0-0.6.25.jar",
          "url": "cassandra-1.117.0-0.6.25.jar",
          "size": 96264,
          "sha512": "8263d3cd9b72fef610a3930645c2e9163f103133b52a85515931eaba46115efe7d3391b85c008265163c77c9e46eef3c1a70105fbcaa5553723500cc92da8dc4",
          "sha256": "a2bd1d9b488133b7bd6f49c02d0d6c04a10fcc9ba86789d4698a2c3704c6e1a0",
          "sha1": "1e8c54b59f559a33b8a019a41d40c8d54ac25c46",
          "md5": "bc5640866ebb50a7bdb1dfd245aee51c"
        }
      ]
    }
  ]
}
