{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "alexa-ask",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "alexa-ask",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "alexa-ask-1.113.0-0.6.21.jar",
          "url": "alexa-ask-1.113.0-0.6.21.jar",
          "size": 41766,
          "sha512": "cd14b1b40a1bf155e4c90a62bec4e30ffe4bf7a68fda73145ad9408e125f2623bba4e4734e9e43dcf919c1b2186d177ded5d5abb3d437860d231a803f3ae4340",
          "sha256": "ff207c433f8356f15ac74f1054d9f887fc537abaf7cc3dcac8ef02f98e7405d1",
          "sha1": "3f6163f7c2012d31bb1aee62d5a1afe4a93d9230",
          "md5": "aa8615d508b8e973bfe8c8af3ef87bac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "alexa-ask",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "alexa-ask-1.113.0-0.6.21.jar",
          "url": "alexa-ask-1.113.0-0.6.21.jar",
          "size": 41766,
          "sha512": "cd14b1b40a1bf155e4c90a62bec4e30ffe4bf7a68fda73145ad9408e125f2623bba4e4734e9e43dcf919c1b2186d177ded5d5abb3d437860d231a803f3ae4340",
          "sha256": "ff207c433f8356f15ac74f1054d9f887fc537abaf7cc3dcac8ef02f98e7405d1",
          "sha1": "3f6163f7c2012d31bb1aee62d5a1afe4a93d9230",
          "md5": "aa8615d508b8e973bfe8c8af3ef87bac"
        }
      ]
    }
  ]
}
