{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "kinesis",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "kinesis",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesis-1.106.0-0.6.21.jar",
          "url": "kinesis-1.106.0-0.6.21.jar",
          "size": 40323,
          "sha512": "e148528a6e60d2d8ae034686cdf1b882957cd3f026c9c4ccd3a44aafb566c235abf0f82772023907c0ab640b989f2c7036fc731be17ae477d401b569de627d60",
          "sha256": "ece535d1dffacd252f70f2776115bd0e56c944c58b7dc418adcaa2be36dee00d",
          "sha1": "8558320f2bb75441e6bad7c4f7c577d21239adf9",
          "md5": "cccc7df0592501b84eca4761ba15fbfb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "kinesis",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "logs",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kinesis-1.106.0-0.6.21.jar",
          "url": "kinesis-1.106.0-0.6.21.jar",
          "size": 40323,
          "sha512": "e148528a6e60d2d8ae034686cdf1b882957cd3f026c9c4ccd3a44aafb566c235abf0f82772023907c0ab640b989f2c7036fc731be17ae477d401b569de627d60",
          "sha256": "ece535d1dffacd252f70f2776115bd0e56c944c58b7dc418adcaa2be36dee00d",
          "sha1": "8558320f2bb75441e6bad7c4f7c577d21239adf9",
          "md5": "cccc7df0592501b84eca4761ba15fbfb"
        }
      ]
    }
  ]
}
