{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "transfer",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "transfer",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "transfer-1.111.0-0.6.21.jar",
          "url": "transfer-1.111.0-0.6.21.jar",
          "size": 86865,
          "sha512": "df5276718f55928383f34be81cd64908268ce1862b596a21a9f8e3e1abfe0864cbe22c805df67270022a5139b928498ccddc54ce7b891e534788fa5527bbced2",
          "sha256": "2539c5f5dc73831625a4dd8e63c243f5a08ea0745aced6ebebb83cbb44f2e7c8",
          "sha1": "aa7a8badddc7db42b58102523cf2a7b5fc6c1353",
          "md5": "9cc6764b1ef0469d4ae25a40c77cdeba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "transfer",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "transfer-1.111.0-0.6.21.jar",
          "url": "transfer-1.111.0-0.6.21.jar",
          "size": 86865,
          "sha512": "df5276718f55928383f34be81cd64908268ce1862b596a21a9f8e3e1abfe0864cbe22c805df67270022a5139b928498ccddc54ce7b891e534788fa5527bbced2",
          "sha256": "2539c5f5dc73831625a4dd8e63c243f5a08ea0745aced6ebebb83cbb44f2e7c8",
          "sha1": "aa7a8badddc7db42b58102523cf2a7b5fc6c1353",
          "md5": "9cc6764b1ef0469d4ae25a40c77cdeba"
        }
      ]
    }
  ]
}
