{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "managedblockchain",
    "version": "1.116.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u6lzbl5mhzberecib7k5lnyrnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "managedblockchain",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "managedblockchain-1.116.0-0.6.21.jar",
          "url": "managedblockchain-1.116.0-0.6.21.jar",
          "size": 105042,
          "sha512": "87698759096ffca6dc7cfaa8f45256528f1d7222ff9c47ded5e374fe55a5660584d1e7855960d44145989d15e5e456c6f39222073aa1b517b94f42f9bef9d1b0",
          "sha256": "8c41e57b115f91ee1f05c4c686b5c7663d2774cdd06b78c3e6b6fe1e0342c178",
          "sha1": "3cc4bc340e059aadcaab5f0b78eea64b88666da9",
          "md5": "c18246ab420093364589527cae84b39d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "managedblockchain",
          "version": {
            "requires": "1.116.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.116.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "managedblockchain-1.116.0-0.6.21.jar",
          "url": "managedblockchain-1.116.0-0.6.21.jar",
          "size": 105042,
          "sha512": "87698759096ffca6dc7cfaa8f45256528f1d7222ff9c47ded5e374fe55a5660584d1e7855960d44145989d15e5e456c6f39222073aa1b517b94f42f9bef9d1b0",
          "sha256": "8c41e57b115f91ee1f05c4c686b5c7663d2774cdd06b78c3e6b6fe1e0342c178",
          "sha1": "3cc4bc340e059aadcaab5f0b78eea64b88666da9",
          "md5": "c18246ab420093364589527cae84b39d"
        }
      ]
    }
  ]
}
