{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "managedblockchain",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "managedblockchain",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "managedblockchain-1.106.0-0.6.21.jar",
          "url": "managedblockchain-1.106.0-0.6.21.jar",
          "size": 105078,
          "sha512": "8428ba57f55dd1428fc87a803ba3f9977752cde522de7c10a0adaaa40b3c2847e0e2367e31e7667716718f982c5d0da63549ef83cbbe380667a0a58ce5f5e703",
          "sha256": "6c9645e7e23717250176a54d2c4f6b264104c12ab733b4108bb6134674c7badf",
          "sha1": "ec920c4ae14fdc9a1b51a8d3892c4ec4f60cd607",
          "md5": "afe2b2cf058211952f4aebef4db02133"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "managedblockchain",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "managedblockchain-1.106.0-0.6.21.jar",
          "url": "managedblockchain-1.106.0-0.6.21.jar",
          "size": 105078,
          "sha512": "8428ba57f55dd1428fc87a803ba3f9977752cde522de7c10a0adaaa40b3c2847e0e2367e31e7667716718f982c5d0da63549ef83cbbe380667a0a58ce5f5e703",
          "sha256": "6c9645e7e23717250176a54d2c4f6b264104c12ab733b4108bb6134674c7badf",
          "sha1": "ec920c4ae14fdc9a1b51a8d3892c4ec4f60cd607",
          "md5": "afe2b2cf058211952f4aebef4db02133"
        }
      ]
    }
  ]
}
