{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "auditmanager",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "auditmanager",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "auditmanager-1.117.0-0.6.25.jar",
          "url": "auditmanager-1.117.0-0.6.25.jar",
          "size": 76380,
          "sha512": "2ac2e6551e62c6868d70e5f092ab6005f12a97235ea0c075626334f90401dd028c81ef457e745c368dd1e4f2d97648034e1e445e3e01c4eb75f8eb9a1c0718ad",
          "sha256": "5e24d02ebb994940810efb95a5a8a76569a5d48303d9c04bf87da7fd7268210d",
          "sha1": "49d9ff01370925dd2f6a5f9dad1f3c8a20a9f83a",
          "md5": "55207dbf21a46cb90edbc49e1fe6d0e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "auditmanager",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "auditmanager-1.117.0-0.6.25.jar",
          "url": "auditmanager-1.117.0-0.6.25.jar",
          "size": 76380,
          "sha512": "2ac2e6551e62c6868d70e5f092ab6005f12a97235ea0c075626334f90401dd028c81ef457e745c368dd1e4f2d97648034e1e445e3e01c4eb75f8eb9a1c0718ad",
          "sha256": "5e24d02ebb994940810efb95a5a8a76569a5d48303d9c04bf87da7fd7268210d",
          "sha1": "49d9ff01370925dd2f6a5f9dad1f3c8a20a9f83a",
          "md5": "55207dbf21a46cb90edbc49e1fe6d0e2"
        }
      ]
    }
  ]
}
