{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestarconnections",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestarconnections",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarconnections-1.104.0-0.6.21.jar",
          "url": "codestarconnections-1.104.0-0.6.21.jar",
          "size": 9592,
          "sha512": "338acdb1ad490d25955e1680ff0f344e9601b2237c22b54623b2057efea36760243d7738b08b4c46d4db624f25514e375013f87db04d5e81729a3cab136725c6",
          "sha256": "544519221b734fe57a1eef9a758430a7c21ace496f61ed62f59dc00e157fcaa",
          "sha1": "27dd2ad78d0bd288aee5a1f94656572958bcbb5c",
          "md5": "a029868c35d2be369860e110852c0084"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestarconnections",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarconnections-1.104.0-0.6.21.jar",
          "url": "codestarconnections-1.104.0-0.6.21.jar",
          "size": 9592,
          "sha512": "338acdb1ad490d25955e1680ff0f344e9601b2237c22b54623b2057efea36760243d7738b08b4c46d4db624f25514e375013f87db04d5e81729a3cab136725c6",
          "sha256": "544519221b734fe57a1eef9a758430a7c21ace496f61ed62f59dc00e157fcaa",
          "sha1": "27dd2ad78d0bd288aee5a1f94656572958bcbb5c",
          "md5": "a029868c35d2be369860e110852c0084"
        }
      ]
    }
  ]
}
