{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "gamelift",
    "version": "1.113.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4eq3z6kztfacfbxsxa2ublfmc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "gamelift",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "gamelift-1.113.0-0.6.21.jar",
          "url": "gamelift-1.113.0-0.6.21.jar",
          "size": 302884,
          "sha512": "d4460b881b0b32d7dce3c43d08656091708a77a931bcab84d4ba757304f85e88b6f6518897a1a9d4dcce35635a26fcf1e162ffcf1c3bb8c765cc8653ead318f8",
          "sha256": "aa79975782313887d3df752f1bbd5252e67b39814b276e32ad3d24ea5169f145",
          "sha1": "83cfe6bc434cf604be373f3e71da03eef6fcaccb",
          "md5": "532d173bf72b42be8bc48eaa1fa49b4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "gamelift",
          "version": {
            "requires": "1.113.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.113.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "gamelift-1.113.0-0.6.21.jar",
          "url": "gamelift-1.113.0-0.6.21.jar",
          "size": 302884,
          "sha512": "d4460b881b0b32d7dce3c43d08656091708a77a931bcab84d4ba757304f85e88b6f6518897a1a9d4dcce35635a26fcf1e162ffcf1c3bb8c765cc8653ead318f8",
          "sha256": "aa79975782313887d3df752f1bbd5252e67b39814b276e32ad3d24ea5169f145",
          "sha1": "83cfe6bc434cf604be373f3e71da03eef6fcaccb",
          "md5": "532d173bf72b42be8bc48eaa1fa49b4c"
        }
      ]
    }
  ]
}
