{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "nimblestudio",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "nimblestudio",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "nimblestudio-1.114.0-0.6.21.jar",
          "url": "nimblestudio-1.114.0-0.6.21.jar",
          "size": 142411,
          "sha512": "d3e440eabac037635c16378c4f01f58f521b6d0b00597f5da6d4aee367f453a4be8cf17b69e6606faaff51f373a4800f1dcbab0095ff8b0b954672da56167db3",
          "sha256": "a8f1760dc81b786a07be657f5f308a6cd6752c9498f5a99f5e59f30f0ab7899c",
          "sha1": "8bb5626d30953b925707beceda7a7c46d7f1ed73",
          "md5": "26f9e56567c8131b0845ba8f66e5eb2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "nimblestudio",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "nimblestudio-1.114.0-0.6.21.jar",
          "url": "nimblestudio-1.114.0-0.6.21.jar",
          "size": 142411,
          "sha512": "d3e440eabac037635c16378c4f01f58f521b6d0b00597f5da6d4aee367f453a4be8cf17b69e6606faaff51f373a4800f1dcbab0095ff8b0b954672da56167db3",
          "sha256": "a8f1760dc81b786a07be657f5f308a6cd6752c9498f5a99f5e59f30f0ab7899c",
          "sha1": "8bb5626d30953b925707beceda7a7c46d7f1ed73",
          "md5": "26f9e56567c8131b0845ba8f66e5eb2b"
        }
      ]
    }
  ]
}
