{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestarnotifications",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarnotifications-1.106.0-0.6.21.jar",
          "url": "codestarnotifications-1.106.0-0.6.21.jar",
          "size": 23623,
          "sha512": "5f950788802d4e509673a74e57e7053c47b68b34e36041a5cfbb719652d49b1b9446fc539c7eca22027ada924653065ead3f095859a2c21fde6fcfa75c4e0b80",
          "sha256": "b6aa4619875ca11860f23fa7185f4c03b8253b29706d4bb894fe29c7e3abc095",
          "sha1": "507df6e5f637f0c17054355d30cb0427636edfd8",
          "md5": "f0ac10ebef62ac234afd2fae2b1d1db7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestarnotifications",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarnotifications-1.106.0-0.6.21.jar",
          "url": "codestarnotifications-1.106.0-0.6.21.jar",
          "size": 23623,
          "sha512": "5f950788802d4e509673a74e57e7053c47b68b34e36041a5cfbb719652d49b1b9446fc539c7eca22027ada924653065ead3f095859a2c21fde6fcfa75c4e0b80",
          "sha256": "b6aa4619875ca11860f23fa7185f4c03b8253b29706d4bb894fe29c7e3abc095",
          "sha1": "507df6e5f637f0c17054355d30cb0427636edfd8",
          "md5": "f0ac10ebef62ac234afd2fae2b1d1db7"
        }
      ]
    }
  ]
}
