{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "globalaccelerator-endpoints",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "globalaccelerator-endpoints",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "globalaccelerator",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "globalaccelerator-endpoints-1.99.0-0.6.21.jar",
          "url": "globalaccelerator-endpoints-1.99.0-0.6.21.jar",
          "size": 16041,
          "sha512": "abf79c76d2f20fb2b178baeea62f2e3c85472810d588eb9f79efa080042dc88b0a0c6294cf38f58f8d7495026697330f06a8fb8a5f6d47644f8562ed49eba039",
          "sha256": "32c563c4d173c0221e6d93059ee841a37306bd57a8d9ba68941ec4c08a6a6739",
          "sha1": "b4689956b255890f9c77d52b9e3234acee9eb089",
          "md5": "2142d86279823f65e9afa16f49779871"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "globalaccelerator-endpoints",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "globalaccelerator",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "globalaccelerator-endpoints-1.99.0-0.6.21.jar",
          "url": "globalaccelerator-endpoints-1.99.0-0.6.21.jar",
          "size": 16041,
          "sha512": "abf79c76d2f20fb2b178baeea62f2e3c85472810d588eb9f79efa080042dc88b0a0c6294cf38f58f8d7495026697330f06a8fb8a5f6d47644f8562ed49eba039",
          "sha256": "32c563c4d173c0221e6d93059ee841a37306bd57a8d9ba68941ec4c08a6a6739",
          "sha1": "b4689956b255890f9c77d52b9e3234acee9eb089",
          "md5": "2142d86279823f65e9afa16f49779871"
        }
      ]
    }
  ]
}
