{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-cloud-assembly-schema",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.104.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cloud-assembly-schema-1.104.0-0.6.21.jar",
          "url": "cdk-cloud-assembly-schema-1.104.0-0.6.21.jar",
          "size": 142646,
          "sha512": "dc5da5d393554fd24e0ab470149fb84bd87d4d3b7578e4bc7b848d30336badb7901f9d148a680e0ade3910cbe87b852272f30a0703023447925f11fc5528cdc9",
          "sha256": "d9da82ade089183e65f083c1de849722f4cad1d6e8f4703a05d15d7eb53181ea",
          "sha1": "1c6e9b04ea3e3b87abc11f0b6aee30c6f986f1b",
          "md5": "8753b11c7f97ebaa44d6112686243f1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.104.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-cloud-assembly-schema-1.104.0-0.6.21.jar",
          "url": "cdk-cloud-assembly-schema-1.104.0-0.6.21.jar",
          "size": 142646,
          "sha512": "dc5da5d393554fd24e0ab470149fb84bd87d4d3b7578e4bc7b848d30336badb7901f9d148a680e0ade3910cbe87b852272f30a0703023447925f11fc5528cdc9",
          "sha256": "d9da82ade089183e65f083c1de849722f4cad1d6e8f4703a05d15d7eb53181ea",
          "sha1": "1c6e9b04ea3e3b87abc11f0b6aee30c6f986f1b",
          "md5": "8753b11c7f97ebaa44d6112686243f1c"
        }
      ]
    }
  ]
}
