{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cassandra",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cassandra",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "cassandra-1.118.0-0.6.25.jar",
          "url": "cassandra-1.118.0-0.6.25.jar",
          "size": 96270,
          "sha512": "453905d0a9301194f90483405912708281a4594503be75da959c99bf09860b856660e06a489aea8470aeb44ff3ed50c5f5af36cd2874511930decdecb00e4c8e",
          "sha256": "efab5d347d8b774668b6c1fc3c66fbcbd28334aace1a6d4f4045cb73eacc3fcc",
          "sha1": "09c9795088ae680978a54c47c66a7ed1388de137",
          "md5": "fd243affa8e6f69d2df4e221d34f04b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cassandra",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "cassandra-1.118.0-0.6.25.jar",
          "url": "cassandra-1.118.0-0.6.25.jar",
          "size": 96270,
          "sha512": "453905d0a9301194f90483405912708281a4594503be75da959c99bf09860b856660e06a489aea8470aeb44ff3ed50c5f5af36cd2874511930decdecb00e4c8e",
          "sha256": "efab5d347d8b774668b6c1fc3c66fbcbd28334aace1a6d4f4045cb73eacc3fcc",
          "sha1": "09c9795088ae680978a54c47c66a7ed1388de137",
          "md5": "fd243affa8e6f69d2df4e221d34f04b0"
        }
      ]
    }
  ]
}
