{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "location",
    "version": "1.110.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cnrjfrtzdvad5bhmsg7msamtuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "location",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "location-1.110.0-0.6.21.jar",
          "url": "location-1.110.0-0.6.21.jar",
          "size": 70703,
          "sha512": "9df7bfb31c335b59a57af934034cc8a1c74ec9cb11aac744738d5e823335ce52548a626b9fc78d532a28efab11a1f37328063e0733323de09d84ac9449036d16",
          "sha256": "3f3079bd38a8ef0397b4300a9f0ff3321cadeaf5152049aa5099a0c2fb81cc1b",
          "sha1": "b996ac799a019ddc34f2eb98a1e8249011b29ee2",
          "md5": "1c08b819f69302bc6fb556095361a95b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "location",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "location-1.110.0-0.6.21.jar",
          "url": "location-1.110.0-0.6.21.jar",
          "size": 70703,
          "sha512": "9df7bfb31c335b59a57af934034cc8a1c74ec9cb11aac744738d5e823335ce52548a626b9fc78d532a28efab11a1f37328063e0733323de09d84ac9449036d16",
          "sha256": "3f3079bd38a8ef0397b4300a9f0ff3321cadeaf5152049aa5099a0c2fb81cc1b",
          "sha1": "b996ac799a019ddc34f2eb98a1e8249011b29ee2",
          "md5": "1c08b819f69302bc6fb556095361a95b"
        }
      ]
    }
  ]
}
