{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "mwaa",
    "version": "1.106.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "apa3jttzlbgsjbklj7vcehaque"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "mwaa",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mwaa-1.106.1-0.6.21.jar",
          "url": "mwaa-1.106.1-0.6.21.jar",
          "size": 71894,
          "sha512": "98282046a05f0f616edb591da24b4c9e3699e3359f4be81e87b6b662d3c1dbe3ccac75f5de4ffdd57de1d0d8d5929380ee61e0bf763ec597f456aab4801ca828",
          "sha256": "a76832d0dad3115862b4973d00c439d72c0d41f16df0ac1acf334462b9545ea1",
          "sha1": "4dbfceba72ca82cce818439044e089c3aef5281",
          "md5": "8b316699b208e7f4b2456732d3462c40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "mwaa",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mwaa-1.106.1-0.6.21.jar",
          "url": "mwaa-1.106.1-0.6.21.jar",
          "size": 71894,
          "sha512": "98282046a05f0f616edb591da24b4c9e3699e3359f4be81e87b6b662d3c1dbe3ccac75f5de4ffdd57de1d0d8d5929380ee61e0bf763ec597f456aab4801ca828",
          "sha256": "a76832d0dad3115862b4973d00c439d72c0d41f16df0ac1acf334462b9545ea1",
          "sha1": "4dbfceba72ca82cce818439044e089c3aef5281",
          "md5": "8b316699b208e7f4b2456732d3462c40"
        }
      ]
    }
  ]
}
