{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "s3objectlambda",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "s3objectlambda",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "s3objectlambda-1.118.0-0.6.25.jar",
          "url": "s3objectlambda-1.118.0-0.6.25.jar",
          "size": 42834,
          "sha512": "348a3a5c1f7c1d83377d375ae8c1cb8ad5148b63e680d1a64a19dd82087aafbe42f1d2d0746383cc1cfb8879496c3e90eb0a924165dd2b62c4fc3ac4ddf4a4d9",
          "sha256": "bdcfb18fc47d64b31c48d6a83e7a9ec2c632fca5bbd4e1dd8b9b7d090881213c",
          "sha1": "ed4a8e0b478b867aba9d1f6d01e051d04535df48",
          "md5": "73ee16f7961cf97d8a87cf02ee9075ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "s3objectlambda",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "s3objectlambda-1.118.0-0.6.25.jar",
          "url": "s3objectlambda-1.118.0-0.6.25.jar",
          "size": 42834,
          "sha512": "348a3a5c1f7c1d83377d375ae8c1cb8ad5148b63e680d1a64a19dd82087aafbe42f1d2d0746383cc1cfb8879496c3e90eb0a924165dd2b62c4fc3ac4ddf4a4d9",
          "sha256": "bdcfb18fc47d64b31c48d6a83e7a9ec2c632fca5bbd4e1dd8b9b7d090881213c",
          "sha1": "ed4a8e0b478b867aba9d1f6d01e051d04535df48",
          "md5": "73ee16f7961cf97d8a87cf02ee9075ce"
        }
      ]
    }
  ]
}
