{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestar",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestar",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "codestar-1.117.0-0.6.25.jar",
          "url": "codestar-1.117.0-0.6.25.jar",
          "size": 56247,
          "sha512": "5cd789b9d560dd3598fbd6940ea5146f7d5daccb67205501e07d957777eee461e84062f445ecf84cb5df738884cb03ac1e0e452777252e44e6a18d12c2603635",
          "sha256": "44c712897546d21de2914a6a89370d541f9dfa86ff412dd6457613b115eee6a9",
          "sha1": "857fd7542c01ac9e573e7867bfc159d147fc37f2",
          "md5": "ce3bb82bac75c4b0b83656bf8fffd2c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestar",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "codestar-1.117.0-0.6.25.jar",
          "url": "codestar-1.117.0-0.6.25.jar",
          "size": 56247,
          "sha512": "5cd789b9d560dd3598fbd6940ea5146f7d5daccb67205501e07d957777eee461e84062f445ecf84cb5df738884cb03ac1e0e452777252e44e6a18d12c2603635",
          "sha256": "44c712897546d21de2914a6a89370d541f9dfa86ff412dd6457613b115eee6a9",
          "sha1": "857fd7542c01ac9e573e7867bfc159d147fc37f2",
          "md5": "ce3bb82bac75c4b0b83656bf8fffd2c4"
        }
      ]
    }
  ]
}
