{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "groundstation",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "groundstation",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "groundstation-1.115.0-0.6.21.jar",
          "url": "groundstation-1.115.0-0.6.21.jar",
          "size": 219882,
          "sha512": "d45187c3e6c37500f4d67751eb12ed11084b37c986c8fa5a9c5b219971dddc9ad0bc4a10b845d219d0a52ba42b038f4c73d8790cced22dc55774b9e9d5edc834",
          "sha256": "10ce5293b67b32b71c7f92d098d5e22d6f9dcf8412a616557bf8429a9113b556",
          "sha1": "d681a9303955154bbe425c09d4fa8925077a3b95",
          "md5": "5ac08e1e9dbbd2b3f5e98c264410d388"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "groundstation",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "groundstation-1.115.0-0.6.21.jar",
          "url": "groundstation-1.115.0-0.6.21.jar",
          "size": 219882,
          "sha512": "d45187c3e6c37500f4d67751eb12ed11084b37c986c8fa5a9c5b219971dddc9ad0bc4a10b845d219d0a52ba42b038f4c73d8790cced22dc55774b9e9d5edc834",
          "sha256": "10ce5293b67b32b71c7f92d098d5e22d6f9dcf8412a616557bf8429a9113b556",
          "sha1": "d681a9303955154bbe425c09d4fa8925077a3b95",
          "md5": "5ac08e1e9dbbd2b3f5e98c264410d388"
        }
      ]
    }
  ]
}
