{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "inspector",
    "version": "1.100.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "smkqp7thvbfexba6catfwegxzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "inspector",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "inspector-1.100.0-0.6.21.jar",
          "url": "inspector-1.100.0-0.6.21.jar",
          "size": 41154,
          "sha512": "9ab017aedb817b3288b1b1cb24aad40b63f6355e15489cddfe755b40919fdcef2e9c33cd0a63953900c93149c478f5a284fa6158b195cdf1e3821d5841deb665",
          "sha256": "88d76c685631e7c8008c84fce6b2f7a8abae8b5121154b9751384ad3270ddd56",
          "sha1": "9f4a3aa8a50e837049226e6fd85baa28242d593b",
          "md5": "bdab5159fb7f0bf6112425825c3cb740"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "inspector",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "inspector-1.100.0-0.6.21.jar",
          "url": "inspector-1.100.0-0.6.21.jar",
          "size": 41154,
          "sha512": "9ab017aedb817b3288b1b1cb24aad40b63f6355e15489cddfe755b40919fdcef2e9c33cd0a63953900c93149c478f5a284fa6158b195cdf1e3821d5841deb665",
          "sha256": "88d76c685631e7c8008c84fce6b2f7a8abae8b5121154b9751384ad3270ddd56",
          "sha1": "9f4a3aa8a50e837049226e6fd85baa28242d593b",
          "md5": "bdab5159fb7f0bf6112425825c3cb740"
        }
      ]
    }
  ]
}
