{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "eventschemas",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.109.0-0.6.21.jar",
          "url": "eventschemas-1.109.0-0.6.21.jar",
          "size": 43028,
          "sha512": "d7f584502c60dcd8eaaa89e25e86ed60575c0f5ed0bf0dd29d1f82d1ecd8888c52a074dce8e6f984c37b73397f962ca51b4116358b5a97f30a64d80712f6c0c4",
          "sha256": "e717be02247ff00236500b4e2e9809d0d47f0efc08dbdca2f195e01e879e01d4",
          "sha1": "6274dbbab7e2e59cecee14b376231025b5dda3d2",
          "md5": "e8e001a99e499218861c428333c0cf1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.109.0-0.6.21.jar",
          "url": "eventschemas-1.109.0-0.6.21.jar",
          "size": 43028,
          "sha512": "d7f584502c60dcd8eaaa89e25e86ed60575c0f5ed0bf0dd29d1f82d1ecd8888c52a074dce8e6f984c37b73397f962ca51b4116358b5a97f30a64d80712f6c0c4",
          "sha256": "e717be02247ff00236500b4e2e9809d0d47f0efc08dbdca2f195e01e879e01d4",
          "sha1": "6274dbbab7e2e59cecee14b376231025b5dda3d2",
          "md5": "e8e001a99e499218861c428333c0cf1e"
        }
      ]
    }
  ]
}
