{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "managedblockchain",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "managedblockchain",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "managedblockchain-1.112.0-0.6.21.jar",
          "url": "managedblockchain-1.112.0-0.6.21.jar",
          "size": 105057,
          "sha512": "1fd4ab6099b8ef4476d7ae1b810326e96f0a30edd0d6320c5593225df7169fc7835f0b3c70046f948d1fa7c29230c4c5b265de4b5f5dab329b1ff1ee15e4817d",
          "sha256": "200246d2e607712077e7b80e50625871303cb71998de9b07434641c91c63baba",
          "sha1": "f0eb4fb54703f9e7c356d1cdf198a7a6d135f1f5",
          "md5": "a87d188651d0e0fe92cba262cde04e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "managedblockchain",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "managedblockchain-1.112.0-0.6.21.jar",
          "url": "managedblockchain-1.112.0-0.6.21.jar",
          "size": 105057,
          "sha512": "1fd4ab6099b8ef4476d7ae1b810326e96f0a30edd0d6320c5593225df7169fc7835f0b3c70046f948d1fa7c29230c4c5b265de4b5f5dab329b1ff1ee15e4817d",
          "sha256": "200246d2e607712077e7b80e50625871303cb71998de9b07434641c91c63baba",
          "sha1": "f0eb4fb54703f9e7c356d1cdf198a7a6d135f1f5",
          "md5": "a87d188651d0e0fe92cba262cde04e5"
        }
      ]
    }
  ]
}
