{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iam",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iam",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iam-1.104.0-0.6.21.jar",
          "url": "iam-1.104.0-0.6.21.jar",
          "size": 269193,
          "sha512": "e30742d9f2d8e1ec2349e2fce15dbce5af9ac9d925e072a4973e9138cd407238e7e644c14b3b61bcecec28760eb6f25b2e264211fa35296d62e46b4d6734b4a7",
          "sha256": "1983960ba243249b38513d0c4e9b6a3454c52a66b15f015ee8fc1fe21805c414",
          "sha1": "157371dcf11ee525452f8ca077852925217c647c",
          "md5": "fec47de21a80be8214462f89e01f4b92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iam",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iam-1.104.0-0.6.21.jar",
          "url": "iam-1.104.0-0.6.21.jar",
          "size": 269193,
          "sha512": "e30742d9f2d8e1ec2349e2fce15dbce5af9ac9d925e072a4973e9138cd407238e7e644c14b3b61bcecec28760eb6f25b2e264211fa35296d62e46b4d6734b4a7",
          "sha256": "1983960ba243249b38513d0c4e9b6a3454c52a66b15f015ee8fc1fe21805c414",
          "sha1": "157371dcf11ee525452f8ca077852925217c647c",
          "md5": "fec47de21a80be8214462f89e01f4b92"
        }
      ]
    }
  ]
}
