{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "pinpointemail",
    "version": "1.64.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "pinpointemail",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "pinpointemail-1.64.0-0.6.22.jar",
          "url": "pinpointemail-1.64.0-0.6.22.jar",
          "size": 191986,
          "sha512": "dfb209eebfc68350dfcba56d295fe46892b25580f4360f34888c4bd8a969d58f3d89c1315e5f8ecaf66d8bdab1bdebdd62e448bc082d5d14b26eb7a7e5a23203",
          "sha256": "bf406c6caeca2e23213369ac8f5b541d7ca43aca743bde4ca0fb898b680192d8",
          "sha1": "945239f68558be476684345bd014293cea02c4cf",
          "md5": "ce326df303f81fdb2d3e5b7ba70be19e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "pinpointemail",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "pinpointemail-1.64.0-0.6.22.jar",
          "url": "pinpointemail-1.64.0-0.6.22.jar",
          "size": 191986,
          "sha512": "dfb209eebfc68350dfcba56d295fe46892b25580f4360f34888c4bd8a969d58f3d89c1315e5f8ecaf66d8bdab1bdebdd62e448bc082d5d14b26eb7a7e5a23203",
          "sha256": "bf406c6caeca2e23213369ac8f5b541d7ca43aca743bde4ca0fb898b680192d8",
          "sha1": "945239f68558be476684345bd014293cea02c4cf",
          "md5": "ce326df303f81fdb2d3e5b7ba70be19e"
        }
      ]
    }
  ]
}
