{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iam",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iam",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iam-1.106.0-0.6.21.jar",
          "url": "iam-1.106.0-0.6.21.jar",
          "size": 269173,
          "sha512": "fe51103da88bfebabce17149cb20c72e50ebc606308c362e7b893de4fc4731d7e4531c74a4d9fbc9fccf9fd5cab3ea702648aa9fc287ec67b40d184eca21883c",
          "sha256": "5a4f83367734cba1e694792c1f3e8af1180e168394cbd320fde544dabc564bb2",
          "sha1": "d2ddbe7048f2508312ad5a21ef29c8b1c1e1f1b9",
          "md5": "269fa22bfe08b6b3522135229ae6e500"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iam",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iam-1.106.0-0.6.21.jar",
          "url": "iam-1.106.0-0.6.21.jar",
          "size": 269173,
          "sha512": "fe51103da88bfebabce17149cb20c72e50ebc606308c362e7b893de4fc4731d7e4531c74a4d9fbc9fccf9fd5cab3ea702648aa9fc287ec67b40d184eca21883c",
          "sha256": "5a4f83367734cba1e694792c1f3e8af1180e168394cbd320fde544dabc564bb2",
          "sha1": "d2ddbe7048f2508312ad5a21ef29c8b1c1e1f1b9",
          "md5": "269fa22bfe08b6b3522135229ae6e500"
        }
      ]
    }
  ]
}
