{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "greengrass",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "greengrass",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrass-1.115.0-0.6.21.jar",
          "url": "greengrass-1.115.0-0.6.21.jar",
          "size": 685771,
          "sha512": "467c9e7b5a4de948cbed0c3d78fcaf6e7f1f0e149c036ef7564b288c19d9e1a9933d842d9a10914823888e4348525ff78f9ad0dac38f886b2e14df8dcd575687",
          "sha256": "24da09c7edd27ddc885692e740d01815c83f5168e173d2c44ed924cac261b879",
          "sha1": "2c4061cf6fa6f70784c6ceb047ba82e3952bf215",
          "md5": "5c440a27c9bdbe65118feef44a34ceb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "greengrass",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrass-1.115.0-0.6.21.jar",
          "url": "greengrass-1.115.0-0.6.21.jar",
          "size": 685771,
          "sha512": "467c9e7b5a4de948cbed0c3d78fcaf6e7f1f0e149c036ef7564b288c19d9e1a9933d842d9a10914823888e4348525ff78f9ad0dac38f886b2e14df8dcd575687",
          "sha256": "24da09c7edd27ddc885692e740d01815c83f5168e173d2c44ed924cac261b879",
          "sha1": "2c4061cf6fa6f70784c6ceb047ba82e3952bf215",
          "md5": "5c440a27c9bdbe65118feef44a34ceb4"
        }
      ]
    }
  ]
}
