{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "fis",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "fis",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fis-1.108.1-0.6.21.jar",
          "url": "fis-1.108.1-0.6.21.jar",
          "size": 69981,
          "sha512": "85f00a11a55b5efc4b62cc9c4b86a5d038519afda6561183c78ada0f2652e69c8538b19555363e67a9c7af3090068eb778304cf9fe6add2e50fa62ac2805d07c",
          "sha256": "33d590583791eaec66c3e8c8c8716d2ef60ebe0394dc8f5394b8f633d88fd030",
          "sha1": "726d747bf0daaf456d0769d8ff9d2b79932de1fb",
          "md5": "b71312f3d3931695190744054b6ef2d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "fis",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fis-1.108.1-0.6.21.jar",
          "url": "fis-1.108.1-0.6.21.jar",
          "size": 69981,
          "sha512": "85f00a11a55b5efc4b62cc9c4b86a5d038519afda6561183c78ada0f2652e69c8538b19555363e67a9c7af3090068eb778304cf9fe6add2e50fa62ac2805d07c",
          "sha256": "33d590583791eaec66c3e8c8c8716d2ef60ebe0394dc8f5394b8f633d88fd030",
          "sha1": "726d747bf0daaf456d0769d8ff9d2b79932de1fb",
          "md5": "b71312f3d3931695190744054b6ef2d9"
        }
      ]
    }
  ]
}
