{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-assertions",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assertions",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assertions-1.117.0-0.6.25.jar",
          "url": "cdk-assertions-1.117.0-0.6.25.jar",
          "size": 430,
          "sha512": "02b4bb49a28d9c36e7899bfb4513820e1600c30eb8522ed815b45798fde3d11b3d48f962cd01d6a64d61ba41e7c3fe6aff60e6aec8a1d184a9e347e950a444aa",
          "sha256": "5b94aeca4178d2f946eec3f2d4bd9303d6b74211dd374f9e8be5c7056eac1d2b",
          "sha1": "c009bad1b21071325d8a9a3e7dbb56f7e22c53bd",
          "md5": "7e31a6afc0538c0b82fcf8ce2f7e43f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assertions",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cloud-assembly-schema",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assertions-1.117.0-0.6.25.jar",
          "url": "cdk-assertions-1.117.0-0.6.25.jar",
          "size": 430,
          "sha512": "02b4bb49a28d9c36e7899bfb4513820e1600c30eb8522ed815b45798fde3d11b3d48f962cd01d6a64d61ba41e7c3fe6aff60e6aec8a1d184a9e347e950a444aa",
          "sha256": "5b94aeca4178d2f946eec3f2d4bd9303d6b74211dd374f9e8be5c7056eac1d2b",
          "sha1": "c009bad1b21071325d8a9a3e7dbb56f7e22c53bd",
          "md5": "7e31a6afc0538c0b82fcf8ce2f7e43f3"
        }
      ]
    }
  ]
}
