{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "servicecatalogappregistry",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "servicecatalogappregistry",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "servicecatalogappregistry-1.117.0-0.6.25.jar",
          "url": "servicecatalogappregistry-1.117.0-0.6.25.jar",
          "size": 45209,
          "sha512": "a62ea0f8db178cf88defee18f359b124dedd0e9ed537af3c8b1f1faf760c04eb14269fd8ddecaf89cf5c20582ac4bdf70a38d162990db11896789926377e0dd0",
          "sha256": "832632dd48fd9b2a3839e2e2c73aafae51ae80581103fe8b2fb77efb12b0ca33",
          "sha1": "0dd9c6a0a44e0ba08d80a60560f5fec28b2c1928",
          "md5": "fcaa0e049508480386f21e073e773d11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "servicecatalogappregistry",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "servicecatalogappregistry-1.117.0-0.6.25.jar",
          "url": "servicecatalogappregistry-1.117.0-0.6.25.jar",
          "size": 45209,
          "sha512": "a62ea0f8db178cf88defee18f359b124dedd0e9ed537af3c8b1f1faf760c04eb14269fd8ddecaf89cf5c20582ac4bdf70a38d162990db11896789926377e0dd0",
          "sha256": "832632dd48fd9b2a3839e2e2c73aafae51ae80581103fe8b2fb77efb12b0ca33",
          "sha1": "0dd9c6a0a44e0ba08d80a60560f5fec28b2c1928",
          "md5": "fcaa0e049508480386f21e073e773d11"
        }
      ]
    }
  ]
}
