{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "networkmanager",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "networkmanager",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "networkmanager-1.103.0-0.6.21.jar",
          "url": "networkmanager-1.103.0-0.6.21.jar",
          "size": 92760,
          "sha512": "56ae4f202f3c5e4218001a84e1ac0d4c49cd395a9a087ff0505e34ce9cbcbee6b17f7453e8b87321e785a6cbf681917c3922ca9f539347c970841c1577fcd26e",
          "sha256": "be6cc2fb78344fe68abeb69f4cb0d498bd9d7fd67aca7f0c73fd3824dcc98423",
          "sha1": "976b5afe5e233a48b13cf7d3a1bcbaf41768d7a9",
          "md5": "2fee75b1ef605ccab2b74f3b91cdb88f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "networkmanager",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "networkmanager-1.103.0-0.6.21.jar",
          "url": "networkmanager-1.103.0-0.6.21.jar",
          "size": 92760,
          "sha512": "56ae4f202f3c5e4218001a84e1ac0d4c49cd395a9a087ff0505e34ce9cbcbee6b17f7453e8b87321e785a6cbf681917c3922ca9f539347c970841c1577fcd26e",
          "sha256": "be6cc2fb78344fe68abeb69f4cb0d498bd9d7fd67aca7f0c73fd3824dcc98423",
          "sha1": "976b5afe5e233a48b13cf7d3a1bcbaf41768d7a9",
          "md5": "2fee75b1ef605ccab2b74f3b91cdb88f"
        }
      ]
    }
  ]
}
