{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-assets-schema",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets-schema",
          "version": {
            "requires": "1.99.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-schema-1.99.0-0.6.21.jar",
          "url": "cdk-assets-schema-1.99.0-0.6.21.jar",
          "size": 436,
          "sha512": "6448d7be3df9b511367d1f9e8ef0c80f3a9ae58f74310f9222c9331a9f12530a0dc8b4ac014cfbe051c1a4bb3539347bb944330ef4633b6ebcadcfcc5ff94649",
          "sha256": "a2d47224716c317ad26b3836185c90d1293cac61cc7f7d946d0f50098c48022d",
          "sha1": "f3c8b929f7831e69b3046fcbf21a41fc068207e0",
          "md5": "ed6441931359dad98ff7115c022341f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets-schema",
          "version": {
            "requires": "1.99.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-schema-1.99.0-0.6.21.jar",
          "url": "cdk-assets-schema-1.99.0-0.6.21.jar",
          "size": 436,
          "sha512": "6448d7be3df9b511367d1f9e8ef0c80f3a9ae58f74310f9222c9331a9f12530a0dc8b4ac014cfbe051c1a4bb3539347bb944330ef4633b6ebcadcfcc5ff94649",
          "sha256": "a2d47224716c317ad26b3836185c90d1293cac61cc7f7d946d0f50098c48022d",
          "sha1": "f3c8b929f7831e69b3046fcbf21a41fc068207e0",
          "md5": "ed6441931359dad98ff7115c022341f5"
        }
      ]
    }
  ]
}
