{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sns-subscriptions",
    "version": "1.108.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "kpsw6vvxevhebcaohgovtllzpe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sns-subscriptions",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sns-subscriptions-1.108.0-0.6.21.jar",
          "url": "sns-subscriptions-1.108.0-0.6.21.jar",
          "size": 23735,
          "sha512": "6428a81209a036376732fae8ac23949c6977f7d0c68e733f06402c3c898e927a7b153aa72052053047862d750805190897369ea897e02a7cacc886667b910770",
          "sha256": "ec3ceeefbb90f31fea907633a15d7d143a53fc09107526a3e63582861de6664e",
          "sha1": "e71588a6fedec460ad08670c505cda68bd9bce00",
          "md5": "988a2e821b58c7bac1d156054939c2ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sns-subscriptions",
          "version": {
            "requires": "1.108.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sns",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "sqs",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sns-subscriptions-1.108.0-0.6.21.jar",
          "url": "sns-subscriptions-1.108.0-0.6.21.jar",
          "size": 23735,
          "sha512": "6428a81209a036376732fae8ac23949c6977f7d0c68e733f06402c3c898e927a7b153aa72052053047862d750805190897369ea897e02a7cacc886667b910770",
          "sha256": "ec3ceeefbb90f31fea907633a15d7d143a53fc09107526a3e63582861de6664e",
          "sha1": "e71588a6fedec460ad08670c505cda68bd9bce00",
          "md5": "988a2e821b58c7bac1d156054939c2ab"
        }
      ]
    }
  ]
}
