{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "codestarconnections",
    "version": "1.117.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ka4pthfoybhvvnwbwaxmu2dbry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "codestarconnections",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarconnections-1.117.0-0.6.21.jar",
          "url": "codestarconnections-1.117.0-0.6.21.jar",
          "size": 9592,
          "sha512": "11165cba2bc5f32b9d8221c35a75db5774f1390c673d721cbf57391263b1fb2ef93932fd2b4ac084f7a360b767bea37850b2b1c4a098bf202de2bcccc4a7ebe",
          "sha256": "4f05fa92352f9bd67e7d3c5e4d87ad379b33f28194ef43b8ccef6de412967638",
          "sha1": "dbfdb3cbba183c04c0aef0910ba9fa254366b49f",
          "md5": "c10f3ba61f5a01ed47bcde896646ea92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "codestarconnections",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "codestarconnections-1.117.0-0.6.21.jar",
          "url": "codestarconnections-1.117.0-0.6.21.jar",
          "size": 9592,
          "sha512": "11165cba2bc5f32b9d8221c35a75db5774f1390c673d721cbf57391263b1fb2ef93932fd2b4ac084f7a360b767bea37850b2b1c4a098bf202de2bcccc4a7ebe",
          "sha256": "4f05fa92352f9bd67e7d3c5e4d87ad379b33f28194ef43b8ccef6de412967638",
          "sha1": "dbfdb3cbba183c04c0aef0910ba9fa254366b49f",
          "md5": "c10f3ba61f5a01ed47bcde896646ea92"
        }
      ]
    }
  ]
}
