{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lambda-nodejs",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-nodejs",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-nodejs-1.112.0-0.6.21.jar",
          "url": "lambda-nodejs-1.112.0-0.6.21.jar",
          "size": 25890,
          "sha512": "3be5c376b15d6f5748619eacfceebe8e5caa5495171f375869cd514031c5c065f471b27e2433b58ee4ac1c50b95a88d8c75ded1bd7f7670709ee43ac319fc72a",
          "sha256": "d5b71010b7b40bcdeb109c52409c3857633ae4e5a5d87b97d44ae43f8a00c5e7",
          "sha1": "2b8512aa2be8429a330a1d87695033731613d9da",
          "md5": "16e97d115e8ed505eaf688a90fd42ebe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-nodejs",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-nodejs-1.112.0-0.6.21.jar",
          "url": "lambda-nodejs-1.112.0-0.6.21.jar",
          "size": 25890,
          "sha512": "3be5c376b15d6f5748619eacfceebe8e5caa5495171f375869cd514031c5c065f471b27e2433b58ee4ac1c50b95a88d8c75ded1bd7f7670709ee43ac319fc72a",
          "sha256": "d5b71010b7b40bcdeb109c52409c3857633ae4e5a5d87b97d44ae43f8a00c5e7",
          "sha1": "2b8512aa2be8429a330a1d87695033731613d9da",
          "md5": "16e97d115e8ed505eaf688a90fd42ebe"
        }
      ]
    }
  ]
}
