{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-assets",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-1.112.0-0.6.21.jar",
          "url": "cdk-assets-1.112.0-0.6.21.jar",
          "size": 16447,
          "sha512": "4483050a3977c7a741baf8d2cfdb5f0f77d0d0a7b5eaf7dea536ca67b3a69686a858a5e7801b5a3bf409b2784eff9a72b70e158579a95a0188058883995da662",
          "sha256": "9e51adc5d570f10322fa33fcbaf5a2d47449ad702965ae9c6bdfaf3f860c6248",
          "sha1": "b952ac1d2c953040894cb70ffd0404363b18b61e",
          "md5": "c34ad9c189738baf521647377bfe738e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-assets",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-assets-1.112.0-0.6.21.jar",
          "url": "cdk-assets-1.112.0-0.6.21.jar",
          "size": 16447,
          "sha512": "4483050a3977c7a741baf8d2cfdb5f0f77d0d0a7b5eaf7dea536ca67b3a69686a858a5e7801b5a3bf409b2784eff9a72b70e158579a95a0188058883995da662",
          "sha256": "9e51adc5d570f10322fa33fcbaf5a2d47449ad702965ae9c6bdfaf3f860c6248",
          "sha1": "b952ac1d2c953040894cb70ffd0404363b18b61e",
          "md5": "c34ad9c189738baf521647377bfe738e"
        }
      ]
    }
  ]
}
