{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sdb",
    "version": "1.112.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "635otboqmzf4dpqli6tn2j4rca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sdb",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdb-1.112.0-0.6.21.jar",
          "url": "sdb-1.112.0-0.6.21.jar",
          "size": 8453,
          "sha512": "2b3a4530f3bb0ca8e9dc584add70399f93b6a83f6a4bde65fc5be999b3eba75b255a2466ea7476985328710fa5951b0d934ffc1ffb44fa2122531ce25a66dbec",
          "sha256": "5e28e9e03317f30ada37f4f7e9b20e62c4cc3bc40d6cb5bab3b3f54c3f3fc9db",
          "sha1": "4e9085e60305b49ea9d49eb978e012ac0ea6fc46",
          "md5": "18a8d909e51ab4c47caf717089b17cea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sdb",
          "version": {
            "requires": "1.112.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.112.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdb-1.112.0-0.6.21.jar",
          "url": "sdb-1.112.0-0.6.21.jar",
          "size": 8453,
          "sha512": "2b3a4530f3bb0ca8e9dc584add70399f93b6a83f6a4bde65fc5be999b3eba75b255a2466ea7476985328710fa5951b0d934ffc1ffb44fa2122531ce25a66dbec",
          "sha256": "5e28e9e03317f30ada37f4f7e9b20e62c4cc3bc40d6cb5bab3b3f54c3f3fc9db",
          "sha1": "4e9085e60305b49ea9d49eb978e012ac0ea6fc46",
          "md5": "18a8d909e51ab4c47caf717089b17cea"
        }
      ]
    }
  ]
}
