{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "transfer",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "transfer",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "transfer-1.109.0-0.6.21.jar",
          "url": "transfer-1.109.0-0.6.21.jar",
          "size": 74771,
          "sha512": "aea7a6741b42bdb465c5b6906258d1996a48b124764b49524479dd37ce401f48d9743170d3c6cadd43ed1129a9a46c4d35a2e3fb9d26a6dd27f33bbbbc11d390",
          "sha256": "cfb4cb56b2484664f448fcaa68558184a7f24cd9a705bc7611945e6822df3603",
          "sha1": "1ea8a257834dd10c6a94c0f3e9cea8933061fe51",
          "md5": "527e78adc7d069457516684660f8c46f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "transfer",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "transfer-1.109.0-0.6.21.jar",
          "url": "transfer-1.109.0-0.6.21.jar",
          "size": 74771,
          "sha512": "aea7a6741b42bdb465c5b6906258d1996a48b124764b49524479dd37ce401f48d9743170d3c6cadd43ed1129a9a46c4d35a2e3fb9d26a6dd27f33bbbbc11d390",
          "sha256": "cfb4cb56b2484664f448fcaa68558184a7f24cd9a705bc7611945e6822df3603",
          "sha1": "1ea8a257834dd10c6a94c0f3e9cea8933061fe51",
          "md5": "527e78adc7d069457516684660f8c46f"
        }
      ]
    }
  ]
}
