{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "groundstation",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "groundstation",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "groundstation-1.114.0-0.6.21.jar",
          "url": "groundstation-1.114.0-0.6.21.jar",
          "size": 219916,
          "sha512": "8b0448f11851ad34a0ddca67767697a85943448c1683ecca44f68d71cf7c7001680b6ae4cbd2d424bdfc1b44c57db1f249e631a934c4dbfc9f4821b497faff15",
          "sha256": "fc4e2e36aeb53f810d3887341d3ddb826c2874b10393be497c519b52d9307e76",
          "sha1": "4d0bd7cf31208cd2aaeca27594d551a68c2e127",
          "md5": "57a35c1c258a0e4fdc8c5df0676da905"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "groundstation",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "groundstation-1.114.0-0.6.21.jar",
          "url": "groundstation-1.114.0-0.6.21.jar",
          "size": 219916,
          "sha512": "8b0448f11851ad34a0ddca67767697a85943448c1683ecca44f68d71cf7c7001680b6ae4cbd2d424bdfc1b44c57db1f249e631a934c4dbfc9f4821b497faff15",
          "sha256": "fc4e2e36aeb53f810d3887341d3ddb826c2874b10393be497c519b52d9307e76",
          "sha1": "4d0bd7cf31208cd2aaeca27594d551a68c2e127",
          "md5": "57a35c1c258a0e4fdc8c5df0676da905"
        }
      ]
    }
  ]
}
