{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "autoscaling-common",
    "version": "1.101.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "d5vusioiqzbnxk6vuwjeusvgpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling-common",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-common-1.101.0-0.6.21.jar",
          "url": "autoscaling-common-1.101.0-0.6.21.jar",
          "size": 15776,
          "sha512": "b638ab951b96d76df353097b53bd72b436aaa1205a403f93bc419bfc30a9816e21cee31c8aeaa3077b0c459737e1f5f0e8df57bb4d64bd847dccd2561d04693c",
          "sha256": "fa9450d248f7065cdde7439e1c8cf75175738bc81351b915545d220589e18409",
          "sha1": "3e996571308117c7cc16d158e15de49bef6c7aae",
          "md5": "4e3c179a017b505b2b5f87fbb40507a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling-common",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-common-1.101.0-0.6.21.jar",
          "url": "autoscaling-common-1.101.0-0.6.21.jar",
          "size": 15776,
          "sha512": "b638ab951b96d76df353097b53bd72b436aaa1205a403f93bc419bfc30a9816e21cee31c8aeaa3077b0c459737e1f5f0e8df57bb4d64bd847dccd2561d04693c",
          "sha256": "fa9450d248f7065cdde7439e1c8cf75175738bc81351b915545d220589e18409",
          "sha1": "3e996571308117c7cc16d158e15de49bef6c7aae",
          "md5": "4e3c179a017b505b2b5f87fbb40507a2"
        }
      ]
    }
  ]
}
