{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "s3outposts",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "s3outposts",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "s3outposts-1.115.0-0.6.21.jar",
          "url": "s3outposts-1.115.0-0.6.21.jar",
          "size": 77020,
          "sha512": "2b2c2ee6bfe0452dff8274306cc23c2b1797e3761fd5afcfe2bb0e943c65957b4ef56994dad138d3a916bfeaefc758bd42a7ed57ab784fdd37eb53d896ce296d",
          "sha256": "80078c30d8fa47725e40f6f89cbdf99c586be707d21325a8477d53ff6f954e7",
          "sha1": "3d42e134d705808df6e0945395feb18fe23349d2",
          "md5": "7c38a9a9dea1826220bc41cc2993ad70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "s3outposts",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "s3outposts-1.115.0-0.6.21.jar",
          "url": "s3outposts-1.115.0-0.6.21.jar",
          "size": 77020,
          "sha512": "2b2c2ee6bfe0452dff8274306cc23c2b1797e3761fd5afcfe2bb0e943c65957b4ef56994dad138d3a916bfeaefc758bd42a7ed57ab784fdd37eb53d896ce296d",
          "sha256": "80078c30d8fa47725e40f6f89cbdf99c586be707d21325a8477d53ff6f954e7",
          "sha1": "3d42e134d705808df6e0945395feb18fe23349d2",
          "md5": "7c38a9a9dea1826220bc41cc2993ad70"
        }
      ]
    }
  ]
}
