{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "athena",
    "version": "1.101.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "d5vusioiqzbnxk6vuwjeusvgpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "athena",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "athena-1.101.0-0.6.21.jar",
          "url": "athena-1.101.0-0.6.21.jar",
          "size": 152056,
          "sha512": "e83e2eca0f8b6b7ed06d0f272e85089c502a10ef0886ab9809b26e75bc8fd2c7dd3d66888f24299e5bf4d33050a477bc3e4a545c652210c613b0a6a0f14faa04",
          "sha256": "4349c9a2ebe7b3c76d0bfe5d901cc2e5fa584ba728600297ba5c1891c3c3ccca",
          "sha1": "955d7a73eaeb7ba1dcce01b49abda59d4014df26",
          "md5": "d368929febd2e68f5ef549dcb5e7e4c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "athena",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "athena-1.101.0-0.6.21.jar",
          "url": "athena-1.101.0-0.6.21.jar",
          "size": 152056,
          "sha512": "e83e2eca0f8b6b7ed06d0f272e85089c502a10ef0886ab9809b26e75bc8fd2c7dd3d66888f24299e5bf4d33050a477bc3e4a545c652210c613b0a6a0f14faa04",
          "sha256": "4349c9a2ebe7b3c76d0bfe5d901cc2e5fa584ba728600297ba5c1891c3c3ccca",
          "sha1": "955d7a73eaeb7ba1dcce01b49abda59d4014df26",
          "md5": "d368929febd2e68f5ef549dcb5e7e4c2"
        }
      ]
    }
  ]
}
