{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "amazonmq",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "amazonmq",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "amazonmq-1.104.0-0.6.21.jar",
          "url": "amazonmq-1.104.0-0.6.21.jar",
          "size": 164752,
          "sha512": "4c8ed10349d3e7afa13c92eae4fef5e106e628887591cfdcc0e8ee934f10f2fa901200106f86c71e614d1fbd1c11622cbe9a6178e1d4918b47dec063765ffc36",
          "sha256": "2d343a1ce96d1c1437e5340fe3587d52c813d9198f7139326b5b603bfdba2b04",
          "sha1": "205310b95b999e69fa9af2ddeb95180d49266fc1",
          "md5": "b864a169e7ed3e47d74ad94a4c50efa7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "amazonmq",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "amazonmq-1.104.0-0.6.21.jar",
          "url": "amazonmq-1.104.0-0.6.21.jar",
          "size": 164752,
          "sha512": "4c8ed10349d3e7afa13c92eae4fef5e106e628887591cfdcc0e8ee934f10f2fa901200106f86c71e614d1fbd1c11622cbe9a6178e1d4918b47dec063765ffc36",
          "sha256": "2d343a1ce96d1c1437e5340fe3587d52c813d9198f7139326b5b603bfdba2b04",
          "sha1": "205310b95b999e69fa9af2ddeb95180d49266fc1",
          "md5": "b864a169e7ed3e47d74ad94a4c50efa7"
        }
      ]
    }
  ]
}
