{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "datasync",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "datasync",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "datasync-1.104.0-0.6.21.jar",
          "url": "datasync-1.104.0-0.6.21.jar",
          "size": 165815,
          "sha512": "21dec3f3aaa0ffddde9e87f0d7e57855616a03c6a4fe7b20b29bc5c7b6e5996835b62cd5472f8317476b666368854648688f2586942bffd0fabcd2a010810bfd",
          "sha256": "2df5392cb2604f7c682301638a5d411d25325ab638a33d7d4a65c5167e1520ff",
          "sha1": "aeae63082da84741eee393cadd271280b2d91d42",
          "md5": "131c570a532adabd0f25f301a8459faf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "datasync",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "datasync-1.104.0-0.6.21.jar",
          "url": "datasync-1.104.0-0.6.21.jar",
          "size": 165815,
          "sha512": "21dec3f3aaa0ffddde9e87f0d7e57855616a03c6a4fe7b20b29bc5c7b6e5996835b62cd5472f8317476b666368854648688f2586942bffd0fabcd2a010810bfd",
          "sha256": "2df5392cb2604f7c682301638a5d411d25325ab638a33d7d4a65c5167e1520ff",
          "sha1": "aeae63082da84741eee393cadd271280b2d91d42",
          "md5": "131c570a532adabd0f25f301a8459faf"
        }
      ]
    }
  ]
}
