{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iotevents",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "pksuzuox3ne6pgnvsva7g32w2m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iotevents",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotevents-1.110.1-0.6.21.jar",
          "url": "iotevents-1.110.1-0.6.21.jar",
          "size": 292861,
          "sha512": "b3e7606aeae4837bf1092a478968a1a0d17cda548d8d7b97baacb97dee3ebde9acad0f89d1380f3cd8e950577d38965b8a625cf77bc394b847504f472104c74a",
          "sha256": "58f5ebcd70f92278223ac4d4bc5c1b494d0cf3ebf1c2db6a625833da136a6146",
          "sha1": "666901244bfe42d060193977fee052808de3ab6",
          "md5": "4b14275cbf4cef28054b2cf9ef9d40b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iotevents",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "iotevents-1.110.1-0.6.21.jar",
          "url": "iotevents-1.110.1-0.6.21.jar",
          "size": 292861,
          "sha512": "b3e7606aeae4837bf1092a478968a1a0d17cda548d8d7b97baacb97dee3ebde9acad0f89d1380f3cd8e950577d38965b8a625cf77bc394b847504f472104c74a",
          "sha256": "58f5ebcd70f92278223ac4d4bc5c1b494d0cf3ebf1c2db6a625833da136a6146",
          "sha1": "666901244bfe42d060193977fee052808de3ab6",
          "md5": "4b14275cbf4cef28054b2cf9ef9d40b9"
        }
      ]
    }
  ]
}
