{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ce",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ce",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ce-1.102.0-0.6.21.jar",
          "url": "ce-1.102.0-0.6.21.jar",
          "size": 36794,
          "sha512": "fb137d982051269ea1e616fa081ed35fbcaf325b96ac2d71ab7a5831d065e9cb14fbbc1182e052ba8e1392d86aaf5ea1405ad859d78747b6d1f081c6d1d1c5c3",
          "sha256": "954d6752662bf53ae48104321f391f68da999b33e402e2f464925e2be8eb2c0d",
          "sha1": "4f08cd74a468d9f535f224af52925ef91f58b10f",
          "md5": "8de7a0d35999837337e31e4d2a5bddb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ce",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ce-1.102.0-0.6.21.jar",
          "url": "ce-1.102.0-0.6.21.jar",
          "size": 36794,
          "sha512": "fb137d982051269ea1e616fa081ed35fbcaf325b96ac2d71ab7a5831d065e9cb14fbbc1182e052ba8e1392d86aaf5ea1405ad859d78747b6d1f081c6d1d1c5c3",
          "sha256": "954d6752662bf53ae48104321f391f68da999b33e402e2f464925e2be8eb2c0d",
          "sha1": "4f08cd74a468d9f535f224af52925ef91f58b10f",
          "md5": "8de7a0d35999837337e31e4d2a5bddb6"
        }
      ]
    }
  ]
}
