{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "route53resolver",
    "version": "1.64.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "route53resolver",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "route53resolver-1.64.0-0.6.22.jar",
          "url": "route53resolver-1.64.0-0.6.22.jar",
          "size": 65200,
          "sha512": "0242bfbc982e1435ede7e657b307d7a535d668e1749623c16142e6769ff3f5bd20ae68bc7de2d8641ef964234bf1c316bf5c39e9c6af02319623975ccdca9ae3",
          "sha256": "d81db5ee8d6c87a51a9af098ef73a60b0ffc58db636851ce683526435944de80",
          "sha1": "c365bdb5faeb29a150ecb76d6e602db99f5f19f9",
          "md5": "983cd18d1b88fc38fcca208f712c8443"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "route53resolver",
          "version": {
            "requires": "1.64.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.64.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "route53resolver-1.64.0-0.6.22.jar",
          "url": "route53resolver-1.64.0-0.6.22.jar",
          "size": 65200,
          "sha512": "0242bfbc982e1435ede7e657b307d7a535d668e1749623c16142e6769ff3f5bd20ae68bc7de2d8641ef964234bf1c316bf5c39e9c6af02319623975ccdca9ae3",
          "sha256": "d81db5ee8d6c87a51a9af098ef73a60b0ffc58db636851ce683526435944de80",
          "sha1": "c365bdb5faeb29a150ecb76d6e602db99f5f19f9",
          "md5": "983cd18d1b88fc38fcca208f712c8443"
        }
      ]
    }
  ]
}
