{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "imagebuilder",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.109.0-0.6.21.jar",
          "url": "imagebuilder-1.109.0-0.6.21.jar",
          "size": 284914,
          "sha512": "e89147a1d2bd4185c983242b07369ec25b47cd8e56731539b7d5024f2daa03c3048510ad7d6bbd15585767e643a0551332d10174f0776ecac04068c70354270d",
          "sha256": "ec43c7a778c3649364315554b48a3d3fc03a3e3570bf32dd7a337c14da9dc65d",
          "sha1": "be3e9bf363b2b9fdfb0af3dc361f20f663a88d6b",
          "md5": "8b74691faa964f7c38ebe5eb7da5bab3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.109.0-0.6.21.jar",
          "url": "imagebuilder-1.109.0-0.6.21.jar",
          "size": 284914,
          "sha512": "e89147a1d2bd4185c983242b07369ec25b47cd8e56731539b7d5024f2daa03c3048510ad7d6bbd15585767e643a0551332d10174f0776ecac04068c70354270d",
          "sha256": "ec43c7a778c3649364315554b48a3d3fc03a3e3570bf32dd7a337c14da9dc65d",
          "sha1": "be3e9bf363b2b9fdfb0af3dc361f20f663a88d6b",
          "md5": "8b74691faa964f7c38ebe5eb7da5bab3"
        }
      ]
    }
  ]
}
