{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "appstream",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "appstream",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appstream-1.104.0-0.6.21.jar",
          "url": "appstream-1.104.0-0.6.21.jar",
          "size": 234462,
          "sha512": "77d879371ddf6159407462f6b6bc035ce7968bccb9b7a7d9ed77a38da344f9837f57c9cf6e40f4067051a573bd21d95f1ebc60182adc065df4fbbab20479cab5",
          "sha256": "209e8598d190f15de450a4286a8ee839ea59c704625b501e9dd6a03f372cd2e5",
          "sha1": "c42017a5c2572f0eb136f4b2fa4dae57707c25e6",
          "md5": "a042603772fcf5898d3e13355c656bbc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "appstream",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appstream-1.104.0-0.6.21.jar",
          "url": "appstream-1.104.0-0.6.21.jar",
          "size": 234462,
          "sha512": "77d879371ddf6159407462f6b6bc035ce7968bccb9b7a7d9ed77a38da344f9837f57c9cf6e40f4067051a573bd21d95f1ebc60182adc065df4fbbab20479cab5",
          "sha256": "209e8598d190f15de450a4286a8ee839ea59c704625b501e9dd6a03f372cd2e5",
          "sha1": "c42017a5c2572f0eb136f4b2fa4dae57707c25e6",
          "md5": "a042603772fcf5898d3e13355c656bbc"
        }
      ]
    }
  ]
}
