{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cloud9",
    "version": "1.31.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cloud9",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "cloud9-1.31.0-0.6.22.jar",
          "url": "cloud9-1.31.0-0.6.22.jar",
          "size": 31173,
          "sha512": "c64961e33238325e831335ddb7e30da9d3ce5f95d9ab80a43202515bfc0bfda1fc84e8eb2c72d638014cba23813402689fcfb07af8faa007eb558c3937eceb55",
          "sha256": "3a900e1cf30c6465e014bef43d0b04b43d90550e8dbac804cbb3357bc669b0f7",
          "sha1": "e4d75d3df5a8fbd5d5bcad8c8c01d02c72f01275",
          "md5": "71cd1c95ace7ff91be8a89d049a8d034"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cloud9",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "cloud9-1.31.0-0.6.22.jar",
          "url": "cloud9-1.31.0-0.6.22.jar",
          "size": 31173,
          "sha512": "c64961e33238325e831335ddb7e30da9d3ce5f95d9ab80a43202515bfc0bfda1fc84e8eb2c72d638014cba23813402689fcfb07af8faa007eb558c3937eceb55",
          "sha256": "3a900e1cf30c6465e014bef43d0b04b43d90550e8dbac804cbb3357bc669b0f7",
          "sha1": "e4d75d3df5a8fbd5d5bcad8c8c01d02c72f01275",
          "md5": "71cd1c95ace7ff91be8a89d049a8d034"
        }
      ]
    }
  ]
}
