{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-lambda-layer-awscli",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "k23roxkwqjbs5i6arr4lg4r4xm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-lambda-layer-awscli",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-lambda-layer-awscli-1.110.1-0.6.21.jar",
          "url": "cdk-lambda-layer-awscli-1.110.1-0.6.21.jar",
          "size": 448,
          "sha512": "4b8c2b1a91a78a66743238c03bde57777ae240ab88f6b66dc14e1f856b26384ec04b8bce956b383aa17ed5386d74e00658ac755af9934ced79d02fa525ec0312",
          "sha256": "93b5e4d6a5335589fb15421c0fcb44c3234cc66815f018681ed5db1b4852908b",
          "sha1": "4290258c769e139c6caedd04cc610527530ea4d4",
          "md5": "45e9655e428c6859e7d09b79c15e1a6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-lambda-layer-awscli",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-lambda-layer-awscli-1.110.1-0.6.21.jar",
          "url": "cdk-lambda-layer-awscli-1.110.1-0.6.21.jar",
          "size": 448,
          "sha512": "4b8c2b1a91a78a66743238c03bde57777ae240ab88f6b66dc14e1f856b26384ec04b8bce956b383aa17ed5386d74e00658ac755af9934ced79d02fa525ec0312",
          "sha256": "93b5e4d6a5335589fb15421c0fcb44c3234cc66815f018681ed5db1b4852908b",
          "sha1": "4290258c769e139c6caedd04cc610527530ea4d4",
          "md5": "45e9655e428c6859e7d09b79c15e1a6a"
        }
      ]
    }
  ]
}
