{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "dax",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "dax",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dax-1.102.0-0.6.21.jar",
          "url": "dax-1.102.0-0.6.21.jar",
          "size": 42372,
          "sha512": "48bdc52cf2c41e080d58f186e8ec25fe7844b5f272bc602ef08e551e73557ec7f609a0e0d21a0b6b73fdac46ed55b9b6f93117d07e4239c24da3678e7b41dd1e",
          "sha256": "d557dd928c7444ea0246de6e34172ed1718e76d90b2fffc2b7922bc9c9fb0e9b",
          "sha1": "c161c0759d94e413066e2002165b72ef4ef5167",
          "md5": "336f7473947828c0f23e2b4cffcc4eb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "dax",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dax-1.102.0-0.6.21.jar",
          "url": "dax-1.102.0-0.6.21.jar",
          "size": 42372,
          "sha512": "48bdc52cf2c41e080d58f186e8ec25fe7844b5f272bc602ef08e551e73557ec7f609a0e0d21a0b6b73fdac46ed55b9b6f93117d07e4239c24da3678e7b41dd1e",
          "sha256": "d557dd928c7444ea0246de6e34172ed1718e76d90b2fffc2b7922bc9c9fb0e9b",
          "sha1": "c161c0759d94e413066e2002165b72ef4ef5167",
          "md5": "336f7473947828c0f23e2b4cffcc4eb8"
        }
      ]
    }
  ]
}
