{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "pinpointemail",
    "version": "1.106.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "dr3fova3trezxe3kqt6fk3hm3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "pinpointemail",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "pinpointemail-1.106.0-0.6.21.jar",
          "url": "pinpointemail-1.106.0-0.6.21.jar",
          "size": 191958,
          "sha512": "c1aaaddd3ef4f7bd54f2b7e34f5d4be5c3086a070db02ce425058dab9645210540aeb99452b5a88efcf20403cbfc3f8949d24b6cd7fd75e5cf4b415bd0d24172",
          "sha256": "c419015b92ab01d5c078981c85c06a7c5ee337089e868eb54bb406eb2c9f9e81",
          "sha1": "ce52bfb749eb471c2ff98ce51da2b7127f6ad10d",
          "md5": "14c77f5f2c79e0f5fc6af323b0b53e66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "pinpointemail",
          "version": {
            "requires": "1.106.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "pinpointemail-1.106.0-0.6.21.jar",
          "url": "pinpointemail-1.106.0-0.6.21.jar",
          "size": 191958,
          "sha512": "c1aaaddd3ef4f7bd54f2b7e34f5d4be5c3086a070db02ce425058dab9645210540aeb99452b5a88efcf20403cbfc3f8949d24b6cd7fd75e5cf4b415bd0d24172",
          "sha256": "c419015b92ab01d5c078981c85c06a7c5ee337089e868eb54bb406eb2c9f9e81",
          "sha1": "ce52bfb749eb471c2ff98ce51da2b7127f6ad10d",
          "md5": "14c77f5f2c79e0f5fc6af323b0b53e66"
        }
      ]
    }
  ]
}
