{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "amazonmq",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "amazonmq",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "amazonmq-1.117.0-0.6.25.jar",
          "url": "amazonmq-1.117.0-0.6.25.jar",
          "size": 164800,
          "sha512": "f28cc67162a6bf8c0129b0c3b83b38a0d37c8789182b98f36792151597182d13c57448239d3e471b4e9ce0e816dc3cf59375242b9fda7a7404a63c94ac6a510f",
          "sha256": "33870c2154995ab4133639ade534b0b02ecc0b2abab2b96f3c828b016ce28b75",
          "sha1": "21a0efbdd0873d4e4eb238f0f5d07c90bf697f7d",
          "md5": "3c556df90412f8b393675074d0a78c05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "amazonmq",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "amazonmq-1.117.0-0.6.25.jar",
          "url": "amazonmq-1.117.0-0.6.25.jar",
          "size": 164800,
          "sha512": "f28cc67162a6bf8c0129b0c3b83b38a0d37c8789182b98f36792151597182d13c57448239d3e471b4e9ce0e816dc3cf59375242b9fda7a7404a63c94ac6a510f",
          "sha256": "33870c2154995ab4133639ade534b0b02ecc0b2abab2b96f3c828b016ce28b75",
          "sha1": "21a0efbdd0873d4e4eb238f0f5d07c90bf697f7d",
          "md5": "3c556df90412f8b393675074d0a78c05"
        }
      ]
    }
  ]
}
