{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "robomaker",
    "version": "1.117.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "robomaker",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "robomaker-1.117.0-0.6.25.jar",
          "url": "robomaker-1.117.0-0.6.25.jar",
          "size": 120996,
          "sha512": "858954675588a52ab20421f1927dccf3334422fe2d0d378d318dfb137d26a5613aca8c40ff0253a80735ff5d84a9bc7100d9f6f5f04ccd38bc50186083955732",
          "sha256": "81790d861325bc5b9227cbbbf46f3d862c359ade0bd454fbb48e758ef385c64d",
          "sha1": "2376e28dfde319537d1b54a546632a664937bed8",
          "md5": "9c7fbb90627c7620f6d6758b73e531f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "robomaker",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "robomaker-1.117.0-0.6.25.jar",
          "url": "robomaker-1.117.0-0.6.25.jar",
          "size": 120996,
          "sha512": "858954675588a52ab20421f1927dccf3334422fe2d0d378d318dfb137d26a5613aca8c40ff0253a80735ff5d84a9bc7100d9f6f5f04ccd38bc50186083955732",
          "sha256": "81790d861325bc5b9227cbbbf46f3d862c359ade0bd454fbb48e758ef385c64d",
          "sha1": "2376e28dfde319537d1b54a546632a664937bed8",
          "md5": "9c7fbb90627c7620f6d6758b73e531f9"
        }
      ]
    }
  ]
}
