{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "acmpca",
    "version": "1.102.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3v7jvpyge5da5n7rhvpphv65wa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "acmpca",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "acmpca-1.102.0-0.6.21.jar",
          "url": "acmpca-1.102.0-0.6.21.jar",
          "size": 327831,
          "sha512": "20650bf423be91ef0f18cc2f150c9538bfe1a3ad1378a2117b9c057c05ed960ec3355ce126c6dcc8c18b610a2fb6071d5fe163333113e9b1be0efd5210a0afd",
          "sha256": "376b22ec7534318efa888cb90cd5993f61a579594133e6841a8eba3e8fc6d375",
          "sha1": "db9eb66e35c94a0e99bd25c1531f8002d498c819",
          "md5": "f1fd0263a4f8c45bc98467e84970eefb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "acmpca",
          "version": {
            "requires": "1.102.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.102.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "acmpca-1.102.0-0.6.21.jar",
          "url": "acmpca-1.102.0-0.6.21.jar",
          "size": 327831,
          "sha512": "20650bf423be91ef0f18cc2f150c9538bfe1a3ad1378a2117b9c057c05ed960ec3355ce126c6dcc8c18b610a2fb6071d5fe163333113e9b1be0efd5210a0afd",
          "sha256": "376b22ec7534318efa888cb90cd5993f61a579594133e6841a8eba3e8fc6d375",
          "sha1": "db9eb66e35c94a0e99bd25c1531f8002d498c819",
          "md5": "f1fd0263a4f8c45bc98467e84970eefb"
        }
      ]
    }
  ]
}
