{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "eks-legacy",
    "version": "1.117.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ka4pthfoybhvvnwbwaxmu2dbry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "eks-legacy",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudformation",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ssm",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eks-legacy-1.117.0-0.6.21.jar",
          "url": "eks-legacy-1.117.0-0.6.21.jar",
          "size": 236317,
          "sha512": "ec83dd3f64d04f6fc8f4c3a23631c5d73dcf87460b94b878de263a732a40e255c95da4de0ff74be117f5e8471e60ee590da68ca32927e718893fd34a10a39d04",
          "sha256": "3a824d7a337b5b8b90abafdb70eb20d810bb213075598fb281a44013fcfed971",
          "sha1": "3cd4fc847efe31080d0c6883ecb156e3cfcc49dd",
          "md5": "b396e06faa2ae2a7a2859073461526cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "eks-legacy",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "autoscaling",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudformation",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ssm",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eks-legacy-1.117.0-0.6.21.jar",
          "url": "eks-legacy-1.117.0-0.6.21.jar",
          "size": 236317,
          "sha512": "ec83dd3f64d04f6fc8f4c3a23631c5d73dcf87460b94b878de263a732a40e255c95da4de0ff74be117f5e8471e60ee590da68ca32927e718893fd34a10a39d04",
          "sha256": "3a824d7a337b5b8b90abafdb70eb20d810bb213075598fb281a44013fcfed971",
          "sha1": "3cd4fc847efe31080d0c6883ecb156e3cfcc49dd",
          "md5": "b396e06faa2ae2a7a2859073461526cf"
        }
      ]
    }
  ]
}
