{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "inspector",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "inspector",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "inspector-1.114.0-0.6.21.jar",
          "url": "inspector-1.114.0-0.6.21.jar",
          "size": 41126,
          "sha512": "d64b9762784be2121829b45c566a529d9e3885ae61e416f73f234a642a03e5f6f7955398fadc24f12ee8accada279ee7309d6abe976379a57a4c44826012e2ee",
          "sha256": "c35037efda44c4c7b3d49158d332abfd1a147c6fd683631a0e051f5a03c5e2a6",
          "sha1": "ec104f63690d7e5980404eb971ed6e3172034735",
          "md5": "b0192f5d5116412ce60d2886976e436d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "inspector",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "inspector-1.114.0-0.6.21.jar",
          "url": "inspector-1.114.0-0.6.21.jar",
          "size": 41126,
          "sha512": "d64b9762784be2121829b45c566a529d9e3885ae61e416f73f234a642a03e5f6f7955398fadc24f12ee8accada279ee7309d6abe976379a57a4c44826012e2ee",
          "sha256": "c35037efda44c4c7b3d49158d332abfd1a147c6fd683631a0e051f5a03c5e2a6",
          "sha1": "ec104f63690d7e5980404eb971ed6e3172034735",
          "md5": "b0192f5d5116412ce60d2886976e436d"
        }
      ]
    }
  ]
}
