{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "amazonmq",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "amazonmq",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "amazonmq-1.103.0-0.6.21.jar",
          "url": "amazonmq-1.103.0-0.6.21.jar",
          "size": 164748,
          "sha512": "c1cc596000134523bdb479df3f88e5101b9cecbfee50ee270e3a810bc25c6937c3587817f55a266697b22329b960a33d7f75267f0277f0d2fe8d7ebf0a15ad37",
          "sha256": "3f1223c4ed0a816475b989a490383c9713e3c2d0463bdc8279b5de4e36ffc59b",
          "sha1": "a118245fc6cb05bf7f35dbd179da5e90a901a010",
          "md5": "f94846386ca20f0256a7d89aacf41ae6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "amazonmq",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "amazonmq-1.103.0-0.6.21.jar",
          "url": "amazonmq-1.103.0-0.6.21.jar",
          "size": 164748,
          "sha512": "c1cc596000134523bdb479df3f88e5101b9cecbfee50ee270e3a810bc25c6937c3587817f55a266697b22329b960a33d7f75267f0277f0d2fe8d7ebf0a15ad37",
          "sha256": "3f1223c4ed0a816475b989a490383c9713e3c2d0463bdc8279b5de4e36ffc59b",
          "sha1": "a118245fc6cb05bf7f35dbd179da5e90a901a010",
          "md5": "f94846386ca20f0256a7d89aacf41ae6"
        }
      ]
    }
  ]
}
