{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-region-info",
    "version": "1.34.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.34.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-region-info-1.34.0-0.6.22.jar",
          "url": "cdk-region-info-1.34.0-0.6.22.jar",
          "size": 432,
          "sha512": "3113da25c47fda4dd9aeb001defd079001f6a9a9c3d56d7514abeebb408fafb6a4e4d6b2a9d5782399a13f84d6edcb6933aa84ad84dc3a8d63aa5def142843ac",
          "sha256": "2eb389a0765ce9f461405a60eef47a1cb42f516fd24c01e0466ea1964dd64e1b",
          "sha1": "590e5667269c502b1e4860c04bdc642900ff0f6c",
          "md5": "0a3fa294484c6f8e6e9f6a1dffdff966"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.34.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-region-info-1.34.0-0.6.22.jar",
          "url": "cdk-region-info-1.34.0-0.6.22.jar",
          "size": 432,
          "sha512": "3113da25c47fda4dd9aeb001defd079001f6a9a9c3d56d7514abeebb408fafb6a4e4d6b2a9d5782399a13f84d6edcb6933aa84ad84dc3a8d63aa5def142843ac",
          "sha256": "2eb389a0765ce9f461405a60eef47a1cb42f516fd24c01e0466ea1964dd64e1b",
          "sha1": "590e5667269c502b1e4860c04bdc642900ff0f6c",
          "md5": "0a3fa294484c6f8e6e9f6a1dffdff966"
        }
      ]
    }
  ]
}
