{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "greengrass",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "greengrass",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrass-1.105.0-0.6.21.jar",
          "url": "greengrass-1.105.0-0.6.21.jar",
          "size": 685806,
          "sha512": "a8ba42ffd98f1b7761537d00ae4421d5ea580e5a2ec2e14868223fbb090f056dedc0e33caf7cbfcc0a135a274ed20773556709dc0cbbfc8ed37e973156cdc94",
          "sha256": "6b5d95abae46316703ca8995bb0ef44906df898d7acfaf650427fe910b3fcfa",
          "sha1": "57612fad8d99404be7af4bab1a9de8b6d5a866a5",
          "md5": "2aa8fde1e448dfeacc84c92fa87a4779"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "greengrass",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrass-1.105.0-0.6.21.jar",
          "url": "greengrass-1.105.0-0.6.21.jar",
          "size": 685806,
          "sha512": "a8ba42ffd98f1b7761537d00ae4421d5ea580e5a2ec2e14868223fbb090f056dedc0e33caf7cbfcc0a135a274ed20773556709dc0cbbfc8ed37e973156cdc94",
          "sha256": "6b5d95abae46316703ca8995bb0ef44906df898d7acfaf650427fe910b3fcfa",
          "sha1": "57612fad8d99404be7af4bab1a9de8b6d5a866a5",
          "md5": "2aa8fde1e448dfeacc84c92fa87a4779"
        }
      ]
    }
  ]
}
