{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "mediapackage",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "mediapackage",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediapackage-1.115.0-0.6.21.jar",
          "url": "mediapackage-1.115.0-0.6.21.jar",
          "size": 440701,
          "sha512": "a2c4eed54c826a1b5dcf15847e78e2ec1373386fc25445b032e20e5897eaab730550e080ef14616f3291df280deb975ee42a44c9af3c21db30e8fa66277ca4a3",
          "sha256": "febdf91cf70681d5a0faa828bdc9325cd1edcb41b603e724860bf9266739b065",
          "sha1": "303400a91164dd37d6364f82d6e137d842438813",
          "md5": "8e35e0683156e89f7633c021d55bbadc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "mediapackage",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "mediapackage-1.115.0-0.6.21.jar",
          "url": "mediapackage-1.115.0-0.6.21.jar",
          "size": 440701,
          "sha512": "a2c4eed54c826a1b5dcf15847e78e2ec1373386fc25445b032e20e5897eaab730550e080ef14616f3291df280deb975ee42a44c9af3c21db30e8fa66277ca4a3",
          "sha256": "febdf91cf70681d5a0faa828bdc9325cd1edcb41b603e724860bf9266739b065",
          "sha1": "303400a91164dd37d6364f82d6e137d842438813",
          "md5": "8e35e0683156e89f7633c021d55bbadc"
        }
      ]
    }
  ]
}
