{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lambda-go",
    "version": "1.105.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6ksfungeebg7lbcagzumy3ww64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-go",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-go-1.105.0-0.6.21.jar",
          "url": "lambda-go-1.105.0-0.6.21.jar",
          "size": 24042,
          "sha512": "cc8f4634868dfa4414d3b2380d3a67aec11371433fbf12badc98f8ee6e72fcaac9c59c5e082630a3f04887bee95623fa6dd24abaa29f266b66f9e8dafe512b4c",
          "sha256": "2096b094aa71f68f5104a5c7bba22318f1db239702fcd66dc641e2b3cc1c6297",
          "sha1": "9ca54076fc7c322cceaf51522ae91149cd5b77c5",
          "md5": "78e99b6f15d8dd877b9fb59ef4184695"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-go",
          "version": {
            "requires": "1.105.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.105.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-go-1.105.0-0.6.21.jar",
          "url": "lambda-go-1.105.0-0.6.21.jar",
          "size": 24042,
          "sha512": "cc8f4634868dfa4414d3b2380d3a67aec11371433fbf12badc98f8ee6e72fcaac9c59c5e082630a3f04887bee95623fa6dd24abaa29f266b66f9e8dafe512b4c",
          "sha256": "2096b094aa71f68f5104a5c7bba22318f1db239702fcd66dc641e2b3cc1c6297",
          "sha1": "9ca54076fc7c322cceaf51522ae91149cd5b77c5",
          "md5": "78e99b6f15d8dd877b9fb59ef4184695"
        }
      ]
    }
  ]
}
