{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "ssm",
    "version": "1.31.0-0.6.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "ssm",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "ssm-1.31.0-0.6.23.jar",
          "url": "ssm-1.31.0-0.6.23.jar",
          "size": 355104,
          "sha512": "af1e14bf029be44f37badf2e62586466345f9ad2d68bef8bcb1ad733d3d342e4cea28723e3c8bc6410cbb65096f5a5cf45b4fcbc71576f22d427d79f709dd55c",
          "sha256": "512460ac90726c1aaca8e5915acaf10f2585fa3f91d07a4415a5522dd0c63408",
          "sha1": "eb345517a565654504c6ea4d16eb218c7a7d56e6",
          "md5": "d3c5438af66ba05356f89dadc4390392"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.23"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "ssm",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-cx-api",
          "version": {
            "requires": "1.31.0-0.6.23"
          }
        }
      ],
      "files": [
        {
          "name": "ssm-1.31.0-0.6.23.jar",
          "url": "ssm-1.31.0-0.6.23.jar",
          "size": 355104,
          "sha512": "af1e14bf029be44f37badf2e62586466345f9ad2d68bef8bcb1ad733d3d342e4cea28723e3c8bc6410cbb65096f5a5cf45b4fcbc71576f22d427d79f709dd55c",
          "sha256": "512460ac90726c1aaca8e5915acaf10f2585fa3f91d07a4415a5522dd0c63408",
          "sha1": "eb345517a565654504c6ea4d16eb218c7a7d56e6",
          "md5": "d3c5438af66ba05356f89dadc4390392"
        }
      ]
    }
  ]
}
