{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "fis",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "fis",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fis-1.111.0-0.6.21.jar",
          "url": "fis-1.111.0-0.6.21.jar",
          "size": 70003,
          "sha512": "cef1a089f871f2638fe230ae7f778a1ce426a317d1fb152d457864fc9f808a99fed1e00ddc269ffa5ca4702f424dc8386ebd80c1b8fdb63d6a60bd7249d45505",
          "sha256": "d79b77c9c48e9818b782f76101c27f33a67c3bc28cd82607e59794a5a689bbb2",
          "sha1": "64b0f2bcbfe7b18a0784cd60afecae446e787bb4",
          "md5": "2b2d46755624fa3c06a1c0d274c4a591"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "fis",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "fis-1.111.0-0.6.21.jar",
          "url": "fis-1.111.0-0.6.21.jar",
          "size": 70003,
          "sha512": "cef1a089f871f2638fe230ae7f778a1ce426a317d1fb152d457864fc9f808a99fed1e00ddc269ffa5ca4702f424dc8386ebd80c1b8fdb63d6a60bd7249d45505",
          "sha256": "d79b77c9c48e9818b782f76101c27f33a67c3bc28cd82607e59794a5a689bbb2",
          "sha1": "64b0f2bcbfe7b18a0784cd60afecae446e787bb4",
          "md5": "2b2d46755624fa3c06a1c0d274c4a591"
        }
      ]
    }
  ]
}
