{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "apigatewayv2-integrations",
    "version": "1.111.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x2nrgrzbtvb4vn7ivydfsyaxee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "apigatewayv2-integrations",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "apigatewayv2",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "servicediscovery",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apigatewayv2-integrations-1.111.0-0.6.21.jar",
          "url": "apigatewayv2-integrations-1.111.0-0.6.21.jar",
          "size": 47920,
          "sha512": "f554e0840b2d940d4c57b02e4384835fcf09b8dad0307451d400426da6acd29b0bd2cd4da4b1ae70b9982d77ec1d0db37dcd1d07d7ceb154b40f765b00eb464d",
          "sha256": "d2ff11e33bfa6dbe378c352ef57761e49a49667e8fb6f0aa327f6745bcdeb509",
          "sha1": "a49ab0475d92aa8d9b6a58faa5238ae024233bda",
          "md5": "bea9842c869b53dbbf2dba3f846e5526"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "apigatewayv2-integrations",
          "version": {
            "requires": "1.111.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "apigatewayv2",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "ec2",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "elasticloadbalancingv2",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "servicediscovery",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.111.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "apigatewayv2-integrations-1.111.0-0.6.21.jar",
          "url": "apigatewayv2-integrations-1.111.0-0.6.21.jar",
          "size": 47920,
          "sha512": "f554e0840b2d940d4c57b02e4384835fcf09b8dad0307451d400426da6acd29b0bd2cd4da4b1ae70b9982d77ec1d0db37dcd1d07d7ceb154b40f765b00eb464d",
          "sha256": "d2ff11e33bfa6dbe378c352ef57761e49a49667e8fb6f0aa327f6745bcdeb509",
          "sha1": "a49ab0475d92aa8d9b6a58faa5238ae024233bda",
          "md5": "bea9842c869b53dbbf2dba3f846e5526"
        }
      ]
    }
  ]
}
