{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "greengrassv2",
    "version": "1.110.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cnrjfrtzdvad5bhmsg7msamtuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "greengrassv2",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrassv2-1.110.0-0.6.21.jar",
          "url": "greengrassv2-1.110.0-0.6.21.jar",
          "size": 119285,
          "sha512": "9920a5a1e28a920b2bf9a7abe801ee74ba76f256085b07a5bac99af8977ff2f4cde6dca7e7692f26ee5ef2fcf24d7317b7737060207e06766de4d4d6021a8487",
          "sha256": "9a56599989b49fa0c021f29b067d7013dd431bbc794bdddea509fbe5aa8ac7e0",
          "sha1": "e1d1654cbb9d8abf29bd828f459063471535b780",
          "md5": "b22b73025b1972afefbf2dd3a17d8fb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "greengrassv2",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "greengrassv2-1.110.0-0.6.21.jar",
          "url": "greengrassv2-1.110.0-0.6.21.jar",
          "size": 119285,
          "sha512": "9920a5a1e28a920b2bf9a7abe801ee74ba76f256085b07a5bac99af8977ff2f4cde6dca7e7692f26ee5ef2fcf24d7317b7737060207e06766de4d4d6021a8487",
          "sha256": "9a56599989b49fa0c021f29b067d7013dd431bbc794bdddea509fbe5aa8ac7e0",
          "sha1": "e1d1654cbb9d8abf29bd828f459063471535b780",
          "md5": "b22b73025b1972afefbf2dd3a17d8fb6"
        }
      ]
    }
  ]
}
