{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "resourcegroups",
    "version": "1.100.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "smkqp7thvbfexba6catfwegxzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "resourcegroups",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "resourcegroups-1.100.0-0.6.21.jar",
          "url": "resourcegroups-1.100.0-0.6.21.jar",
          "size": 38506,
          "sha512": "96ec19413f8e997f66b7071a4d051d1363dcea5d6bbdea9771fb34ca154e6d51e78ce5f06084ca8a7fb8a4041c5aa32b97ff9e04eb56ea62968ef10401b90409",
          "sha256": "206c51d1bb8694ee646cceb40ed5ee3551241caa920b8732c7a4be94723f56ce",
          "sha1": "6e05390329da54f4b29feacc2232e445d5df5f77",
          "md5": "d27f7d78d495109c9438bfd92c7c9e9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "resourcegroups",
          "version": {
            "requires": "1.100.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.100.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "resourcegroups-1.100.0-0.6.21.jar",
          "url": "resourcegroups-1.100.0-0.6.21.jar",
          "size": 38506,
          "sha512": "96ec19413f8e997f66b7071a4d051d1363dcea5d6bbdea9771fb34ca154e6d51e78ce5f06084ca8a7fb8a4041c5aa32b97ff9e04eb56ea62968ef10401b90409",
          "sha256": "206c51d1bb8694ee646cceb40ed5ee3551241caa920b8732c7a4be94723f56ce",
          "sha1": "6e05390329da54f4b29feacc2232e445d5df5f77",
          "md5": "d27f7d78d495109c9438bfd92c7c9e9c"
        }
      ]
    }
  ]
}
