{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "pinpointemail",
    "version": "1.110.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "k23roxkwqjbs5i6arr4lg4r4xm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "pinpointemail",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "pinpointemail-1.110.1-0.6.21.jar",
          "url": "pinpointemail-1.110.1-0.6.21.jar",
          "size": 191949,
          "sha512": "b274996ca6c44cbc75aae680330bcdfd5cd83dd75503d43782db72e0ee9e4984720e419060ddf6273ce56e69bcd19653445bab644f82c09a7481c4a3c5f79d0f",
          "sha256": "39fe2ddf33202a60f98fc2c098d49a0ed3cc958341b6a8e0709faf34083e5726",
          "sha1": "87fd94befee22810f08b61fc3978e5fe007de3ce",
          "md5": "8b3c1e58606ff75738e61834e575bf1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "pinpointemail",
          "version": {
            "requires": "1.110.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "pinpointemail-1.110.1-0.6.21.jar",
          "url": "pinpointemail-1.110.1-0.6.21.jar",
          "size": 191949,
          "sha512": "b274996ca6c44cbc75aae680330bcdfd5cd83dd75503d43782db72e0ee9e4984720e419060ddf6273ce56e69bcd19653445bab644f82c09a7481c4a3c5f79d0f",
          "sha256": "39fe2ddf33202a60f98fc2c098d49a0ed3cc958341b6a8e0709faf34083e5726",
          "sha1": "87fd94befee22810f08b61fc3978e5fe007de3ce",
          "md5": "8b3c1e58606ff75738e61834e575bf1e"
        }
      ]
    }
  ]
}
