{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "sam",
    "version": "1.106.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "apa3jttzlbgsjbklj7vcehaque"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "sam",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sam-1.106.1-0.6.21.jar",
          "url": "sam-1.106.1-0.6.21.jar",
          "size": 799412,
          "sha512": "b397b7bb2a8ba25044a439498cefae3cb5832cf824cf72dc095216b7c239282a797f8b3ca279d296c6dd14992ffb25a43358194c26ad924de6d55b581af9d3b3",
          "sha256": "867e6ed856d7ea442311b74b0a8e45f354ff3a3da210f2f27dfa683140666afb",
          "sha1": "a1f0fe982a2f7beb06d8fa3d6a570373a7b5f7f9",
          "md5": "115f1fb269b78504b1dacc3461a39a9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "sam",
          "version": {
            "requires": "1.106.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.106.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sam-1.106.1-0.6.21.jar",
          "url": "sam-1.106.1-0.6.21.jar",
          "size": 799412,
          "sha512": "b397b7bb2a8ba25044a439498cefae3cb5832cf824cf72dc095216b7c239282a797f8b3ca279d296c6dd14992ffb25a43358194c26ad924de6d55b581af9d3b3",
          "sha256": "867e6ed856d7ea442311b74b0a8e45f354ff3a3da210f2f27dfa683140666afb",
          "sha1": "a1f0fe982a2f7beb06d8fa3d6a570373a7b5f7f9",
          "md5": "115f1fb269b78504b1dacc3461a39a9a"
        }
      ]
    }
  ]
}
