{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "eventschemas",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.114.0-0.6.21.jar",
          "url": "eventschemas-1.114.0-0.6.21.jar",
          "size": 43038,
          "sha512": "f53bded54b599535ad890abae30642b8d9eade0f9b7bd44fe3e02026c48738367918a54ffc81a670f913d83b9363b9d0e55d9365bda635dc7be21ab7a7506f91",
          "sha256": "d86e7479cf2a4844b7ae7b96c3129e69de6a4405461ec0436ef1b102b4f60819",
          "sha1": "f39baa597d1867213c81ee521a9cb0bfe2d657d",
          "md5": "1d5a43ecdc47715803b963980c433fd4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "eventschemas",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "eventschemas-1.114.0-0.6.21.jar",
          "url": "eventschemas-1.114.0-0.6.21.jar",
          "size": 43038,
          "sha512": "f53bded54b599535ad890abae30642b8d9eade0f9b7bd44fe3e02026c48738367918a54ffc81a670f913d83b9363b9d0e55d9365bda635dc7be21ab7a7506f91",
          "sha256": "d86e7479cf2a4844b7ae7b96c3129e69de6a4405461ec0436ef1b102b4f60819",
          "sha1": "f39baa597d1867213c81ee521a9cb0bfe2d657d",
          "md5": "1d5a43ecdc47715803b963980c433fd4"
        }
      ]
    }
  ]
}
