{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticbeanstalk",
    "version": "1.114.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "eyeo232rubbsjhxluyggv7snsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticbeanstalk",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticbeanstalk-1.114.0-0.6.21.jar",
          "url": "elasticbeanstalk-1.114.0-0.6.21.jar",
          "size": 155155,
          "sha512": "2085915607b18d19d8ac6018b3590fccd0c7535aeab84bb2b16328f5ff315c5653742671999322032fc27188de5643139464ecd5bae420d05193a4ac976d9cfb",
          "sha256": "cff6b5939e8d4b5aebae289d967cb3d8089f6fa353d186dd2a861cf870668ad7",
          "sha1": "6e0bab7aa9b4de8acee59c8e76193934bbac6aaa",
          "md5": "f7fe986cf64fcba6d9c49b2d35c66204"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticbeanstalk",
          "version": {
            "requires": "1.114.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.114.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticbeanstalk-1.114.0-0.6.21.jar",
          "url": "elasticbeanstalk-1.114.0-0.6.21.jar",
          "size": 155155,
          "sha512": "2085915607b18d19d8ac6018b3590fccd0c7535aeab84bb2b16328f5ff315c5653742671999322032fc27188de5643139464ecd5bae420d05193a4ac976d9cfb",
          "sha256": "cff6b5939e8d4b5aebae289d967cb3d8089f6fa353d186dd2a861cf870668ad7",
          "sha1": "6e0bab7aa9b4de8acee59c8e76193934bbac6aaa",
          "md5": "f7fe986cf64fcba6d9c49b2d35c66204"
        }
      ]
    }
  ]
}
