{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "autoscaling-common",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling-common",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-common-1.99.0-0.6.21.jar",
          "url": "autoscaling-common-1.99.0-0.6.21.jar",
          "size": 15783,
          "sha512": "4a426e90c5497c190cc6a4c5d5059699f4593d1cbf595ecdc7c817ae6557b754e0c3b53ea128039a0d6fb8e5e530597ac885095a23601ba8af8330392bf90e38",
          "sha256": "78f1616151a40292e89969f2b88027263b7e6b0aaa49ef1bd4ed7fd309cf2afe",
          "sha1": "89de3defe1dc0330579e942d24cd6f78b8bc9d84",
          "md5": "d9007a2570ba67aab440a5cd440cf43a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "autoscaling-common",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoscaling-common-1.99.0-0.6.21.jar",
          "url": "autoscaling-common-1.99.0-0.6.21.jar",
          "size": 15783,
          "sha512": "4a426e90c5497c190cc6a4c5d5059699f4593d1cbf595ecdc7c817ae6557b754e0c3b53ea128039a0d6fb8e5e530597ac885095a23601ba8af8330392bf90e38",
          "sha256": "78f1616151a40292e89969f2b88027263b7e6b0aaa49ef1bd4ed7fd309cf2afe",
          "sha1": "89de3defe1dc0330579e942d24cd6f78b8bc9d84",
          "md5": "d9007a2570ba67aab440a5cd440cf43a"
        }
      ]
    }
  ]
}
