{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "managedblockchain",
    "version": "1.110.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cnrjfrtzdvad5bhmsg7msamtuq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "managedblockchain",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "managedblockchain-1.110.0-0.6.21.jar",
          "url": "managedblockchain-1.110.0-0.6.21.jar",
          "size": 105078,
          "sha512": "d8a83d214a30db098f30351217ab476f49be5b3060fbfeb386b8e7b1201aeaa9fbc7f20a90c901d0113e76e20219637a45fce836d7810c285d9961c1fd6d70f7",
          "sha256": "2c2ad765cd17de742b3c419a1885c315ad43a8f39989c7b041f120c42b4a8e40",
          "sha1": "749dc1f28592858470fb19a4935e736393d1bcce",
          "md5": "ad3a7fe0879a08a0b82fe3e8ebfd99bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "managedblockchain",
          "version": {
            "requires": "1.110.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.110.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "managedblockchain-1.110.0-0.6.21.jar",
          "url": "managedblockchain-1.110.0-0.6.21.jar",
          "size": 105078,
          "sha512": "d8a83d214a30db098f30351217ab476f49be5b3060fbfeb386b8e7b1201aeaa9fbc7f20a90c901d0113e76e20219637a45fce836d7810c285d9961c1fd6d70f7",
          "sha256": "2c2ad765cd17de742b3c419a1885c315ad43a8f39989c7b041f120c42b4a8e40",
          "sha1": "749dc1f28592858470fb19a4935e736393d1bcce",
          "md5": "ad3a7fe0879a08a0b82fe3e8ebfd99bb"
        }
      ]
    }
  ]
}
