{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "servicecatalog",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "servicecatalog",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "servicecatalog-1.103.0-0.6.21.jar",
          "url": "servicecatalog-1.103.0-0.6.21.jar",
          "size": 209843,
          "sha512": "efce938ee2fad9f6aa4ff31d83865805145b9c91021c0463f033ed88b653434f03cbfc0e750c291809c8e8dea9c48335d15a48eb5028cc30e1b651971648062f",
          "sha256": "e568750fa8c04957cd012d665ed51facaf3afad3eeba05079e55f3ec226ce656",
          "sha1": "4b2e99b4142e39bcd119348a337fb581751cc333",
          "md5": "3823a2907fc4657fb855468d3f26e77a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "servicecatalog",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.103.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "servicecatalog-1.103.0-0.6.21.jar",
          "url": "servicecatalog-1.103.0-0.6.21.jar",
          "size": 209843,
          "sha512": "efce938ee2fad9f6aa4ff31d83865805145b9c91021c0463f033ed88b653434f03cbfc0e750c291809c8e8dea9c48335d15a48eb5028cc30e1b651971648062f",
          "sha256": "e568750fa8c04957cd012d665ed51facaf3afad3eeba05079e55f3ec226ce656",
          "sha1": "4b2e99b4142e39bcd119348a337fb581751cc333",
          "md5": "3823a2907fc4657fb855468d3f26e77a"
        }
      ]
    }
  ]
}
