{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "lambda-nodejs",
    "version": "1.108.1-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "gmwtoadzizbz5jj3nknjggc274"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-nodejs",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-nodejs-1.108.1-0.6.21.jar",
          "url": "lambda-nodejs-1.108.1-0.6.21.jar",
          "size": 25632,
          "sha512": "2e49ef146795f2fee3b41fc8eee8fa37eb76b75ae1f222544c8545bf6011662a4c5163239e6c0a11634b4fed7e4703bd89b997b4ff1c13a4e08d6b361c05dbe9",
          "sha256": "8383337bf6ba1482a99ac9f3c32d9d76a93c2d339faf3121fa17706d6024ab98",
          "sha1": "a017bf6ff9d7a66b6de5298d5b1754ee62ffb158",
          "md5": "1036734758c160ffb2da4e22ec1835b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "lambda-nodejs",
          "version": {
            "requires": "1.108.1"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.108.1-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lambda-nodejs-1.108.1-0.6.21.jar",
          "url": "lambda-nodejs-1.108.1-0.6.21.jar",
          "size": 25632,
          "sha512": "2e49ef146795f2fee3b41fc8eee8fa37eb76b75ae1f222544c8545bf6011662a4c5163239e6c0a11634b4fed7e4703bd89b997b4ff1c13a4e08d6b361c05dbe9",
          "sha256": "8383337bf6ba1482a99ac9f3c32d9d76a93c2d339faf3121fa17706d6024ab98",
          "sha1": "a017bf6ff9d7a66b6de5298d5b1754ee62ffb158",
          "md5": "1036734758c160ffb2da4e22ec1835b2"
        }
      ]
    }
  ]
}
