{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "databrew",
    "version": "1.118.0-0.6.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "databrew",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "databrew-1.118.0-0.6.25.jar",
          "url": "databrew-1.118.0-0.6.25.jar",
          "size": 497119,
          "sha512": "a113f845793d0d8dd77215a29d25a28fecd756a7262ce71493a3f606a93f680aac6a250e966fe1d1add5f782a13ba6200c04185362d088bc7fa695a97fd76e94",
          "sha256": "3909e5aa7365cf54daf3b4e66adbc4ba6b3fa866c5808bb9893bf637860d7119",
          "sha1": "9f94a957f8fbca26476ffb7c41658887c1444f37",
          "md5": "00b6037f5396e10e1bfcbb99f2ac10fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.25"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "databrew",
          "version": {
            "requires": "1.118.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.118.0-0.6.25"
          }
        }
      ],
      "files": [
        {
          "name": "databrew-1.118.0-0.6.25.jar",
          "url": "databrew-1.118.0-0.6.25.jar",
          "size": 497119,
          "sha512": "a113f845793d0d8dd77215a29d25a28fecd756a7262ce71493a3f606a93f680aac6a250e966fe1d1add5f782a13ba6200c04185362d088bc7fa695a97fd76e94",
          "sha256": "3909e5aa7365cf54daf3b4e66adbc4ba6b3fa866c5808bb9893bf637860d7119",
          "sha1": "9f94a957f8fbca26476ffb7c41658887c1444f37",
          "md5": "00b6037f5396e10e1bfcbb99f2ac10fe"
        }
      ]
    }
  ]
}
