{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "appconfig",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "appconfig",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appconfig-1.104.0-0.6.21.jar",
          "url": "appconfig-1.104.0-0.6.21.jar",
          "size": 93420,
          "sha512": "3e277336ffce1f142c1b185bc7405f861abc24f985f0828725655dd2a3fe9b2a639ae82b06cfb2494551a57608e46f0a38ca4b01b9f3c94a8a1203b6f83f2b8b",
          "sha256": "2d28e75cc62c97b0c89ad906fbdff86dc6e7a228e36d201a91dc37d2da15e361",
          "sha1": "a2dc819b11933f09c6b83ea2fd79f1d42252e168",
          "md5": "87c2c63237a97d7bdcbd06d965a39832"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "appconfig",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "appconfig-1.104.0-0.6.21.jar",
          "url": "appconfig-1.104.0-0.6.21.jar",
          "size": 93420,
          "sha512": "3e277336ffce1f142c1b185bc7405f861abc24f985f0828725655dd2a3fe9b2a639ae82b06cfb2494551a57608e46f0a38ca4b01b9f3c94a8a1203b6f83f2b8b",
          "sha256": "2d28e75cc62c97b0c89ad906fbdff86dc6e7a228e36d201a91dc37d2da15e361",
          "sha1": "a2dc819b11933f09c6b83ea2fd79f1d42252e168",
          "md5": "87c2c63237a97d7bdcbd06d965a39832"
        }
      ]
    }
  ]
}
