{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticache",
    "version": "1.107.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ii37qlm56fdwtlikv7tspxqqje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticache",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticache-1.107.0-0.6.21.jar",
          "url": "elasticache-1.107.0-0.6.21.jar",
          "size": 281376,
          "sha512": "285a2bcf35e8bfe81e685934ca1ac0a56b33e6a76d6a72a0e189d9ff3e0e1df09e6b7dbf5ea2588e8ab18e09d94c3a77bd8c533a41c8fac39c25d27ebda653b5",
          "sha256": "5473db0c83459b273ea72d7ff975e6a1adca7dd74ad8199d6d20779e6be68753",
          "sha1": "fb4eae9200cefe76c144c6d670bfb5cb907a4567",
          "md5": "d270680e6eb5c9b89cd15349e446d188"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticache",
          "version": {
            "requires": "1.107.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.107.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticache-1.107.0-0.6.21.jar",
          "url": "elasticache-1.107.0-0.6.21.jar",
          "size": 281376,
          "sha512": "285a2bcf35e8bfe81e685934ca1ac0a56b33e6a76d6a72a0e189d9ff3e0e1df09e6b7dbf5ea2588e8ab18e09d94c3a77bd8c533a41c8fac39c25d27ebda653b5",
          "sha256": "5473db0c83459b273ea72d7ff975e6a1adca7dd74ad8199d6d20779e6be68753",
          "sha1": "fb4eae9200cefe76c144c6d670bfb5cb907a4567",
          "md5": "d270680e6eb5c9b89cd15349e446d188"
        }
      ]
    }
  ]
}
