{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "elasticache",
    "version": "1.115.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "mmt4x645szht5dd4sh3qtmk2ta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "elasticache",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticache-1.115.0-0.6.21.jar",
          "url": "elasticache-1.115.0-0.6.21.jar",
          "size": 281384,
          "sha512": "a144647f96b105de937b217ecddc12b4e91852ce3aeeef4f6b22cccb79e5d26eaa463ffa79142b0d4e057a84e63520b1d949877192ffbdd8d1c4de95453e6d3f",
          "sha256": "7a18c2c97a33774730d0e2872be65851c50370a7148363da318762647fa2cd7e",
          "sha1": "63072214659bfd8044ebe320fb79b61647e9e425",
          "md5": "6514f571fd1b3ad64f5bdad1dba43c9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "elasticache",
          "version": {
            "requires": "1.115.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.115.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "elasticache-1.115.0-0.6.21.jar",
          "url": "elasticache-1.115.0-0.6.21.jar",
          "size": 281384,
          "sha512": "a144647f96b105de937b217ecddc12b4e91852ce3aeeef4f6b22cccb79e5d26eaa463ffa79142b0d4e057a84e63520b1d949877192ffbdd8d1c4de95453e6d3f",
          "sha256": "7a18c2c97a33774730d0e2872be65851c50370a7148363da318762647fa2cd7e",
          "sha1": "63072214659bfd8044ebe320fb79b61647e9e425",
          "md5": "6514f571fd1b3ad64f5bdad1dba43c9d"
        }
      ]
    }
  ]
}
