{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "cdk-yaml-cfn",
    "version": "1.103.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "scwtlzl2vng5vmpmjwmjvsfnoa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-yaml-cfn",
          "version": {
            "requires": "1.103.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-yaml-cfn-1.103.0-0.6.21.jar",
          "url": "cdk-yaml-cfn-1.103.0-0.6.21.jar",
          "size": 426,
          "sha512": "23e061276f19ad563a3adb6956b12c645482b464148417aaa79a21fff1218faf1f0c8c04d8a9ede618d2de4165cd4944db9d439c04735b41ee7c87b5381f8e21",
          "sha256": "f7a3c8e06c04b14f283b7d5ceebb2471523bb3c3b2965e94eaf0efa8cbac0cf7",
          "sha1": "814c33a6a7b03bc37cd4bfe40a89db3df7fbfa2d",
          "md5": "8890d51b03651fbea4f4bfa94cc046f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.103.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "cdk-yaml-cfn",
          "version": {
            "requires": "1.103.0"
          }
        }
      ],
      "files": [
        {
          "name": "cdk-yaml-cfn-1.103.0-0.6.21.jar",
          "url": "cdk-yaml-cfn-1.103.0-0.6.21.jar",
          "size": 426,
          "sha512": "23e061276f19ad563a3adb6956b12c645482b464148417aaa79a21fff1218faf1f0c8c04d8a9ede618d2de4165cd4944db9d439c04735b41ee7c87b5381f8e21",
          "sha256": "f7a3c8e06c04b14f283b7d5ceebb2471523bb3c3b2965e94eaf0efa8cbac0cf7",
          "sha1": "814c33a6a7b03bc37cd4bfe40a89db3df7fbfa2d",
          "md5": "8890d51b03651fbea4f4bfa94cc046f1"
        }
      ]
    }
  ]
}
