{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "imagebuilder",
    "version": "1.99.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "77l3wsmng5dcnbpnx6e7ui64wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.99.0-0.6.21.jar",
          "url": "imagebuilder-1.99.0-0.6.21.jar",
          "size": 240709,
          "sha512": "a1e52dd377a3bd850fea0869b8c8930b6a1a135630aee7fc3a7f8e9ef4e6e1c44207e8567d4188ecc5cf9923e39180f1dd7fd296f4a7cd50741de142c9253fd8",
          "sha256": "bc3b2a2479ac4b75cb9e38d94b14a7128008fa3ad92a7e735a60661754367fa4",
          "sha1": "5e20ec24e1e7dba2ea0a12e91aced4e7090a78aa",
          "md5": "9f1394b948e421e4d620e7cad50cf758"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "imagebuilder",
          "version": {
            "requires": "1.99.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.99.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "imagebuilder-1.99.0-0.6.21.jar",
          "url": "imagebuilder-1.99.0-0.6.21.jar",
          "size": 240709,
          "sha512": "a1e52dd377a3bd850fea0869b8c8930b6a1a135630aee7fc3a7f8e9ef4e6e1c44207e8567d4188ecc5cf9923e39180f1dd7fd296f4a7cd50741de142c9253fd8",
          "sha256": "bc3b2a2479ac4b75cb9e38d94b14a7128008fa3ad92a7e735a60661754367fa4",
          "sha1": "5e20ec24e1e7dba2ea0a12e91aced4e7090a78aa",
          "md5": "9f1394b948e421e4d620e7cad50cf758"
        }
      ]
    }
  ]
}
