{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "auditmanager",
    "version": "1.109.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "4umeix6puva4lkvlrzj7iisxg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "auditmanager",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "auditmanager-1.109.0-0.6.21.jar",
          "url": "auditmanager-1.109.0-0.6.21.jar",
          "size": 76350,
          "sha512": "cd2231894dedffa2c945f44640b558ab4239303c5b31e01100de95d45e46fadc982020ad837f203acb03a639fd5e41528c0c1811ecc5577d530ffbbf152777dc",
          "sha256": "ee3edc912bbb55ac2abc0ff43e492e8b4fe5ee75ef0e2e1e0412c60b44efebc0",
          "sha1": "b333f059aa17e59647e7a3e5e54e397ce32d21cd",
          "md5": "e0523a9cb77d2e87133abf5a4ba55810"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "auditmanager",
          "version": {
            "requires": "1.109.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.109.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "auditmanager-1.109.0-0.6.21.jar",
          "url": "auditmanager-1.109.0-0.6.21.jar",
          "size": 76350,
          "sha512": "cd2231894dedffa2c945f44640b558ab4239303c5b31e01100de95d45e46fadc982020ad837f203acb03a639fd5e41528c0c1811ecc5577d530ffbbf152777dc",
          "sha256": "ee3edc912bbb55ac2abc0ff43e492e8b4fe5ee75ef0e2e1e0412c60b44efebc0",
          "sha1": "b333f059aa17e59647e7a3e5e54e397ce32d21cd",
          "md5": "e0523a9cb77d2e87133abf5a4ba55810"
        }
      ]
    }
  ]
}
