{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "pinpointemail",
    "version": "1.31.0-unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "pinpointemail",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "pinpointemail-1.31.0-unspecified.jar",
          "url": "pinpointemail-1.31.0-unspecified.jar",
          "size": 191909,
          "sha512": "b4753025d4c8707991d1c6c7b55904a6f7c721f7b1940cdadab3adb2775b3819019704313ccd8e52aa2df0767e806639b8b0fd503a07ef97e8afd6986ad709b6",
          "sha256": "5a3f6253d29fb46b2f33b48945250e6e14d02cbfa16b49d47e5046fc9f250db6",
          "sha1": "5b2be031598bcc81b2cbe2ac38b2c847eb8e6d18",
          "md5": "d5583b38fc84e5d3b29139b56f6a57d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "pinpointemail",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "pinpointemail-1.31.0-unspecified.jar",
          "url": "pinpointemail-1.31.0-unspecified.jar",
          "size": 191909,
          "sha512": "b4753025d4c8707991d1c6c7b55904a6f7c721f7b1940cdadab3adb2775b3819019704313ccd8e52aa2df0767e806639b8b0fd503a07ef97e8afd6986ad709b6",
          "sha256": "5a3f6253d29fb46b2f33b48945250e6e14d02cbfa16b49d47e5046fc9f250db6",
          "sha1": "5b2be031598bcc81b2cbe2ac38b2c847eb8e6d18",
          "md5": "d5583b38fc84e5d3b29139b56f6a57d2"
        }
      ]
    }
  ]
}
