{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "logs",
    "version": "1.101.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "jaowebu54rhl3bnpwvdhdg2v5y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "logs",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "logs-1.101.0-0.6.21.jar",
          "url": "logs-1.101.0-0.6.21.jar",
          "size": 116799,
          "sha512": "284302558b8b49e151e7ed81fb222556887244ca7b3789b9cab1562c0ac118c5fb654c709d4da9a75cfdbe390d793750f0166fd6fbe3e757c6a6a90089b75a2c",
          "sha256": "4b85bb2ec0ae17b719e8155704f3782a3e33add5fd4df207107154dce2504b65",
          "sha1": "bf0b8ef1970296e2912cf912e19aed09cdbba8ed",
          "md5": "a23bc99ab54cc0c3d8ca77b9d41339e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "logs",
          "version": {
            "requires": "1.101.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "s3-assets",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.101.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "logs-1.101.0-0.6.21.jar",
          "url": "logs-1.101.0-0.6.21.jar",
          "size": 116799,
          "sha512": "284302558b8b49e151e7ed81fb222556887244ca7b3789b9cab1562c0ac118c5fb654c709d4da9a75cfdbe390d793750f0166fd6fbe3e757c6a6a90089b75a2c",
          "sha256": "4b85bb2ec0ae17b719e8155704f3782a3e33add5fd4df207107154dce2504b65",
          "sha1": "bf0b8ef1970296e2912cf912e19aed09cdbba8ed",
          "md5": "a23bc99ab54cc0c3d8ca77b9d41339e1"
        }
      ]
    }
  ]
}
