{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "mediastore",
    "version": "1.31.0-unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "mediastore",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "mediastore-1.31.0-unspecified.jar",
          "url": "mediastore-1.31.0-unspecified.jar",
          "size": 31422,
          "sha512": "8b3f9c1c8097b3ead5480dd55da70e93720c5e55cda1a8c01a55fca8acae549f315b18e3c00ccc109d3b22cb3ca4ac349bee9bd7261bd2eccdc5e4feb3d56b77",
          "sha256": "ce2453c5b36e47de07aa7b1a164c35206d42d74a2f63252bbb4d4a7b297ccca8",
          "sha1": "ae33b3252c14a04cd0940cecbe3a3f6a7bee4557",
          "md5": "1a6e341d9d12259e5c3213ffc97bf356"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "mediastore",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.31.0-unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "mediastore-1.31.0-unspecified.jar",
          "url": "mediastore-1.31.0-unspecified.jar",
          "size": 31422,
          "sha512": "8b3f9c1c8097b3ead5480dd55da70e93720c5e55cda1a8c01a55fca8acae549f315b18e3c00ccc109d3b22cb3ca4ac349bee9bd7261bd2eccdc5e4feb3d56b77",
          "sha256": "ce2453c5b36e47de07aa7b1a164c35206d42d74a2f63252bbb4d4a7b297ccca8",
          "sha1": "ae33b3252c14a04cd0940cecbe3a3f6a7bee4557",
          "md5": "1a6e341d9d12259e5c3213ffc97bf356"
        }
      ]
    }
  ]
}
