{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "iam",
    "version": "1.34.0-0.6.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "iam",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "iam-1.34.0-0.6.22.jar",
          "url": "iam-1.34.0-0.6.22.jar",
          "size": 215619,
          "sha512": "46619992d7862e0946cb923ff73c3cc570f6006a61a09de6cf6256d585407a16162e570b2bc37bc2ecb77f1faeceabb5e2a77459c59db11d6e0f08567d3110ee",
          "sha256": "5dda56b408059035ac44f8319f5f8779e183d5d35a76eafea3106abcd003702e",
          "sha1": "999fcce91b35506af978bec7eccb5ef5e19f49c0",
          "md5": "90ed35c83929c20447527ba15a010100"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.22"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "iam",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-region-info",
          "version": {
            "requires": "1.34.0-0.6.22"
          }
        }
      ],
      "files": [
        {
          "name": "iam-1.34.0-0.6.22.jar",
          "url": "iam-1.34.0-0.6.22.jar",
          "size": 215619,
          "sha512": "46619992d7862e0946cb923ff73c3cc570f6006a61a09de6cf6256d585407a16162e570b2bc37bc2ecb77f1faeceabb5e2a77459c59db11d6e0f08567d3110ee",
          "sha256": "5dda56b408059035ac44f8319f5f8779e183d5d35a76eafea3106abcd003702e",
          "sha1": "999fcce91b35506af978bec7eccb5ef5e19f49c0",
          "md5": "90ed35c83929c20447527ba15a010100"
        }
      ]
    }
  ]
}
