{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "dynamodb",
    "version": "1.104.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qufggsntgrgwvj22f7mprctb2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "dynamodb",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "applicationautoscaling",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamodb-1.104.0-0.6.21.jar",
          "url": "dynamodb-1.104.0-0.6.21.jar",
          "size": 241206,
          "sha512": "5e9c70133f48d0a686eb45cc2715782ee2830653482e0e855174218a00e2117df7add811c72d023387c7232a06e7637a1afaf8494a009a7d09ddc63a85d079f6",
          "sha256": "a0dce6e5f57eca582161850f9676e74a255c5788496810b8bf6dff6d764edfd6",
          "sha1": "e688aa204eb44ce24adb42bbbc2597ae55c10feb",
          "md5": "5e9d6515a5932cdd4a0d44a5778001f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "dynamodb",
          "version": {
            "requires": "1.104.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "applicationautoscaling",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cloudwatch",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "iam",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "kms",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "lambda",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "cdk-customresources",
          "version": {
            "requires": "1.104.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "dynamodb-1.104.0-0.6.21.jar",
          "url": "dynamodb-1.104.0-0.6.21.jar",
          "size": 241206,
          "sha512": "5e9c70133f48d0a686eb45cc2715782ee2830653482e0e855174218a00e2117df7add811c72d023387c7232a06e7637a1afaf8494a009a7d09ddc63a85d079f6",
          "sha256": "a0dce6e5f57eca582161850f9676e74a255c5788496810b8bf6dff6d764edfd6",
          "sha1": "e688aa204eb44ce24adb42bbbc2597ae55c10feb",
          "md5": "5e9d6515a5932cdd4a0d44a5778001f8"
        }
      ]
    }
  ]
}
