{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.justincase.aws-cdk-kotlin-dsl",
    "module": "directoryservice",
    "version": "1.117.0-0.6.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ka4pthfoybhvvnwbwaxmu2dbry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "software.amazon.awscdk",
          "module": "directoryservice",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "directoryservice-1.117.0-0.6.21.jar",
          "url": "directoryservice-1.117.0-0.6.21.jar",
          "size": 77676,
          "sha512": "6f21ff3cb1d5676456107f2a5e8d6cb5c31f7cf21c8916e20194c54e862a7744581f9ea9e1a97c5b9437acda57a5e34e6103201808bd1a8761295c13dd8433af",
          "sha256": "a531f9107269ef14cd89befc0e945208b8e7c1b92fdb421d861a83895bdca6c8",
          "sha1": "3cb64b1abb079d105b9015695c7afacf8d55b17e",
          "md5": "ae7b4073812b5f0cf3640121b317bbf6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "dsl-common",
          "version": {
            "requires": "0.6.21"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "core",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "software.amazon.awscdk",
          "module": "directoryservice",
          "version": {
            "requires": "1.117.0"
          }
        },
        {
          "group": "jp.justincase.aws-cdk-kotlin-dsl",
          "module": "core",
          "version": {
            "requires": "1.117.0-0.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "directoryservice-1.117.0-0.6.21.jar",
          "url": "directoryservice-1.117.0-0.6.21.jar",
          "size": 77676,
          "sha512": "6f21ff3cb1d5676456107f2a5e8d6cb5c31f7cf21c8916e20194c54e862a7744581f9ea9e1a97c5b9437acda57a5e34e6103201808bd1a8761295c13dd8433af",
          "sha256": "a531f9107269ef14cd89befc0e945208b8e7c1b92fdb421d861a83895bdca6c8",
          "sha1": "3cb64b1abb079d105b9015695c7afacf8d55b17e",
          "md5": "ae7b4073812b5f0cf3640121b317bbf6"
        }
      ]
    }
  ]
}
